### ISSUE TITLE
Running application using Gunicorn

### ISSUE THREAD

**Issue by orangeluc** [Avaiga/taipy#100]
Having issues with the use of gevent for deploying into production: 

MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['pymongo.ssl_context (/usr/local/lib/python3.9/site-packages/pymongo/ssl_context.py)'].****

**Comment by FlorianJacta** [comment]
Could you tell us the Python and Taipy version you are using? Taipy is compatible with Python 3.8 and above.

**Comment by orangeluc** [comment]
I use Python 3.9 and taipy 2.1

**Comment by FredLL-Avaiga** [comment]
Hi @orangeluc 
Do you think it would be possible (easy enough) to provide a small sample of code that allows us to replicate your issue ?
I suppose it involves pymongo ?

**Comment by FlorianJacta** [comment]
Hi @orangeluc,

We recently deployed Taipy in production on multiple cloud providers and had no issues. What were the steps to get this error? Where do you host your app? Would you happen to have a code sample to reproduce the issue?

**Comment by orangeluc** [comment]
Sorry for the late response. We tried a few things, and it probably has sth to do with memory allocation. When we assign more memories, it sort of worked.
