### ISSUE TITLE
BUG-Using tgb.Page() inside a Python method gives an indentation error

### ISSUE THREAD

**Issue by herrschmidt** [Avaiga/taipy#1029]
**Description**
 When using ```with tgp.Page() as page:``` inside a Python method, the indentation of the code to place it inside the method in the class, causes an indentation error in Taipy.

**How to reproduce**

- Example code to reproduce the error:
```python
import pandas as pd
import taipy.gui.builder as tgb
from taipy.gui import Gui


class FoodDatabase:
    def __init__(self):
        self.food_df = pd.DataFrame({
            "Meal": ["Lunch", "Dinner", "Lunch", "Lunch"],
            "Category": ["Food", "Food", "Drink", "Food"],
            "Name": ["Burger", "Pizza", "Soda", "Salad"],
            "Calories": [300, 400, 150, 200],
        })

    def create_page(self):
        with tgb.Page() as page:
            tgb.table('{self.food_df}', filter=True)
            return page

if __name__ == '__main__':
    food_database = FoodDatabase()
    page = food_database.create_page()
    Gui(page).run(debug=True, use_reloader=True)

```

- This is the Error Message:
```python
Traceback (most recent call last):
  File "c:\PROJECTS\datagui\main.py", line 22, in <module>
    Gui(page).run(debug=True, use_reloader=True)
    ^^^^^^^^^
  File "C:\PROJECTS\datagui\.venv\Lib\site-packages\taipy\gui\gui.py", line 360, in __init__
    self.add_page(name=Gui.__root_page_name, page=page)
  File "C:\PROJECTS\datagui\.venv\Lib\site-packages\taipy\gui\gui.py", line 1666, in add_page
    self.__var_dir.add_frame(page._frame)
  File "C:\PROJECTS\datagui\.venv\Lib\site-packages\taipy\gui\utils\_variable_directory.py", line 38, in add_frame
    imported_var_list = _get_imported_var(frame)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROJECTS\datagui\.venv\Lib\site-packages\taipy\gui\utils\get_imported_var.py", line 19, in _get_imported_var
    st = ast.parse(inspect.getsource(frame))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 1
    def create_page(self):
IndentationError: unexpected indent
```

**Runtime environment**
Please specify relevant indications.
 - Taipy version (or branch name): 3.1.0
 - OS: Windows 11
 - Python Version: 3.11
 - Browser: Firefox
 - Code Editor: Visual Studio Code

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Create related issue in taipy-doc for documentation and Release Notes if relevant

**Comment by FlorianJacta** [comment]
Thank you for creating the issue! This issue seems to be connected to this other issue: https://github.com/Avaiga/taipy/issues/614

**Comment by dinhlongviolin1** [comment]
@FlorianJacta The page should be created at the top level of a module to make sure that the locals is properly captured. This syntax will not work as the creation of the page is within the function. The content of a page can be created through a function.

**Comment by dinhlongviolin1** [comment]
If you really want to have this syntax (class based page), we already have a feature called Class Modules. This might not have been properly documented but here is how to implement it.
```
import pandas as pd
import taipy.gui.builder as tgb
from taipy.gui import Gui, Page


class FoodDatabase(Page):
    def __init__(self):
        self.food_df = pd.DataFrame({
            "Meal": ["Lunch", "Dinner", "Lunch", "Lunch"],
            "Category": ["Food", "Food", "Drink", "Food"],
            "Name": ["Burger", "Pizza", "Soda", "Salad"],
            "Calories": [300, 400, 150, 200],
        })
        super().__init__()

    def create_page(self):
        with tgb.Page() as page:
            tgb.table('{food_df}', filter=True)
        return page

if __name__ == '__main__':
    Gui(page=FoodDatabase()).run()
```

**Comment by dinhlongviolin1** [comment]
@herrschmidt Please try it out and let me know if that works for you.

**Comment by FlorianJacta** [comment]
This is really nice! How does it interact with callbacks? and how to assign new *state* values?

**Comment by dinhlongviolin1** [comment]
@FlorianJacta I hope that this example I just created answer your question
```
import pandas as pd
import taipy.gui.builder as tgb
from taipy.gui import Gui, Page


class SimplePage(Page):
    def __init__(self):
        self.x = 2
        self.y = 4 # x = y * 2
        super().__init__()

    def on_change(self, var, val):
        if var == 'x':
            self.y = val * 2

    def create_page(self):
        with tgb.Page() as page:
            tgb.text('x = ')
            tgb.number('{x}')
            tgb.text("y = {y} = x * 2")
        return page

if __name__ == '__main__':
    Gui(page=SimplePage()).run()

```

**Comment by dinhlongviolin1** [comment]
From what I have heard, if I am not mistaken, the one and only @FabienLelaquais is providing a doc section for this feature

**Comment by herrschmidt** [comment]
Great, this works! Thanks so much for posting this here. I usually split my GUI code into model, view, controller (and main) module files. Would this be possible here, too? Couldn't figure out, how to place the create_page method in the View class inside the view module file and use it in the main module class.

> If you really want to have this syntax (class based page), we already have a feature called Class Modules. This might not have been properly documented but here is how to implement it.
> 
> ```
> import pandas as pd
> import taipy.gui.builder as tgb
> from taipy.gui import Gui, Page
> 
> 
> class FoodDatabase(Page):
>     def __init__(self):
>         self.food_df = pd.DataFrame({
>             "Meal": ["Lunch", "Dinner", "Lunch", "Lunch"],
>             "Category": ["Food", "Food", "Drink", "Food"],
>             "Name": ["Burger", "Pizza", "Soda", "Salad"],
>             "Calories": [300, 400, 150, 200],
>         })
>         super().__init__()
> 
>     def create_page(self):
>         with tgb.Page() as page:
>             tgb.table('{food_df}', filter=True)
>         return page
> 
> if __name__ == '__main__':
>     Gui(page=FoodDatabase()).run()
> ```

**Comment by dinhlongviolin1** [comment]
> Great, this works! Thanks so much for posting this here. I usually split my GUI code into model, view, controller (and main) module files. Would this be possible here, too? Couldn't figure out, how to place the create_page method in the View class inside the view module file and use it in the main module class.
> 
> > If you really want to have this syntax (class based page), we already have a feature called Class Modules. This might not have been properly documented but here is how to implement it.
> > ```
> > import pandas as pd
> > import taipy.gui.builder as tgb
> > from taipy.gui import Gui, Page
> > 
> > 
> > class FoodDatabase(Page):
> >     def __init__(self):
> >         self.food_df = pd.DataFrame({
> >             "Meal": ["Lunch", "Dinner", "Lunch", "Lunch"],
> >             "Category": ["Food", "Food", "Drink", "Food"],
> >             "Name": ["Burger", "Pizza", "Soda", "Salad"],
> >             "Calories": [300, 400, 150, 200],
> >         })
> >         super().__init__()
> > 
> >     def create_page(self):
> >         with tgb.Page() as page:
> >             tgb.table('{food_df}', filter=True)
> >         return page
> > 
> > if __name__ == '__main__':
> >     Gui(page=FoodDatabase()).run()
> > ```

Hi @herrschmidt. For taipy-gui we don't follow the usual MVC structure but we do provide ways for you the scale your app if you have a large projects with different pages. Have fun trying things out and if you have any questions, you can contact me directly through nguyen.dinh.long@taipy.io or through @FlorianJacta. If you have any issue along the way, please create an issue like you just did.

**Comment by herrschmidt** [comment]
Okay, thank you, I will have a deeper look at the docs on how to work with different pages.
