### ISSUE TITLE
Allow DMY and YMD formats to be displayed in the date input control

### ISSUE THREAD

**Issue by VFLins** [Avaiga/taipy#1037]
**Description**
[Date input](https://docs.taipy.io/en/latest/manuals/gui/viselements/date/#formatting-the-date) currently shows dates only in MDY. Would be good to allow DMY and YMD for a non-USA audience, as they are used in [most places](https://en.wikipedia.org/wiki/List_of_date_formats_by_country).

Desired usage would be with either a `display_format` (or something similar) parameter:

```
import taipy.gui.builder as tgb

tgb.date("{date}", display_format='DMY')
```

Or a `locale` parameter:

```
import taipy.gui.builder as tgb

tgb.date("{date}", locale='es')
```

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FlorianJacta** [comment]
This seems like a good issue. Most of the R&D is in France, so we also use "MDY"! Thank you for the feedback.

**Comment by jrobinAV** [comment]
@FlorianJacta I thought it was already done. Is it still relevent?

**Comment by FlorianJacta** [comment]
There is a similar feature [here](https://docs.taipy.io/en/latest/manuals/gui/viselements/date/#formatting-the-date) but what you describe goes beyond this. This is relevant.

**Comment by FredLL-Avaiga** [comment]
We will support the same date (time) format as field (not editable date) ie `format=MM-yyyy-dd`
