### ISSUE TITLE
Scenario-selector - provide an explicit list of scenarios

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#1040]
**Improvement:**
Adding the possibility for a developer to filter scenarios by scenario_config can be useful in the scenario selector.

**Possible solutions:**
Here are some alternatives:

1. Having a simple optional property to pass the scenario_config
    
    `<|{scenario}|scenario_selector|scenario_config=my_scenario_config_id|>`

2. Having an optional property to pass a custom filter method to apply to the list of scenarios to display.
    
    `<|{scenario}|scenario_selector|filter=my_filter|>`

    Here is an example of a filter method that a user can build:
    ```python
    def my_filter(scenario):
        if scenario.config_id == "my_scenario_config_id":
            return True
        return False
    ```

3. Having an optional lov-like property allows the user to pass a scenario list. By default, the property should be bound to the result of `tp.get_scenarios()` if the property is not defined.

    `<|{scenario}|scenario_selector|lov=scenarios|>`

     ```python
    scenarios = [sc for sc in tp.get_scenarios() if sc.config_id == "my_scenario_config_id"]
    ```

**Comment by FlorianJacta** [comment]
The ideal solution would be to have by default an automatic filter on the scenario selector. It could also filter on the properties inside the scenario. For example, I want to select all scenarios where *promotion* is *True*. This information could be found in the properties of the scenario.

![image](https://github.com/Avaiga/taipy/assets/98709993/2ed37847-730c-4a4e-9590-2d65afb8011c)

**Comment by jrobinAV** [comment]
@FlorianJacta The solution you propose is a filter mechanism for the end user. It is more appropriate to solve the ticket #1075 .
This issue is more about how the developer filters the scenarios.

After some discussion, we would like to make this issue more generic. It should consider not only config_id filtering but any filter as well. The third option of the description should be preferred.
