### ISSUE TITLE
BUG-Inconsistent frontend chart refresh when periodically updating with invoke_long_callback status function on linux

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy#1048]
**Description**
When using invoke_long_callback, we can provide a `period` argument to call the status function every `period` ms. When using `period=500` and a status function that updates the data of a chart, we would expect the chart to refresh every 500ms.

On Linux, the chart refresh seems to be inconsistent/buffered. The status function is correctly being called every 500ms, but the chart does not visually update in the browser. Every 3-5 seconds, the updates come in one go. On Windows, it works fine. Using `Gui.run(async_mode="threading")` also works fine.

**How to reproduce**

The following is a line chart which should alternate between 0 and 1 every 500ms:

```python
from taipy.gui import Gui, invoke_long_callback
import time

def generate_data():
    i = 0
    while True:
        yield (i, i%2)
        i += 1

gen = generate_data()
data = [next(gen) for _ in range(10)]

def idle():
    while True:
        time.sleep(1)

# chart alternates between 0 and 1 every 500ms
def update_real_time_chart(state):
    state.data = state.data[1:] + [next(gen)]

def on_init(state):
    invoke_long_callback(state, idle, [], update_real_time_chart, [], 1000)

Gui("<|{data}|chart|>").run()#async_mode="threading")
```

**Expected behavior**
Chart should update every 500ms.

**Screenshots**
When available and relevant, screenshots to better highlight the problem.

**Runtime environment**
Please specify relevant indications.
 - Taipy 3.1
 - WSL Ubuntu (reproducible on Docker Python Debian image)
 - Chrome/Firefox

**Comment by dinhlongviolin1** [comment]
You might need to change the ping_interval from socketio. I have included the change for you to see. Let me know if it helps.
```
import time

from taipy.gui import Gui, invoke_long_callback


def generate_data():
    i = 0
    while True:
        yield (i, i % 2)
        i += 1


gen = generate_data()
data = [next(gen) for _ in range(10)]


def idle():
    while True:
        time.sleep(0.5)


# chart alternates between 0 and 1 every 500ms
def update_real_time_chart(state):
    state.data = state.data[1:] + [next(gen)]


def on_init(state):
    invoke_long_callback(state, idle, [], update_real_time_chart, [], 500)


Gui("<|{data}|chart|>").run(server_config={"socketio": {"ping_interval": 1}})
```

**Comment by arcanaxion** [comment]
@dinhlongviolin1 Yes, that works for me. Is this something that can be "fixed"? Admittedly I don't understand what this is

**Comment by dinhlongviolin1** [comment]
Normally, websocket stacks a bunch of messages together and push them periodically. Changing the ping_interval in this case allows the frontend to receive messages more frequently.

I think we can put this in the doc so people know how to edit this if needed. I will create another doc issue.
