### ISSUE TITLE
BUG - Using File Upload with a large file generates a large notification

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1060]
## **Description**
When uploading a file using the file selector visual element on a large file (bigger than 10Mb), Taipy will create a very long success notification with `file_name,file_name,file_name,file_name,file_name,file_name,file_name Uploaded successfully` Here is an example with a 200Mb dataset:

![image](https://github.com/Avaiga/taipy/assets/62465003/a87df6a7-db4c-47ae-a413-5a0af3e36148)

## **How to reproduce**

Use this example Taipy app:
```python
from taipy.gui import Gui

content = ""

page = """
<|{content}|file_selector|>
"""

Gui(page).run()
```

and upload this example 8Mb dataset:
[example_data.csv](https://github.com/Avaiga/taipy/files/14790078/example_data.csv)

This will result in the notification issue:
![image](https://github.com/Avaiga/taipy/assets/62465003/d66934d3-de5b-4c58-9848-9f408ee7e4c3)

## **Expected behavior**
The notification should only display the file name once

## **Runtime environment**
 - Taipy version: 3.1.0
 - OS: Windows
 - Browser: Chrome

**Comment by Satoshi-Sh** [comment]
Hi there, can someone look at my PR on this issue?

**Comment by trgiangdo** [comment]
Hello @Satoshi-Sh, thank you for your contribution.

Next time, please follow the guide in the [Contribution page](https://github.com/Avaiga/taipy/blob/develop/CONTRIBUTING.md) before engaging an issue so we can better manage the PRs. It should save you a lot of waiting time.

For the meantime, I will assign this issue to you, and request a suitable maintainer to review your PR. Thank you for your collaboration.
