### ISSUE TITLE
Selecting points on a line chart only works for single trace

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1061]
## Issue
The documentation currently provides a great example of how to get the mean value of selected points on a line chart:
https://docs.taipy.io/en/latest/manuals/gui/viselements/charts/advanced/#tracking-selection
![image](https://github.com/Avaiga/taipy/assets/62465003/f85443a5-8238-462c-a4bf-8b2300dcc347)

Unfortunately, this only works with line charts with one trace. When you have multiple traces, this approach does not work:
![image](https://github.com/Avaiga/taipy/assets/62465003/1c01adf8-c5ad-43e3-b758-6fad655678a8)
Here, the user selected points from trace B (red line). When selecting these points, Taipy returns a new value for `selected={selected_indices}.` The dev then has to pre-define which trace he wants to calculate the mean on using:

```python
def on_change(state, var, val):
    if var == "selected_indices":
        state.mean_value = np.mean([data["A"][idx] for idx in val]) if len(val) else 0
```
Here, the dev chose to calculate on trace A, which leads to `mean_value` returning 12.03 instead of 3.5, i.e., returning the mean of points from trace A that were not selected.

## Feature Improvement

Ideally, the `selected` property should not only return indices in the dataset. It should return the actual points that were selected (indices and columns)

## Workaround

The current workaround is to ask the user which traces he wants to select using a selector visual element, but it is not ideal:
![image](https://github.com/Avaiga/taipy/assets/62465003/71cc3234-3eef-4fcf-90de-4972e848cf14)

## Code example
```python
from taipy.gui import Gui
import pandas as pd
import numpy as np

mean_value = 0
selected_indices = []

data = pd.DataFrame(
    {
        "Time": np.arange(0, 10, 0.1),
        "A": np.arange(0, 10, 0.1) + np.random.randn(100) + 10,
        "B": np.arange(0, 10, 0.1) + np.random.randn(100),
    }
)

layout = {
    # Force the Box select tool
    "dragmode": "select",
}


def on_change(state, var, val):
    if var == "selected_indices":
        state.mean_value = np.mean([data["A"][idx] for idx in val]) if len(val) else 0


page = """
## Mean of <|{len(selected_indices)}|raw|> selected points: <|{mean_value}|format=%.2f|raw|>

<|{data}|chart|selected={selected_indices}|x=Time|y[1]=A|y[2]=B|layout={layout}|>
"""

Gui(page).run()
```

**Comment by jrobinAV** [comment]
This first requires a dicussion to align on the API.

**Comment by FredLL-Avaiga** [comment]
If you have multiple traces you can specify multiple selected properties: `selected[0]=[selected0}|selected[1]={selected1}|`
Does this answer your question @AlexandreSajus  ?

**Comment by AlexandreSajus** [comment]
This is a good workaround but it would not solve what the user requested. The user specifically wants selected to return the data for the selected points. If it's too hard to implement, maybe documenting `selected[0]=[selected0}|selected[1]={selected1}|` would be enough

**Comment by FlorianJacta** [comment]
We should then know what is the real use case behind it. I think having the selected property indexed is powerful but it comes with three flaws:
- how *selected0* and *selected1* are updated? Which one is called the first one in the *on_change*? *selected0*? And what is the value of *selected1* when the first update is done?
- What happens when there are a lot of different traces? Do we have to define it one by one or use the property dict?
- How does it work with Plotly figure? Is it an issue?

**Comment by FredLL-Avaiga** [comment]
if present selected[1] is updated with the indices of the 1st trace AND selected[2] is updated with the indices of the 2nd trace.

**Comment by FlorianJacta** [comment]
Yes, but I think you will have a problem with the order of updates. I will try it out.

**Comment by FredLL-Avaiga** [comment]
I don't understand what the order of updates has to do with the choucroute ?

**Comment by FlorianJacta** [comment]
This is what I am talking about. The first call of the *on_change* doesn't have the correct value of *selected_indices2*. Here I just selected once the chart.

```
Var selected_indices1 val [31, 32, 33, 34, 35]
selected_indices1 [31, 32, 33, 34, 35]
selected_indices2 []
Var selected_indices2 val [47, 48, 50, 52, 53, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]  
selected_indices1 [31, 32, 33, 34, 35]
selected_indices2 [47, 48, 50, 52, 53, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]
```

Code:

```python
from taipy.gui import Gui
import pandas as pd
import numpy as np

mean_value = 0
selected_indices1 = []
selected_indices2 = []

data = pd.DataFrame(
    {
        "Time": np.arange(0, 10, 0.1),
        "A": np.arange(0, 10, 0.1) + np.random.randn(100) + 10,
        "B": np.arange(0, 10, 0.1) + np.random.randn(100),
    }
)

layout = {
    # Force the Box select tool
    "dragmode": "select",
}


def on_change(state, var, val):
    print("Var", var, "val", val)
    print("selected_indices1", state.selected_indices1)
    print("selected_indices2", state.selected_indices2)


page = """
<|{data}|chart|selected[1]={selected_indices1}|selected[2]={selected_indices2}|x=Time|y[1]=A|y[2]=B|layout={layout}|>
"""

Gui(page).run()
```
