### ISSUE TITLE
BUG - Decimator does not work with multiple traces

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1062]
## Without decimator:
![image](https://github.com/Avaiga/taipy/assets/62465003/276623e1-79c9-4f7a-9045-5e3aa061b441)

## With decimator:
```bash
[2024-03-28 15:10:31][Taipy][INFO]  * Server starting on http://127.0.0.1:5000
C:\Users\asaju\Desktop\report_issues\venv\Lib\site-packages\taipy\gui\gui.py:635: TaipyGuiWarning: A problem occurred while resolving variable 'data' in module '__main__'.
  _warn(
```

![image](https://github.com/Avaiga/taipy/assets/62465003/bd340547-0d81-4eef-9a87-1a2ed929ab78)

## Code:
```python
from taipy.gui import Gui
from taipy.gui.data.decimator import MinMaxDecimator
import pandas as pd
import numpy as np

NOP = 500
decimator_instance = MinMaxDecimator(n_out=NOP)


data = pd.DataFrame(
    {
        "Time": np.arange(0, 10, 0.1),
        "A": np.arange(0, 10, 0.1) + np.random.randn(100) + 10,
        "B": np.arange(0, 10, 0.1) + np.random.randn(100),
    }
)

page = """
<|{data}|chart|x=Time|y[1]=A|y[2]=B|decimator=decimator_instance|>
"""

Gui(page).run()
```

**Comment by arcanaxion** [comment]
I believe you have to index the `decimator` property when you have multiple traces: https://docs.taipy.io/en/latest/manuals/gui/viselements/chart/#p-decimator

```python
page = """
<|{data}|chart|x=Time|y[1]=A|y[2]=B|decimator[1]=decimator_instance|decimator[2]=decimator_instance|>
"""
```

**Comment by arcanaxion** [comment]
I initially couldn't get the decimator to work for your example even after the modification I made, and lowering NOP to 10. Seems like even when `Decimator.threshold=None`, there's still some threshold before the decimator kicks in. Maybe the devs can shed more light on this.

In the meantime, explicitly setting threshold to NOP seems to work:

```python
from taipy.gui import Gui
from taipy.gui.data.decimator import MinMaxDecimator
import pandas as pd
import numpy as np

NOP = 10
decimator_instance = MinMaxDecimator(n_out=NOP, threshold=NOP)

data = pd.DataFrame(
    {
        "Time": np.arange(0, 10, 0.1),
        "A": np.arange(0, 10, 0.1) + np.random.randn(100) + 10,
        "B": np.arange(0, 10, 0.1) + np.random.randn(100),
    }
)

page = """
<|{data}|chart|x=Time|y[1]=A|y[2]=B|decimator[1]=decimator_instance|decimator[2]=decimator_instance|>
"""

Gui(page).run()
```

**Comment by AlexandreSajus** [comment]
Thanks finding the workaround, this does indeed seem to work properly. We should definitely still look at this, having to explicitely set the threshold does not make sense from the user's perspective

**Comment by anunayasri** [comment]
@AlexandreSajus Is the expectation that `decimator_instance = MinMaxDecimator()` should work with the default values?
If this issue is still relevant I would live to work on it.

**Comment by AlexandreSajus** [comment]
> anunayasri

Yes, assigned!

**Comment by anunayasri** [comment]
Seems like this issue has been closed in another PR. Unassigning myself. cc: @AlexandreSajus
