### ISSUE TITLE
Improve docs for `navbar` (using `lov`)

### ISSUE THREAD

**Issue by Dr-Irv** [Avaiga/taipy#1063]
**Description**

In `https://docs.taipy.io/en/develop/refmans/gui/viselements/generic/navbar/`, there is an example for using `navbar` with a list of values, but it is confusing (and possibly incorrect).

The example has this code for markdown:
```text
<|navbar|lov={[("page1", "Page 1"), ("http://www.google.com", "Google")]}|>
```

The issue is that "page1" won't be found.  So if you have pages that you have added to the application, via `gui.add_pages({"page1" : some_markdown_text})`, it won't reference `"page1"`.  So I think the correct example should be:

```text
<|navbar|lov={[("/page1", "Page 1"), ("http://www.google.com", "Google")]}|>
```

It took me over an hour to figure this out!!

**Additional requests**

Beside this doc bug, the documentation for `navbar` is pretty weak as of today.
This issue is an opportunity to improve that globally.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FlorianJacta** [comment]
You are right @Dr-Irv! I am putting this issue to high priority as it could be pretty frustrating.

**Comment by Satoshi-Sh** [comment]
I can take on this issue. This should be `taipy-doc` repo, right?

**Comment by FlorianJacta** [comment]
@FabienLelaquais @FredLL-Avaiga Is this behavior planned to be changed?

**Comment by SGCODEX** [comment]
@jrobinAV @Dr-Irv 
Hi, please assign me this issue under Devfest ai and Hacktoberfest

**Comment by jrobinAV** [comment]
@SGCODEX For hacktoberfest, we only assign one issue at a time. You have already been assigned to another issue. Please submit a Pull Request for issue 558 or remove your assignment from it.

**Comment by aniketh-varma** [comment]
Hi @jrobinAV @FlorianJacta, I don't think this issue is valid anymore. The link referred to in the issue description (https://docs.taipy.io/en/develop/manuals/gui/viselements/navbar/) gives a **404 - Not Found error**. However, the correct docs page (https://docs.taipy.io/en/develop/refmans/gui/viselements/generic/navbar/#__tabbed_2_1) shows the correct example for the Navbar with list of values.

**Comment by FlorianJacta** [comment]
You are right the documentation is now correct. Should we close it? @FabienLelaquais

**Comment by SGCODEX** [comment]
Please assign it to me

**Comment by SGCODEX** [comment]
@quest-bot embark

**Comment by FlorianJacta** [comment]
@SGCODEX You are now assigned to this issue!

**Comment by wizaye** [comment]
hey @FlorianJacta would like to work on this too, please assign this issue to me! :)

**Comment by FabienLelaquais** [comment]
> You are right the documentation is now correct. Should we close it? @FabienLelaquais

@FlorianJacta if you bless the fix, yes!
And I will... now

**Comment by FabienLelaquais** [comment]
@FlorianJacta I know why I didn't want to close this:
@Dr-Irv explicitly said "Beside this doc bug, the documentation [...] is pretty weak [...]". Which is true.
I will create a specific issue for that.
