### ISSUE TITLE
BUG-Chart alternatingly disappears when changing dynamic data

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy#1064]
**Description**
When changing a chart's dynamic property (e.g. data or layout), the chart disappears. Change something again, and it reappears.

**How to reproduce**

```python
from taipy.gui import Gui
from math import cos, exp

def compute_data(decay: int) -> list:
    return [cos(i / 6) * exp(-i * decay / 600) for i in range(100)]

decay = 10

title_lov = list("ABC")
title = title_lov[0]

page = """
<|{decay}|slider|continuous=False|>

<|{title}|selector|lov={title_lov}|>

<|{compute_data(decay)}|chart|layout={dict(title=dict(text=title))}|>
"""

Gui(page).run()
```

**Expected behavior**
Description of what would be the expected outcome.

**Screenshots**
When available and relevant, screenshots to better highlight the problem.

**Runtime environment**
Please specify relevant indications.
 - Taipy version (or branch name): develop @ 44162cf
 - OS: WSL Ubuntu
 - Browser: Chrome, Firefox

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Create related issue in taipy-doc for documentation and Release Notes if relevant

**Comment by arcanaxion** [comment]
This bug is not present when installing the latest release (3.1.1) from whl. But it is still present if I build from the 3.1.1 source commit. Any ideas? Node version: v20.12.1

**Comment by FredLL-Avaiga** [comment]
duplicate #1339
