### ISSUE TITLE
Data Node Default Data does not accept Dataframes

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1071]
Feeding a data node a pd.DataFrame as a default_data fails with error:
```python
X_cfg = Config.configure_data_node("X", default_data=pd.DataFrame(dataset[0]))
```
```bash
TypeError: Object of type DataFrame is not JSON serializable
```

On the other hand, writing to a data node a pd.DataFrame works fine:
```python
scenario.X.write(pd.DataFrame(dataset[0], columns=["x1", "x2"]))
```

## Data Nodes should accept pd.DataFrame or pd.Series

The frustration here is that I can create and run scenarios from the code that use pd.DataFrames as input data using code. But I can't do it from the scenario visual elements since I can't set the input data to a DataFrame within my configuration

**Comment by jrobinAV** [comment]
The `default_data` attributes of pickle data nodes are stored in the configuration. That's the technical reason why it must be Json serializable. The `default_data` attribute is designed only to handle static parameters like literals but not to contain real datasets.
It is documented in the pickle section of the [data node config page](https://docs.taipy.io/en/latest/manuals/core/config/data-node-config/#pickle). The explanation could be improved.

In any case, you don't want to initialize your scenario with static data. What would be the use case to create a scenario with always the same data?
Most of the time the input data for initialization either comes from an integration with a third party software or directly from the user (like a variable in the state: state.my_df)

In that case, if you want to initialize your scenario when created, you should use the on_creation callback that is made for that:
https://docs.taipy.io/en/latest/manuals/gui/corelements/scenario_selector/#customizing-the-creation
Something like:

``` python
def my_on_creation(state, id, payload):
    scenario = tp.create_scenario(payload["config"], payload["date"], payload["label"])
    scenario.my_input_data = state.my_df
    return scenario
```

**Comment by jrobinAV** [comment]
I propose to close this ticket as not planned.

**Comment by AlexandreSajus** [comment]
Yes you can close as non-planned. Exposing more this on_creation thing in the docs would be the solution

**Comment by trgiangdo** [comment]
@AlexandreSajus If you really need a DataFrame as the default value, you can convert the DF to a dictionary as a workaround.

```python
X_cfg = Config.configure_data_node("X", default_data=pd.DataFrame(dataset[0])).to_dict()
```

If the exposed type is "pandas" (by default), the dictionary will be convert to DF automatically.
