### ISSUE TITLE
Multiple selection of scenarios in Scenario Selector

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1081]
**Description**
Being able to select multiple scenarios in the Scenario Selector.

Ideal solution: a *multiple* property should be created, and the scenario selector should return a list of scenarios when interacting. This should behave like the Taipy selector.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by jrobinAV** [comment]
It should be similar to the data node selector.
By the way, the documentation of the data node selector is already saying we can bind the control to a list of data nodes.
https://docs.taipy.io/en/develop/manuals/gui/corelements/data_node_selector/#properties
