### ISSUE TITLE
Create the Scenario Selector control

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy#109]
**Description**

Create a control that holds the scenario entities from Core.

See overall features in [GUI controls for Core](https://docs.google.com/document/d/19R0SiykrlGALWU9ONDdtmni4PNBmJ-95s9i755FhWgg).

**Acceptance Criteria**
- [ ] Scenarios are listed, selectable, updated on Core message, and new scenarios can be created.
- [ ] Documentation is updated.

**Comment by FredLL-Avaiga** [comment]
* backend name scenario_selector
* frontend name ScenarioSelector
