### ISSUE TITLE
BUG-Incorrect Schema for Taipy Core Config

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1091]
**Description**
The [*schema*](https://raw.githubusercontent.com/Avaiga/taipy/release/3.1/taipy/core/config/config.schema.json) is not readable. It throws an error:

```
File "C:\Users\jacta\.conda\envs\3.1_release\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 104 column 13 (char 3168)
```

In the same issue, you could also fix the *collection_name* property.

```
          "collection_name ": {
            "description": "storage_type: mongo_collection specific.",
            "type": "string"
          },
```

should be (delete the space after *collection_name*):

          "collection_name": {
            "description": "storage_type: mongo_collection specific.",
            "type": "string"
          },

**How to reproduce**

```python
import urllib.request
import json

SCHEMA_URL = "https://raw.githubusercontent.com/Avaiga/taipy/release/3.1/taipy/core/config/config.schema.json"

# Load schema from URL
with urllib.request.urlopen(SCHEMA_URL) as url:
    schema = json.load(url)
```

**Expected behavior**
To be readable.

**Runtime environment**
Please specify relevant indications.
 - Taipy version (or branch name): 3.1 and develop (maybe 3.0)

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Create related issue in taipy-doc for documentation and Release Notes if relevant

**Comment by jrobinAV** [comment]
We should add a unit test that loads the schema to ensure it is loadable. 
@FlorianJacta Does that mean Taipy Studio is broken?

**Comment by FlorianJacta** [comment]
I don't know; it seems to work, which is strange.
