### ISSUE TITLE
Add decimator support for chart mode="none"

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy#1098]
**Description**
Chart mode="none" is useful for stacked area charts, as shown in the [docs](https://docs.taipy.io/en/develop/manuals/gui/viselements/charts/filled-area/). It would be great if decimators could be used with this mode.

Also, it seems that decimators do not recompute on zoom for mode="lines".

```python
from taipy.gui import Gui
from taipy.gui.data import MinMaxDecimator
import pandas as pd
import numpy as np

N_OUT = 200
decimator = MinMaxDecimator(n_out=N_OUT, threshold=N_OUT)

n = 5000
df = pd.DataFrame({
    # "date": pd.date_range("2020-01-01", periods=n),
    "date": np.arange(n),
    "a": np.sin(np.linspace(0, 100, n)),
    "b": np.sin(np.linspace(0, 100, n)),
    "c": np.sin(np.linspace(0, 100, n)),
})
df1 = df
df2 = df
df3 = df

properties = {
    "x": "date",
    "y": ["a", "b", "c"],
    "decimator[1]": "decimator",
    "decimator[2]": "decimator",
    "decimator[3]": "decimator",
    "options": dict(stackgroup="first_group", fill="tonexty"),
}

page = """
<|{df1}|chart|properties=properties|mode=lines+markers|>

<|{df2}|chart|properties=properties|mode=lines|>

<|{df3}|chart|properties=properties|mode=none|>
"""

def on_change(state, var_name, var_value):
    print(var_name, type(var_value), var_value)

Gui(page).run(use_reloader=True)
```

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by jrobinAV** [comment]
@dinhlongviolin1, you self-assigned this ticket. Should you move it to the sprint backlog? What are the priorities and the estimates?

**Comment by jrobinAV** [comment]
@dinhlongviolin1 If we want to implement it, we need to have a sampling algorithm working on all dimensions of the dataset.
