### ISSUE TITLE
Update of Core from Core elements

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy#111]
**Description**

Some Core elements (see [GUI controls for Core](https://docs.google.com/document/d/19R0SiykrlGALWU9ONDdtmni4PNBmJ-95s9i755FhWgg)) can provide feedback to Core (such as: "Create a new scenario").

We need to come up with a way to make this possible.

**Acceptance Criteria**
- [ ] An API is accessible from the front-end to trigger Core actions.

**Comment by FredLL-Avaiga** [comment]
this is handled by the GuiCoreContext
- it provides callbacks for the front-end components
- it calls the core API
