### ISSUE TITLE
BUG- hover_text not showing for indicator

### ISSUE THREAD

**Issue by tomeck8** [Avaiga/taipy#1147]
**Description**
When adding a hover_text to an indicator, it does not show when hovering over it. (When I use hover_text on a selector instead of indicator, it works, though..)

**How to reproduce**

- A code fragment
    ```python
     from taipy.gui import Gui, State
  
    Gui("""
    #test
    <|message|indicator|value=50|min=0|max=100|hover_text=This does not show|>
    """).run()

    ```

**Expected behavior**
Description of what would be the expected outcome.

**Screenshots**
When available and relevant, screenshots to better highlight the problem.

**Runtime environment**
Please specify relevant indications.
 - Taipy==3.0.0:
 - OS: MacOS 14.4.1
 - Browser: Chrome

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Create related issue in taipy-doc for documentation and Release Notes if relevant

**Comment by FlorianJacta** [comment]
I was able to replicate it. Thank you for the issue. It is still present in the latest release 3.1.1.

**Comment by Satoshi-Sh** [comment]
Can I take on this issue?

**Comment by FlorianJacta** [comment]
@FabienLelaquais What do you think about this? Is the issue well documented?

**Comment by FlorianJacta** [comment]
@Satoshi-Sh You are assigned to the issue. You can ask us for any help!
