### ISSUE TITLE
Feed the ScenarioSelector with actual data from the back-end

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy#115]
**What would that feature address**

So far the data is hard-coded (in the front-end).
We want some context variable to be holding the data we want to represent (the scenario tree).

***Description of the ideal solution***

One LOV would hold the list of items as tuples.

***Caveats***

This list has to be updated when the model is modified.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%

**Comment by FredLL-Avaiga** [comment]
A first step would be to feed fake data from the Back-End
