### ISSUE TITLE
Design CLI: taipy create --blueprint

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#1152]
Propose requirements for the new functionality of taipy about creating CLI option.

https://docs.google.com/document/d/1w3WW7S-9lYsGdlABtk5SEnEBZyn5XQUT3q9ZPUh2mQw/edit

**Comment by trgiangdo** [comment]
I don't like the term `--blueprint` here because it can be confusing for the user along side the `--template` term. They seem similar to me.

I propose use something more distinct like `--example`, `--demo`, or just integrate the new application to the `--template` option

**Comment by jrobinAV** [comment]
@trgiangdo, Can you put a comment directly in the document?
