### ISSUE TITLE
Feature Improvement: Status controls could have a way to have icons instead of the default letters

### ISSUE THREAD

**Issue by gbritoda** [Avaiga/taipy#1157]
**Description**
For the Status GUI control, instead of showing E, S, I and W, it would be nice to have a way to put icons in it instead.
![](https://docs.taipy.io/en/release-3.0/manuals/gui/viselements/status-multiple3-d.png)

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented
- [ ] Status control from TaiPy gui can have Icons instead of the default letters

**Comment by pravintargaryen** [comment]
Please assign this to me

**Comment by jrobinAV** [comment]
Hello @pravintargaryen,

Our core maintainer team still needs to review this issue. We are still determining if or how we want to include it in the taipy library. Please give us some time to review the issue before engaging it. This should not be long.

Meanwhile, I invite you to look at the issues with the labels "good first issue" or "Help wanted". These tickets have been reviewed, approved and are opened for a contribution.

thank you.

**Comment by jrobinAV** [comment]
Hello @pravintargaryen,

The issue has been reviewed. Thank you for volunteering. Go ahead, give it a try. 
This is not so easy, so make sure you get in touch with the appropriate maintainers:
@FredLL-Avaiga @FabienLelaquais @dinhlongviolin1 @namnguyen20999

**Comment by FabienLelaquais** [comment]
Thank you @jrobinAV and @pravintargaryen

The real difficulty is going to be to keep the control's property API backward compatible.
We certainly can help designing this.

**Comment by jrobinAV** [comment]
Hello @pravintargaryen,

Any news on the issue?

Cheers,

**Comment by pravintargaryen** [comment]
Hi @jrobinAV,

Apologies for being behind schedule

Working on new icons from Material UI for the frontend status component. Have to test it though. 

\taipy\frontend\taipy-gui\src\components\Taipy\Status.tsx
\taipy\frontend\taipy-gui\src\components\Taipy\StatusList.tsx

![1](https://github.com/Avaiga/taipy/assets/96950453/b73d1063-4eb6-4183-92aa-cfc132b04c83)

**Comment by jrobinAV** [comment]
No pb. Take the time you need, of course.

**Comment by FredLL-Avaiga** [comment]
> Hi @jrobinAV,
> 
> Apologies for being behind schedule
> 
> Working on new icons from Material UI for the frontend status component. Have to test it though.
> 
> \taipy\frontend\taipy-gui\src\components\Taipy\Status.tsx \taipy\frontend\taipy-gui\src\components\Taipy\StatusList.tsx
> 
> ![1](https://private-user-images.githubusercontent.com/96950453/332543798-b73d1063-4eb6-4183-92aa-cfc132b04c83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjQyNzksIm5iZiI6MTcxNjM2Mzk3OSwicGF0aCI6Ii85Njk1MDQ1My8zMzI1NDM3OTgtYjczZDEwNjMtNGViNi00MTgzLTkyYWEtY2ZjMTMyYjA0YzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA3NDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ZTFkYTBiMDExYmYxM2RiY2Q0YmI1M2I5ZjYyMjc3Mjg3ZWJiMjdiZDA1ZGM4ZDE5Y2JiOGRhZTEzMDc0ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sbf7HXw6T4BYgMXM7ZSZ1d4XLYVl81gEY3G8HAIR_gw)

Are the new icons "in line" with the icons we already use ?
I thought you'd design a way to provide external icons ie allows the developer to add icons without changing the taipy-gui bundle.

**Comment by pravintargaryen** [comment]
Approaching PR

**Comment by pravintargaryen** [comment]
PR https://github.com/Avaiga/taipy/pull/1413

**Comment by jrobinAV** [comment]
Thank you @pravintargaryen. The maintainers team is reviewing your PR.

**Comment by pravintargaryen** [comment]
Made a glitch from my end https://github.com/Avaiga/taipy/pull/1413. Will resend the PR.

**Comment by pravintargaryen** [comment]
Sent a pull request with updated branch details  https://github.com/Avaiga/taipy/pull/1580

**Comment by Vaibhav91one** [comment]
Please assign this issue to me @jrobinAV.

**Comment by jrobinAV** [comment]
@Vaibhav91one Sure. 

Thank you for your help. Let me assign it to you. 

To avoid making the same errors, please consider looking at previous closed PRs. 

Thanks

**Comment by Vaibhav91one** [comment]
Thanks @jrobinAV, Will give a look at previous closed PR's.

**Comment by Vaibhav91one** [comment]
Hi @jrobinAV, I had a few queries before moving forward. Is there a way to check the changes that were made locally. And also in contributing docs, it says to create a local env which means to create a virutal environment right?

**Comment by jrobinAV** [comment]
@Vaibhav91one Yes, absolutely. Creating a dedicated environment for testing your changes will definitely help.

@namnguyen20999 @FabienLelaquais @dinhlongviolin1 @FredLL-Avaiga are front-end developers. They are used to test their devs all the time. They should be able to help you with that.

**Comment by Vaibhav91one** [comment]
Will be submitting a PR soon.

**Comment by Vaibhav91one** [comment]
Hi @jrobinAV @namnguyen20999 @FabienLelaquais @dinhlongviolin1 @FredLL-Avaiga . PFA, the variants of the icon and Pleae provide feedback.
1. Variant 1: 
      ![image](https://github.com/user-attachments/assets/d90a1d5f-deb9-41f6-b557-dae8733d20ff)
2.  Variant 2:
![image](https://github.com/user-attachments/assets/f85ce7e8-1818-4113-960c-b73b9e36c308)
