### ISSUE TITLE
BUG-adapter property doesn't behave uniformely

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy#1159]
**Description**

This issue exposes a bug in the code, as a complement to #567,

The *adapter* of a lov-based control may or may not be reusable in another control.
Specifically, sliders seem to allow for a local setting of a lov adapter, where selectors don't.

**How to reproduce**

Consider the following code:

 ```python
from taipy.gui import Gui

class Number:
  def __init__(self, index: int, name: str) -> None:
    self._index = index
    self._name = name
  def to_string(self) -> tuple:
    return (str(self._index), str(self._index))
  def to_name(self) -> tuple:
    return (str(self._index), str(self._name))

numbers = [Number(i, n) for i, n in enumerate(["Zero", "One", "Two", "Three"])]
n = numbers[1]

page = """<|1 1|layout|
<|{n}|slider|lov={numbers}|adapter={lambda d: d.to_string()}|>

<|{n}|slider|lov={numbers}|adapter={lambda d: d.to_name()}|>
|>"""

Gui(page=page).run(run_browser=False)
```

Running this application gives the following image: ![image](https://github.com/Avaiga/taipy/assets/86590727/2f60caba-ceec-48a2-b271-549df7276d1d)
which is just fine.

Now if the page uses selector controls instead of sliders, the code becomes:
```
page = """<|1 1|layout|
<|{n}|selector|lov={numbers}|adapter={lambda d: d.to_string()}|>

<|{n}|selector|lov={numbers}|adapter={lambda d: d.to_name()}|>
|>"""
```
And the page render gives: ![image](https://github.com/Avaiga/taipy/assets/86590727/8054e9b8-e7a7-488f-9862-a261cb918482)

As you can see, the adapter of the second control has replaced the adapter of the first control.
Note that using the *type* property does not fix anything.
A workaround is to duplicate the expression for the *lov* property (that is creating *numbers2* set to *number*).

Note that the `toggle` control has the *adapter* property working properly.

**Expected behavior**

The *adapter* property should behave in a homogeneous manner across all lov-based controls.

**Screenshots**
When available and relevant, screenshots to better highlight the problem.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Create related issue in taipy-doc for documentation and Release Notes if relevant

**Comment by FredLL-Avaiga** [comment]
interesting ... and strange
If one refreshes the `numbers` variable in `state`, the behavior is consistent even if not desired :-)

**Comment by FredLL-Avaiga** [comment]
![image](https://github.com/Avaiga/taipy/assets/90181748/06306cec-aa75-4038-918f-8a62e31ec740)
