### ISSUE TITLE
BUG- Scenario Viewer - Job is not accessible in on_submission_change

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1197]
**Description**
There are no keys for the 'job' in the *details* variable. We cannot provide correct user feedback.

This is not in line with the doc.
![image](https://github.com/Avaiga/taipy/assets/98709993/de893b36-ea5f-4b2c-bfb1-4bb44474a37e)

**How to reproduce**

```python
from taipy.config import Config
import taipy as tp
from taipy.gui import Gui, notify

Config.configure_job_executions(mode="standalone")


# Normal function used by Taipy
def double(nb):
    return nb * 2


# Configuration of Data Nodes
input_cfg = Config.configure_data_node(id="somedata", default_data=21)
output_cfg = Config.configure_data_node(id="result")


# Configuration of tasks
first_task_cfg = Config.configure_task(id="double",
                                       function=double,
                                       input=input_cfg,
                                       output=output_cfg)


# Configuration of scenario
scenario_cfg = Config.configure_scenario(id="my_scenario",
                                         task_configs=[first_task_cfg],
                                         name="my_scenario")



def notify_from_submissions(state, submittable, details):
    print(details.keys())

if __name__=="__main__":
    tp.Core().run()
    scenario_1 = tp.create_scenario(scenario_cfg)

    scenario_md = """
<|{scenario_1}|scenario|on_submission_change=notify_from_submissions|>
"""
    Gui(scenario_md).run()
```

![image](https://github.com/Avaiga/taipy/assets/98709993/d5befe10-075b-4ff3-b510-9ee0bdfbe16d)

**Expected behavior**
There should be the job that changes the status of the scenario.

**Runtime environment**
 - Taipy: 3.1.1

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Create related issue in taipy-doc for documentation and Release Notes if relevant

**Comment by jrobinAV** [comment]
We need to add non-regression unit tests for these kinds of issues.

**Comment by toan-quach** [comment]
@jrobinAV this is due to the event publication is relying on the self_setter which only publish the attribute name and no extra information to go with it. In this case, we have to either change the documentation or  find a way to change the self_setter function entirely
