### ISSUE TITLE
BUG- support pandas series

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#1199]
**Description**
Running mypy generates some errors: 
```
mypy --ignore-missing-imports --implicit-optional --no-namespace-packages --exclude '(taipy/templates/|generate_pyi.py|tools)' --follow-imports skip --disable-error-code import-untyped --show-column-numbers --hide-error-context .
```
Some errors relate to the returned type of the `_convert_data_to_dataframe` method in `_abstract_tabular`, `Union[pd.DataFrame, pd.Series]`.

The error is that the callers cannot accept a `pd.Series` type.

```
taipy\core\data\sql_table.py:126:13: error: 
Argument 1 to "__insert_dataframe" of "SQLTableDataNode" has incompatible type "DataFrame | Series[Any]"; expected "DataFrame"  [arg-type]
taipy\core\data\parquet.py:250:18: error: 
Incompatible types in assignment (expression has type "DataFrame | Series[Any]", variable has type "DataFrame")  [assignment]
```

**Acceptance Criteria**
- [ ] Exhibit the bug in a unit test
- [ ] Fix the issue

**Comment by SarthakNikhal** [comment]
@jrobinAV I want to work in this issue. Already downloaded and exploring the code. Please let me know how I can reproduce, if possible in code

**Comment by jrobinAV** [comment]
Thank you for your help. 

The issue is about a wrong type error generated by mypy. Running the following mypy command should show you the error (and its line) about the returned type.
```
mypy --ignore-missing-imports --implicit-optional --no-namespace-packages --exclude '(taipy/templates/|generate_pyi.py|tools)' --follow-imports skip --disable-error-code import-untyped --show-column-numbers --hide-error-context .
```

The purpose of the current ticket is first to exhibit a use case in a unit test that is failing. 
Once the use case is exhibited, we should understand how to fix the problem.

**Comment by SarthakNikhal** [comment]
@jrobinAV What is the generate_pyi file

**Comment by jrobinAV** [comment]
Hello @SarthakNikhal, 

It is a script used to generate some pyi files during the build time. They are not used at run time. That's why we are excluding the file from the mypy command line. You should not need to look at it for working on this issue.

Thanks again for helping us.

**Comment by jrobinAV** [comment]
@SarthakNikhal Any news on this ticket?

**Comment by jrobinAV** [comment]
Thank you @trgiangdo For taking over this issue.
