### ISSUE TITLE
Possibility to forward a change to a subset of clients (conditional broadcast)

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1207]
**Description**
Being able to broadcast variables not to all the clients but only a subset. A user variable or filter function defines this subset.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FlorianJacta** [comment]
I think we have internally a *_broadcast* function that broadcasts to a list of clients. Is it true?

**Comment by FabienLelaquais** [comment]
A great use case is a Chat application: not all clients should receive a message sent to a subset of connected users.

**Comment by jrobinAV** [comment]
A use case is in this issue: https://github.com/Avaiga/taipy-doc/issues/941

**Comment by FredLL-Avaiga** [comment]
Conditional broadcast is achieved via callback: 
broadcast_callback is called on every State with parameters and the callback can modify (or not) each state.
