### ISSUE TITLE
Source code or example of Talk To Taipy

### ISSUE THREAD

**Issue by rubgithub** [Avaiga/taipy#1208]
Could you provide an example or the source code of Talk To Taipy's?

https://docs.taipy.io/en/release-3.0/knowledge_base/demos/talk_to_taipy/

**Comment by jrobinAV** [comment]
Hello @rubgithub,

Unfortunately, the Talk To Taipy application relies on some non-open source parts. We can't give you access to the source code.

Maybe you can book a call [here](https://taipy.io/book-a-call) so we can discuss your motivation and see how we can help you implement the features you want.
