### ISSUE TITLE
BUG-tgb.tree on_change is not working

### ISSUE THREAD

**Issue by gorkemalgan** [Avaiga/taipy#1218]
**Description**
on_change callback provided in tgb.tree is not called when there is an interaction with the tree widget.

**How to reproduce**

- Code:
    ```python
    import taipy.gui as tg
    import taipy.gui.builder as tgb

    def my_on_change(state: tg.State, _: str, payload: dict) -> None:
        print("Action triggered!")
        print(payload)
    
    value = "Item 1"

    with tgb.Page() as page:
        tgb.tree(
            "{value}",
            lov="Item 1;Item 2;Item 3",
            on_change=my_on_change,
        )

    tg.Gui(page=page).run(port=5001)
    ```

**Expected behavior**
When clicked on an item on tree, my_on_change function should be called

**Runtime environment**
 - Taipy version (or branch name): 3.1.1
 - OS: MacOS
 - Browser: Chrome

**Comment by pravintargaryen** [comment]
I could replicate this issue

**Comment by FlorianJacta** [comment]
The problem comes from the fact that for this visual element, the first property is not value so the visual element is not properly bound. This is indeed not intended.

Try with this code:

```python
import taipy.gui as tg
import taipy.gui.builder as tgb

def my_on_change(state: tg.State, var_name: str, var_value) -> None:
    print("Value changed!")
    print(f"var_name: {var_name}, var_value: {var_value}")

value = "Item 1"

with tgb.Page() as page:
    tgb.tree(
        value="{value}",
        lov="Item 1;Item 2;Item 3",
        on_change=my_on_change,
    )

tg.Gui(page=page).run(port=5001)
```

Everything should work fine.

This should have been fixed with this issue already: https://github.com/Avaiga/taipy/issues/994

Can you confirm @dinhlongviolin1 ?

**Comment by gorkemalgan** [comment]
Ah I see, but then [docs](https://docs.taipy.io/en/latest/manuals/gui/viselements/tree/) should be updated since they assume value is the first argument

**Comment by FlorianJacta** [comment]
Yes, it should be the first argument. The docs are correct, and not the code itself. It comes from how the TGB syntax was created incorrectly for this visual element. It has already been fixed but is not released yet
