### ISSUE TITLE
chore: add new Taipy logo in readme

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Avaiga/taipy#1223]
I'm opening a blank issue because these refer to docs and don't change the existing functionality.

## Proposed changes

Update the Taipy logo.
   - The current logo in the readme:
   
     ![taipy old logo](https://github.com/Avaiga/taipy/assets/74038190/91ec2dff-1a38-4039-9ee8-bf86c5796d92)

   - Updated logo:
   
     ![taipy new logo](https://github.com/Avaiga/taipy/assets/74038190/8c999dbb-7668-4375-9773-21d79723b5fc)

---

I'd love to contribute to this. Please assign me, and I'll make a PR.

**Comment by jrobinAV** [comment]
Hello @Anmol-Baranwal, Thank you for your help. 

These are two very different topics. They should be split into two different issues.

**Comment by Anmol-Baranwal** [comment]
> Hello @Anmol-Baranwal, Thank you for your help.
> 
> These are two very different topics. They should be split into two different issues.

Sure, let me create two separate issues. I will tag you after that.

**Comment by jrobinAV** [comment]
Thank you very much.

**Comment by Anmol-Baranwal** [comment]
Hi @jrobinAV 
I've created #1234 for contribution regarding issue forms and this one for the Taipy logo in readme.

Please assign me both, and I will make PRs till tomorrow.

**Comment by marisogo** [comment]
Hey @Anmol-Baranwal  we are working on a PR and changed the logo! Thanks for you help :)

**Comment by Anmol-Baranwal** [comment]
> Hey @Anmol-Baranwal we are working on a PR and changed the logo! Thanks for you help :)

Sure, thanks for letting me know!
