### ISSUE TITLE
How to update dynamically created UI?

### ISSUE THREAD

**Issue by vishalvora** [Avaiga/taipy#1232]
I created the dynamic UI with for loop. How to update the text on button click?
```python
    for a in State.text:
        tgb.text(a)
```

**Comment by FlorianJacta** [comment]
Have you checked this [Getting Started ](https://docs.taipy.io/en/latest/tutorials/fundamentals/1_understanding_gui/) and [Tutorial](https://docs.taipy.io/en/latest/tutorials/fundamentals/1_understanding_gui/)?

**Comment by FredLL-Avaiga** [comment]
use a dict with dynamically specified bound variables 
`idx += 1`
`adict[f"v{idx"] = a`
`tgb.text("{adict.v" + str(idx) + "}")`

**Comment by FlorianJacta** [comment]
Do you need any more help? If not, I will close this issue.

**Comment by FlorianJacta** [comment]
Closing the issue as the creator is not responding.
