### ISSUE TITLE
docs: convert markdown templates to issue forms

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Avaiga/taipy#1234]
I'm opening a blank issue because these refer to docs and don't change the existing functionality.

## Proposed Changes

1. Convert the issue templates to YML form to simplify the process for contributors and remove the markdown templates (.yml).
   - Issue forms are more user-friendly than Markdown templates, especially for contributors unfamiliar with Markdown syntax. They can fill out the fields and provide the requested information easily.
   
   - Issue forms standardize the information provided by contributors, reducing the need for follow-up questions and clarifications.
   
   - With issue forms, all issues are created in a consistent format, making it easier for maintainers to review and respond quickly.
   
   You can refer to [this example](https://github.com/Anmol-Baranwal/Awesome-Illustrations-4Projects/issues/new?assignees=&labels=enhancement&projects=&template=Feature_Request.yml&title=%F0%9F%92%A1+%5BREQUEST%5D+-+%3Ctitle%3E) to see how an issue form looks. 

2. Add more issue templates.

Currently, there are only 3 issue templates, but there can be more templates for documentation, refactoring the codebase, or discussion. Let me know if you want me to add any of these or something specific.

![image](https://github.com/Avaiga/taipy/assets/74038190/403450d9-9004-4909-9148-5ffec2f9596b)

---

I'd love to contribute to this. Please assign me, and I'll make a PR.

**Comment by jrobinAV** [comment]
Hello @Anmol-Baranwal.

Thank you for your contribution. We would love to see your proposal for new templates. That would be great. 

I am just assigning the issue to you. Thank you.
