### ISSUE TITLE
BUG-Unable to change the Icon post launch

### ISSUE THREAD

**Issue by EVAUTOAI** [Avaiga/taipy#1244]
**Description**
Unable to change the icon that appears on the browser
<img width="437" alt="image" src="https://github.com/Avaiga/taipy/assets/97277014/37ba195f-7bab-4c23-9a8e-459a1fa36fc6">

Also, any way to add headers & header validations for the GETing of the html page for security purposes?

**Comment by FlorianJacta** [comment]
You can change the icon by specifying it in the *run*.

`<Gui>.run(favicon="path/to/your/icon.png")`

I will let the R&D respond to the other question. We should maybe create another issue. @FredLL-Avaiga @FabienLelaquais

**Comment by FredLL-Avaiga** [comment]
if you specify your taipy page as HTML, the head section is kept

**Comment by jrobinAV** [comment]
@EVAUTOAI Did you solve your favicon issue?

We are currently designing a solution for the second question that will be part of another issue.
