### ISSUE TITLE
Cover JSON data in Data node control

### ISSUE THREAD

**Issue by EYisaac** [Avaiga/taipy#1248]
**What would that feature address**

I have some transactional data as json file representing a list of shops with various characteristics address, size, location, opening time, type, owner, contact, etc... The structure of the document is globally the same all the time, but time to time a new field appears,  disappears or changes. I am using data node to keep track of the changes since it is edited by many people, and because I also have sql data nodes on the side.

I want to show the JSON data node in the data node control.

***Description of the ideal solution***
The ideal solution would be to have the possibility to collapse and expand recursively the various sections of the document. A syntax coloration or a visual hint could give the type of the field displayed like in the following example

![image](https://github.com/Avaiga/taipy/assets/168626589/c7b8b24f-2a96-4e0b-a514-bf91284ff593)

```
{"web-app": {
  "servlet": [   
    {
      "servlet-name": "cofaxCDS",
      "servlet-class": "org.cofax.cds.CDSServlet",
      "init-param": {
        "configGlossary:installationAt": "Philadelphia, PA",
        "configGlossary:adminEmail": "ksm@pobox.com",
        "configGlossary:poweredBy": "Cofax",
        "configGlossary:poweredByIcon": "/images/cofax.gif",
        "dataStoreDriver": "com.microsoft.jdbc.sqlserver.SQLServerDriver",
        "dataStoreUrl": "jdbc:microsoft:sqlserver://LOCALHOST:1433;DatabaseName=goon",
        "dataStoreInitConns": 10,
        "dataStoreMaxConns": 100,
        "dataStoreConnUsageLimit": 100,
        "dataStoreLogLevel": "debug",
        "maxUrlLength": 500}},
    {
      "servlet-name": "cofaxEmail",
      "servlet-class": "org.cofax.cds.EmailServlet",
      "init-param": {
      "mailHost": "mail1",
      "mailHostOverride": "mail2"}},
    {
      "servlet-name": "cofaxAdmin",
      "servlet-class": "org.cofax.cds.AdminServlet"},
 
    {
      "servlet-name": "fileServlet",
      "servlet-class": "org.cofax.cds.FileServlet"},
    {
      "servlet-name": "cofaxTools",
      "servlet-class": "org.cofax.cms.CofaxToolsServlet",
      "init-param": {
        "templatePath": "toolstemplates/",
        "log": 1,
        "logLocation": "/usr/local/tomcat/logs/CofaxTools.log",

        "fileTransferFolder": "/usr/local/tomcat/webapps/content/fileTransferFolder",
        "lookInContext": 1,
        "adminGroupID": 4,
        "betaServer": true}}],
  "servlet-mapping": {
    "cofaxCDS": "/",
    "cofaxEmail": "/cofaxutil/aemail/*",
    "cofaxAdmin": "/admin/*",
    "fileServlet": "/static/*",
    "cofaxTools": "/tools/*"},
 
  "taglib": {
    "taglib-uri": "cofax.tld",
    "taglib-location": "/WEB-INF/tlds/cofax.tld"}}}
```

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Create related issue in taipy-doc for documentation and Release Notes
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it
- [ ] Ensure any change is well documented

**Comment by EYisaac** [comment]
@vhfgosselin @dinhlongviolin1 @toan-quach ?

**Comment by FlorianJacta** [comment]
Thank you for the issue @EYisaac. This feature aligns with what the Data Node viewer aims to do.

You could also use the [tree](https://docs.taipy.io/en/latest/manuals/gui/viselements/tree/#display-a-tree-of-dictionary-entries) visual element to obtain this effect in the meantime.

@jrobinAV @FabienLelaquais what do you think about it?

**Comment by EYisaac** [comment]
I would prefer it to be in a data node control instead of a tree control. Especially for editing the content of the JSON file.
I guess I can use the tree if there is no other way.

**Comment by FlorianJacta** [comment]
I agree! This is just a workaround in the meantime

**Comment by jrobinAV** [comment]
It is a great idea. @FabienLelaquais Let's discuss this.

**Comment by jrobinAV** [comment]
After discussing it, we plan to add it to the Enterprise edition.

**Comment by EYisaac** [comment]
Will it be in the next release?

**Comment by FlorianJacta** [comment]
> Will it be in the next release?

This won't be in the next release that is going to be published in a few days. It is still an open issue.

**Comment by KunjShah95** [comment]
CAN U PLEASE ASSIGN IT TO EME AND REMOVE MY ALL PREVIOUS ASSIGNEED ONE

**Comment by FlorianJacta** [comment]
@KunjShah95 You are assigned to this ticket! Thank you

**Comment by THEBOSS0369** [comment]
Hey @FlorianJacta ! Can i work on this issue ? I have completed my previous issue and it has been marked hacktoberfest-apporved here #2018 . 

Also can you tell which file contains the logic for this issue. 
Thanks

**Comment by FlorianJacta** [comment]
Here you go @THEBOSS0369, you can work on it! I will not be able to tell you which files are to be changed. Maybe, @jrobinAV or @FredLL-Avaiga will help you on that

**Comment by THEBOSS0369** [comment]
@quest-bot embark

**Comment by THEBOSS0369** [comment]
Hey Everyone ! I have created a PR for this issue #2164 . Please review it and give the feedback. Thanks!

**Comment by FredLL-Avaiga** [comment]
Are we supposed to support json edition in this issue ? @FlorianJacta @jrobinAV @EYisaac ?

**Comment by jrobinAV** [comment]
> Are we supposed to support json edition in this issue ? @FlorianJacta @jrobinAV @EYisaac ?

@FredLL-Avaiga 
Being able to edit the JSON data is part of the issue, yes. 

However, if it is too complex at first, we can split it into two issues and start with the reading part only. But we should at least keep in mind that editing the data will, in the end, be part of it.

**Comment by FredLL-Avaiga** [comment]
the chosen frontend package allows for editing.
So we'll be good when we decide to implement that feature. 
Would you mind creating another issue for that purpose @jrobinAV ?

**Comment by jrobinAV** [comment]
@FredLL-Avaiga SOunds fair. Let me create another ticket.

@EYisaac Do not hesitate to get back to us with more details on your edition needs, if ever.
