### ISSUE TITLE
Add import/export button on data node widget

### ISSUE THREAD

**Issue by MariahLeone** [Avaiga/taipy#1250]
**Description**
An import/export button on the data node widget to upload or download the file of a data node.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FlorianJacta** [comment]
This seems related to this issue: https://github.com/Avaiga/taipy/issues/1196

@MariahLeone Do you agree? The other issue lacks the import feature however.

What is your opinion @jrobinAV

**Comment by MariahLeone** [comment]
@FlorianJacta 
Thank you. Yes it's the same with the possibility to upload the data as well. The other ticket is more precise.

**Comment by FlorianJacta** [comment]
Just to let you know, we have put this issue in the "Product Backlog" which means it is ready to be taken by a contributor or R&D. I hope we'll see this feature as it is a really nice one

**Comment by MariahLeone** [comment]
Great!

**Comment by jrobinAV** [comment]
@FlorianJacta @MariahLeone Yes, this ticket is very close to #1196 . I can Modify the other to include the possibility of writing the data by uploading a file.

Thank you,

**Comment by FlorianJacta** [comment]
@jrobinAV We could do that!

**Comment by trgiangdo** [comment]
Should we close one as duplicated?
