### ISSUE TITLE
Show stack trace in job selector when job fails 

### ISSUE THREAD

**Issue by MariahLeone** [Avaiga/taipy#1251]
**What would that feature address**
When a job is failing, it is helpful to show the logs in the job selector to understand why the data is incorrect.

***Description of the ideal solution***
Display the job logs in a modal accessible from a job in the list

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Create related issue in taipy-doc for documentation and Release Notes
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it
- [ ] Ensure any change is well documented

**Comment by FlorianJacta** [comment]
It will be really useful; you are correct! Would having a visual element called *job* be the solution for you, or should it be totally integrated within the *job selector*?

**Comment by MariahLeone** [comment]
Integrated with the job selector is better, so all the job handling functionalities are supported with a single visual element. It is much easier to design a page when controls are integrated.

**Comment by yaten2302** [comment]
Hi @FlorianJacta, if this issue is still needed, then I would like to work on this, could you please assign this to me.
Also, could you please give some information on how to reproduce this issue.

**Comment by MariahLeone** [comment]
This is not an issue, but a new functionality asked.

When a job is failing, I would like to have a button in the job selector to display the job's logs and stacktrace.

**Comment by jrobinAV** [comment]
Here is the proposal: 

We want to add to the job selector a detail button for each job similarly to the following mockup:
![image](https://github.com/user-attachments/assets/d147d360-7dc7-41d3-a116-e8f9d51282c0)
This button should be controlled by a `on_detail` property deactivable or replacable by a gui callback.

By default clicking on a detail button should open a dialogue similar to the following mockup:
![image](https://github.com/user-attachments/assets/1b4777cc-9464-4b06-a406-2896d8db5925)

**Comment by jrobinAV** [comment]
Note that we want to take the opportunity of this issue to improve the UX of the job selector control.

In particular we want to use the label as the man information in each column instead of the id. The id would be the second level information and could be displayed like an ellipse.

**Comment by FredLL-Avaiga** [comment]
added a property `on_details`
- not set : adds a icon to the selector list that shows a dialog with details
- set to False: hide the icon
- set to a callback: calls the callback with the job id
on_details_callback(state: State, id: str, payload: {'action': 'on_details_callback', 'args': ['JOB_scenario_task_e2e9329d-2d2c-45fd-b2e0-64921b88a666']})

**Comment by jrobinAV** [comment]
Note that for now, only the stack trace is collected when the job fails. The logs are not collected. It may come later.
