### ISSUE TITLE
BUG-Cannot install version 3.1.1 with python 3.9 on window 10

### ISSUE THREAD

**Issue by jmarchand1** [Avaiga/taipy#1260]
**Description**

```
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\QS5526\PycharmProjects\taipy\venv\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\QS5526\\AppData\\Local\\Temp\\pip-install-bjgqiemj\\taipy-rest_4c966492dd954b62a0
de364a7ac88507\\setup.py'"'"'; __file__='"'"'C:\\Users\\QS5526\\AppData\\Local\\Temp\\pip-install-bjgqiemj\\taipy-rest_4c966492dd954b62a0de364a7ac88507\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exi
sts(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\QS5526\AppData
\Local\Temp\pip-pip-egg-info-v275dz57'
         cwd: C:\Users\QS5526\AppData\Local\Temp\pip-install-bjgqiemj\taipy-rest_4c966492dd954b62a0de364a7ac88507\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\QS5526\AppData\Local\Temp\pip-install-bjgqiemj\taipy-rest_4c966492dd954b62a0de364a7ac88507\setup.py", line 40, in <module>
        packages=find_packages(where=root_folder, include=["taipy", "taipy.rest", "taipy.rest.*"]),
      File "C:\Users\QS5526\PycharmProjects\taipy\venv\lib\site-packages\setuptools\__init__.py", line 64, in find
        convert_path(where),
      File "C:\Users\QS5526\AppData\Local\Programs\Python\Python39\lib\distutils\util.py", line 122, in convert_path
        if pathname[0] == '/':
    TypeError: 'WindowsPath' object is not subscriptable
    ----------------------------------------
```

**Comment by FlorianJacta** [comment]
What kind of Python environment are you using? Is it a clean environment? Did you have the same problem on 3.1.0?

I would suggest trying with a new Python environment.

**Comment by jmarchand1** [comment]
yes it's a virtual env dedicated for my application test.
Yes same problem with 3.1.0, i can only install 3.0.0
pip freeze:
alembic==1.13.1
aniso8601==9.0.1
apispec==5.2.2
apispec-webframeworks==0.5.2
appdirs==1.4.4
arrow==1.3.0
attrs==23.2.0
Automat==22.10.0
beautifulsoup4==4.12.3
bidict==0.23.1
binaryornot==0.4.4
blinker==1.8.1
certifi==2024.2.2
cffi==1.16.0
chardet==5.2.0
charset-normalizer==3.3.2
click==8.1.7
cloudpickle==3.0.0
colorama==0.4.6
constantly==23.10.4
cookiecutter==2.1.1
dask==2024.5.0
deepdiff==6.2.3
distributed==2024.5.0
dnspython==2.6.1
et-xmlfile==1.1.0
flask==3.0.3
Flask-Cors==4.0.0
flask-marshmallow==0.14.0
Flask-Migrate==3.1.0
Flask-RESTful==0.3.10
Flask-SocketIO==5.3.6
flask-sqlalchemy==3.1.1
frozendict==2.4.2
fsspec==2024.3.1
gevent==23.9.1
gevent-websocket==0.10.1
gitignore-parser==0.1.11
greenlet==3.0.3
h11==0.14.0
html5lib==1.1
hyperlink==21.0.0
idna==3.7
importlib-metadata==7.1.0
incremental==22.10.0
itsdangerous==2.2.0
Jinja2==3.1.3
jinja2-time==0.2.0
kthread==0.2.3
locket==1.0.0
lxml==5.2.1
Mako==1.3.3
Markdown==3.6
MarkupSafe==2.1.5
marshmallow==3.21.2
marshmallow-sqlalchemy==0.28.1
modin==0.29.0
msgpack==1.0.8
multitasking==0.0.11
networkx==2.8.8
numpy==1.26.4
openpyxl==3.1.2
ordered-set==4.1.0
orjson==3.10.3
packaging==24.0
pandas==2.2.2
partd==1.4.1
passlib==1.7.4
peewee==3.17.3
plotly==5.22.0
psutil==5.9.8
pyarrow==10.0.1
pycparser==2.22
pymongo==4.7.1
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-engineio==4.9.0
python-slugify==8.0.4
python-socketio==5.11.2
pytz==2024.1
pytz-deprecation-shim==0.1.0.post0
PyYAML==6.0.1
requests==2.31.0
simple-websocket==0.10.1
six==1.16.0
sortedcontainers==2.4.0
soupsieve==2.5
SQLAlchemy==2.0.29
taipy==3.0.0
taipy-config==3.0.0
taipy-core==3.0.0
taipy-gui==3.0.0
taipy-rest==3.0.0
taipy-templates==3.0.0
tblib==3.0.0
tenacity==8.2.3
text-unidecode==1.3
toml==0.10.2
toolz==0.12.1
tornado==6.4
twisted==23.10.0
twisted-iocpsupport==1.0.4
types-python-dateutil==2.9.0.20240316
typing-extensions==4.11.0
tzdata==2024.1
tzlocal==4.3.1
urllib3==2.2.1
webencodings==0.5.1
werkzeug==3.0.2
wsproto==1.2.0
yfinance==0.1.86
zict==3.0.0
zipp==3.18.1
zope.event==5.0
zope.interface==6.3

**Comment by FlorianJacta** [comment]
What kind of virtual env (conda, pipenv, ...) do you use? What are the commands you are writing? I want to replicate the behavior so that we could try to help you

**Comment by jmarchand1** [comment]
It s a Pycharm virtual env.
I have try these following command
pip install taipy, 
Or pip install taipy==3.1.1
Or pip install taipy==3.1.0
Thank you for your help

**Comment by FlorianJacta** [comment]
Hi, I have issues using Pycharm with Python 3.9 despite many attempts but unrelated to Taipy. Could you try to upgrade your Python to 3.11 version and tell us what you get from the `pip install taipy`?

**Comment by FlorianJacta** [comment]
Do you still have the issue?

**Comment by jmarchand1** [comment]
I have no the issue anymore, with python 3.11.9 and following pipi freeze:
aniso8601==9.0.1
apispec==6.4.0
apispec-webframeworks==1.0.0
arrow==1.3.0
attrs==23.2.0
Automat==22.10.0
beautifulsoup4==4.12.3
bidict==0.23.1
binaryornot==0.4.4
blinker==1.8.2
boto3==1.34.34
botocore==1.34.143
certifi==2024.7.4
cffi==1.16.0
chardet==5.2.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
constantly==23.10.4
cookiecutter==2.5.0
deepdiff==6.7.1
dnspython==2.6.1
et-xmlfile==1.1.0
Flask==3.0.2
Flask-Cors==4.0.0
Flask-RESTful==0.3.10
Flask-SocketIO==5.3.6
frozendict==2.4.4
gevent==23.9.1
gevent-websocket==0.10.1
gitignore_parser==0.1.11
greenlet==3.0.3
h11==0.14.0
html5lib==1.1
hyperlink==21.0.0
idna==3.7
incremental==22.10.0
itsdangerous==2.2.0
Jinja2==3.1.4
jmespath==1.0.1
kthread==0.2.3
lxml==5.2.2
Markdown==3.5.2
markdown-it-py==3.0.0
MarkupSafe==2.1.5
marshmallow==3.20.2
mdurl==0.1.2
multitasking==0.0.11
networkx==3.2.1
numpy==1.26.4
openpyxl==3.1.2
ordered-set==4.1.0
packaging==24.1
pandas==2.2.0
passlib==1.7.4
peewee==3.17.6
platformdirs==4.2.2
plotly==5.22.0
pyarrow==15.0.0
pycparser==2.22
Pygments==2.18.0
pymongo==4.6.1
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-engineio==4.9.1
python-slugify==8.0.4
python-socketio==5.11.3
pytz==2023.3.post1
PyYAML==6.0.1
requests==2.32.3
rich==13.7.1
s3transfer==0.10.2
simple-websocket==1.0.0
six==1.16.0
soupsieve==2.5
SQLAlchemy==2.0.25
taipy==3.1.0
taipy-config==3.1.0
taipy-core==3.1.0
taipy-gui==3.1.0
taipy-rest==3.1.0
taipy-templates==3.1.0
tenacity==8.5.0
text-unidecode==1.3
toml==0.10.2
Twisted==23.10.0
twisted-iocpsupport==1.0.4
types-python-dateutil==2.9.0.20240316
typing_extensions==4.12.2
tzdata==2024.1
tzlocal==5.2
urllib3==2.2.2
webencodings==0.5.1
Werkzeug==3.0.3
wsproto==1.2.0
yfinance==0.2.40
zope.event==5.0
zope.interface==6.4.post2

**Comment by FlorianJacta** [comment]
Great! This will maybe help people in the future!
