### ISSUE TITLE
Prototype - Explore the possibility to have page templates

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#1267]
**What would that feature address**
When creating a new application, developers usually design it iteratively, page by page. In such cases, the application templates ( nor the blueprint templates) don't help very much.

The purpose is to have the capability to scaffold pages on top of an existing application (or not).

The following questions must have an answer:
- How to insert new modules in existing applications?
- How to modify existing files?
- How to handle the singleton configuration if it exists?
- How to manage the application version?

**Acceptance Criteria**
- [x] Create a prototype to evaluate the technical feasibility.
- [x] Append the [requirement document](https://docs.google.com/document/d/1w3WW7S-9lYsGdlABtk5SEnEBZyn5XQUT3q9ZPUh2mQw/edit#heading=h.5wavqi9lptet)

**Comment by trgiangdo** [comment]
There is a prototype which shown that the feature is feasible in either community or enterprise version.

We need to discuss about which template to add to this feature and where the page is located.

**Comment by trgiangdo** [comment]
After discussion with the CS team, we agree that there are some page templates that can have some value in enterprise.

There will be an Epic created to follow up with the discussion.
