### ISSUE TITLE
BUG-Styling table cells are not working

### ISSUE THREAD

**Issue by gorkemalgan** [Avaiga/taipy#1279]
**Description**
I want to set the color of each cell in the table. As I see setting color for entire rows is straightforward and works as expected. 
However, styling table cells with style[column_name] is not working. I confirm that all 5 arguments are passed correctly to cell_style, however, in the end table cells are not colored. 

Plus, it is not clear how to set colors for different cells for different columns separately? I could not find any explanations in the docs either. Do we need to create a separate style[column_name] function for each column? This is not practical. Can't we just provide a function that is being called for each cell with row_num and column_num?

**How to reproduce**
```python
import taipy.gui as tg

x_range = range(-10, 11, 4)
data = {
    "x": x_range,
    "y1": [x * x for x in x_range],
    "y2": [100 - x * x for x in x_range],
}

# Code block for coloring cells separately, which does not work
def cell_style(state, value, index, row, column_name):
    if index % 2:
        return "blue-cell"
    else:
        return "red-cell"
tg.Gui(page=tg.Markdown("<|{data}|table|style[y1]=cell_style|>")).run(port=5001)


# # Code block for coloring whole rows, which works as expected
# def even_odd_style(_1, index, _2):
#     if index % 2:
#         return "blue-cell"
#     else:
#         return "red-cell"
# tg.Gui(page=tg.Markdown("<|{data}|table|style=even_odd_style|>")).run(port=5001)

```

.css file that holds color info
```css
.blue-cell>td {
    color: white;
    background-color: blue;
}
.red-cell>td {
    color: yellow;
    background-color: red;
}
```

**Expected behavior**
Coloring cells in the y1 color of the table

**Screenshots**
When I run coloring for whole rows (commented code block in the above code)
<img width="1727" alt="Screenshot 2024-05-12 at 15 17 36" src="https://github.com/Avaiga/taipy/assets/26520871/58fa7db9-625d-4306-bc26-27eee0e3d5c0">

When I run coloring for cells seperately
<img width="1716" alt="Screenshot 2024-05-12 at 15 17 20" src="https://github.com/Avaiga/taipy/assets/26520871/47f66e77-0bed-411a-9da4-2dea62e72ff5">

**Runtime environment**
Please specify relevant indications.
 - Taipy version: 3.1.1
 - OS: MacOS
 - Browser: Chrome

**Comment by FredLL-Avaiga** [comment]
you need to remove the `>td` part of your css declaration

**Comment by gorkemalgan** [comment]
> you need to remove the `>td` part of your css declaration

removing it does not fix the problem either

**Comment by FlorianJacta** [comment]
![image](https://github.com/Avaiga/taipy/assets/98709993/2cc7f820-a347-419a-bba5-05971aa0caf0)

Removing the *td* fixed the issue for me.

```
.blue-cell {
    color: white;
    background-color: blue;
}
.red-cell {
    color: yellow;
    background-color: red;
}
```
