### ISSUE TITLE
[Core-GUI] Visualize scenario as a graph in the Scenario control

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy#128]
**Description**

Extention to the base Scenario control (see #110).
The Scenario control would have a graph representation of its DAG.
This graph cannot be edited or modified or anything.
It would render in a as similar way as possible to what appears in Taipy Studio.

**Acceptance Criteria**
- [ ] The Scenario graph is displayed under the Scenario property list.
- [ ] Documentation is updated.

**Comment by jrobinAV** [comment]
THe data should be retrieve from Core using an API to be opened with 
[ticket #559](https://github.com/Avaiga/taipy-core/issues/559)
