### ISSUE TITLE
Ability to disable notifications for *file_selector*

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1283]
**Description**
A user requested to disable notifications for file_selector. When uploading a file, an automatic notification is created. In this use case, the user would want to disable it and replace it with its notification (with the *notify* function).

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
what about `notify` property ?

**Comment by FlorianJacta** [comment]
Oh, it is already in develop.
