### ISSUE TITLE
Error notifications should not close themselves

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1288]
Error notifications show important information to help debug the app that does not show up in the terminal.

For example, when I receive this notification:
![image](https://github.com/Avaiga/taipy/assets/62465003/3c6126d9-0576-44da-b62e-05283d431b47)
It disappears 3 seconds later, and the error message does not show up in the terminal

Error notifications should not disappear on their own, the user should close them manually instead

**Comment by FlorianJacta** [comment]
Irrelevant, you are the one to code it with *on_exception*

**Comment by AlexandreSajus** [comment]
I did not notice that I coded the notification and I could manually choose the delay
