### ISSUE TITLE
Scenario selector - Sort scenarios

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#1301]
Here's an example: I am doing a what-if analysis on a neural network by changing the parameter alpha. When I create a new scenario, "alpha 2.00", it gets put at the top of the list instead of being ordered alphabetically. The end user should be able to sort scenarios in the scenario_selector.

![core_issues_1_1](https://github.com/Avaiga/taipy/assets/62465003/3c1de549-ac37-436f-80d8-6c992615ccbe)

**Comment by FredLL-Avaiga** [comment]
[Spec](https://docs.google.com/document/d/19R0SiykrlGALWU9ONDdtmni4PNBmJ-95s9i755FhWgg/edit?usp=sharing)
