### ISSUE TITLE
Scenario selector - Search bar

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#1305]
### Description

We want a search bar in the scenario selector to help end-users quickly find scenarios.

### Solution Proposed

A search property is exposed to activate/deactivate the search bar. By default, it is activated.

When an end-user provides text in the search bar (the search input), the system finds matching scenarios (the search result). The matching is performed using the scenario labels. Only the scenarios containing the search input must appear in the search result.
Neither the search input nor the search result are shared among end-users. The search bar acts as a client-side filter on the list of scenarios to display, so the bound variables are not modified.

Default: By default, the developer should not need to do anything:
```<| {selected_scenario} | scenario_selector |>```

Deactivate: If he/she wants to deactivate the filtering mechanism:
```<| {selected_scenario} | scenario_selector | search=False |>```

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [x] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
This does *not* align with the spec document at all. Where is the truth ? @jrobinAV

**Comment by jrobinAV** [comment]
Yes, it does. 
[search requirements](https://docs.google.com/document/d/19R0SiykrlGALWU9ONDdtmni4PNBmJ-95s9i755FhWgg/edit#heading=h.2ws1ofcaf2z0). 
But this ticket has not been discussed in details.

Maybe you are confused with #1301 , no?

**Comment by FredLL-Avaiga** [comment]
> Yes, it does. 
> [search requirements](https://docs.google.com/document/d/19R0SiykrlGALWU9ONDdtmni4PNBmJ-95s9i755FhWgg/edit#heading=h.2ws1ofcaf2z0). 
> But this ticket has not been discussed in details.
> 
> Maybe you are confused with #1301 , no?

Oups sorry 
I mixed sort and search :-(

**Comment by jrobinAV** [comment]
"Sorry and search"? or "sort and search"? 🤣
