### ISSUE TITLE
Analytics: Use remote default favicon

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#1327]
## Description

Gui can use an image hosted on a Taipy server for the default favicon. Each time a GUI application is launched, the browser tries to fetch this image. If no favicon is found on the remote, whatever the reason, if possible, use a local favicon provided with the package so we can still run the app without internet access if needed.

The icon could be stored in Git Hub, which would make it transparent for users and allow Git Hub to process the information for use directly.
## Motivation

The purpose is to get Taipy usage information with metadata for better analytics. The analytics part will be done in another ticket.

EDITED:
Link to the favicon: https://github.com/Avaiga/taipy-assets/blob/develop/favicon.png

EDITED: Add some documentation to explain how to change the favicon and use a local one for unconnected users.

**Comment by florian-vuillemot** [comment]
We'll use 2 images to differentiate between the one used by the application and the one only scrolled by the robots.
When merged, we need to update our traffic analyzer to retrieve traffic data from the taipy-assets repository and perform repository usage analyses.

**Comment by FredLL-Avaiga** [comment]
is it possible to get the new favicon in the following formats:
- 64x64px ico format
- 192x192px png format
both with transparent background

**Comment by FredLL-Avaiga** [comment]
URL is https://raw.githubusercontent.com/Avaiga/taipy-assets/develop/favicon.png

**Comment by jrobinAV** [comment]
> is it possible to get the new favicon in the following formats:
> 
> * 64x64px ico format
> * 192x192px png format
>   both with transparent background

@RymMichaut can you provide these?

**Comment by FredLL-Avaiga** [comment]
not sure it is necessary anymore, I used what's available
