### ISSUE TITLE
[Refactor] Default stylekit applies too much margin to text

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1331]
### Description

The text control applies too much margin with the default stylekit, which leaves a lot of vertical space empty. For example, the code:
```python
tgb.text("# Taipy\n# x 🤖GPT-4o", mode="md")
```
Results in:
![image](https://github.com/Avaiga/taipy/assets/62465003/d0cb3d4e-779d-42c4-b4f3-0cf4d7b07f01)

The two lines are too spaced out for a single break line. This issue seems to be caused by the too large margin:
![image](https://github.com/Avaiga/taipy/assets/62465003/3587586d-4c6a-4107-9ab1-2b8de1c4dad4)

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by AlexandreSajus** [comment]
This is very noticeable in chats:
![image](https://github.com/Avaiga/taipy/assets/62465003/5827567c-23c0-4051-8c5f-5b972a94e9a1)

**Comment by Satoshi-Sh** [comment]
Can I take this issue?

**Comment by FlorianJacta** [comment]
I am not sure this is a bug if you talk about titles. But you are right for the bullet points

**Comment by AlexandreSajus** [comment]
The code is available here: https://github.com/Avaiga/demo-gpt-4o

**Comment by AlexandreSajus** [comment]
Not an issue, the space between the bullet points in my image is caused by my code, can't reproduce
![image](https://github.com/Avaiga/taipy/assets/62465003/fa2eae50-2e93-4fd9-8cb4-a1ab7277208f)
