### ISSUE TITLE
[🐛 BUG] Chart disappears after a change

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1339]
### What went wrong? 🤔

When a chart is changed/updated, the chart disappears.

### Expected Behavior

The charts should not disappear.

### Steps to Reproduce Issue

Run the code below and change the slider value. The chart disappears.

```python
from taipy.gui import Gui
from math import cos, exp

value = 10


page = """
# Taipy *Getting Started*

Value: <|{value}|text|>

<|{value}|slider|on_change=on_slider|>

<|{data}|chart|>
"""

def on_slider(state):
    state.data = compute_data(state.value)

def compute_data(decay:int)->list:
    return [cos(i/6) * exp(-i*decay/600) for i in range(100)]

data = compute_data(value)

Gui(page).run(title="Frontend Demo")
```

![image](https://github.com/Avaiga/taipy/assets/98709993/6e84de48-c1c3-47c9-a8ad-d600e1d04f1d)

### Browsers

Chrome

### OS

Windows

### Version of Taipy

develop-5/30/2024

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create a related issue in taipy-doc for documentation and Release Notes if relevant.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by arcanaxion** [comment]
I opened an issue for this in #1064. 

I also noticed this:

> This bug is not present when installing the latest release (3.1.1) from whl. But it is still present if I build from the 3.1.1 source commit. Any ideas? Node version: v20.12.1

**Comment by FredLL-Avaiga** [comment]
It looks like it might be caused by the latest version of plotly.js...

**Comment by FlorianJacta** [comment]
@arcanaxion I did not have this problem a few weeks ago installing from develop

**Comment by FredLL-Avaiga** [comment]
If you install from develop and reinstall all the npm dependencies you'll get the latest plotly.js which brings this unwanted behavior :-(
