### ISSUE TITLE
[🐛 BUG] Screenshot in Markdown issue report

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1340]
### What went wrong? 🤔

Dropping screenshots or images in the "Screenshot" section is impossible.

### Expected Behavior

It must be possible to dropdown images in the screenshot section.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by jrobinAV** [comment]
Duplicate issue ?
https://github.com/Avaiga/taipy/issues/1306

**Comment by FlorianJacta** [comment]
I changed my issue to not be a duplication.
