### ISSUE TITLE
Scenario Selector - Default filters should be consistent with config 

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1343]
### Description

The goal of this issue is to improve the UX of Scenario Selector filters. Some filters are for example not useful when not using cycles:

- primary
- cycle label
- cycle start
- cycle end

These filters should not be shown as they were not used in this case.

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by ioannastantzou** [comment]
i think i could also investigate this one , could i be assinged??

**Comment by FlorianJacta** [comment]
The R&D is putting these issue with other one as Staff only. Maybe this issue could be of interest to you: https://github.com/Avaiga/taipy/issues/1314 

I know you asked to contribute to Taipy many times and we thank you for that.

**Comment by ioannastantzou** [comment]
sure thank you!
