### ISSUE TITLE
[🐛 BUG] <center> tag not working in Markdown files

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1351]
### What went wrong? 🤔

Users can no longer use the center tag inside Markdown files in CRLF mode. This is a regression.

![image](https://github.com/Avaiga/taipy/assets/98709993/50ec8d2e-5722-4c56-b3a6-f95999131b3e)

This is what can be seen in the Python console:

```
[2024-06-04 10:35:31.237][Taipy][INFO] Detected 'ascii' encoding for file 'c:\Users\jacta\OneDrive\Bureau\taipy\Code\basic-demo\gui\t.md'.
[2024-06-04 10:35:31.436][Taipy][INFO]  * Server starting on http://127.0.0.1:5000
```

### Expected Behavior

The text should be centered.

### Steps to Reproduce Issue

*t.md*:

Working in LF: 
[t.md](https://github.com/user-attachments/files/15545591/t.md)

Not working in CRLF: 
[t.md](https://github.com/user-attachments/files/15545635/t.md)

```
<center>
Hello world
</center>
```

*t.py*
```python
from taipy.gui import Gui, Markdown

md = Markdown('t.md')

Gui(md).run(title="Frontend Demo")
```

### Browsers

Chrome

### OS

Windows

### Version of Taipy

Develop 5/31/2024

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create a related issue in taipy-doc for documentation and Release Notes if relevant.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
I suppose the issue is not present with markdown string ?
```
from taipy.gui import Gui, Markdown

Gui("<center>Hello world</center>").run(title="Frontend Demo")
```

**Comment by FlorianJacta** [comment]
It is not. In fact, if the Markdown is in LF mode I have no issues. This is surely related to this issue: https://github.com/Avaiga/taipy/issues/1255

[t.md](https://github.com/user-attachments/files/15545587/t.md)
