### ISSUE TITLE
[Refactor] Data Node Selector - Default filters should be consistent with config 

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1352]
### Description

The goal of this issue is to improve the UX of Data Node Selector filters. Some filters are for example not useful when not using validity period:

- expired
- expiration date

These filters should not be shown as they were not used in this case.

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by ioannastantzou** [comment]
hi could i be assigned?
