### ISSUE TITLE
[🐛 BUG] Delete no response in issue forms template

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1357]
### What went wrong? 🤔

Sections without responses shouldn't be shown. It makes it hard to view the issue.

### Expected Behavior

Empty sections appear in the description after the issue creation.

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create a related issue in taipy-doc for documentation and Release Notes if relevant.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by ranjanmangla1** [comment]
new to project, can I take this one?

**Comment by AdityaS8804** [comment]
Hey, I'd like to contribute to this. Is it still open?

**Comment by jrobinAV** [comment]
Hello @AdityaS8804 ,

Yes, the issue is still up for contribution. It would be great if you could solve this, as I don't know how.
Let me assign you the issue.

Thank you,

**Comment by AdityaS8804** [comment]
Hey,

From what I have read, GitHub issue form YAML doesn’t support conditional rendering. A potential fix is to use GitHub Actions to remove unused sections after submission. However, this:
- Runs post-submissoin, which may confuse users.
- Increases action usage, potentially affecting our plan limits.
Would you suggest going ahead with GitHub Actions for this, or do you have alternative ideas? Looking forward to your input.

Thanks,

**Comment by jrobinAV** [comment]
Hi,

Even with the drawbacks you mentioned, I believe the GitHub Action method you propose is better than what we have today. If you can proceed, that would be great.

Thank you.

**Comment by Aanchallllll** [comment]
Hello,
would like to contribute.can i be assigned?

**Comment by AdityaS8804** [comment]
Hey,
I'm working on this issue at the moment. But it would be great to have your input in this matter.

**Comment by FlorianJacta** [comment]
> Hello, would like to contribute.can i be assigned?

@AdityaS8804 You have been assigned to another issue. For hacktoberfest, we only assign issues one at a time. Please submit a PR on the other issue first, or remove your assignment.

Thank you.

**Comment by AdityaS8804** [comment]
> > Hello, would like to contribute.can i be assigned?
> 
> @AdityaS8804 You have been assigned to another issue. For hacktoberfest, we only assign issues one at a time. Please submit a PR on the other issue first, or remove your assignment.
> 
> Thank you.


Hi,

It seems there might be a misunderstanding. I'm currently assigned to this issue and I am actively working on it. I'll raise a PR as soon as possible.

Thank you.

**Comment by FlorianJacta** [comment]
@AdityaS8804 You are right! Sorry for that, we receive a lot of spam. Please take your time, your proposal was great 😄

**Comment by Harish-2003** [comment]
Is this issue still open if yes can I work on it

**Comment by FlorianJacta** [comment]
It is done thanks to @AdityaS8804 !
