### ISSUE TITLE
[DOCS] Create a "Docker" label

### ISSUE THREAD

**Issue by ioannastantzou** [Avaiga/taipy#1361]
### Issue Description

Since Docker is a something used more and more , I consider it important to create a specific place to report vulnerabilities and possible improvements for it.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
We normally used DevOps as a label to handle this kind of issues. Do you think it is too vast?

**Comment by ioannastantzou** [comment]
hey ! yes maybe its too vague in my opinion , I considered it useful while building taipy's docker image.

**Comment by trgiangdo** [comment]
We are talking about Github labels right?

If we add the "Docker" label, we may also add "GH Action", "Kubernetes", "Ray", "Azure", "AWS", "Podman", ...

The purpose of labels is to categorizing and filtering. For now, we don't have enough issues with these labels to specifically categorize them in different labels.
I would not add those.

**Comment by ioannastantzou** [comment]
okay got it thank you!
