### ISSUE TITLE
Use Github Actions for labeling.

### ISSUE THREAD

**Issue by ioannastantzou** [Avaiga/taipy#1362]
### Description

Creating worflow files with all the labels gathered , the process of potential modification will be simplified.

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
Could you elaborate on what the aim is?

**Comment by ioannastantzou** [comment]
just a thought for easier management and easier to work with in case of  change!

**Comment by trgiangdo** [comment]
When editing a label, the workflow will update all issues with the old label to the new label?

I think that's already supported by Github

**Comment by jrobinAV** [comment]
I don't understand the issue. Are we talking about GitHub labels? What is the link with GitHub actions?

**Comment by trgiangdo** [comment]
I don't think it does
