### ISSUE TITLE
[🐛 BUG] Cannot use Page Builder's dialog() in a context manager

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1387]
### What went wrong? 🤔

It is not possible to use the dialog as a block.

```
Traceback (most recent call last):
  File "c:\Users\jacta\OneDrive\Bureau\taipy\Code\TTT-SDM-Interview\src_complete\h.py", line 8, in <module>
    with tgb.dialog(open="{open_modal}"):
  File "C:\Users\jacta\.conda\envs\develop\lib\site-packages\taipy\gui\builder\_element.py", line 189, in __enter__
    raise RuntimeError(f"Can't use Context Manager for control type '{self._ELEMENT_NAME}'")
RuntimeError: Can't use Context Manager for control type 'dialog'
```

### Expected Behavior

We should be able to use the syntax below because ` dialog()` is not a Context Manager.

### Steps to Reproduce Issue

```python
from taipy import Core, Gui
import taipy.gui.builder as tgb


open_modal = False

with tgb.Page() as page:
    with tgb.dialog(open="{open_modal}"):
        tgb.text("Hello")


if __name__ == "__main__":
    gui = Gui(page=page)
    gui.run(title="Sales Prediction", port=1221)
```

### Version of Taipy

develop - 6/10/24 (M/D/Y)

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by yaten2302** [comment]
Hey @FlorianJacta, I would like to work on this issue, could you please assign it to me?
Also, could you please elaborate a bit on using 'dialog as a block'. I've understood this partially, but I'm not able to completely understand that what exactly is the problem?
As far as I've understood according to [taipy docs](https://docs.taipy.io/en/latest/manuals/gui/viselements/dialog/), the `on_action` property return -1, 0, 1 or  for closing, validating, cancelling respectively, am I right?

**Comment by FlorianJacta** [comment]
@yaten2302 I have updated the issue. The problem is that you cannot use it inside the context manager. I will show you the Markdown syntax and the Python API.

Markdown syntax that works:

```python
page = """
<|dialog|open={open_modal}|
Hello
|>
"""
```

Here, it is not working with a `with`.
```python
with tgb.Page() as page:
    with tgb.dialog(open="{open_modal}"):
        tgb.text("Hello")
```

We will maybe put this issue in *Staff Only*.

**Comment by yaten2302** [comment]
I'll try to work on some other issues, if this one is Staff Only 👍

**Comment by FredLL-Avaiga** [comment]
The problem here is that dialog is a control *and* a block
