### ISSUE TITLE
[🐛 BUG] Can't select data nodes in data node selector

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1388]
### What went wrong? 🤔

I can't select and view these data nodes:
![image](https://github.com/Avaiga/taipy/assets/62465003/adabd09a-fff8-44c6-9f2b-e4e379785310)

I can select initial_dataset without issue

### Steps to Reproduce Issue

Use this code:

[app.zip](https://github.com/user-attachments/files/15785399/app.zip)

1. pip install taipy develop
2. run app.py
3. In the interface, create a scenario and submit it
4. In the data node page, try to select a node of the scenario, it will not appear in the data node viewer

### Runtime Environment

Windows 11

### Browsers

Chrome

### OS

Windows

### Version of Taipy

develop

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
Can you share some code ?

**Comment by FlorianJacta** [comment]
I am putting this as critical as it breaks applications/demos.
