### ISSUE TITLE
Color outline to indicate task execution state in scenario dag

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1389]
### Description

The scenario dag tasks could have outline colors to indicate in which state they are in when the scenario is submitted:
- yellow means "pending"
- orange means "running"
- green means "ran"
- red means "errored"
- nothing means "not pending"

![image](https://github.com/Avaiga/taipy/assets/62465003/5a4eada1-9a4f-4507-83c5-0466c62dfb0a)

For example, here it would mean that clean_data has ran without issue, predict is currently running and evaluate will be ran afterwards.

This is very similar to a product an INCREDIBLE engineer made (or Zerve):
![flow_example](https://github.com/Avaiga/taipy/assets/62465003/7e48934b-d584-4459-8973-38840f776bc8)

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by jrobinAV** [comment]
This feature is interesting, but I believe we need to have to put it into a global context. We need to redefine global requirements for the dag.

Examples of questions that need to be answered globally:
- The Orange box is a Task, not a job. There is no such thing as a Task state. You can have a Job status (pending, running, failed, etc.). A Task can be linked to multiple jobs, submitted by multiple users, eventually running simultaneously. Which Job should be chosen to represent in the dag?
- What is the added value, and for who?
The two big differences I can see with the tool you showed are the multi-user context and the targeted user. In your picture, you are in a development environment (IDE or notebook). There is only one user concerned, a developer. The UX is easy. The dag control is for a web application for multiple end-users. What is exactly the end user's need related to the job status?

**Comment by FlorianJacta** [comment]
You wanted to add features to the DAG. Who was the target of these features?

I agree that we must know what this is for and, most importantly, for whom. In my opinion, it is a better UX to show the progress of your scenario inside the DAG. It is more visual.

We could provide a selector of submissions, and when a submission on the scenario is created, the DAG represents the submission being run.

**Comment by FredLL-Avaiga** [comment]
This is implemented. Can you comment on the current implementation?

**Comment by AlexandreSajus** [comment]
What is implemented? I just ran a scenario with develop and the dag does not have color outlines:
![image](https://github.com/Avaiga/taipy/assets/62465003/25ed20f8-00d6-428a-a825-050d20b256df)

**Comment by FredLL-Avaiga** [comment]
The tasks change colors when the corresponding job change status

**Comment by FabienLelaquais** [comment]
@FlorianJacta @AlexandreSajus 
Please come up with a (SHORT) code sample.

**Comment by FlorianJacta** [comment]
I have not been able to reproduce the issue with different codes.

I guess it has to use the standalone mode for Core. I am closing this issue for now and we'll reopen if it comes back again.
