### ISSUE TITLE
Adding color_range_step Property to Metric Component

### ISSUE THREAD

**Issue by namnguyen20999** [Avaiga/taipy#1396]
![Image](https://github.com/Avaiga/taipy/assets/36433663/fe2f86be-375e-4a4e-91b2-aac7f388db3b)

### Overview
We are proposing the addition of a new property called `color_range_step` to the metric component. This feature aims to enhance the visual representation of metric data by allowing users to define specific colors for defined value ranges.

### Purpose
The `color_range_step` property will enable users to customize the color of metric values based on their range. This can improve data readability and highlight important thresholds, making it easier to interpret and analyze metrics at a glance.

```
color_map = {
    20: "red",
    40: None,
    60: "green",
    80: None
}

page = """
<|50|metric|color_range_step={color_map}|>
"""
```

**Comment by FabienLelaquais** [comment]
Changed the comments.
Context: min=0, max=100

`<|{v}|metric|color_map={color_map}|>`

```
color_map = {
    # 0-20 - Let Plotly decide
    # 20-40 - red
    20: "red",
    # 40-60 - Let Plotly decide
    40: None,
    # 60-80 - green
    60: "green",
    # 80-100 - Let Plotly decide
    80: None
}
```
in short:
```
color_map = {
    20: "red",
    40: None,
    60: "green",
    80: None
}
```
