### ISSUE TITLE
LaTeX in text control

### ISSUE THREAD

**Issue by anquetos** [Avaiga/taipy#1401]
### Description

Add the possibilty to use LaTeX within the pages using this type of expression :
`$$ your equation $$`

This could be interesting to display the equation at the origin of a calculation made in our Taipy app.

### Solution Proposed

Add a 'latex' mode to the `text` control.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by sumanth-tccc** [comment]
This would really be helpfull

**Comment by kaze-droid** [comment]
Can I take this issue for Hacktoberfest and DevFest AI?

**Comment by jrobinAV** [comment]
@kaze-droid Thank you for your help.
