### ISSUE TITLE
[🐛 BUG] Pandas Timestamp not compatible with Data Node viewer

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1410]
### What went wrong? 🤔

Pandas Timestamps are not supported by the Data Node viewer. Nothing shows up in the Data Node viewer.

### Expected Behavior

We should see at least that the Data Node was selected with a message saying that this data can not be viewed or directly support this type. 

### Steps to Reproduce Issue

Clone this [repo](https://github.com/FlorianJacta/TTT-SDM-Interview/tree/main/src_complete), run the main.py, and submit the scenario. The date cannot be selected.

### Screenshots

![image](https://github.com/Avaiga/taipy/assets/98709993/cadb988c-deb7-48f2-accf-ae814af6d2c2)

### Browsers

Chrome

### OS

Windows

### Version of Taipy

Develop - 6/14/24

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
Is this still true ?

**Comment by FlorianJacta** [comment]
This has been solved!
