### ISSUE TITLE
[🐛 BUG] Submission status in Scenario Viewer not updating properly

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1419]
### What went wrong? 🤔

The Submission Status is sometimes not appropriately aligned with the current jobs' statuses. For example, the status is "blocked" even if all the jobs have been completed.

Here is my scenario viewer:

![image](https://github.com/Avaiga/taipy/assets/98709993/1ae00677-629f-49a0-86be-f792a7ba94ef)

Here are my jobs (all of them are completed):

![image](https://github.com/Avaiga/taipy/assets/98709993/a6bda304-8097-46a0-a3a4-69461671341f)

### Expected Behavior

The status should properly reflect the status of the submission/jobs.

### Steps to Reproduce Issue

This happens when the scenario is more complex. I wasn't able to replicate it with a simple example. Here is some code to test it out.

https://github.com/FlorianJacta/TTT-SDM-Interview/tree/main/src_complete

Run main.py, create a scenario, and submit it. Then, you can see the status of the scenario viewer and the jobs' status inside the job selector.

### Version of Taipy

develop - 6/17/24

### Acceptance Criteria

- [ ] Ensure the new code is unit tested, and check that the code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by jrobinAV** [comment]
I don't know if it is a problem or if it can help, but here is some information.
The updates of submissions' statuses and jobs' statuses rely on different core events published one after the other. So they are consumed one after the other as well. This can imply a latency between job status refresh and submission status refresh.

**Comment by FlorianJacta** [comment]
Maybe. I notice a latency also. But here the submission status will never be changed.

**Comment by FredLL-Avaiga** [comment]
A first investigation shows that the right message is sent from the backend but not always received :-(
