### ISSUE TITLE
[🐛 BUG] `on_change` of selector not working

### ISSUE THREAD

**Issue by failable** [Avaiga/taipy#1422]
### What went wrong? 🤔

The `on_change` function of selector is not working.

### Expected Behavior

The `on_change` function of selector should work. 

### Steps to Reproduce Issue

Test code:

```python
import taipy.gui.builder as tgb
from taipy.gui import Gui


def on_change(state, var, val):
    print(state)
    print(var)
    print(val)


if __name__ == "__main__":
    collection_names = ["collection1", "collection2", "collection3"]
    with tgb.Page() as page:
        tgb.selector(
            label="Collection",
            lov=";".join(collection_names),
            dropdown=True,
            on_change=on_change,
        )

    Gui(page=page).run(
        dark_mode=False,
        debug=True,
        use_reloader=True,
        port=5001,
    )

```

### Runtime Environment

macOS 14.5 (23F79), Chrome Version 125.0.6422.142 (Official Build) (x86_64)

### Browsers

Chrome

### OS

Mac

### Version of Taipy

taipy==3.1.1 taipy-config==3.1.1 taipy-core==3.1.1 taipy-gui==3.1.2 taipy-rest==3.1.1 taipy-templates==3.1.1

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
Hi, your selector is not bound to any variable. This behavior is normal.

I have bound your selector to a variable called *selected_collection*. Try this code and tell me if this works:

```python
import taipy.gui.builder as tgb
from taipy.gui import Gui

def on_change(state, var, val):
    print(var)
    print(val)


if __name__ == "__main__":
    collection_names = ["collection1", "collection2", "collection"]
    selected_collection = None
    with tgb.Page() as page:
        tgb.selector(
            value="{selected_collection}",
            label="Collection",
            lov=collection_names,
            dropdown=True,
            on_change=on_change,
        )

    Gui(page=page).run(
        dark_mode=False,
        debug=True,
        use_reloader=True,
        port=5001,
    )
```

**Comment by failable** [comment]
@FlorianJacta Thanks, that works!

**Comment by FlorianJacta** [comment]
Great to hear! You can now access your real-time variable *selected_collection* in any callback.
