### ISSUE TITLE
[🐛 BUG] step function in slider not working

### ISSUE THREAD

**Issue by pradeepinani** [Avaiga/taipy#1428]
### What went wrong? 🤔

We we provide step details for slider the code shows error. It does not throw error in execution but step functionality does not work. The code used is given as follows
<|{vari}|slider|min=0|max=200|step=5|change_delay=2000|orientation=hori|on_change=sliderchange|>

![2024-06-18_09h42_40](https://github.com/Avaiga/taipy/assets/173182825/e7c95c4b-0401-4e5d-b016-b6e0411cc10f)

### Steps to Reproduce Issue

1. A code fragment
2. And/or configuration files or code
3. And/or Taipy GUI Markdown or HTML files

### Screenshots

![image](https://github.com/Avaiga/taipy/assets/173182825/e71b147e-a97b-490e-b7e5-4c570066afa8)

### Version of Taipy

3.1.1

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
Thank you @pradeepinani ! The code syntax highlight is not blocking. Does the actual code work?

```python
from taipy.gui import Gui 

vari = 0

md = "# Step slider\n <|{vari}|slider|min=0|max=200|step=5|>"

Gui(md).run(port=2452)
```

Try this one, for example. Does the step mechanism work in the application?

**Comment by FlorianJacta** [comment]
Do you have any news on this issue? @pradeepinani

**Comment by yaten2302** [comment]
I tried this code, it's working for me @FlorianJacta 👍

**Comment by pradeepinani** [comment]
Will try next week, I am out travelling.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by FlorianJacta** [comment]
Closing this issue, don't hesitate to open it back!
