### ISSUE TITLE
The number visual element number should have property type step.

### ISSUE THREAD

**Issue by pradeepinani** [Avaiga/taipy#1429]
### Description

The visual element Number should have property type step, buy this feature we can define the increment or decrement by each click. Default should be in 1 incase number is a whole number. 

### Solution Proposed

- New `step` property indicating the increment for each up or down tick (default 1).
- New `step_multiplier` property indicating how much to multiply `step` when the Shift key is press while clicking the down or up arrow (default 10).

### Impact of Solution

If some one defaults 0.8 as number and wants to make it 0.6 or 1.3, then they would define increment step as 0.1 and thus by each click of  it would increase or decrease by .1 (needed at many places). with The current arrangement the number changes by 1. Manual overwriting of number can be avoided/saved by this additional functionality. There would be more flexibility to user.

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
I like this feature!

**Comment by FlorianJacta** [comment]
We could even add a min and max property to the number control.

**Comment by pradeepinani** [comment]
Yes, that will also help when process requires number validation to be in a defined range. It will also reduce errors in user input to a number field.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
