### ISSUE TITLE
Is Taipy.io down?

### ISSUE THREAD

**Issue by yaten2302** [Avaiga/taipy#1433]
### What went wrong? 🤔

Taipy.io is not working in the normal window, but it's working sometimes in the Incognito window.

Here are some screenshots of the website in normal and incognito window <br>
*Normal Window*
![image](https://github.com/Avaiga/taipy/assets/129659514/9463689c-40e4-43bf-8c4c-e32b6d2c7bb4)

*Incognito Window*
![image](https://github.com/Avaiga/taipy/assets/129659514/1fe508bd-d8c2-4f4e-9d37-c14e66879c62)

I've tried this on 3 devices and same issue is there in all 3 of them.

### Expected Behavior

Taipy.io should be working both in normal and incognito windows

### Runtime Environment

Chrome Version: 126.0.6478.114

### Browsers

Chrome

### OS

Windows

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
Really weird!

**Comment by yaten2302** [comment]
@FlorianJacta, is this issue on you side also or there might be a problem with my system?

**Comment by FlorianJacta** [comment]
It works fine for me. I have asked @RymMichaut

**Comment by jrobinAV** [comment]
@yaten2302 Removing the cookies (shift+F5 on Chrome Windows) fixed the issue for me.

**Comment by yaten2302** [comment]
Yes, now it's working @jrobinAV 👍
