### ISSUE TITLE
Accept Pandas Series in lov property

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1444]
### Description

A user had an issue putting a Pandas Series as a Lov property, as it is not allowed. A better warning has been issued since the 3.1 release. Accepting a Pandas series as a potential value for the Lov property would be great.

```python
from taipy.gui import Gui
import pandas as pd

data = pd.DataFrame({"Countries":["France", "Germany", "Italy", "Spain"],
                     "Population": [65, 83, 59, 47]})
selected = data["Countries"][0]
selection = data["Countries"]

page = "<|{selected}|selector|lov={selection}|dropdown|>"

Gui(page).run(port="auto")

```

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by Satoshi-Sh** [comment]
Can I take this issue?

**Comment by FlorianJacta** [comment]
It has not been approved by R&D. @FredLL-Avaiga @FabienLelaquais what do you think?

**Comment by FredLL-Avaiga** [comment]
I guess it makes sense

**Comment by FlorianJacta** [comment]
Ok, I will assign it to you @Satoshi-Sh

**Comment by FlorianJacta** [comment]
Waiting for an answer from @FabienLelaquais
