### ISSUE TITLE
[🐛 BUG] Check if old versions have the numpy issue

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#1462]
### What went wrong? 🤔

Recently, a numpy error appeared in develop. To fix it, we had to update the Pipfile with some new dependencies.

The problem probably appeared in previous versions: 2.0, 2.1, 2.2, 2.3, 2.4, 3.0, 3.1. 
We have to check for each single version to see if the problem appears, and if it does, we have to update and release a patch version.

- [ ] List all the versions where the problem appears
- [ ] Patch a new version for each version.

### Code of Conduct

- [x] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by trgiangdo** [comment]
The problem seems to be on taipy since taipy 2.1.0
Which means we will have to release a patch for 2.1, 2.2, 2.3, 2.4, 3.0, 3.1.

**Comment by jrobinAV** [comment]
At least 2.0 is not impacted. :/
