### ISSUE TITLE
integrate component react with markdown

### ISSUE THREAD

**Issue by carza06** [Avaiga/taipy#1463]
### What would you like to share or ask?

I made a component datetime-local in react and added it to a markdown of taipygui, but it doesn't grab the value of the component, what should I do?

taipy_gui:
``` 
<|{btn_from_date_destinations}|example.date_input|>
```
button react:
```js
         <input
            type="datetime-local"
            className="custom-datetime-input css-1weoyhk css-1weoyhk"
            onChange={handleChange}
            // value={dateTime}
          />
```

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
Have you read [this documentation](https://docs.taipy.io/en/latest/manuals/gui/extension/)?

**Comment by carza06** [comment]
yes, but i have a problem, I see the component in markdown but taipy does not take the date I choose

**Comment by FlorianJacta** [comment]
@FabienLelaquais @FredLL-Avaiga Would you be able to help? Here is a question related with more code: https://github.com/Avaiga/taipy/discussions/1465

**Comment by FredLL-Avaiga** [comment]
We'll need a bit more context.
How is the component declared in the library? 
How is it declared in react (props) ?

**Comment by FabienLelaquais** [comment]
I have commented the [Discussion part](https://github.com/Avaiga/taipy/discussions/1465) of this to get more information.

**Comment by jrobinAV** [comment]
I am closing the issue since it is covered by the [discussion](https://github.com/Avaiga/taipy/discussions/1465).
