### ISSUE TITLE
[OTHER] No module named 'taipy.gui' while running taipy application in Google Colab 

### ISSUE THREAD

**Issue by pravintargaryen** [Avaiga/taipy#1506]
### What would you like to share or ask?

I am trying to run a basic taipy application in Google Colab using ngrok by following the docs https://docs.taipy.io/en/latest/tutorials/integration/2_colab_with_ngrok/. However I get the  **No module named 'taipy.gui'** error during run.

![1](https://github.com/Avaiga/taipy/assets/96950453/98d00fe4-9f89-4f0c-99cb-7e56f81bfeb7)
![2](https://github.com/Avaiga/taipy/assets/96950453/cb637189-c897-42c0-a605-084b328a2271)

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
Try this [documentation](https://docs.taipy.io/en/latest/installation/#installing-taipy-with-colab). The problem could be that the environment have not been restarted when you downloaded Taipy. You can also use `pip list` to see the downloaded packages inside your Colab environment.

**Comment by FlorianJacta** [comment]
Did it solve your issue? Can this issue be closed?

**Comment by FlorianJacta** [comment]
No answer from user
