### ISSUE TITLE
The ability to filter and sort scenarios in scenario selector according to data node contents

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1511]
### Description

Zach created a custom scenario selector that displays a summary table of your scenarios with the content of some of their data nodes.

This selector is helpful because it is easy to find the scenario I want from the list. I can also easily filter where "Promotion?" is True and sort by "Air Pollution" in descending order.

![image](https://github.com/user-attachments/assets/2f41fee1-f9f2-49f7-ab96-9c137f27b4e9)

### Solution Proposed

The scenario selector visual element can only sort and filter according to tags. It would be helpful if the scenario selector had a property `filter_dn` associated with a list of data node names. These would be data node names on which the end user could filter and sort his scenarios. For example, it would be `<|{scenario}|scenario_selector|filter_dn=Promotion?;Air Pollution|>`.

### Impact of Solution

The idea here is to allow the user to filter and sort his scenarios without having to create callbacks to define proper tags. Also, since the dev defines which data nodes to filter, he can ensure that the user does not try to sort complex data structures.

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
this is supported

**Comment by FlorianJacta** [comment]
How?

**Comment by FredLL-Avaiga** [comment]
&lt;datanode>.property (define in filter)

Defined [here](https://docs.google.com/document/d/19R0SiykrlGALWU9ONDdtmni4PNBmJ-95s9i755FhWgg/edit?usp=sharing)

**Comment by FlorianJacta** [comment]
The issue is to discuss whether this is enough or not. Having a property on the data node content will duplicate information. I don't think `<datanode>.property ` allows you to read the data node directly.

**Comment by FredLL-Avaiga** [comment]
After discussion, the filters have been enhanced in their description and support.
We now provide 3 classes
- ScenarioFilter: filter on a scenario property or databnode value) 
- ScenarioDatanodeFilter: filter on datanode property value
- ScenarioCustomFilter: filter on the value returned by a function that takes the scenario as a parameter
