### ISSUE TITLE
Possibility to use decimator on Plotly charts

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1515]
### Description

The goal would be to allow users to use the decimator alongside Plotly charts.

```python
import yfinance as yf
from taipy.gui import Gui
from taipy.gui.data.decimator import MinMaxDecimator, RDP, LTTB


df_AAPL = yf.Ticker("AAPL").history(interval="1d", period = "max")
df_AAPL["DATE"] = df_AAPL.index.astype('int64').astype(float)

n_out = 50
decimator_instance = MinMaxDecimator(n_out=n_out)

decimate_data_count = len(df_AAPL)

import plotly.express as px

fig = px.line(df_AAPL, x="DATE", y="Open", markers=True)

page = """
# Decimator

From a data length of <|{len(df_AAPL)}|> to <|{n_out}|>

## Without decimator

<|chart|figure={fig}|>

## With decimator

<|chart|figure={fig}|decimator=decimator_instance|>
"""

gui = Gui(page)
gui.run(port=5026, title="Decimator")

```

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by dinhlongviolin1** [comment]
We wont be applying directly for the fig. But, we might expose the decimator so the user can apply it themselves.

**Comment by FlorianJacta** [comment]
What do you mean?

**Comment by dinhlongviolin1** [comment]
it is an on going PR but you will get it soon enough with a proper API
![unnamed](https://github.com/user-attachments/assets/742aeb91-4a61-4415-926f-879b561881f4)
![unnamed-2](https://github.com/user-attachments/assets/1d777eca-6616-4047-8cb7-24b33a75fd1f)

**Comment by FlorianJacta** [comment]
Great news!
