### ISSUE TITLE
[🐛 BUG] port="auto" does not work everytime

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1519]
### What went wrong? 🤔

Sometimes, when using `port="auto"`, an error arises and stops the application from being run.

```python
[2024-07-15 14:39:11.409][Taipy][INFO]  * Server starting on http://127.0.0.1:57990
 * Serving Flask app 'Taipy'
 * Debug mode: on
An attempt was made to access a socket in a way forbidden by its access permissions
```

### Expected Behavior

It would be best if it works everytime.

### Steps to Reproduce Issue

Put `port="auto"` on an app and test many times.

### Version of Taipy

develop - 7/15/24

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

The problem may come from a backend configuration issue, which is NOT our responsibility.

Plan could be to extend the 'port' syntax to a comma-separated list of ports or port ranges - simplifying avoiding wrong firewall settings.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by dinhlongviolin1** [comment]
We will be adding a port range option so you can declare your own range
