### ISSUE TITLE
Possibility to swap colors for metric viz elements

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1520]
### Description

Sometimes, if the delta is negative, it is good, and the associated color should be green, not red.

In this example, we want to decrease the cost and carbon footprint so the metric should indicate that this solution is good. The color associated with that should be green and not red.

![image](https://github.com/user-attachments/assets/b3907d52-ac12-4cbf-a0ee-040c46a16813)

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by Satoshi-Sh** [comment]
Can I take take this issue?

**Comment by FlorianJacta** [comment]
This has not been discussed internally yet. What do you think @FabienLelaquais and @FredLL-Avaiga ?

**Comment by FabienLelaquais** [comment]
That sounds like a very reasonable feature requirement.
Providing a full fledge API to indicate what color should be used depending on the value of delta seems a bit overkill at this point. But it would make sense. Like: red if delta <= -10, yellow if -10 < delta < 10; green if delta >= 10).

The positive/negative value of delta sounds like something that would be the most valuable use case.
So let's go for it.

I would create two new properties `positive_delta_color` and `negative_delta_color` (although those property names are rather long), that would be strings (dynamic don't seem useful) indicating the color to be used in both cases.

If @FredLL-Avaiga agrees, I think you're good to go, @Satoshi-Sh !

**Comment by FredLL-Avaiga** [comment]
> That sounds like a very reasonable feature requirement. Providing a full fledge API to indicate what color should be used depending on the value of delta seems a bit overkill at this point. But it would make sense. Like: red if delta <= -10, yellow if -10 < delta < 10; green if delta >= 10).
> 
> The positive/negative value of delta sounds like something that would be the most valuable use case. So let's go for it.
> 
> I would create two new properties `positive_delta_color` and `negative_delta_color` (although those property names are rather long), that would be strings (dynamic don't seem useful) indicating the color to be used in both cases.
> 
> If @FredLL-Avaiga agrees, I think you're good to go, @Satoshi-Sh !

I do

**Comment by Satoshi-Sh** [comment]
> I would create two new properties positive_delta_color and negative_delta_color (although those property names are rather long), that would be strings (dynamic don't seem useful) indicating the color to be used in both cases. 

I was thinking about reverse_delta_color(boolean) and it switches the default colors of negative(red) and positive(green).  

Is it better to have two properties as you mentioned?
@FabienLelaquais

**Comment by FabienLelaquais** [comment]
Well... my proposal is only (?) one more property, and makes things far more flexible wouldn't you say?

**Comment by FabienLelaquais** [comment]
Thanks a great lot for your help on this one @Satoshi-Sh!

**Comment by Satoshi-Sh** [comment]
Thanks for the guidance. I learned a lot from this issue.
