### ISSUE TITLE
[🐛 BUG] Lambda expression not working with new line

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1522]
### What went wrong? 🤔

Lambda expressions are not working for no reason.

The second selector is not working.

![image](https://github.com/user-attachments/assets/4f83a3f7-a6f8-433b-8a18-e9fdd69c03ff)

### Expected Behavior

It should work.

### Steps to Reproduce Issue

```python
from taipy.gui import Gui 
import taipy.gui.builder as tgb

value: int = 10
value_selector = 10


def get_list(value):
    return [str(i) for i in range(value)]

with tgb.Page() as page:
    # Works
    tgb.selector(value="{value_selector}", lov=lambda value: get_list(value))

    # don't work
    tgb.selector(value="{value_selector}",
                 lov=lambda value: get_list(value))


Gui(page=page).run(title="Frontend Demo")


```
### Browsers

Chrome

### OS

Windows

### Version of Taipy

develop - 7/15/24

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
I think I know why
