### ISSUE TITLE
Improve style of metric control

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1535]
### Description

Having two metrics takes all my page. Metric takes 100% of my screen. This is unusable by itself. 

![image](https://github.com/user-attachments/assets/d480aa23-29af-43d9-80d8-2b3a55897408)

The size must be configurable.

This should look like this by default:

![image](https://github.com/user-attachments/assets/409ff477-6749-4c50-8de6-c31a599d3c05)

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
Is this still an issue @FlorianJacta ?

**Comment by FlorianJacta** [comment]
What has changed? I believe it is still an issue

**Comment by FredLL-Avaiga** [comment]
You used metrics in your demo on Friday and they looked fine

**Comment by FlorianJacta** [comment]
I used the layout and height property to adjust it. There is also an issue that the metric component doesn't work because the height is too small. By default, I don't think it is so great
