### ISSUE TITLE
[🐛 BUG] Stylekit is not applied for text with mode="md" 

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1553]
### What went wrong? 🤔

Some styles in the Stylekit (through the class_name) are not applied when mode="md" is set for text visual element. This prevents the user from changing the text element like he wants.

The issue comes from a user: https://github.com/Avaiga/taipy/discussions/1547

### Expected Behavior

The class_name/stylekit should be applied for all styles even with mode="md".

### Steps to Reproduce Issue

Style don't work:

```python
import taipy.gui.builder as tgb 
from taipy import Gui 

x = {"a": {"b": {"": 1}}}

with tgb.Page() as page:
    with tgb.layout('5*1', gap='2.0rem'):
        card_style = 'card pb0 m0'
        heading_style = 'text-right h5 color-primary pb0'
        number_style = 'text-right h1 pb0'
        with tgb.part(card_style):
            tgb.text("**Headline**", class_name=heading_style, mode="md")
            tgb.text("{x['a']['b']['']}", format='%.0f', class_name=number_style, "mode="md")

Gui(page).run()
```
![image](https://github.com/user-attachments/assets/c8443d75-cc27-4e64-aee7-03dbce770f6e)

Works (but without the Markdown format:
```python
import taipy.gui.builder as tgb 
from taipy import Gui 

x = {"a": {"b": {"": 1}}}

with tgb.Page() as page:
    with tgb.layout('5*1', gap='2.0rem'):
        card_style = 'card pb0 m0'
        heading_style = 'text-right h5 color-primary pb0'
        number_style = 'text-right h1 pb0'
        with tgb.part(card_style):
            tgb.text("**Headline**", class_name=heading_style)
            tgb.text("{x['a']['b']['']}", format='%.0f', class_name=number_style)

Gui(page).run()
```
![image](https://github.com/user-attachments/assets/2ea37083-1ca5-4e05-81c6-2f0bd0b7eb96)

### Solution Proposed

This seems to come from a *<p>* tag surrounding the text and not being a *span* like the normal visual element.

### Version of Taipy

3.1.1 / Develop

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
It seems legit that HTML elements are added when in markdown mode (that's the point of markdown: generate HTML tags) and that one would have to set styles differently ...

**Comment by Satoshi-Sh** [comment]
Can I take this issue?

**Comment by jrobinAV** [comment]
Sure

**Comment by Satoshi-Sh** [comment]
I have a question. `tgb.text` with md mode is related to the Field.tsx component using reac-markdown?  

![Screenshot from 2024-10-08 13-11-02](https://github.com/user-attachments/assets/ed58d1c9-947d-4842-8b97-b550d2ec7116)

I updated this code but the behavior doesn't change. Let me know if I'm missing something. Thanks. 

@FredLL-Avaiga

**Comment by FredLL-Avaiga** [comment]
Yes it is
Did you rebuild the frontend bundle?

**Comment by Satoshi-Sh** [comment]
Yes, I rebuilt it. I will try again.

UPDATE
I found an eslint error. That's why I couldn't see the change.

**Comment by Satoshi-Sh** [comment]
I tried to fix this issue but there seems no reasonable solution after talking with Fred. I closed my PR. You may change the state of the issue. @jrobinAV Thanks

**Comment by FredLL-Avaiga** [comment]
won't fix:
Stylekit classes usually cannot be applied to text in mode "md" because the markdown creates new tags inside the div that receives the stylekit classes.for example any simple text in md mode will be rendered as `<div data-comment="from text comp" class="taipy-text stylekit classes"><p>{text value}</p></div>`
Some stylekit classes might have an effect but I would recommend to not use them and use direct styling of the component via CSS.
