### ISSUE TITLE
Rename Core service to Orchestrator

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#1567]
## Motivations 
- Today, the Core service only runs the dispatcher after some checking (config and version). 
- The name `Core` is not meaningful. People don't know what is done behind the scenes. On the contrary, the term Orchestrator is explicit.
- Running the service is only necessary for task orchestration, not for scenario mgt or data integration. You can have some data nodes and scenarios, and you can read, write, and compare them without submitting anything. In this case, you don't need to run Core service. Having it named Orchestrator makes it easier to document.

Note that the package core must remain unchanged.

## TODO

- Rename the class to Orchestrator. The Orchestrator class would be the public facade for the _Orchestrator, the _Dispatcher, and their Factory.
- Rename the corresponding variables
- Rename the tests and their variables
- Change the documentation (User man, Ref man, tutorials)
- Change the demos and gallery

**Comment by toan-quach** [comment]
do we also want to rename `CoreSection` to `OrchestratorSection`, `CoreEvent` to `OrchestratorEvent` and `CoreCLI` to `OrchestratorCLI`?

**Comment by trgiangdo** [comment]
The `CoreCLI` only contains options related to the version mode. It's not Core nor Orchestrator CLI. I'm not sure about the naming now.

We already have a different `_VersionCLI` for version management, which is different though.

**Comment by jrobinAV** [comment]
> do we also want to rename `CoreSection` to `OrchestratorSection`, `CoreEvent` to `OrchestratorEvent` and `CoreCLI` to `OrchestratorCLI`?

I would not. 
-> The `CoreSection` is dedicated to the core package and not to the job orchestration.
-> The events are not related to orchestration either.

**Comment by jrobinAV** [comment]
> The `CoreCLI` only contains options related to the version mode. It's not Core nor Orchestrator CLI. I'm not sure about the naming now.
> 
> We already have a different `_VersionCLI` for version management, which is different though.

I would keep CoreCLI since it is the related to the way we run the core package. :/

**Comment by jrobinAV** [comment]
I reopened the issue because of the documentation part.

**Comment by jrobinAV** [comment]
Another PR related to this issue: 
https://github.com/Avaiga/taipy-doc/pull/1098
