### ISSUE TITLE
[OTHER] Broken link in README.md

### ISSUE THREAD

**Issue by ThibautPV** [Avaiga/taipy#1569]
### What would you like to share or ask?

Hello,

Link to https://docs.taipy.io/en/latest/knowledge_base/demos/movie_genre_selector/ (anchor "Demo") is broken in README.md file

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
Which README.md file are you talking about?

**Comment by ThibautPV** [comment]
This : https://github.com/Avaiga/taipy/blob/develop/README.md
