### ISSUE TITLE
Data Node viewer - Add parent label next to data node label

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1571]
### Description

The goal is to add the data node's parent next to its label in the Data Node viewer.

Here, I am displaying two data nodes from different scenarios, but they look the same:

![image](https://github.com/user-attachments/assets/983e1d50-4e9a-4bef-a550-b02654f26790)

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

**Comment by jrobinAV** [comment]
Two labels are available for each entity: the `simple label`, which is used today, and the `label`, which is made of the concatenation of the parent label and the simple label.

This change must be configurable. By default, we want the simple label to be displayed and by configuration, the developer may chose to use the label.

Does it make sense?

**Comment by FlorianJacta** [comment]
Why not.

**Comment by FredLL-Avaiga** [comment]
![Image](https://github.com/user-attachments/assets/8859c7d3-12a8-41b8-a27b-6effa652457d)
