### ISSUE TITLE
Block the interface 

### ISSUE THREAD

**Issue by carza06** [Avaiga/taipy#1579]
### What would you like to share or ask?

Is it possible to block the interface with taipy.gui while an action occurs?

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FabienLelaquais** [comment]
Please check https://docs.taipy.io/en/latest/manuals/reference/taipy.gui.hold_control/.
That might answer that question.

Thanks you for closing this issue if you consider this an answer.

**Comment by carza06** [comment]
thanks, it helped me
