### ISSUE TITLE
Chat control height property should force widget height regardless of messages

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1586]
### Description

Setting height when using the chat control should limit the chat window's height regardless of the messages' size. Currently, it overflows:
![image](https://github.com/user-attachments/assets/283b5f3d-d228-449c-beb4-698c5382a1cb)

The chat window should have a fixed size defined by the height property:
![image](https://github.com/user-attachments/assets/40e63d95-480c-46d6-9f42-3283661af22c)

Take https://demo-llm-chat.taipy.cloud/ as reference

Example code (just type long messages to reproduce):
```python
from taipy.gui import Gui, Icon

msgs = [
    ["1", "msg 1", "Fred"],
    ["2", "msg From Another unknown User", "Fredo"],
    ["3", "This from the sender User", "taipy"],
    ["4", "And from another known one", "Fredi"],
]

users = [
    ["Fred", Icon("/images/favicon.png", "Fred.png")],
    ["Fredi", Icon("/images/fred.png", "Fred.png")],
]


def button_action(state, var_name: str, payload: dict):
    args = payload.get("args", [])
    msgs.append([f"{len(msgs) +1 }", args[2], "Fred"])
    state.msgs = msgs


Gui(
    """
<|{msgs}|chat|users={users}|on_action=button_action|height=300|sender_id=Me|>
""",
    path_mapping={"images": "c:\\users\\jeu\\downloads"},
).run()
```

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
@AlexandreSajus Did you try specifying height with an unit
ex: 300px or 40vh ...

**Comment by FredLL-Avaiga** [comment]
```
from taipy.gui import Gui, Icon

msgs = [
    ["1", "msg 1", "Fred"],
    ["2", "msg From Another unknown User", "Fredo"],
    ["3", "This from the sender User", "taipy"],
    ["4", "And from another known one", "Fredi"],
]

users = [
    ["Fred", Icon("/images/favicon.png", "Fred.png")],
    ["Fredi", Icon("/images/fred.png", "Fred.png")],
]


def button_action(state, var_name: str, payload: dict):
    args = payload.get("args", [])
    msgs.append([f"{len(msgs) +1 }", args[2], "Fred"])
    state.msgs = msgs


Gui(
    """
<|{msgs}|chat|users={users}|on_action=button_action|height=50vh|sender_id=Me|>
""",
    path_mapping={"images": "c:\\users\\jeu\\downloads"},
).run(title="1686 chat height")

```

**Comment by FredLL-Avaiga** [comment]
But I get you, it would be nice that `height=300` => `height=300px`
As the doc says hight can be str, int or float
