### ISSUE TITLE
[DOCS] Chat control should be documented

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1588]
### Issue Description

The chat control should be documented with code examples. Giving examples on how to style the chat (change font, font size, icon size...) would be a big plus

https://docs.taipy.io/en/develop/manuals/userman/gui/viselements/generic/chat/
![image](https://github.com/user-attachments/assets/c7067033-13da-4d91-86d2-2b1c33e85f5d)

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FabienLelaquais** [comment]
This is a duplicate of [taipy-doc#971](https://github.com/Avaiga/taipy-doc/issues/971).
