### ISSUE TITLE
[Refactor] Chat control should scroll down to focus on the last message when a new message appears

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1589]
### Description

When a new message appears in the chat control, the chat control should scroll to the last message. This assumes that #1586 is fixed. Use https://demo-llm-chat.taipy.cloud/ as reference: when I receive a new message from GPT, the chat window scrolls down to the message and highlights it:
![image](https://github.com/user-attachments/assets/cf4a951e-05ea-4318-8b7d-3b16a1d1509d)

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by heysolomon** [comment]
> ### Description
> When a new message appears in the chat control, the chat control should scroll to the last message. This assumes that #1586 is fixed. Use https://demo-llm-chat.taipy.cloud/ as reference: when I receive a new message from GPT, the chat window scrolls down to the message and highlights it: ![image](https://private-user-images.githubusercontent.com/62465003/352265370-cf4a951e-05ea-4318-8b7d-3b16a1d1509d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MzI2NjYsIm5iZiI6MTcyNjkzMjM2NiwicGF0aCI6Ii82MjQ2NTAwMy8zNTIyNjUzNzAtY2Y0YTk1MWUtMDVlYS00MzE4LThiN2QtM2IxNmExZDE1MDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDE1MjYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZjcxZjRkNTBlNjk3ZmU4YjAyOTQxNzRlMDQ3YjI5NjM1YzNkOTBkMmM5MTcyOGY1ODFkMDVkMDg3YmU2NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FYuRdGXVaM3g8BYnoeXEhfOqpz9hMnH-2_EQVFug4JA)
> 
> ### Acceptance Criteria
> * [ ]  Ensure new code is unit tested, and check code coverage is at least 90%.
> * [ ]  Propagate any change on the demos and run all of them to ensure there is no breaking change.
> * [ ]  Ensure any change is well documented.
> 
> ### Code of Conduct
> * [x]  I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
> * [ ]  I am willing to work on this issue (optional)

Okay, so what is the expected behaviour? it shouldn't scroll and highlight the chat?

**Comment by jrobinAV** [comment]
@AlexandreSajus @FredLL-Avaiga Is this issue done already?

**Comment by FredLL-Avaiga** [comment]
yes it is
if the content is scrolled to the bottom it then shows new messages when they're added
