### ISSUE TITLE
When processing images with larger sizes, notify does not display

### ISSUE THREAD

**Issue by Sillyyk** [Avaiga/taipy#1590]
### What went wrong? 🤔

```python
def fix_image(state):
       state.fixed = False
      # this notify can be displayed
       notify(state, 'info', '运行中，请等待！')

       fixed_image = inference(
        input_image=state.image,
        denoise_steps=int(state.advanced_properties['denoise_steps']),
        prompt=str(state.advanced_properties['prompt']),
        a_prompt="clean, high-resolution ,8k",
        n_prompt="blurry, dotted, noise, raster lines, unclear, lowres, over-smoothed",
        upscale=int(state.advanced_properties['upsample_scale']),
        alpha=int(state.advanced_properties['conditioning_scale']),
        cfg=int(state.advanced_properties['classier_free_guidance']),
        seed=random.randint(0, 5000000000),
    )
    # # this notify cant be displayed but not enter except
    try:
        notify(state, 'success', 'inference操作完成！')
    except Exception as e:
        print(f"Error in notify: {e}")

    state.fixed_image = convert_image(fixed_image)
    state.fixed = True
    print("完成!")
```

When this function is called, the latter notify does not output and display, and the picture results are not displayed, but the function runs normally and is completed.
If I use a very small image everything works fine.

### Expected Behavior

want to know why and how to deal with it

### Steps to Reproduce Issue

1. A code fragment
2. And/or configuration files or code
3. And/or Taipy GUI Markdown or HTML files

### Solution Proposed

Is it because the cache is not enough or something else?

### Version of Taipy

Version: 3.1.1

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [x] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
When a function takes too much time, it can disconnect itself from the *state*. To avoid that you can asynchronous call ( or Taipy Core). Check this article and see if this fixes your issue: https://docs.taipy.io/en/release-3.1/tutorials/visuals/4_long_callbacks/

**Comment by Sillyyk** [comment]
> When a function takes too much time, it can disconnect itself from the _state_. To avoid that you can asynchronous call ( or Taipy Core). Check this article and see if this fixes your issue: https://docs.taipy.io/en/release-3.1/tutorials/visuals/4_long_callbacks/

Thank you for your reply. Initially, I have adjusted 'use_deloader=True' to solve the problem in a short period of time. I will study your advice carefully.

**Comment by FabienLelaquais** [comment]
Hi @Sillyyk 
Did the read that @FlorianJacta recommended give you the answer to your initial question?
(namely, if the backend is busy processing something - like running an algorithm on a large dataset - then the frontend may suffer from a lack of responsiveness)

Thanks!

**Comment by Sillyyk** [comment]
> Hi @Sillyyk Did the read that @FlorianJacta recommended give you the answer to your initial question? (namely, if the backend is busy processing something - like running an algorithm on a large dataset - then the frontend may suffer from a lack of responsiveness)
> 
> Thanks!

Thanks for your reply. Yes, I saw his suggestion and will try to solve this problem when I have time.

**Comment by Sillyyk** [comment]
> Hi @Sillyyk Did the read that @FlorianJacta recommended give you the answer to your initial question? (namely, if the backend is busy processing something - like running an algorithm on a large dataset - then the frontend may suffer from a lack of responsiveness)
> 
> Thanks!

Can I close this issue?

**Comment by FlorianJacta** [comment]
If this works for you, yes! Otherwise, no.
