### ISSUE TITLE
Open ScenarioConfig API to export a scenario config graph as a picture.

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#1592]
The purpose of this issue is to let developers draw a scenario config DAG using matplotlib (or an alternative) and networkx to visualize the graph he just created, helping him understand if it is correct.

### Description

In the `ScenarioConfig` class (located at `taipy/core/config/scenario_config.py`), we want a new method named `draw()` that exports the scenario configuration graph (a DAG) as an image file.

The graph comprises the input `DataNodeConfigs`, the output `DataNodeConfigs`, and the `TaskConfigs` as nodes. 
There is a directed edge from a `DatanodeConfig` node to a `TaskConfig` node if and only if the `DatanodeConfig` is a `TaskConfig` input. 
A directed edge is from a `TaskConfig` node to a `DatanodeConfig` node if and only if the `DatanodeConfig` is a `TaskConfig` input.

### Implementation constraint.

If a new package is required (matplotlib?, marmaid?, etc.), it must be made optional. The `draw` function should check the presence of the package before using it. If the package is not installed, the `draw` function should log a warning message and return doing nothing else.

https://networkx.org/documentation/stable/reference/drawing.html

**Comment by FabienLelaquais** [comment]
I certainly don't like this idea, involving both the import of another (large) package but also impacts the global product homogeneity, as Taipy GUI and Taipy Studio already provide ways of representing DAGs.
Why chose a technology that we don't already use?

**Comment by HimangshuYadav** [comment]
@quest-bot loot #1932

**Comment by HimangshuYadav** [comment]
@quest-bot embark

**Comment by xyfer17** [comment]
@jrobinAV could you please assign this issue to me, I would like to take this up.

**Comment by satyyam11** [comment]
@quest-bot loot #1592

**Comment by jrobinAV** [comment]
Yep sure, you are assigned, @xyfer17 .

**Comment by jrobinAV** [comment]
### Description

In the `ScenarioConfig` class, we want a new method named `draw()` that exports the scenario configuration graph as an image file.

The graph comprises the input `DataNodeConfigs`, the output `DataNodeConfigs`, and the `TaskConfigs` as nodes. There is a directed edge from a `DatanodeConfig` node to a `TaskConfig` node if and only if the `DatanodeConfig` is a `TaskConfig` input. There is a directed edge from a `TaskConfig` node to a `DatanodeConfig` node if and only if the `DatanodeConfig` is a `TaskConfig` input.

### Implementation constraint.

If a new package is required, it must be made optional. The `draw` function should check the presence of the package before using it. If the package is not installed, the `draw` function should log a warning message and return doing nothing else.

**Comment by satyyam11** [comment]
Hey can you assign me this

**Comment by xyfer17** [comment]
@jrobinAV can you please tell me that image format should be a svg or png ( mention if any other format is suitable ), also what would be the warning log message please specify?

**Comment by jrobinAV** [comment]
@xyfer17 The functionality is really for developers, not for end-users, so I don't think the image format matters. 
Both `svg` or `png` are good. By the way, the format could also be an optional parameter to the draw method with one of the two as a default value. 

If you need an external package with a specific version range, and if the package is not installed, the log message could be: 
```
f"Package '{package_name}' between version '{min_version}'and '{max_version}' is required to use the draw method. Please install the package first."
```
