### ISSUE TITLE
[DOCS] Getting Started with Taipy Page --Run Command

### ISSUE THREAD

**Issue by pravintargaryen** [Avaiga/taipy#1593]
### Issue Description

It would be nice if Getting Started Page has a line or two for command to start the Taipy application so that it would be easy for new Developers to get started right away. Right now the code ends with the below line and one has to navigate to https://docs.taipy.io/en/latest/manuals/cli/run/ 

if __name__ == "__main__":
    Gui(page=page).run(title="Dynamic chart")

### Screenshots or Examples (if applicable)

![taipy](https://github.com/user-attachments/assets/3ebc3bb8-7a89-40bb-aed0-1ef5223c3c7d)

### Proposed Solution (optional)

Nice to have somthing like this in the Getting Started Page (https://docs.taipy.io/en/latest/getting_started/)

![taipy1](https://github.com/user-attachments/assets/3d33712d-7971-4e18-8f57-07a143cbe4fe)

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
This seems really reasonable!

**Comment by jrobinAV** [comment]
I like the idea as well.

**Comment by Satoshi-Sh** [comment]
Can I take this issue?

**Comment by FlorianJacta** [comment]
Here you go, @Satoshi-Sh; thank you for taking this issue!

**Comment by Satoshi-Sh** [comment]
Thanks, Florian.

I have trouble running taipy-doc and created the issue https://github.com/Avaiga/taipy-doc/issues/1142 . I will work on this once I can run the doc.

**Comment by Satoshi-Sh** [comment]
Thanks for the guidance, @jrobinAV  You can close this issue.
