### ISSUE TITLE
Apply same style across all Taipy GUI applications

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy#1597]
### Description

At this time, we have no mean to create a stylesheet that can be applied systematically to all Taipy GUI applications.
Code is mandatory to do that.

### Solution Proposed

If a CSS file called `taipy.css` sits next to the Python script running Taipy GUI (`<app>.py`) that is being run, and there is no `<app>.css` file next to it, then `taipy.css` is loaded with all the application pages.

### Impact of Solution

Legacy applications run in `taipy.py` will behave the same way.
However, other scripts sitting next to this one would now load the CSS file, which was not the case before.

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
Is this not the aim of the Stylekit?

**Comment by FabienLelaquais** [comment]
> Is this not the aim of the Stylekit?

Kind of. But how do you then apply the same Stylekit settings across apps?
And what if you don't want the Stylekit?

**Comment by jrobinAV** [comment]
I am not sure this answers the question, but can't we leverage the taipy create command line?
We can ask the developer if he/she wants to use the default CSS. That could also be the default choice.

What do you think?
