### ISSUE TITLE
[SEO] Hide reference manual pages and non-latest pages from Google Search

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1611]
### Issue Description

We got a support ticket about documentation. Someone looked on Google for Taipy table doc and stumbled onto this page and complained that there was no information on the page: https://docs.taipy.io/en/release-3.0/manuals/reference/taipy.gui.builder.table/

This is because it is a reference manual page and not the page he was looking for (also it is a 3.0 page instead of latest). The page he was looking for is this one: https://docs.taipy.io/en/latest/manuals/gui/viselements/table/#__tabbed_1_3

Is there any way to not expose on Google search ref manual pages and non latest pages? This is not the first time we have had this issue

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#version-warning

**Comment by AlexandreSajus** [comment]
Only showing the latest release is the important part. For the other part of the issue, ref man pages for visual elements should have a big button that redirects to the doc of the visual element

**Comment by jrobinAV** [comment]
Split in two other issues
