### ISSUE TITLE
[🐛 BUG] Switching scenario does not change displayed data node

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1614]
### What went wrong? 🤔

I have a Taipy application with a scenario_selector. That scenario selector has an on_change callback, which sets the "demand" data node displayed in the data node viewer to the selected scenario. When I switch between two scenarios with different "demand" data nodes, the data node viewer does not change.

![image](https://github.com/user-attachments/assets/3014261a-f85a-4959-a43e-04a16b58c8cb)

### Expected Behavior

The scenario selector has the following on_change callback:
```python
def scenario_change(state: State):
    state.demand_dn = state.scenario.demand
    refresh_results_of_scenario(state)
```
This callback should be properly triggered and should change the contents of the data node viewer that displays "demand_dn"

### Steps to Reproduce Issue

1. Clone the demo repo
```bash
git clone https://github.com/Avaiga/demo-workforce-plan.git
```
2. Install the develop version of Taipy
```bash
pip install git+https://github.com/Avaiga/taipy.git
```
3. Install requirements
```bash
pip install -r requirements.txt
```
4. Run main.py
```
python main.py
```
5. Create a new scenario using the scenario selector. The data node viewer will now show the data node of the new scenario with "Sunday - 50". When switching between the "Default Scenario" and the new scenario, the data node viewer content does not change

### Browsers

Chrome

### OS

Windows

### Version of Taipy

develop

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
This code works with the *develop* version.

```python
# Import necessary libraries
import pandas as pd
import taipy as tp
from taipy import Config, Scope, Frequency
from taipy.gui import notify
import time

import datetime as dt

Config.configure_job_executions(mode="standalone", max_nb_of_workers=2)

# Function to run a Dataiku scenario
def run_something(input_1, input_2):
    datetime = dt.datetime.now()
    date = dt.date(2018, 1, 1)
    int_var = 10
    string_var = "String"
    return datetime, date, int_var, string_var


data = {"toto": [i for i in range(10_000)], 
        "titi": [2*i for i in range(10_000)],
        "tata": [4*i for i in range(10_000)]}

data_2 = {"toto": [2*i for i in range(10_000)], 
        "titi": [i for i in range(10_000)],
        "tata": [3*i for i in range(10_000)]}


input_1_cfg = Config.configure_data_node(
    id="input_1_data_node",
    default_data=1,
)


input_2_cfg = Config.configure_data_node(
    id="input_2_data_node",
    default_data=data,
)

datetime_cfg = Config.configure_data_node(id="datetime_data_node")
date_cfg = Config.configure_data_node(id="date_data_node")
int_cfg = Config.configure_data_node(id="int_data_node")
string_cfg = Config.configure_data_node(id="string_data_node")


# Scenario and task configuration in Taipy
scenario_task_cfg = Config.configure_task(
    id="scenario_task",
    function=run_something,
    input=[input_1_cfg, input_2_cfg],
    output=[datetime_cfg, date_cfg, int_cfg, string_cfg]
)

scenario_cfg = Config.configure_scenario(
    id="scenario",
    task_configs=[scenario_task_cfg],
    frequency=Frequency.DAILY)

data_node = None
# GUI Markdown content
scenario_md = """
<|{scenario}|scenario_selector|on_change=change_data_node|>

<|{data_node}|data_node|>
"""


def change_data_node(state):
    if isinstance(state.scenario, tp.Scenario):
        state.data_node = state.scenario.input_1_data_node

# Main execution block with GUI setup
if __name__ == "__main__":
    tp.Core().run()
    scenario = tp.create_scenario(scenario_cfg, name="Scenario 1")
    scenario.input_1_data_node.write(data_2)
    scenario = tp.create_scenario(scenario_cfg, name="Scenario 2")
    scenario.input_1_data_node.write(data)

    scenario = tp.create_scenario(scenario_cfg, name="Scenario 3")


    tp.Gui(scenario_md).run(title="Bug replication", port=3248)
```

**Comment by FlorianJacta** [comment]
Change in your code your metric component with this:

```python
value=lambda result_staff: float(result_staff) if result_staff is not None else 0
```

The metric component has a hard time dealing with None. This is breaking the refresh of the data node.

**Comment by FlorianJacta** [comment]
I think this issue can be closed. I created two more specific issues:

https://github.com/Avaiga/taipy/issues/1617 -> the metric component don't support None variables

https://github.com/Avaiga/taipy/issues/1616 -> the global on_change is used when creating a new scenario

This is why the change of scenarios in scenario selector was not changing your data node.

**Comment by AlexandreSajus** [comment]
Replacing the on_change and on_create callbacks with a global on_change function like so:
```python
def on_change(state: State, var_name, var_value):
    if var_name == "scenario" and isinstance(state.scenario, Scenario):
        state.demand_dn = state.scenario.demand
        refresh_results_of_scenario(state)
```
is a workaround (found by Florian J)

**Comment by AlexandreSajus** [comment]
Fixed by replacing on_change and on_creation callbacks with:
```python
def create_scenario(state: State, id: str, payload: dict):
    scenario = tp.create_scenario(
        config=payload["config"], name=payload["label"], creation_date=payload["date"]
    )
    scenario.demand.write(default_demand)
    return scenario


def on_change(state: State, var_name, var_value):
    if var_name == "scenario" and isinstance(state.scenario, Scenario):
        state.demand_dn = state.scenario.demand
        refresh_results_of_scenario(state)
```

```python
tgb.scenario_selector(
                "{scenario}", on_creation=create_scenario, height="500px"
            )
```
