### ISSUE TITLE
[🐛 BUG] windows python3.8 pip install taipy failed

### ISSUE THREAD

**Issue by levalup** [Avaiga/taipy#1615]
### What went wrong? 🤔

In windows10 python3.8.

Run `pip install taipy==3.1.1 -i https://pypi.org/simple`

```log
pip install taipy==3.1.1 -i https://pypi.org/simple
Collecting taipy==3.1.1
  Using cached taipy-3.1.1-py3-none-any.whl (2.9 MB)
Collecting taipy-gui<3.2.0,>=3.1.1
  Using cached taipy-gui-3.1.4.tar.gz (2.7 MB)
    ERROR: Command errored out with exit status 1:
     command: 'd:\opt\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\levalup\\AppData\\Local\\Temp\\pip-install-g0dibpcc\\taipy-gui\\setup.py'"'"'; __file__='"'"'C:\\Users\\levalup\\AppData\\Local\\Temp\\pip-install-g0dibpcc\\taipy-gui\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\levalup\AppData\Local\Temp\pip-pip-egg-info-yf226mwx'
         cwd: C:\Users\levalup\AppData\Local\Temp\pip-install-g0dibpcc\taipy-gui\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\levalup\AppData\Local\Temp\pip-install-g0dibpcc\taipy-gui\setup.py", line 99, in <module>
        packages=find_packages(where=root_folder, include=["taipy", "taipy.gui", "taipy.gui.*"]),
      File "d:\opt\python38\lib\site-packages\setuptools\__init__.py", line 70, in find
        convert_path(where),
      File "d:\opt\python38\lib\distutils\util.py", line 121, in convert_path
        if pathname[0] == '/':
    TypeError: 'WindowsPath' object is not subscriptable
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.1.1; however, version 24.2 is available.
You should consider upgrading via the 'd:\opt\python38\python.exe -m pip install --upgrade pip' command.
```

### Steps to Reproduce Issue

1. Run `pip install taipy==3.1.1 -i https://pypi.org/simple`

### Runtime Environment

Windows 10

### OS

Windows

### Version of Taipy

3.1.1

### Additional Context

```bash
Using pip for Python 3.11 can successfully install it, but it always fails for Python 3.8.
```

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
I was able to correctly install Taipy with Python 3.8 and the command you are showing on windows 11.

Could you try to upgrade your pip version `pip install --upgrade pip` or `python -m pip install --upgrade pip`?

**Comment by levalup** [comment]
> I was able to correctly install Taipy with Python 3.8 and the command you are showing on windows 11.
> 
> Could you try to upgrade your pip version `pip install --upgrade pip` or `python -m pip install --upgrade pip`?

Yes, I upgraded to `pip-24.2` and it has been installed successfully. Thank you.
It does seem to be related to the pip version. It was `pip-20.1.1` before, and this is the first time I've encountered such a situation. 

Anyway, thanks again.

**Comment by FlorianJacta** [comment]
Great to hear!
