### ISSUE TITLE
[🐛 BUG] Setting metric bound value to None raises an error  

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1617]
### What went wrong? 🤔

Setting the metric bound value to None raises an error and will break the changes done to the UI as an error is raised.

```
C:\Users\jacta\.conda\envs\develop\lib\site-packages\taipy\gui\gui.py:1477: TaipyGuiWarning: on_action(): Exception raised in 'set_value_to_none()':
Variable 'value' should hold a number: float() argument must be a string or a real number, not 'NoneType'
  _warn(f"on_action(): Exception raised in '{action_function.__name__}()'", e)
C:\Users\jacta\.conda\envs\develop\lib\site-packages\taipy\gui\gui.py:1449: TaipyGuiWarning: on_action(): 'set_value_to_none' is not a valid function.
  _warn(f"on_action(): '{action}' is not a valid function.")
```

### Expected Behavior

It should support the None variable.

### Steps to Reproduce Issue

```python
from taipy.gui import Gui
import taipy.gui.builder as tgb

value = None 

def set_value_to_none(state):
    state.value = None

with tgb.Page() as page:
    tgb.metric("{value}")
    tgb.button("Set value to None!", on_action=set_value_to_none)

Gui(page=page).run(title="Frontend Demo")
```
### Version of Taipy

develop

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
resolves by #1627
