### ISSUE TITLE
chat control: no refresh when clearing the message list

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy#1618]
### What went wrong? 🤔

If I empty the list that stores the chat messages, the display does not reflect it.
Refreshing the page is needed, which is wrong.

*Hint*
The problem is due to a wrong test in the useEffects hook that depends on props.messages.
We test if `props.messages`, which in this case is false.

### Expected Behavior

When the message list is emptied, the control should reflect it immediately.

### Steps to Reproduce Issue

```
from taipy.gui import Gui

users = ["user1", "user2"]
messages = [
    ("0", "message 0", "user1"), ("1", "message 1", "user2"),
    ("2", "message 2", "user1"), ("3", "message 3", "user2"),
]

input_index = 0

def add_message(state):
    global input_index
    state.messages.append((f"{len(messages)}", f"message {len(messages)}", users[input_index]))
    input_index = 1-input_index
    state.assign("messages", messages)


def clear_messages(state):
    state.messages.clear()
    state.assign("messages", messages)


page = """
<|{messages}|chat|users={users}|sender_id={users[0]}|with_input=False|>

<|Add message|button|on_action=add_message|>
<|Clear messages|button|on_action=clear_messages|>
"""

Gui(page).run()
```
### Version of Taipy

Taipy develop branch.

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by pravintargaryen** [comment]
I tried to replicate. I get the following error

![1](https://github.com/user-attachments/assets/6a6d5b8e-3787-4c31-a3ae-44de35fe24e5)
![2](https://github.com/user-attachments/assets/0d5c2114-e87c-4cde-b345-1e8d0cc5fbc0)

**Comment by FlorianJacta** [comment]
The chat control has not been released yet. You have to install the develop version of Taipy.

`pip install git+https://github.com/Avaiga/taipy.git`


As a developer, you should clone it like this: https://github.com/Avaiga/taipy/blob/develop/INSTALLATION.md#installing-for-development
