### ISSUE TITLE
[🐛 BUG] tgb objects are not detected by linter

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1620]
### What went wrong? 🤔

Here, `tgb.html` is recognized by my linter (Pylint) which allows me to look at the documentation
![image](https://github.com/user-attachments/assets/d995c1ad-203a-4ad6-90bf-977d9317f4c9)

For a lot of the other tgb objects, this is not the case. All tgb objects in white in this picture are not recognized by the linter, I don't have access to their possible properties or documentation:
![image](https://github.com/user-attachments/assets/4fca13f8-104e-4485-a5af-8569215f3722)

### Expected Behavior

tgb objects should be recognized by linters so the user knows which properties they take and so he can read their documentation

### OS

Windows

### Version of Taipy

develop

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
I think the issue comes from how we download the develop version. A release or pre release will not have this issue

**Comment by AlexandreSajus** [comment]
Understood, closing for now

**Comment by AlexandreSajus** [comment]
Reopening this, still an issue in 4.0.0:
![image](https://github.com/user-attachments/assets/12c54193-fe9f-444e-b8cb-67a098d38221)

**Comment by FredLL-Avaiga** [comment]
only for Core viz elements then ?

**Comment by AlexandreSajus** [comment]
Seems like it yes

**Comment by AlexandreSajus** [comment]
Fixed in 4.0.1.dev1
🎉
