### ISSUE TITLE
[🐛 BUG] tgb.text("\n", mode="md") does not create space

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1622]
### What went wrong? 🤔

I would expect `tgb.text("\n", mode="md")` to create space in my app just the way `tgb.html("br")` does but it does nothing. Is this intended?

### Screenshots

![DESCRIPTION](LINK.png)

### Browsers

Chrome

### OS

Windows

### Version of Taipy

develop

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
In Markdown, this does not work also. You will also need a `<br>` tag.

**Comment by AlexandreSajus** [comment]
Ah my bad

**Comment by FlorianJacta** [comment]
It does not mean, it is not a good issue

**Comment by AlexandreSajus** [comment]
Maybe there should be an easier, documented issue to create space outside of tgb.html("br"). But that should be in a separate issue
