### ISSUE TITLE
I want to make a web application related to video processing

### ISSUE THREAD

**Issue by Sillyyk** [Avaiga/taipy#1630]
### Description

Is there anyone who has done video custom dynamic controls or has relevant experience, please guide me

### Solution Proposed

make video custom dynamic controls 

### Impact of Solution

Improve user manual

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by dinhlongviolin1** [comment]
@FlorianJacta @AlexandreSajus do you guys have any relevance demos

**Comment by Sillyyk** [comment]
> @FlorianJacta @AlexandreSajus do you guys have any relevance demos

Thank you very much for your help. I really want to make a custom control for the video and hope to have a relevant demo for reference.

**Comment by FlorianJacta** [comment]
We don't have a custom component for video and no demos on videos, either. @dinhlongviolin1 How would you integrate a video in Taipy?

**Comment by Sillyyk** [comment]
I tried to simulate video playback by real-time callback of images, but that was useless and not smooth.

**Comment by FlorianJacta** [comment]
## How to add videos: 

This example was created using [this doc](https://docs.taipy.io/en/release-3.1/tutorials/integration/1_3rd_party_components/) about integrating Python objects inside Taipy.

```python
from taipy.gui import Gui
import taipy.gui.builder as tgb


class Video:
    def __init__(self, path, width="1500px", height="800px"):
        self.path = path
        self.width = width
        self.height = height


def create_video(video: Video):
    html = f"""
<video controls width="{video.width}" height="{video.height}">
  <source src="/{video.path}" type="video/mp4" />
</video>
"""
    return html


video = Video("flower.mp4")

with tgb.Page() as page:
    tgb.part(content="{video}", height="800px")


gui = Gui(page)
gui.register_content_provider(Video, create_video)
gui.run(use_reloader=True, port=5001, title="Frontend Demo")
```

**Comment by Sillyyk** [comment]
> ## How to add videos:
> This example was created using [this doc](https://docs.taipy.io/en/release-3.1/tutorials/integration/1_3rd_party_components/) about integrating Python objects inside Taipy.
> 
> ```python
> from taipy.gui import Gui
> import taipy.gui.builder as tgb
> 
> 
> class Video:
>     def __init__(self, path, width="1500px", height="800px"):
>         self.path = path
>         self.width = width
>         self.height = height
> 
> 
> def create_video(video: Video):
>     html = f"""
> <video controls width="{video.width}" height="{video.height}">
>   <source src="/{video.path}" type="video/mp4" />
> </video>
> """
>     return html
> 
> 
> video = Video("flower.mp4")
> 
> with tgb.Page() as page:
>     tgb.part(content="{video}", height="800px")
> 
> 
> gui = Gui(page)
> gui.register_content_provider(Video, create_video)
> gui.run(use_reloader=True, port=5001, title="Frontend Demo")
> ```

Thank you very much for your reply and your work.
