### ISSUE TITLE
[🐛 BUG] Scenario submit button does not refresh results when deployed

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1636]
### What went wrong? 🤔

Check out this application: https://github.com/Avaiga/demo-workforce-plan
![results](https://github.com/user-attachments/assets/c056eca8-49e8-43d3-b613-d3cb3796e986)
It works fine when running locally
When deployed on Taipy Cloud: https://workforce-optim.taipy.cloud/
When I try to submit a new scenario, it does not update the results until I deselect and reselect the scenario in the scenario selector
![image](https://github.com/user-attachments/assets/2aaefb48-ec12-4860-99fe-b14a81770ba0)

### Browsers

Chrome

### OS

Windows

### Version of Taipy

4.0.0.dev0

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by jrobinAV** [comment]
@AlexandreSajus It works just fine with other demos.
Can you check how it is done on other demos to try to spot the differences? 
Otherwise can you provide a minimal reproducible codebase?

**Comment by AlexandreSajus** [comment]
It seems to work when deploying locally on Docker; I will try redeploying after the demo migration. Closing for now

**Comment by jrobinAV** [comment]
All right, Thx !
