### ISSUE TITLE
Add TOML config option to default taipy create (Taipy CLI)

### ISSUE THREAD

**Issue by enarroied** [Avaiga/taipy#1641]
### Description

When you create a Taipy application with `taipy create`, you have the option:
`[5/6] Does the application use scenario management or version management? (No) 
`
When you create a taipy core application with `taipy create --template scenario-management`, you have the following option: 
`[4/4] Does the application use TOML Config? (No):`

You don't have that option in the default `taipy create`.

### Solution Proposed

It would be great if you had this option when you select Yes in 5/6 within `taipy create`. If you select No, there is no reason to ask for a TOML file.

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by trgiangdo** [comment]
Hello @enarroied, on the default template, even if the answer to the
`[5/6] Does the application use scenario management or version management? (No)`
is `Yes` or `y`, there is no Configuration created.

The template will only have some scaffold for configuring new Config, so there will be no content in the TOML file.

Let me know if it makes sense, or how we can improve the content of the default template. Thank you

**Comment by enarroied** [comment]
Hi @trgiangdo,
Thank you for your answer. I see what you mean, in the default template, the Config file is empty, while in the scenario-management template, there is a mock configuration (in either TOML or Python format).

I would find it useful to have the demonstration code, especially for beginners, but I also understand that having too many options in the CLI tool (and nested options) could be confusing, so now I'm having second thoughts! 

In the main template, when you choose to add config file, you have a comment section, you could add the info there, something like:
```python
# #############################################################################
# PLACEHOLDER: Put your application's configurations here                     #
#                                                                             #
# Example:                                                                    #
# scenario_config = Config.configure_scenario("placeholder_scenario", [])     #
# Comment, remove or replace the previous lines with your own use case        #
#
# Or create a config.toml file and load it like this: 
# def configure():
#    Config.load("config/config.toml")
#    return Config.scenarios["scenario_configuration"]
# #############################################################################
```

I think this extra comment is useful, adds no complexity for the user and requires minimal effort. What do you think?
