### ISSUE TITLE
Make columns[mobile]=1 the default for layout

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1658]
### Description

Many applications don't render correctly on mobiles because this is not the default. Now, all my applications specify this, so I want to discuss putting this as the default behavior for layout.

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
this is the default and working for me with your example from #1683 ...

**Comment by FlorianJacta** [comment]
Was it changed recently? I had to change almost every demo because this was not the case.

In my demo, it took the layout of *columns* and not the default value of 1 as you suggest.

**Comment by FredLL-Avaiga** [comment]
Nope

**Comment by FlorianJacta** [comment]
Ok, I'll close this issue and reopen it if I see it again.
