### ISSUE TITLE
Scenario Selector - Selection of scenario disappears graphically

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#167]
## Issue

When the user selects a scenario and clicks somewhere else, the visual feedback of the selection disappears.

![selection](https://github.com/Avaiga/taipy/assets/98709993/2a805689-2f10-4032-9d4c-7eb5c418fe59)

## Expected behavior

The selection should stay after the user clicks somewhere else.

## Version

Taipy 2.3.0 Draft

**Comment by FredLL-Avaiga** [comment]
Is the issue also visible in standard taipy-gui treeview ?

**Comment by FlorianJacta** [comment]
No, in the standard Taipy-gui tree, the selection stays highlighted. 

![image](https://github.com/Avaiga/taipy/assets/98709993/8ec96a5e-b694-4103-9382-b6454d42b10a)
