### ISSUE TITLE
Add sender icon in the chat

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1670]
### Description

The one that is sending messages doesn't see its own avatar icon. 

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by pravintargaryen** [comment]
I can work on this with @FredLL-Avaiga & @FabienLelaquais Guidance if that is fine

**Comment by youweizheng** [comment]
Hi,

I am not sure what I am supposed to feedback on this post. But I do have a picture in mind, hopefully that helps to illustrate my simple requirement. The placeholder variables of course shall be able to configured.
![demo-dialogue](https://github.com/user-attachments/assets/bc6dd498-0672-439b-b395-0ae739a53f85)

**Comment by FlorianJacta** [comment]
@pravintargaryen, we have a client who needs this urgently, so we have to prioritize it through our R&D. Unfortunately, we won’t be able to assign you to this issue.
