### ISSUE TITLE
[DOCS] Docs for "Chat" viz element are missing

### ISSUE THREAD

**Issue by yaten2302** [Avaiga/taipy#1672]
### Issue Description

The docs on the taipy website doesn't include "Chat" viz element, which becomes difficult for the users to get a grasp how to use a particular viz element.

### Proposed Solution (optional)

We can add the docs for "Chat" progress element, so that  it becomes easier for the users to understand about the chat viz element.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
It is on the develop version of the doc as this feature has not been released. Check this: https://docs.taipy.io/en/develop/manuals/userman/gui/viselements/generic/chat/

Does this solve your issue?

**Comment by yaten2302** [comment]
Yes @FlorianJacta , actually, while searching on the official website, I wasn't able to find this, that's why I created this issue.
So it'll be released soon 👍 Great!!

**Comment by yaten2302** [comment]
I'll close this issue, since it's already present, but just the release has to be published 👍

**Comment by FlorianJacta** [comment]
For sure! It will be at the same time of Taipy release
