### ISSUE TITLE
Scenario Selector - Scenario without names not appearing and not usable

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#168]
## Isssue

Scenarios without names do not appear in the Scenario Selector.

![image](https://github.com/Avaiga/taipy/assets/98709993/d82af64e-babb-408f-9dbd-9f42be5ce513)

## How to replicate

Run the code
```python
from taipy.config import Config, Frequency
import taipy as tp

import datetime as dt

def f(i):
    return i

d1_cfg = Config.configure_data_node('d1', default_data=1)
d2_cfg = Config.configure_data_node('d2')
task_cfg = Config.configure_task(id="task", function=f, input=d1_cfg, output=d2_cfg)
s = Config.configure_scenario_from_tasks('s', [task_cfg], frequency=Frequency.WEEKLY)

scenario = None

if __name__ == "__main__":
    tp.Core().run()

    [tp.create_scenario(s,
                        creation_date=dt.datetime.now()+dt.timedelta(days=i)) 
                        for i in range(10)]

    tp.Gui('<|{scenario}|scenario_selector|>').run(port=4999)

```

## Expected behavior

The Scenario Selector should display the scenarios created and be usable.

## Version
Taipy 2.3.0 Draft

**Comment by jrobinAV** [comment]
What we display is a label. If a scenario does not have any name, the id is used as a label.
So I believe the name does exist in the use case described here, but it is empty.

**Comment by FlorianJacta** [comment]
This is not really what is happening or at least, there is more to it. For example, I should have ten scenarios here:

![image](https://github.com/Avaiga/taipy/assets/98709993/a515a16e-2057-4c3a-8079-794a4674d6cd)
