### ISSUE TITLE
[🐛 BUG] Incorrect argument ordering following the doc

### ISSUE THREAD

**Issue by florian-vuillemot** [Avaiga/taipy#1687]
### What went wrong? 🤔

The command line doesn't always respect the argument order as the doc explains.

[Here](https://docs.taipy.io/en/latest/manuals/cli/run/) the doc:
```
usage: taipy run [-h] [--port [PORT]] [--host [HOST]] [--ngrok-token [NGROK_TOKEN]]
                 [--webapp-path [WEBAPP_PATH]] [--debug | --no-debug]
                 [--use-reloader | --no-reloader] [--development | --experiment [VERSION] |
                 --production [VERSION]] [--force | --no-force]
                 application_main_file {external-args} ...
```
but following screenshot show the behaviours - at least for the `host` and `port` parameters -.
<img width="551" alt="image" src="https://github.com/user-attachments/assets/d388ce4e-eeb0-48cc-9afc-d3f93db13a75">
<img width="566" alt="image" src="https://github.com/user-attachments/assets/7d70157f-8d90-4afd-aeb8-7452b2e28606">
<img width="563" alt="image" src="https://github.com/user-attachments/assets/a907286f-ba24-440e-812a-2e751add4ebe">
<img width="551" alt="image" src="https://github.com/user-attachments/assets/7760a7ec-136f-42e4-9e31-9ff200b269fe">

### Expected Behavior

The doc behaviour.

### Screenshots

![DESCRIPTION](LINK.png)

### OS

Windows, Linux

### Version of Taipy

3.1

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by trgiangdo** [comment]
The `argparse` library [calculates the usage message from the arguments](https://docs.python.org/3/library/argparse.html#usage).

I'm not sure why they always put the positional argument after all of the optional arguments, but I think we need to clarify this in the doc.

**Comment by trgiangdo** [comment]
Either way, the default behavior of `argparse` is that the positional argument can be either before or after all of the options.

This is not only a doc problem, but probably in the way we handle the CLI.
