### ISSUE TITLE
[🐛 BUG] <Add more than one extension library for dynamic elements>

### ISSUE THREAD

**Issue by AJ-Niro** [Avaiga/taipy#1695]
### What went wrong? 🤔

I currently have a library called `ButtonDownloadFile`, and adding a new library called `PageWrapper` causes the first library to stop working, removing the button that was previously functioning.

### Expected Behavior

Use 2 extension libraries without any conflict

### Steps to Reproduce Issue

Use two libraries using [taipy_gui_ext_library template](https://github.com/Avaiga/guiext-template/tree/develop/taipy_gui_ext_library) and setup the GUI with `libraries=[ButtonDownloadFile() PageWrapper()]`

### Runtime Environment

Debian 12, Brave 1.68.141 

### Browsers

Brave

### OS

Linux

### Version of Taipy

3.1.4

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
Can you share some code example ?

**Comment by jrobinAV** [comment]
@AndresJoaquinNino Can you share some code examples so we can reproduce it?

**Comment by AndresJoaquinNino** [comment]
Apologies, I will no longer continue with the project I was working on, so I will close the issue.

**Comment by AJ-Niro** [comment]
Apologies, I will no longer continue with the project I was working on, so I will close the issue
