### ISSUE TITLE
page127.0.0.1 refused to connect.

### ISSUE THREAD

**Issue by phong-ssk** [Avaiga/taipy#1701]
Hmmm… can't reach this page127.0.0.1 refused to connect.
Try:

Search Bing for 127 0 0 1
Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)

I run taipy for the first time and I crash into this error. could you please help!

**Comment by FlorianJacta** [comment]
Please add more information to your issue.

What do you have on your Python console? 

What is your OS?
What is your browser? And what about other browsers?
What is your Taipy version? 3.1.1?

What do you mean by 
> Checking the connection
Checking the proxy and the firewall

?

Do you have a VPN, Proxy, or Firewall?

The message you sent us seems you haven't correctly started the Taipy application but we'll see together.

**Comment by dinhlongviolin1** [comment]
if he is using macos then it could be a problem since Airplay takes up port 5000

**Comment by jrobinAV** [comment]
@dinhlongviolin1 
We don't know for sure it's this problem yet. We need more information. 

As discussed with @FabienLelaquais , Can you create a dedicated new issue for the port 5000 issue?

**Comment by jrobinAV** [comment]
@phong-ssk Can you please provide more information?

**Comment by AlexandreSajus** [comment]
> Hmmm… can't reach this page127.0.0.1 refused to connect. Try:
> 
> Search Bing for 127 0 0 1 Checking the connection Checking the proxy and the firewall
> 
> I run taipy for the first time and I crash into this error. could you please help!

Why are you looking for "127 0 0 1" on Bing? What are you trying to do? If you're trying to go to a Taipy application you created, the terminal should provide you a link when you run your python script.

**Comment by jrobinAV** [comment]
Without any answer, we consider the issue as closed.
