### ISSUE TITLE
columns_mobile is not recognized as property in Python API

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1715]
### Description

columns__mobile is not recognized as property in Python API. This makes it hard for people to find it or understand it. I had the issue with a customer.

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
you need to use `columns__mobile` (note the 2 _)

**Comment by FlorianJacta** [comment]
The problem is not if there is one ` _` or ` __`. I agree there should be two `__`. `tgb.layout` will not suggest having two I am running a few minutes late; my previous meeting is running over `_` as this parameter is not present
