### ISSUE TITLE
[🐛 BUG] Chat text is grey

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1718]
### What went wrong? 🤔

Text in the chat from the user is grey.

![image](https://github.com/user-attachments/assets/7ac8e272-bf5d-42ad-9494-167ede3d78b0)

### Expected Behavior

It should be white.
### Version of Taipy

develop 8/28/24

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
Let's call this a feature

Which can be changed by css

**Comment by FredLL-Avaiga** [comment]
```

/* sender name color*/
.taipy-chat-sent .MuiBox-root {
    color: var(--color-contrast);
}

/* sender text color */
.taipy-chat-sent .MuiPaper-root {
    color: var(--color-contrast);
}

```

**Comment by FredLL-Avaiga** [comment]
is this enough for you @FlorianJacta ?
Or do you want to change it globally, should we cast a vote ? @FabienLelaquais @jrobinAV

**Comment by FlorianJacta** [comment]
A vote is fair! I vote for white

**Comment by jrobinAV** [comment]
I prefer the white version as well. It seems more consistent with the default stylekit.

**Comment by FredLL-Avaiga** [comment]
@FabienLelaquais what's your vote ?

**Comment by FabienLelaquais** [comment]
@FredLL-Avaiga: I would certainly use white as the base choice.
