### ISSUE TITLE
Add width property to all possible visual elements

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1720]
### Description

**Description**
Add the ability to change the width of all the visual elements. I think those are missing:
- date `<|{date_value}|date|width=100%|>`
- number `<|{value}|number|width=100%|>`
- file_download `<|{path}|file_download|width=100%|>`
- file_selector `<|{path}|file_selector|width=100%|>`
- toggle `<|{selected_value}|toggle|lov=one;two;three|width=100%|>` (this might be tricky because of the different modes)
- date_range `<|{dates}|date_range|width=100%|>`
- button `<|Some label|button|width=100%|>`
 
Something similar to the selector visual element.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
number is already done

**Comment by FredLL-Avaiga** [comment]
date_range is the most complicated ...
