### ISSUE TITLE
[🐛 BUG] Viselements.json of gui_core is broken

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1726]
### What went wrong? 🤔

Viselements.json of gui_core is broken, making the doc generation fail and possibly creating other issues.

### Version of Taipy

_No develop

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
this issue lacks details
