### ISSUE TITLE
Taipy is considered as having vulnerabilities

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1728]
### What would you like to share or ask?

GitHub now considers Taipy vulnerable. This means that any GitHub project that requires Taipy will raise a vulnerability report on Taipy.

https://github.com/Avaiga/taipy-doc/security/dependabot/21

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by dinhlongviolin1** [comment]
this cookie is used for redirection and does not involve any credential information. I will dismiss this alert
