### ISSUE TITLE
Cannot import name 'ReflectionDefaults'

### ISSUE THREAD

**Issue by fzansari007** [Avaiga/taipy#1729]
### What would you like to share or ask?

while running "from taipy import Gui" I am getting the below error,

ImportError: cannot import name 'ReflectionDefaults' from 'sqlalchemy.engine.reflection'

Can anyone please help me sort this out?

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
Did you create an entirely new environment for the project? Do you have *sqlalchemy* on your machine?

**Comment by FlorianJacta** [comment]
Do you still have the issue?

**Comment by FlorianJacta** [comment]
No response from user; I am closing the issue
