### ISSUE TITLE
[🐛 BUG] Continuous Slider change does not work with Lov

### ISSUE THREAD

**Issue by ShootingStarD** [Avaiga/taipy#1733]
### What went wrong? 🤔

I want to make a [slider](https://docs.taipy.io/en/release-3.1/manuals/gui/viselements/slider/) that updates the value of a text each time I slide to a different value, even if I do not release the slider

My code: 
```python
from taipy.gui import builder as tgb
from taipy.gui import Gui
text = "Dio"
with tgb.Page() as page:
    tgb.text("It was me {text} !!!")
    tgb.slider("{text}", lov="Dio;Jotaro;Giorno", continuous=True)
Gui(page,).run(debug=True, use_reloader=True, port=5111)
```
I expect `continuous=True` to do the trick. I know that with `lov` it is disabled by default but setting it to True should still apply it no? Otherwise it should throw an error for me

taipy==3.1.1
taipy-gui==3.1.4

I got the same with taipy dev1 4

### Expected Behavior

Setting `continuous=True` should change the value when cursor position change, not only when it is released
### Browsers

Firefox

### OS

Linux

### Version of Taipy

3.1.1 and develop

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
Thank you for the issue! I was able to reproduce it
