### ISSUE TITLE
Have a default way to open a pane

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1735]
### Description

Currently, the user has to create a button to open a pane. The simplest solution for the user is to create a button, but this is not UX-friendly, so he also has to change the button's style. This requires a lot of code for a simple feature.

**Solution**

We should be able to provide a default way to open the pane with a great UI/UX.

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
Which kind of pane ?

**Comment by FlorianJacta** [comment]
How many kinds do you have? Whether it is persistent or not, it results in the same way as opening a pane. You also have different anchors, so the button to open the pane should be different.
