### ISSUE TITLE
Get geolocation from clicking on a map

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1739]
### Description

The goal would be to get the lon/lat of a point when clicking anywhere on a map.

This was asked by a user [here](https://discord.com/channels/1125797687476887563/1279625158394511360/1280344356066431037)

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FabienLelaquais** [comment]
So that's going to be a tricky one because of the nature of the chart control.
We may consider an on_click callback that would be invoked when users click the chart, and fill a payload with as much information as we get - such as lat/lon in the case of a georeferenced dataset...

**Comment by FredLL-Avaiga** [comment]
Taipy uses plotly.js for displaying charts
Plotly.js doesn't allow natively to catch click event on the background of charts.
But there is a way (a bit hacky)
- we can add a event listener to the chart div
- then get the information from a non public structure in plotly.js

```
plotlyDiv.addEventListener('click', function(evt) {
    console.log("click", "latitude", plotlyDiv._fullLayout.map._subplot.yaxis.p2c(), "longitude", plotlyDiv._fullLayout.map._subplot.xaxis.p2c());})
```

and make it available via a standard Taipy callback `on_click`

**Comment by FredLL-Avaiga** [comment]
Interesting: there's a PR opened for this (for the last 6 years)
https://github.com/plotly/plotly.js/pull/5443
