### ISSUE TITLE
Stop support for Python 3.8

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#1748]
Stop supporting version 3.8 of Python.

**Comment by jrobinAV** [comment]
@FabienLelaquais @AlexandreSajus Check if Dataiku will be a problem if Taipy does not support 3.8 anymore.

**Comment by AlexandreSajus** [comment]
> @FabienLelaquais @AlexandreSajus Check if Dataiku will be a problem if Taipy does not support 3.8 anymore.

As far as I know we don't have anything currently running in Dataiku right now and our working documented integration with them does not rely on Python 3.8 so it should be okay
