### ISSUE TITLE
[Refactor] Shorten Taipy Templates path

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1756]
### Description

`taipy\templates\scenario-management\{{cookiecutter.__root_folder_name}}\pages\scenario_page\data_node_management.py'`

We could shorten:
- scenario-management
- __root_folder_name

and maybe other elements.

This will fix :https://github.com/Avaiga/taipy-enterprise/issues/446 https://github.com/Avaiga/taipy/issues/808

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by jrobinAV** [comment]
We can add a warning on taipy doc.
