### ISSUE TITLE
Possibility to add images to tables

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1758]
### Description

The goal would be to add images in a Taipy table. (This was asked by a user)

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
syntax is similar to button : the text value of the cell should be `![value](<URL>)`
value is used as alt text for image and as value for on_selection.
