### ISSUE TITLE
[OTHER] Chat control design

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1760]
### What would you like to share or ask?

One of our customers is requesting a specific design for the chat control. He wants usernames to be on top of the user images. He also wants the user image on the right to be on the right of the messages. Basically these changes:
![image](https://github.com/user-attachments/assets/5dc1d3bb-7375-4a84-b480-1925386f4ef7)

Result:
![image](https://github.com/user-attachments/assets/ed4ebdc1-282f-4b91-92b9-2ddafd8c1f4b)

Can these changes be made through CSS in 4.0.0.dev1? How?

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
```
/* receiver order */
.taipy-chat-sent > .MuiGrid2-root > .MuiStack-root {
    flex-direction: row-reverse;
}
/* receiver avatar */
.taipy-chat-sent > .MuiGrid2-root > .MuiStack-root > .MuiBox-root {
    padding-top: 1em;
}
/* receiver name */
.taipy-chat-sent .MuiStack-root .MuiStack-root .MuiBox-root {
 text-align: end;
 margin-right: -36px;
 padding-right: 0;
}

/* received avatar */
.taipy-chat-received > .MuiGrid2-root > .MuiStack-root > .MuiBox-root {
    padding-top: 1em;
}

/* received user name */
.taipy-chat-received .MuiStack-root .MuiStack-root .MuiBox-root {
    margin-left: -36px;
    padding-left: 0;
}

```

**Comment by AlexandreSajus** [comment]
This does not seem to work in 4.0.0.dev1. Can you make a CSS script that works with 4.0.0.dev1 since the customer can't install develop (he would have to go through the node installation)?

**Comment by FredLL-Avaiga** [comment]
then maybe ask for a dev2?

**Comment by AlexandreSajus** [comment]
If a dev2 is possible, that would be helpful. This issue might get in the way though: https://github.com/Avaiga/taipy/issues/1754

**Comment by AlexandreSajus** [comment]
Works perfectly in dev2, thanks!
