### ISSUE TITLE
Allow a Stylekit "card" to be side-by-side with width=fit-content

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy#1780]
### Description

Cards can have their width match the size of its content with #468, which is great for displaying metrics (among other things).

I'd like to position cards side-by-side, **without needing to use a layout and explicitly defining the width of each element there**.

Currently, I can use a layout and define the width:

```python
from taipy.gui import Gui, Markdown

page_md_target = Markdown(
"""
<|layout|columns=10em 10em|

<|card|part|width=fit-content|
Metric 1
|>

<|card|part|width=fit-content|
Metric 2
|>

|>
""")

if __name__ == "__main__":
    gui = Gui(page_md_target)
    gui.run(debug=True, run_browser=False, use_reloader=True, dark_mode=False)
```

Which produces:

![image](https://github.com/user-attachments/assets/a6465750-e4d6-4c25-b2af-63b4264909c2)

I want to create this without defining a width anywhere.

### Solution Proposed

Maybe allowing a layout column to "fit-content" ("fc") is a possible solution? I don't like the extra nesting especially if I'm only showing 2 cards, but it makes sense and I can also use layout.gap to add space between the cards.

```python
page_md_layout = Markdown(
"""
<|layout|columns=fc fc|

<|card|part|width=fit-content|
Metric 1
|>

<|card|part|width=fit-content|
Metric 2
|>

|>
""")
```

### Impact of Solution

Needs to work with taipy.gui.builder / tgb also.

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by arcanaxion** [comment]
@dinhlongviolin1 Opened a new feature request per #1725. Thanks for taking a look!

**Comment by HatimZ** [comment]
@arcanaxion @jrobinAV I am interested in this issue. Can you please assign this to me? 
I think I would need to look deep down into the Markdown module and how it translates string into actual GUI code.
Then i would check for "fc" string and apply styles for width 100% to each child, so they can expand in their axis

**Comment by jrobinAV** [comment]
Hello @HatimZ , 

Yep, sure. Let me assign it to you.
If you have any questions, @FredLL-Avaiga @dinhlongviolin1 @namnguyen20999 @FabienLelaquais will be pleased to answer.

**Comment by HatimZ** [comment]
ok great.

**Comment by xyfer17** [comment]
@arcanaxion could please assign the above issue to me, if @HatimZ is not working on it.

**Comment by HatimZ** [comment]
@arcanaxion Will work on this issue. Just caught up with some work. Updates soon

**Comment by HatimZ** [comment]
@quest-bot embark

**Comment by RymMichaut** [comment]
Congrats @HatimZ 
please contact me at rym.michaut@taipy.io to ship your swag :)

**Comment by FredLL-Avaiga** [comment]
This should be enough for your case @arcanaxion 

```py
from taipy.gui import Gui

page = """
<|layout|columns=max-content max-content|

<|card|part|
Metric 1
|>

<|card|part|
Metric 2
|>

|>
"""

if __name__ == "__main__":
    Gui(page).run(title="layout - fit content")

```

![image](https://github.com/user-attachments/assets/d1d055d1-c949-4f97-b0f9-ff699e2565da)

What do you think ?

**Comment by arcanaxion** [comment]
@FredLL-Avaiga Yes that's perfect. Time for me to do some reading on CSS... Thanks Fred!

**Comment by FredLL-Avaiga** [comment]
:+1 can you close the issue then?
