### ISSUE TITLE
Unable to use markdown attribute lists with "text" element

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy#1781]
### What went wrong? 🤔

Per title, cannot use attribute lists with `text`, since Taipy tries to evaluate the content of the curly braces: https://python-markdown.github.io/extensions/attr_list/

```python
from taipy.gui import Gui, Markdown
import taipy.gui.builder as tgb

with tgb.Page() as page_tgb:
    tgb.text("This is a **Taipy**{: style='color:red'} application.")

page_md = Markdown(
"""
<|This is a **Taipy**{: style='color:red'} application.|text|>
""")

if __name__ == "__main__":
    page = page_tgb
    gui = Gui(page)
    gui.run(debug=True, run_browser=False, use_reloader=True)
```

Both `page_tgb` and `page_md` fail with the traceback:
```
  File "<unknown>", line 1
    : style='color:red'
    ^
SyntaxError: invalid syntax
```

`<|Hello|text|>` translates to `tgb.text("Hello")`. How do you represent "normal" text **not** in a text element, like in the page_md example above?

E.g. the following example (seemingly) only available with the markdown syntax, works:

```python
page_md_working = Markdown(
"""
This is a **Taipy**{: style='color:red'} application.
""")
```

### Expected Behavior

1. Attribute lists should work with text controls
2. tgb syntax should have a way to display text without using the text element, like what is possible with the markdown syntax

### Steps to Reproduce Issue

NA

### Solution Proposed

NA

### Screenshots

NA

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
As a workaround, I put these texts as bold in my application, and I use CSS to change the color of all bold texts to show a different color.

```css
strong, b {
    font-weight: bold; /* This is equivalent to 700 */
    color: #ff6049;
}
```

**Comment by yashpal2104** [comment]
@arcanaxion in which repo/branch should I search for this to contribute my solution pls help

**Comment by KunjShah95** [comment]
Kindly assign it to me I want to fix it

**Comment by jrobinAV** [comment]
@yashpal2104 Thank you for your help.

**Comment by FredLL-Avaiga** [comment]
There's already a solution that will be proposed by R&D team soon.
You'll be able to add style to page (available in 4.0) or even components (4.1 I guess)
I think this should be removed from HacktoberFest @jrobinAV

**Comment by yashpal2104** [comment]
oh okay happy to know you did find the solution, no worries I will try on some other good first issues. Thank you for informing about this @FredLL-Avaiga

**Comment by jrobinAV** [comment]
@FredLL-Avaiga OK. Thank you.

**Comment by arcanaxion** [comment]
> There's already a solution that will be proposed by R&D team soon. You'll be able to add style to page (available in 4.0) or even components (4.1 I guess)

Hi @FredLL-Avaiga. Is this feature available yet? Specifically I want to specify the text colour hex code in a text component

**Comment by FredLL-Avaiga** [comment]
it is for pages in 4.0 
It's coming in 4.1 for components

**Comment by arcanaxion** [comment]
@FredLL-Avaiga I see, thank you. For posterity, is this the page style feature you are referring to? https://docs.taipy.io/en/develop/refmans/reference/pkg_taipy/pkg_gui/pkg_builder/Page/#taipy.gui.builder.Page.set_style

**Comment by FredLL-Avaiga** [comment]
yes and it is supported as well in the [page constructor](https://docs.taipy.io/en/develop/refmans/reference/pkg_taipy/pkg_gui/pkg_builder/Page/#taipy.gui.builder.Page.__init__)
ex: `Markdown("""...""", style={...})`
