### ISSUE TITLE
[🐛 BUG] scatter map plotly plot selected property react differently between string and number color points

### ISSUE THREAD

**Issue by ShootingStarD** [Avaiga/taipy#1786]
### What went wrong? 🤔

When ploting a scatter map plotly map on taipy, the `selected` property of `tgb.chart()` does not always update as expected when coloring location with an `str` column, while it does as expected with an int column

### Expected Behavior

I expect to be able to listen to change of `selected`property at each click on a dot on the map

### Steps to Reproduce Issue

```python
from taipy.gui import builder as tgb
from taipy.gui import Gui

import plotly.express as px

df = px.data.carshare()
df["peak_hour"] = df["peak_hour"].astype(str)  # toggle off to get int column
fig = px.scatter_map(
    df,
    lat="centroid_lat",
    lon="centroid_lon",
    color="peak_hour",
    size="car_hours",
    color_continuous_scale=px.colors.cyclical.IceFire,
    size_max=15,
    zoom=10,
)
selected_indices = []


def on_init(state):
    state.selected_indices = []


def on_plot_clicked(state, var, val):
    print(f"On plot clicked : {var}")
    if var == "selected_indices":
        print(f"point selected = {val}")


with tgb.Page() as page:
    tgb.chart(
        figure="{fig}",
        on_change=on_plot_clicked,
        selected="{selected_indices}",
    )
    tgb.text("Point Selected = {selected_indices}")
Gui(
    page,
).run(debug=True, use_reloader=True, port=5111)
```

### Screenshots

Initial 
![image](https://github.com/user-attachments/assets/160aae54-4350-4e36-9d42-b4dd4aec39e2)
After a selection, the selected point was not shown in text and the function on_plot_clicked was not fired : 
![image](https://github.com/user-attachments/assets/cf21f2c4-d3db-4966-858c-e159bdd9cded)
Initial with number as color : 
![image](https://github.com/user-attachments/assets/85ea4dea-5afd-4114-9fb5-4e9c68bab361)
After click, works as expected : 
![image](https://github.com/user-attachments/assets/fa23bf6c-2350-4d38-9a5e-7764451f9809)

### Browsers

Firefox

### OS

Linux

### Version of Taipy

4.0.0dev2

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by AlexandreSajus** [comment]
R&D is looking into it. Bear in mind that currently, when you feed a Plotly figure into the "figure" property, "selected" is not supposed to work. "selected" is only documented when you create charts that are available by default in Taipy, for example the ones documented here: https://docs.taipy.io/en/latest/manuals/gui/viselements/charts/map/ (a previous issue on this topic: https://github.com/Avaiga/taipy/issues/675)

**Comment by ShootingStarD** [comment]
Hi 
I come back since I saw a PR related and the discrepancy of behavior is still there but differently.
Using the same exact code as before I used taipy 4.0.0.dev7. 
Clicking on a point where the chart was ploted with str gives the following result where the value of selected_indices is a list of list with lots of None value
![image](https://github.com/user-attachments/assets/746bf350-dfb4-47f4-ab16-b30cef21d03b)
The number of None values varies accross the points clicked, but each time the selected index is the last element of the list
Using the int charts, I get list of list with only one value for each point clicked
![image](https://github.com/user-attachments/assets/f7e981f6-066e-48fe-81a3-8ad6e3e0bab9)

**Comment by FredLL-Avaiga** [comment]
This is the intended behavior as it shows to know which point in which trace was selected

**Comment by ShootingStarD** [comment]
I do not understand what each element of the first list corresponds to. Since the size of list changes when I select one point or another, I don't think that each None is a trace that is not selected, because the number of traces should not change when I select a different point. What might change would be the number of point inside each trace, for example the trace peak_hour 23 might have different number of points plotted than the peak_hour 20

Then am I right in thinking that each element corresponds to whether or not a point of the trace selected is selected?

**Comment by ShootingStarD** [comment]
I did some tests today. 

Just to be clear, my end goal is to be able to click on a point on the map, and get the index of the element of dataframe corresponding to the point I clicked.
With the int column, it works perfectly as the result of the selected properties gives only one element in the list and each time I click on another, I get another value

With the str column, I get lists of different sizes depending on the point click, but the size of the list is not equal to the number of points with the same color/peak hour
So yeah I do not find a way to find the index of the row of the dataframe corresponding to the point selected, do you know how I can do this with the current implementation @FredLL-Avaiga ?
