### ISSUE TITLE
Chat control default appearance

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy#1798]
### Description

As of now, the chat control displays the sender's avatar (or a generated image if there is none), and this image appears to the left side of the message area, which has an arrow pointing to the right.
![image](https://github.com/user-attachments/assets/3bd28ccb-b7c6-4778-acb2-565a4b4570af)

I suggest we change this behavior:
- No sender avatar by default - force it with 'show_sender' to True
- Display the sender's avatar to the right side of the message box.

I'm not certain at this point that this is going to look better... but I think it will.

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
How about this ?
![Image](https://github.com/user-attachments/assets/24dc4631-22b3-4ceb-a957-13c19789a09f)
