### ISSUE TITLE
Ability to programmatically close a specific notification

### ISSUE THREAD

**Issue by zmikea** [Avaiga/taipy#1801]
### Description

I have potentially 3 notifications during a process, and at the end of the process want to programmatically close a specific one of them immediately, but leave the other two to close based on their duration.

### Solution Proposed

create an ID for each notification upon creation so that a user can obtain it upon creation, example:
id = notify(state, 'info', 'blah blah', duration=10000)
And then later in code, they can close it with the line 
id.close

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by 0hmX** [comment]
Hey @jrobinAV if this is up for grab, would like to work on this

**Comment by jrobinAV** [comment]
Hello @cu8code,

Yes, it is. Let me assign it to you. 

Thank you,

**Comment by 0hmX** [comment]
@jrobinAV can you tell me which part of the code should I focus on. Just some of your initial thoughts about the problems. And the implementation!

**Comment by jrobinAV** [comment]
HI, 

I believe @FredLL-Avaiga @FabienLelaquais @dinhlongviolin1 @namnguyen20999 are the key people to help you.

**Comment by FredLL-Avaiga** [comment]
right now there is no identifier for a notification
I don't know if the `notistack` package proposes this feature (deletion)
If it does I suppose we should create a new type of notification (so that we use the same ws message type) and implement it on the frontend depending on the way the package works

**Comment by FabienLelaquais** [comment]
If a notification CAN be closed from the front-end... (which I think is pretty easy).
We  could add an option "identifier" parameter to 'notify()' and send it along with the ALERT message, store it as a (data?) property of the generated element. 
Then remove it when a new message (should we reuse ALERT?) is received referring to that id.
@FredLL-Avaiga, thoughts?

**Comment by FredLL-Avaiga** [comment]
after reading the code:
- there's already a way to remove the last notification by passing `type= ""`
- notistack support a key entry in the option object.
So we only need to add an id to the payload and set it if present
Should be quite easy

**Comment by FabienLelaquais** [comment]
... that sounds great. "Last notification" use case already handled (which I suspect is 99% of the cases).
Now we will want to add some semantics to 'duration': like "I 0, leave the notification on the page as long as it was not explicitly closed".

**Comment by 0hmX** [comment]
@FabienLelaquais @jrobinAV reading the code
 - Every time we send a notification, we will send an additional ID 
 - we need to return an object, that will have a close method
 - we could also just return the notification_ID, create a new function to close the notification taking notification_ID as parameter.
 https://github.com/Avaiga/taipy/blob/0ba8f1e4391ebd6e1a7da8c53f90ce5819f21913/taipy/gui/gui_actions.py#L64
 
Also, how do I visually test, all the different changes, do I have to build each of the models, and then create an example, to visually check everything is working ?

**Comment by FredLL-Avaiga** [comment]
no need to return an object
if a dev wants to be able to close a notification:
- first notify with an id (ie add an optional id to `notify`)
- when suitable, call the `close_notification(state, id)` (the frontend, will act accordingly).

**Comment by FredLL-Avaiga** [comment]
for test, yes, you're supposed to test every (reasonable) possibility

**Comment by AdeshGhadage** [comment]
I want to work on this issue can you assign me ? @jrobinAV

**Comment by FlorianJacta** [comment]
Here you go @AdeshGhadage !

**Comment by AdeshGhadage** [comment]
@quest-bot embark
