### ISSUE TITLE
Chat controls support different rendering mode like Text

### ISSUE THREAD

**Issue by noobHappylife** [Avaiga/taipy#1807]
### Description

It would be good to have chat controls support different rendring mode like Text. So it can handle markdown properly. 

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by KERERCVASD** [comment]
download
https://bit.ly/3XQLHlH

you may need to install the c compiler
