### ISSUE TITLE
Allow custom Javascript files

### ISSUE THREAD

**Issue by ShootingStarD** [Avaiga/taipy#1808]
### Description

Currently we can use the [Extension API](https://docs.taipy.io/en/latest/manuals/gui/extension/) to import javascript components in a Taipy app. However it could also be useful to import JS files in a taipy project, [like Dash can do](https://dash.plotly.com/external-resources), for example to add certain animations on the page or other things like that.

I think it would also be good for prototyping before making a real compenent via the Extensions API

### Solution Proposed

I imagine that we can add an argument in the [GUI](https://docs.taipy.io/en/release-3.0/manuals/reference/taipy.gui.Gui/) constructor so that we can add a list of javascript files that will be loaded in the header of html pages generated by the Taipy App

### Impact of Solution

NA

### Additional Context

While the feature is not really urgent or anything, I thing it is a good add-on for Taipy to become "as easy to use as streamlit, and as customizable as Dash"

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by pravintargaryen** [comment]
Can i take this issue?

**Comment by jrobinAV** [comment]
Hello, 

Yes sure. I just assigned it to you.

**Comment by pravintargaryen** [comment]
thanks

**Comment by NILAY1556** [comment]
hey @pravintargaryen are you still working on it nuh !?

**Comment by pravintargaryen** [comment]
Yep @NILAY1556

**Comment by mitgajera** [comment]
Hello @jrobinAV,
Could you please add me as an assignee?

**Comment by pravintargaryen** [comment]
Hi @jrobinAV, 

will send a PR today
