### ISSUE TITLE
Typing issue using block elements from the Page Builder API

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy#1817]
### What went wrong? 🤔

Any code that uses a block element (`pane`, `part`...) in a *with* is shown to have a typing problem.
The code checker indicates that the base class for the element class is '_Element' (that does *not* have `__enter__()`/`__exit__()`) instead of `_Block` (that does).

For example, the line `with tgb.part("d-flex"):` shows an error and should not.

`part` explicitly derived from `_Block` that DOES implement `__enter()` and `__exit()` making it a valid context manager.
The code checker seems not to detect that inheritance...

### Expected Behavior

No error should be mentioned.

### Steps to Reproduce Issue

See the checker results on `[taipy]/doc/gui/examples/blocks/pane_persistent/builder.py`.

### Version of Taipy

_develop_

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by dinhlongviolin1** [comment]
User should not have it if installed with the pyi files. Replicated when using from source. Can not replicate it when using the installed package.
