### ISSUE TITLE
[DOCS] Updating docs on Element definition

### ISSUE THREAD

**Issue by namnguyen20999** [Avaiga/taipy#1819]
### Issue Description

Correcting the properties definition in the Element

### Proposed Solution (optional)

Change `properties (List[ElementProperty]): The list of properties for this element. ` to `properties (Dict[ElementProperty]): The dictionary of properties for this element.`

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by jrobinAV** [comment]
@namnguyen20999 There is no priority on that, and you are already assigned. What's the status?
