### ISSUE TITLE
Allow Selector component to filter even when using dropdown

### ISSUE THREAD

**Issue by zmikea** [Avaiga/taipy#1829]
### Description

Currently, if dropdown is enabled in a Selector component, then filter cannot be enabled. 

### Solution Proposed

I would like filter to be available even if dropdown is enabled. These should also both be allowed even if multiple is set to true. Any previously selected items should be unaffected - only the items in the dropdown list should be based on the filter. The filter entry could be in the same area as the selected items (the selected items already have an oval around them with an x next to them, wo it should be easy to distinguish the entry text from the selected items - perhaps the filter area would always be on the left, and any selected items would be to the right of that entry area.  Once you start typing into the filter area, the dropdown should open up, and as you type, it should dynamically update with the filtered list.

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
This is fixed in the next release. You can try it out in a fresh environment with taipy==4.0.0.dev2.
