### ISSUE TITLE
Indexed style in tables don't apply when defined as a lambda function (Markdown format)

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy#1832]
### What went wrong? 🤔

See the code below.

Replacing the element definition by the one shown on the line below generates a table that has no style applied to the cells.

### Expected Behavior

The element definition should behave identically.

### Steps to Reproduce Issue
```
from random import randrange
from taipy.gui import Gui, Markdown

x_range = range(0, 11)
data = {"x": [randrange(10) for _ in x_range]}

def x_style(_, value):
    return f"col{value}"

page = Markdown(
    "<|{data}|table|style[x]=x_style|show_all|>",
    # "<|{data}|table|style[x]={lambda _, v: f'col{v}'}|show_all|>",
    style={
        ".col0": {"background-color": "##b0b0b0"},
        ".col1": {"background-color": "#a5a4b0"},
        ".col2": {"background-color": "#9994b3"},
        ".col3": {"background-color": "#8880b0"},
        ".col4": {"background-color": "#7a71b0", "color": "white"},
        ".col5": {"background-color": "#6b5fad", "color": "white"},
        ".col6": {"background-color": "#5e50ad", "color": "white"},
        ".col7": {"background-color": "#5141ab", "color": "white"},
        ".col8": {"background-color": "#412eab", "color": "white"},
        ".col9": {"background-color": "#2c16a8", "color": "white"},
        ".col10": {"background-color": "#1b02a8", "color": "white"},
    },
)

Gui(page=page).run()
```

### Screenshots

![image](https://github.com/user-attachments/assets/9c97d319-af49-459c-b585-58a261f6259c)

### Version of Taipy

develop

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
you have 2 issues here:
- lambda
- f strings in lambda in taipy markdown
