### ISSUE TITLE
Scenario Selector - Primary scenario not in sync

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#184]
### Issue

Scenario Selector is not updated after a scenario has been put primary through the 'scenario' visual element. Refreshing the page updates the scenario selector as it should be.

![image](https://github.com/Avaiga/taipy/assets/98709993/9f142c1b-5e9d-47d4-99d3-441f8138088d)

### How to replicate

- Create scenarios in a cycle
- Promote a scenario to primary through the 'scenario' visual element

Version: Taipy 2.3.dev2

**Comment by FredLL-Avaiga** [comment]
I already reported this to the core team @jrobinAV 
https://github.com/Avaiga/taipy-core/issues/619

**Comment by jrobinAV** [comment]
@toan-quach Can you have a look at it ? This is for release 2.3.

Thx

**Comment by toan-quach** [comment]
Has been fixed in https://github.com/Avaiga/taipy-core/pull/630
Not yet released
