### ISSUE TITLE
[🐛 BUG] Input - "lines_shown" displays double the number of lines than expected

### ISSUE THREAD

**Issue by namnguyen20999** [Avaiga/taipy#1846]
### What went wrong? 🤔

The `lines_shown` property in the Input component is not behaving as expected. When the `lines_shown` value is defined, the actual number of lines displayed is double the value provided.

```
from taipy.gui import Gui

text = "1 \n2 \n3 \n4 \n5"


page = """
<|{text}|input|multiline|lines_shown=5|>
"""

Gui(page=page).run(port=3000, use_reloader=True)
```

### Expected Behavior

The Input should display the exact number of lines specified by the `lines_shown` property (e.g., 5 lines when `lines_shown=5)`.

### Steps to Reproduce Issue

1.	Set up a Input component in multiline mode.
2.	Define the lines_shown property to control the number of visible lines (e.g., lines_shown=5).
3.	Run the application and check the number of lines rendered.

### Screenshots

<img width="1056" alt="image" src="https://github.com/user-attachments/assets/b3671805-8b40-4b97-98b4-603a3cea2ef2">

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
https://mui.com/material-ui/api/text-field/

**Comment by FredLL-Avaiga** [comment]
looks like height is set by Mui ?
we could override it to `(n+3)em` ...

**Comment by FredLL-Avaiga** [comment]
https://github.com/mui/material-ui/blob/master/packages/mui-base/src/TextareaAutosize/TextareaAutosize.tsx
Line 107
