### ISSUE TITLE
Table: add css class to column headers

### ISSUE THREAD

**Issue by FredLL-Avaiga** [Avaiga/taipy#1853]
### Description

It would be helpful to have CSS classes associated to column header.

### Solution Proposed

I propose that the classes would be name via this procedure:
- prefix: taipy-table-header-
- suffix: the column name transformed to only allow A-Za-z\-_0-9

Make sure that the CSS class name is unique among all the columns of the table.

That calculation could be done completely in the front end.
TableUtils.ts seems a good place for this.

### Impact of Solution

Should be None

### Acceptance Criteria

- [X] Ensure new code is unit tested, and check code coverage is at least 90%.
- [X] Create related issue in taipy-doc for documentation and Release Notes.
- [X] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [X] Ensure any change is well documented.

### Code of Conduct

- [x] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by THEBOSS0369** [comment]
Hey @FredLL-Avaiga ! Can i work on this issue? Thanks!

**Comment by FredLL-Avaiga** [comment]
Would be nice also to add a class name to the "action" column (dfid = taipy_edit): header and cells

**Comment by FredLL-Avaiga** [comment]
> Hey [@FredLL-Avaiga](https://github.com/FredLL-Avaiga) ! Can i work on this issue? Thanks!

I guess this issue is a candidate for the Hacktoberfest ?
@jrobinAV @FabienLelaquais

**Comment by jrobinAV** [comment]
Sounds good to me.

**Comment by jrobinAV** [comment]
@FabienLelaquais any objection?

**Comment by THEBOSS0369** [comment]
Hey @jrobinAV @FredLL-Avaiga ! I found that taipy is sponsoring Devfest AI, So can I work on this Issue ? Thanks

**Comment by THEBOSS0369** [comment]
Hey @jrobinAV @FredLL-Avaiga ! I have come through Devfest AI, So can i work on this issue like should I wait for the assignment or get started. Thanks!

**Comment by Abhi0049k** [comment]
> > Hey [@FredLL-Avaiga](https://github.com/FredLL-Avaiga) ! Can i work on this issue? Thanks!
> 
> I guess this issue is a candidate for the Hacktoberfest ? @jrobinAV @FabienLelaquais

yes

**Comment by Abhi0049k** [comment]
Hi @FredLL-Avaiga, 

I hope you're doing well. I came across the issue regarding associating CSS classes to column headers, and I would like to request that this issue be assigned to me.

I have experience working with HTML, CSS, JavaScript, and have also worked with React and TypeScript. I believe my background will help in implementing the solution effectively, particularly in creating the CSS class naming conventions and handling the front-end logic.

Looking forward to contributing to this feature!

Best regards
Mangalam Kumar

**Comment by SaiNivedh26** [comment]
@FredLL-Avaiga Sounds interesting.  I think I can work on this !

**Comment by SGCODEX** [comment]
@jrobinAV @FredLL-Avaiga
Hi, please assign me this issue under Devfest ai and Hacktoberfest

**Comment by jrobinAV** [comment]
Thank you all for proposing your help. 
@THEBOSS0369 You were the first one to propose, so let me assign it to you. 

@Abhi0049k @SaiNivedh26 @SGCODEX  Thank you for your proposal. We have plenty of other tickets available for hacktoberfest. Do not hesitate to have a look at them.

**Comment by Abhi0049k** [comment]
Looking forward to contributing and collaborating with you all!

**Comment by THEBOSS0369** [comment]
>Thank you all for proposing your help. 
> @THEBOSS0369 You were the first one to propose, so let me assign it to you. 
> 
> @Abhi0049k @SaiNivedh26 @SGCODEX  Thank you for your proposal. We have plenty of other tickets available for hacktoberfest. Do not hesitate to have a look at them.
> 
> 
> 

Thank you sir! I will start workin on this issue Now 😀

**Comment by THEBOSS0369** [comment]
Hey @FredLL-Avaiga @jrobinAV ! Can you guide me how do i start the server. I have done every steps mentioned in contributing.md file and same file present in frontend folder. But i haven't been able to start the server yet. I tried running `pipenv run pytest` but then my server started for 10 second and stopped  these are the ss for the errors. Can you tell which command i have to run to start the server. I have been stuck for 2 days and still ain't able to start the server. Thanks
![image](https://github.com/user-attachments/assets/e32d34b5-f60f-49e1-9cd6-ada7f0b0469a)
![image](https://github.com/user-attachments/assets/dc2ed8d9-6d2e-45df-8bd3-e2e5837bcb1a)

**Comment by FredLL-Avaiga** [comment]
you need to write a python script and then run it with `python script.py`

**Comment by Ranj8521Kumar** [comment]
I wanna tackle this issue, please assign to me.

**Comment by THEBOSS0369** [comment]
Hey @Ranj8521Kumar ! Thanks for Asking! Actually I am working on this issue . So you can checkout other issues.

**Comment by FredLL-Avaiga** [comment]
1- you build the front end package by npm run build:dev
2- you create a python script that uses the component and the feature that your working on.
3- run that script and debug your component in the browser

For examples of simple script go to the doc\gui\examples directory

**Comment by THEBOSS0369** [comment]
Hey @FredLL-Avaiga ! This solved the problem now i can finally start working on this problem. Thanks Again :)

**Comment by THEBOSS0369** [comment]
@quest-bot embark 
This comment is not necessary just writing it for this quest thing 😅😅

**Comment by THEBOSS0369** [comment]
Hey Everyone!
Update regarding this issue : i'm almost done just left some testing will create PR as soon as i done with the testing (most probably today or tomorrow). 
Thanks!

**Comment by FlorianJacta** [comment]
Great @THEBOSS0369 !

**Comment by THEBOSS0369** [comment]
Hey Everyone ! 
I have created a PR for this Issue #2018 Your Feedback will be appreciated. 
Thanks

**Comment by TecHAyusH6476** [comment]
@SGCODEX @jrobinAV Please assign issue to me

**Comment by FlorianJacta** [comment]
@TecHAyusH6476, you can take a look at this PR https://github.com/Avaiga/taipy/pull/2018 and help if you want!

**Comment by sajithcode** [comment]
assign me to this

**Comment by THEBOSS0369** [comment]
Hey @sajithcode !  I have already submitted the PR for this issue #2018 which is almost completed, if you want you can also give your review on this Pr else There are plenty more issues you can work on em. Thanks
