### ISSUE TITLE
CouchBase Datanode

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#1862]
### Description

CouchBase is a widely used NoSQL Database. The purpose of this issue is to implement a CouchBase Datanode similar to the MongoDatanode.

More information in the comments: https://github.com/Avaiga/taipy/issues/1862#issuecomment-2404783206

**Comment by Rishi-0007** [comment]
Please assign this issue to me.

**Comment by FlorianJacta** [comment]
@Rishi-0007 Assigned

**Comment by snehaamujri** [comment]
Please assign this to me @jrobinAV

**Comment by Rishi-0007** [comment]
Hi @jrobinAV @FlorianJacta 
I’m currently working on issue #1862, which involves implementing CouchBase as a storage type for DataNodes. I would appreciate some guidance on the following:

   1.  Are there any existing patterns or classes I should extend for CouchBase support?
   2. How should the configuration setup look for CouchBase storage?
   3.  Are there specific testing strategies you recommend for this integration?

Any additional pointers would be helpful!

**Comment by jrobinAV** [comment]
Here are some additional info:

In Taipy, the crucial concept of a data node is implemented as a class named [`DataNode`](https://docs.taipy.io/en/latest/refmans/reference/pkg_taipy/pkg_core/DataNode/), which is used to simplify [data integration](https://docs.taipy.io/en/latest/refmans/reference/pkg_taipy/pkg_core/DataNode/). 
A data node is a pointer to some data, holding the metadata and implementing methods to read and write the data.
Each data node has a storage type (SQL, JSON, MongoCollection, etc.) corresponding to a dedicated implementation. 
Taipy instantiates the data nodes directly thanks to a [`DataNOdeConfig`](https://docs.taipy.io/en/latest/refmans/reference/pkg_taipy/pkg_core/pkg_config/DataNodeConfig/) that the user creates through a `configure` method.


**This issue is about exposing a new possible storage type: `couchbase_collection`. A new corresponding data node implementation must be called `CouchBaseCollectionDataNode`. A dedicated configure method should also be exposed.**


The new CouchBaseCollectionDataNode class should be similar to the existing `MongoCollectionDataNode`. 
To understand what to do, one could have a look at:
- The code of the mongo.py file to understand how it works.
- The various usages of the `MongoCollectionDataNode` class.
- The DataNodeConfig._configure_mongo_collection() function.
- The `test_mongo_data_node.py::TestMongoCollectionDataNode.test_create` test function.

1. The `DataNodeConfig` should have a new method named `_configure_couchbase_collection`.
It will be used to configure a new data node. The method signature should expose only the standard parameters, and optional parameters should be passed as **kwargs.

2. The `CouchBaseCollectionDataNode` should be created in the `taipy/core/data/couchbase.py`file. It must implement the abstract `DataNode`class.
The properties dictionary, built as a copy of the `DataNodeConfig` kwargs attributes, provides the required or optional configuration parameters.

Hope that helps.

**Comment by snehaamujri** [comment]
@Rishi-0007 Can we collaborate on this or shall we split the work ??

**Comment by Rishi-0007** [comment]
> @Rishi-0007 Can we collaborate on this or shall we split the work ??

Hi @snehaamujri , do you need any help now?

**Comment by snehaamujri** [comment]
Hey @Rishi-0007, thanks for reaching out! I have already raised a pull request for the Couchbase Datanode issue, but there are some errors and feedback from the reviewers that I need help with. Would you be able to take a look at the PR and collaborate with me on fixing those issues? Your help would be much appreciated!
