### ISSUE TITLE
[🐛 BUG] Problem with data_node edit

### ISSUE THREAD

**Issue by enarroied** [Avaiga/taipy#1864]
### What went wrong? 🤔

I'm using Taipy develop, installed 3-4 days ago. 
I created a `data_node` visual element, from a CSV Data Node. The visual element renders OK. When I click the on_edit button, nothing get edited (the toggle button moves OK).
In the terminal, I get this error:
`C:\Users\PC\anaconda3\envs\taipy_develop1\Lib\site-packages\taipy\gui\gui.py:1490: TaipyGuiWarning: on_action(): 'tp_lock_datanode_for_edit_1' is not a 
valid function.
  _warn(f"on_action(): '{action}' is not a valid function.")`

### Expected Behavior

So I was testing the visual element, and I didn't know exactly what should happen! I believe it should edit my data, without needing a Callback function, and not give an error. 

### Steps to Reproduce Issue

To reproduce the issue, you can use a file called cities.csv, like this:
```
Index,City,Country,population
1,Tokyo,Japan,37468000
2,Delhi,India,28514000
3,Shanghai,China,25582000
4,São Paulo,Brazil,21650000
5,Mexico City,Mexico,21581000
6,Cairo,Egypt,20076000
7,Mumbai,India,19980000
8,Beijing,China,19618000
9,Dhaka,Bangladesh,19578000
10,Osaka,Japan,19281000
```

Here is a single-page app that reproduces the error:
```python
import taipy as tp
import taipy.gui.builder as tgb
from taipy import Config, Orchestrator, Scope
from taipy.gui import Gui

cities_csv_node_config = Config.configure_csv_data_node(
    id="most_populated_cities_csv",
    default_path="./cities.csv",
    has_header=True,
    exposed_type="pandas",
    scope=Scope.GLOBAL,
)


orchestrator = Orchestrator()
orchestrator.run()
biggest_cities = tp.create_global_data_node(cities_csv_node_config)

with tgb.Page() as data_node_selector:
    tgb.text("## Test of Data Node viewer", mode="md")

    tgb.data_node(
        data_node="{biggest_cities}",
    )


gui = Gui(page=data_node_selector)

gui.run(
    use_reloader=True,
)
```

### Solution Proposed

Sorry, no idea :(

### Screenshots

As you can see, the visual part works good:

![image](https://github.com/user-attachments/assets/e6da812e-de35-427a-af64-89e072528cf5)

### Runtime Environment

Windows 10, I used Python 12 within Anaconda, Taipy develop

### Browsers

Brave

### OS

Windows

### Version of Taipy

develop (4)

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by KunjShah95** [comment]
Kindly assign it to me

**Comment by FlorianJacta** [comment]
[@KunjShah95](https://github.com/KunjShah95) You are already assigned to another issue. For hacktoberfest, we only assign issues one at a time. Please submit a PR on the other issue first, or remove your assignment.

Thank you.

**Comment by KunjShah95** [comment]
i have removed my previous issue so kindly assign it to mme now
