### ISSUE TITLE
⭐ Currently, when navbar scrolls up with the page, unlike other websites where it remains sticky. I would like to address this issue.

### ISSUE THREAD

**Issue by prathamesh424** [Avaiga/taipy#1876]
Navbar is not visible 
 ![Screenshot 2024-10-02 015016](https://github.com/user-attachments/assets/e8c7b7d8-3169-4e20-b7ba-4460a587078c)

**Comment by FlorianJacta** [comment]
Rights to the website repo are private. You won't be able to change this yourself. @RymMichaut What do you think of this issue?

**Comment by prathamesh424** [comment]
The Navbar of webasite should be sticky and if not possible to modify by contributor @FlorianJacta  make it visible in this repo also so anyone not waste time on detecting resolved or un authorised issue

**Comment by RymMichaut** [comment]
Hello @prathamesh424 
Thanks for the issue.
However, we wanted to make the website as sober as possible. It's a UX/UI choice :)
