### ISSUE TITLE
[🐛 BUG] Datanodes with unsupported types are not selected

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#1916]
### What went wrong? 🤔

Selecting Data Nodes through the data node selector will sometimes not propagate the selection to the data node viewer.

It seems to happen when data nodes have some unsupported types.

### Expected Behavior

We should be able to select and say that their types are not supported.

### Steps to Reproduce Issue

Run this code and select different data nodes.
```python
from taipy import Config
import taipy as tp

integer_cfg = Config.configure_data_node("integer", default_data=1)

model_cfg = Config.configure_data_node("model", default_data=Config)

scenario_cfg = Config.configure_scenario(
    id="my_scenario",
    additional_data_node_configs=[integer_cfg, model_cfg],
)

data_node = None

if __name__ == "__main__":
    # Run of the Core
    tp.Orchestrator().run()

    # Creation of the scenario and execution
    scenario = tp.create_scenario(scenario_cfg, name="Submitted")

    scenario_md = """
<|{data_node}|data_node_selector|>

<|{data_node}|data_node|>
"""

    tp.Gui(scenario_md).run()

```

### Version of Taipy

develop - 10/3/24
### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by durveshwagh11** [comment]
pls assign it to me

**Comment by SGCODEX** [comment]
Please assign it to me

**Comment by AlexandreSajus** [comment]
Assigned

**Comment by naaa760** [comment]
Hello @FlorianJacta :)
Please assign me this issue!

**Comment by RaedenCodes** [comment]
Please assign it to me

**Comment by FredLL-Avaiga** [comment]
Hi @durveshwagh11 
I'm sorry but there was a misunderstanding.
I'm already working on this and will push a PR very soon.
