### ISSUE TITLE
Make a navbar to be sticky 

### ISSUE THREAD

**Issue by MOHDNEHALKHAN** [Avaiga/taipy#1922]
### What went wrong? 🤔

The navbar goes away after scrolling down
![Screenshot 2024-10-04 190137](https://github.com/user-attachments/assets/cb01c770-184b-46b9-8b6d-0a116cf4aaeb)

### Expected Behavior

The navbar should be fixed at the top of the page
![Screenshot 2024-10-04 190649](https://github.com/user-attachments/assets/72db683c-ffdf-45f6-b096-bac2e8da696c)

### Browsers

Chrome

### OS

Windows

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by MOHDNEHALKHAN** [comment]
@FredLL-Avaiga , please assign this issue to me under hacktoberfest ,
 under hacktoberfest - 100💎

**Comment by RymMichaut** [comment]
> @FredLL-Avaiga , please assign this issue to me under hacktoberfest ,
> 
>  under hacktoberfest - 100💎

@MOHDNEHALKHAN website is not open to contribution. We cannot assign it to you. Sorry

**Comment by MOHDNEHALKHAN** [comment]
Ok thank you for reply👍🏻
