### ISSUE TITLE
[DOCS] Different Languages Readme File

### ISSUE THREAD

**Issue by Durgesh4993** [Avaiga/taipy#1931]
### Issue Description

A ReadMe file issue related to different languages typically arises when trying to make a project's documentation accessible to a broader audience.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by KunjShah95** [comment]
I WANT O WORK ON THIS ISSUE SO KINDLY CAN U ASSIGN ME THIS UNDER HACTOBERFEST ISSUE

**Comment by jrobinAV** [comment]
We want Taipy documentation to remain in American English only. 
It would be costly and difficult to maintain over time. 
Plus, the added value of translating it is not so great, thanks to free and very powerful tools like browser plugins, Google Translate, Chat-GPT, etc.
