### ISSUE TITLE
[DOCS] Add Badges

### ISSUE THREAD

**Issue by yashksaini-coder** [Avaiga/taipy#1934]
### Issue Description

I would like to add interactive badges in a table format, int the header-section of the README documentation. This will enhance the Engagement & interface of the README.

I would like to work on this issue. can you assign this issue to me. @RymMichaut 

### Screenshots or Examples (if applicable)

![image](https://github.com/user-attachments/assets/d7bc338d-e36a-49bc-be4d-0d57c35debc0)

### Proposed Solution (optional)

Use badges to add dynamic & real time updating that will show simple stats.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by RymMichaut** [comment]
hey @yashksaini-coder that would be good.

Can you limit the badges to the following, as in the attached picture?

- Version (could this be automated with the version in the [doc](https://docs.taipy.io/en/latest/relnotes/))?
- License: Apache 2.0
- Python version needed 3.8

And three other cards to illustrate the current links:
- [📚 Explore the docs](https://docs.taipy.io/en/latest/)
- [🫱🏼‍🫲🏼 Discord support](https://discord.com/invite/SJyz2VJGxV)
- [👀 Demos & Examples](https://docs.taipy.io/en/latest/gallery/)

See image below:
![image (5)](https://github.com/user-attachments/assets/ca332445-a487-4224-9cb3-486a39b1c0e9)

**Comment by yashksaini-coder** [comment]
@RymMichaut sure I can do that,can you add more for hacktoberfest and assign this issue to me

**Comment by RymMichaut** [comment]
> @RymMichaut sure I can do that, can you add more for hacktoberfest and assign this issue to me

Sure.

Ensure you respect the charter by replacing the purple with the orange #ff371a

**Comment by yashksaini-coder** [comment]
> > @RymMichaut sure I can do that, can you add more for hacktoberfest and assign this issue to me
> 
> Sure.
> 
> Ensure you respect the charter by replacing the purple with the orange #ff371a

Yes no problem at all. @RymMichaut will follow your guidelines & make sure to meet your requested changes

**Comment by loadinglit** [comment]
hey @jrobinAV  i see the pr is still open , would like to give my contribution to this issue, please assign this to me

**Comment by snehaamujri** [comment]
i would love to work on this @RymMichaut

**Comment by RymMichaut** [comment]
@snehaamujri there's already someone on it @yashksaini-coder 
But let's see how both of you perform :)

**Comment by aniketh-varma** [comment]
Hi @RymMichaut, can I work on this issue?

**Comment by coddingjatin** [comment]
Hi @RymMichaut, can I work on this issue?

**Comment by kaioumdev** [comment]
@RymMichaut Could you please review my code? If there are any issues or necessary changes, I’d be happy to resolve them. Otherwise, kindly proceed with merging my pull request.
