### ISSUE TITLE
[🐛 BUG] No delete chats button in the chatbot

### ISSUE THREAD

**Issue by NishantRana07** [Avaiga/taipy#1942]
### What went wrong? 🤔

![Screenshot 2024-10-06 223942](https://github.com/user-attachments/assets/08a0d308-cd9a-4f5d-9a72-617718ac949c)

### Steps to Reproduce Issue

1. A code fragment
2. And/or configuration files or code
3. And/or Taipy GUI Markdown or HTML files

### Solution Proposed

Delete chat can be added to the cahbot for better communication

### Screenshots

![DESCRIPTION](LINK.png)

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by arnab825** [comment]
Is there any issue? Can you tell me which issue are you faing so I can write the solutuin on the code.

**Comment by FlorianJacta** [comment]
@NishantRana07 This issue is not for Taipy but for Taipy website. I wasn't able to replicate it
