### ISSUE TITLE
[DOCS] Add Hacktoberfest.md for Hacktoberfest Event Guide

### ISSUE THREAD

**Issue by mitgajera** [Avaiga/taipy#1944]
### Issue Description

We are celebrating Hacktoberfest! We need a detailed Hacktoberfest.md file to help new contributors get started with our repository and participate in the Hacktoberfest event. The file should include:

A brief introduction to Hacktoberfest.

- Steps on how to participate in Taipy’s Hacktoberfest (choosing issues, contributing, etc.).
- Links to relevant resources and labels in our repository.
- Information on rewards and how to earn them.
- Process details (forking the repo, submitting a pull request).
- Encouraging developers to give Taipy a star on GitHub for additional swag.

Tasks:

Create a new Hacktoberfest.md file in the root directory.
Add all the relevant sections mentioned in the description.
Make sure to include appropriate links to issues, repository, and event-related content.

I propose to assign this under Hacktoberfest-2024.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by Avii-KS** [comment]
Hi @mitgajera  can I be assigned to solve this issue?
This is my first time takin part in an Open Source Contribution and i would love to work on this issue!

**Comment by FlorianJacta** [comment]
This issue has to be reviewed internally. Thank you for raising it! We will come back to you ASAP

**Comment by manvith12** [comment]
is this issue still open? could i be assigned ? this would be my first-good-issue

**Comment by mitgajera** [comment]
@FlorianJacta 
So what did you decide about this issue ?

**Comment by RymMichaut** [comment]
The document already exists in two places:
- a notion site (and the banner on the Taipy Readme.md leads to it): https://assorted-son-815.notion.site/HacktoberFest-2024-with-Taipy-2a5032a3f01642709e88ffaa5d0d169e
- the website : https://taipy.io/blog/hacktoberfest-2024-contribute-win-swag-taipy/

**Comment by Aienthu1** [comment]
how we solve this issue.

**Comment by RymMichaut** [comment]
@Aienthu1 this issue is closed and won't be solved as we already have the guidelines elsewhere
