### ISSUE TITLE
[🐛 BUG] scenario_selector visual element has inactive edit button

### ISSUE THREAD

**Issue by enarroied** [Avaiga/taipy#1948]
### What went wrong? 🤔

I'm trying out the scenario_selector visual element. I'm working with Taipy develop, I pulled and installed it in a new env yesterday. The editing button doesn't seem to work.

When I click on "Add Scenario", it works, overall it looks fine.

But the edit button (the little pencil) is grayed out (I can see it, and when I hover over it,  it says "Edit Scenario"). When I click on it, it triggers the on_change function but doesn't open the edition panel.

### Expected Behavior

The edit button should be clickable, and open the edit pane.

### Steps to Reproduce Issue

Here is a sample, but I think any `scenario_selector` has the problem.

```
        tgb.scenario_selector(
            value="{None}",
            show_pins=True,
            on_creation=add_scenario,
            on_change=run_scenario,
        )
```

### Screenshots

![DESCRIPTION](LINK.png)

### Runtime Environment

Windows 10, I used Python 12 within Anaconda, Taipy develop

### Browsers

Brave

### OS

Windows

### Version of Taipy

develop (4)

### Additional Context

```bash
I can't select the pencil button, so there are no logs or errors either.
```

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by nehaaprasad** [comment]
Hello Mr @enarroied :)

I want to work on this issue.
Please assign me!
Thankyou!

**Comment by FredLL-Avaiga** [comment]
This issue is already assigned and fixed

**Comment by nehaaprasad** [comment]
> This issue is already assigned and fixed

Okay, thank you for letting me know!
