### ISSUE TITLE
Add Option to Delete Existing Conversation in Chatbot

### ISSUE THREAD

**Issue by Mefisto04** [Avaiga/taipy#1950]
### Description

Currently, the chatbot in Taipy does not provide an option to delete the existing conversation. Users may want to reset the chatbot to start a fresh topic or delete previous messages for clarity. This feature would enhance user experience by allowing them to clear the chat history and begin a new conversation at any time.

### Solution Proposed

Implement a button in the chatbot interface that allows users to:

- Delete all past interactions and refresh the conversation window.
- This could be achieved by adding a "Reset" button in the UI, which when clicked, would clear the chatbot's state and allow the user to start fresh.

### Impact of Solution

This feature will impact the chatbot's flow, as it needs to handle conversation state more effectively. Care must be taken to ensure that resetting the conversation does not interfere with session management or other ongoing tasks. Additionally, this feature may require updates to the chatbot's UI and conversation logic.

### Additional Context

In its current form, users may have to manually scroll through or ignore past messages to start a new topic. This feature will streamline the user experience. Other chatbot solutions often provide such a reset option to help users manage conversations effectively.

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by eleensmathew** [comment]
Can i work on this?

**Comment by Mefisto04** [comment]
please find another issue @eleensmathew, I have started the changes, @FredLL-Avaiga please assign this issue to me so that i can start working on it.

**Comment by FlorianJacta** [comment]
This issue should be discussed internally before it is open for contribution. Thank you for your issue; we'll give you an answer soon

**Comment by AlexandreSajus** [comment]
What chatbot are you referring to?

Are you referring to one of our LLM demos like: https://docs.taipy.io/en/latest/tutorials/fundamentals/4_chatbot/
Or are you referring to the chat visual element in the dev version: https://docs.taipy.io/en/develop/refmans/gui/viselements/generic/chat/

What is preventing you from creating a button that resets the variable storing the conversation messages?

**Comment by SaumyaSubham** [comment]
Hii @Mefisto04 ,  I can work for this feature so that the users can easily reset their conversation which is really good and if we refresh the conversation window, it might affect other crucial items. I suggest the Reset button is absolutely a good idea to clear the conversation. Kindly assign me to do this under hacktoberfest 2024.

**Comment by Vaibhav91one** [comment]
@jrobinAV  Please assign this issue to me and please do clarify whether this RAG chatbot or chat UI component.

**Comment by kekwlboy12469** [comment]
pls assign this work to me am looking forward to work on it

**Comment by jyotiahluwalia** [comment]
@jrobinAV Please assign this issue to me if possible, would like to contribute 

Thank you

**Comment by FredLL-Avaiga** [comment]
No one answered @AlexandreSajus question.
Deleting the current conversation in Taipy chat control is as simple as resetting the backend supporting tabular data to an empty array/dataframe ...
I don't think this should be part of the Taipy control.
I propose to close this issue (unless it refers to Talk To Taipy Demo)
Thoughts @jrobinAV @AlexandreSajus @FlorianJacta @FabienLelaquais ?

**Comment by AlexandreSajus** [comment]
Agreed, let's close this

**Comment by jrobinAV** [comment]
I am OK to close it
