### ISSUE TITLE
Allow Polars DataFrame as argument for tgb.table()

### ISSUE THREAD

**Issue by ShootingStarD** [Avaiga/taipy#1957]
### Description

The `tgb.table()` function does not accept yet polars DataFrame, this can be bypassed by using `df.to_pandas()` but since polars is growing and slowly becoming a replacement for pandas is a lot of area, it would make sense for me to have a native integration in taipy for it.

Here is the code that should work with the new feature : 

```python
from taipy.gui import builder as tgb
from taipy.gui import Gui
import polars as pl

df = pl.DataFrame({"name": ["Héricendre", "Kaiminus", "Germignon"]})
with tgb.Page() as page:
    tgb.table(data="{df}")
Gui(
    page,
).run(debug=True, use_reloader=True, port=5111)
```

For now it does not show a table and raise the following warning : 
```
WARNING:root:
--- 1 warning(s) were found for page '/'  ---
 - Warning 1: Can't find Data Accessor for type <class 'polars.dataframe.frame.DataFrame'>.
----------------------------------------------
```

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
[Taipy Enterprise](https://taipy.io/pricing) will integrate Polars in 4.0 in tables; this feature has already been treated. It will also integrate Polars in its data management capabilities (data nodes). See [Release Notes](https://docs.taipy.io/en/develop/release-notes/#new-features_1)
