### ISSUE TITLE
 show current time 

### ISSUE THREAD

**Issue by AdibaNaushad** [Avaiga/taipy#1962]
### Description

if it shows  current date and time .it will look more fuctional and helpful .it will enhance the feature . a very simple feature but it is very effective

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by RaedenCodes** [comment]
@AdibaNaushad where are you referring exactly ??

**Comment by AdibaNaushad** [comment]
@RaedenCodes  on website

**Comment by FlorianJacta** [comment]
Taipy website is not in the scope of the Taipy repository @AdibaNaushad 

You should create issues related to the Taipy Python package
