### ISSUE TITLE
[DOCS] Consistency in function and method docstrings

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#1968]
### Issue Description

Function and method parameters are documented using either `Parameters`, `Arguments`, or `Args` keywords. We should only use `Arguments` everywhere.

### Code of Conduct

- [x] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by Tushar98644** [comment]
@jrobinAV can i take up the issue ?

**Comment by wizaye** [comment]
@jrobinAV would like to work on this , could you assign this to me?

**Comment by FlorianJacta** [comment]
@Tushar98644 @wizaye I have assigned this issue to both of you! Thank you for your contribution!

**Comment by wizaye** [comment]
@FlorianJacta I've made a PR with the necessary changes. please check it ;)

**Comment by Harish-2003** [comment]
Is this issue still open

**Comment by wizaye** [comment]
@Harish-2003 its open but we're working on it kindly check other issues for time being

**Comment by Harish-2003** [comment]
> @Harish-2003 its open but we're working on it kindly check other issues for time being

Sure

**Comment by wizaye** [comment]
@trgiangdo @FlorianJacta i had a issue with the branch while updating the previous pr, i've opened a new one #1973 with the requested changes, please look into it

**Comment by afrinashar** [comment]
I would like to work on this.

**Comment by FlorianJacta** [comment]
@wizaye is already working on it and created a PR on this issue. But I can also assign you if you want to collaborate.

**Comment by margaret-hu** [comment]
How do I take up an issue?

**Comment by wizaye** [comment]
@margaret-hu  someone from the team assigns it to you and then you work on it and make a valid PR

**Comment by margaret-hu** [comment]
Can I assist with this issue as well?

**Comment by wizaye** [comment]
@margaret-hu yes you can , wait until someone from the team assigns the issue to you. We're currently working on the issue with an ongoing PR you can check that as well.

**Comment by jrobinAV** [comment]
@margaret-hu Thank you for your help. You are assigned as well.

**Comment by margaret-hu** [comment]
How do I directly contribute to an issue?

**Comment by DevyManish** [comment]
i do like to take on this issue please assign it to me!

**Comment by Sushil2k4** [comment]
I would like to work on this project. Please assign it to me .

**Comment by FlorianJacta** [comment]
@Sushil2k4 and @margaret-hu, look up the PR created for this issue. You can either collaborate on it or create your own PR that you think improve it

**Comment by DevyManish** [comment]
@FlorianJacta Sorry for the delay, but I’ve submitted a PR with the required changes. Please take a look when you can! [PR #2046](https://github.com/Avaiga/taipy/pull/2046)

**Comment by coddingjatin** [comment]
@jrobinAV can i take up this issue ?

**Comment by venelouis** [comment]
Hi I want to make my first hacktoberfest contribution, can you help me?

**Comment by jrobinAV** [comment]
This issue has been resolved by #2046
