### ISSUE TITLE
[🐛 BUG] Warning on Brower Console

### ISSUE THREAD

**Issue by Satoshi-Sh** [Avaiga/taipy#1971]
### What went wrong? 🤔

When I run an app, a warning in the browser terminal comes up as the screenshot shows.

### Expected Behavior

Getting no warnings.

### Steps to Reproduce Issue

1. Start an app and check the browser console.

### Screenshots

![Screenshot from 2024-10-08 11-29-39](https://github.com/user-attachments/assets/fcef946b-6d36-4b32-ac9a-1c8bde595100)

### Runtime Environment

Ubuntu 24.04.1 LTS

### Browsers

Chrome, Firefox

### OS

Linux

### Version of Taipy

development

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by wizaye** [comment]
@Satoshi-Sh could you provide me more info on this behaviour and the components it is affecting across the repo!
Based on the issue , i've a glance of what might be the problem in the code base, but i didn't try a hard run in my local machine.
It would be great if you assign this issue to me to work along. Please make sure to take prior assistance from contributors. ;)

**Comment by Satoshi-Sh** [comment]
@wizaye  I'm not a maintainer. The maintainers would be able to assist you if needed.

**Comment by FlorianJacta** [comment]
I have also seen it. I don't think this will create issues, as it is just a warning. What are your thoughts? @FredLL-Avaiga

**Comment by FredLL-Avaiga** [comment]
> I have also seen it. I don't think this will create issues, as it is just a warning. What are your thoughts? @FredLL-Avaiga

You're right we don't care of those
Shall I close the issue or will you do it @Satoshi-Sh ?
