### ISSUE TITLE
[DOCS] Fix Markdown in README.md

### ISSUE THREAD

**Issue by Sriparno08** [Avaiga/taipy#1979]
### Issue Description

In README.md, the following 'Getting Started' link is not rendered correctly as there is a typo in the markdown.

### Screenshots or Examples (if applicable)

![Screenshot](https://github.com/user-attachments/assets/dff1fb0d-8ed3-49c0-b7aa-515a749d92db)

### Proposed Solution (optional)

We should fix the markdown so that the link is rendered correctly.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
This is right; thank you for your feedback! Do you want to be assigned to this issue?

**Comment by manvith12** [comment]
> This is right; thank you for your feedback! Do you want to be assigned to this issue?

i would like to have it!!

**Comment by vidhigoyal619** [comment]
I would love this opportunity to contribute to this issue and provide valuable output.

**Comment by SaumyaSubham** [comment]
I would like to redesign the readme.md file and also fix the Getting Started link so that the users can get an updated look of readme.md file

**Comment by Sriparno08** [comment]
Yeah sure, @FlorianJacta!

**Comment by FlorianJacta** [comment]
I am assigning you then @Sriparno08. Do your magic and thank you!

**Comment by Sriparno08** [comment]
Thanks for assigning, @FlorianJacta!

**Comment by Sriparno08** [comment]
Hey @FlorianJacta, I just found out that this issue has already been fixed via another PR (#1983).

**Comment by FlorianJacta** [comment]
This is true... the process is not respected by everyone, unfortunately. Sorry for that! Hope you can find another issue on our repo

**Comment by Sriparno08** [comment]
It's okay, @FlorianJacta. 🙂
