### ISSUE TITLE
Add back to top functionality

### ISSUE THREAD

**Issue by Rajput-xv** [Avaiga/taipy#1982]
### Description

As the total height of website is long so back to top button is much needed for easy navigation.

So assign this issue to be under Hacktoberfest.

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
This repo is not about the Taipy website but thank you for your feedback.
