### ISSUE TITLE
<Optimizing the blank space>

### ISSUE THREAD

**Issue by Aazib-at-hub** [Avaiga/taipy#2000]
### Description

there is blank space at the bottom on the left side. 

### Solution Proposed

i'm thinking to optimize it by increasing the size of social midea icons and adding username to it.

### Impact of Solution

It will have better visiblity as well someone can just remember the username to go and follow later.

### Acceptance Criteria

- [ yes ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ yes ] Create related issue in taipy-doc for documentation and Release Notes.
- [ yes ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it.
- [ yes ] Ensure any change is well documented.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
What are you talking about? About the Taipy website?

**Comment by Aazib-at-hub** [comment]
> What are you talking about? About the Taipy website?

Yes

**Comment by FlorianJacta** [comment]
Thank you, but this repository is not for the Taipy website (taipy.io). It is for the Taipy package. I am closing this issue
