### ISSUE TITLE
[🐛 BUG] on_action id and payload parameters swapped

### ISSUE THREAD

**Issue by namnguyen20999** [Avaiga/taipy#2045]
### What went wrong? 🤔

The on_action function's id and payload parameters are not behaving as expected. The values of these parameters appear to be swapped. The id parameter is receiving the payload data, and the payload parameter is receiving the id value.

<img width="1213" alt="image" src="https://github.com/user-attachments/assets/b9b934fa-d873-494f-ac2d-400cfeaf1979">

### Expected Behavior

1. id should receives a string representing the identifier of the caller.
2. payload should holds the optional payload data from the caller

### Steps to Reproduce Issue

1. Define an on_action function with state, id, and payload parameters.
2. Trigger the action that calls this function.
3. Observe the values of id and payload within the function.

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
is it everywhere or only for the menu ?

**Comment by FredLL-Avaiga** [comment]
My bad, this is linked to a refactoring when implementing the event listener

**Comment by FredLL-Avaiga** [comment]
PS: it would be easier for everyone to include python source code as test and not as image 😉

**Comment by AlexandreSajus** [comment]
Fixed in 4.0.1.dev1
:tada:
