### ISSUE TITLE
Scenario - Pipeline submission triggers edit mode for label

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#205]
### Issue

Clicking on submit for a pipeline opens the edit mode for the pipeline label.

![image](https://github.com/Avaiga/taipy/assets/98709993/14b98576-4128-49da-be30-dce671a5dc9d)

### Expected behavior

It should just submit the pipeline and not open the 'edit mode' for the pipeline label.

Verison: Taipy 2.3.0.dev4

**Comment by FredLL-Avaiga** [comment]
@FabienLelaquais Should we bring this in ?
