### ISSUE TITLE
[🐛 BUG] tgb.Page style argument not working?

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#2068]
### What went wrong? 🤔

If I apply styling using `main.css`, it works properly:

In `main.py`:
```python
from taipy import Gui
import taipy.gui.builder as tgb

if __name__ == "__main__":
    # Add a navbar to switch from one page to the other
    with tgb.Page() as root_page:
        tgb.navbar()
        tgb.text("# Multi-page application", mode="md")

    with tgb.Page() as page_1:
        tgb.text("## This is page 1", mode="md")
    with tgb.Page() as page_2:
        tgb.text("## This is page 2", mode="md")

    pages = {"/": root_page, "page1": page_1, "page2": page_2}
    Gui(pages=pages).run()
```

In `main.css`:
```css
.taipy-navbar > .MuiTabs-root > .MuiTabs-scroller > .MuiTabs-flexContainer > .MuiButtonBase-root {
  color:brown;
  font-family:sans-serif;
  font-weight: bold;
}
```

![image](https://github.com/user-attachments/assets/cc22cfea-85e4-45a0-9a83-e2fe672ac349)

If I try to apply it directly in `tgb.Page`, it does not work:
```python
from taipy import Gui
import taipy.gui.builder as tgb

if __name__ == "__main__":
    # Add a navbar to switch from one page to the other
    with tgb.Page(
        style={
            ".taipy-navbar>.MuiTabs-root>.MuiTabs-scroller>.MuiTabs-flexContainer>.MuiButtonBase-root": {
                "color": "brown",
                "font-family": "sans-serif",
                "font-weight": "bold",
            }
        }
    ) as root_page:
        tgb.navbar()
        tgb.text("# Multi-page application", mode="md")

    with tgb.Page() as page_1:
        tgb.text("## This is page 1", mode="md")
    with tgb.Page() as page_2:
        tgb.text("## This is page 2", mode="md")

    pages = {"/": root_page, "page1": page_1, "page2": page_2}
    Gui(pages=pages).run()
```

![image](https://github.com/user-attachments/assets/bf8e87a3-eed0-484f-b42a-83f883271530)

What am I doing wrong?

### Steps to Reproduce Issue

1. A code fragment
2. And/or configuration files or code
3. And/or Taipy GUI Markdown or HTML files

### Screenshots

![DESCRIPTION](LINK.png)

### Browsers

Chrome

### OS

Windows

### Version of Taipy

4.0.0

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
this is not working because the page the style is applied to is the root page.
I'll see if we can make this work ... while authorizing the children pages to set their own style ...
if you move the style declaration to the other pages it works.
Another solution would be to apply the style to the navbar component itself ...

**Comment by FredLL-Avaiga** [comment]
Indeed this works well ... provided you can you style on components (which is 4.1 I think)

```py
import taipy.gui.builder as tgb
from taipy import Gui

if __name__ == "__main__":
    # Add a navbar to switch from one page to the other
    with tgb.Page() as root_page:
        tgb.navbar(style={
            ".MuiTabs-root>.MuiTabs-scroller>.MuiTabs-flexContainer>.MuiButtonBase-root": {
                "color": "brown",
                "font-family": "sans-serif",
                "font-weight": "bold",
            }
        })
        tgb.text("# Multi-page application", mode="md")

    with tgb.Page() as page_1:
        tgb.text("## This is page 1", mode="md")
    with tgb.Page() as page_2:
        tgb.text("## This is page 2", mode="md")

    pages = {"/": root_page, "page1": page_1, "page2": page_2}
    Gui(pages=pages).run(title="2068 [🐛 BUG] tgb.Page style argument not working?")

```
