### ISSUE TITLE
Rank data nodes by topological order in the data node selector

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#2071]
> A tradeoff has been proposed.
> The idea is to display in the data node selector the data nodes in a topological order for a scenario. With this proposal, the scenario is the context used to set the data node rank.
> 
> A more formal proposal should come soon. 

 _Originally posted by @jrobinAV in [#1363](https://github.com/Avaiga/taipy/issues/1363#issuecomment-2312412495)_

**Comment by jrobinAV** [comment]
Branch in progress: https://github.com/Avaiga/taipy/tree/feature/%232071-rank-datanodes-in-selector 
Corresponding PR: https://github.com/Avaiga/taipy/pull/2072

@FredLL-Avaiga Does it make sense for you to take over this issue and the related branch?

**Comment by FredLL-Avaiga** [comment]
The issue why not but the branch not really.

**Comment by jrobinAV** [comment]
So please create a PR to merge into my branch instead of develop then. Thx.

**Comment by FredLL-Avaiga** [comment]
Correct me if I'm wrong @jrobinAV :
to get the rank of a datanode:
1. get the datanode's owner
2. if the owner is a scenario, get the config id of the owner
3. get the rank from the datanode config based on the scenario config's id

if this is right, can I propose a new method to datanode that would return the rank ?

**Comment by jrobinAV** [comment]
I understand we want to rank the data node for a given scenario, which is not necessarily the owner of the data node. The given scenario could be:
- the data node's owner, as you said.
- the scenario passed as a property of the data node selector
- the "current" scenario group, when the property `display_cycles` is False.

So the code could look like:
```
given_scenario
datanode_rank = datanode._ranks.get(given_scenario.config_id, None)
```
What you propose is to have an API on the data node's side like the following so you don't need to have a given scenario. Right?:
```
datanode.get_rank_for_owner()
```
I believe your proposal only covers the first case. Am I missing something?

**Comment by FredLL-Avaiga** [comment]
I was not aware there's another case ...
datanode selector builds a tree based on datanode.owner_id
cf. https://github.com/Avaiga/taipy/blob/55bdd46584d3141d75aa242bbcfb516e5d4201f3/taipy/gui_core/_context.py#L698

the datanode_selector can be build by:
- the core list of datanodes (if properties scenario and datanodes are not set)
- the list of datanodes provided (if property datanodes is set)
- the list of datanodes owned by the scenario in the list (if property scenario is set)

Can you enlighten me @jrobinAV ?

PS: as a base for discussion, I've implemented `get_rank` in `data_node.py` https://github.com/Avaiga/taipy/blob/1c622f9d522bc11046744d42d6e61315c65fdefe/taipy/core/data/data_node.py#L575
