### ISSUE TITLE
[OTHER] state doesn't properly works

### ISSUE THREAD

**Issue by Tal-Zamir** [Avaiga/taipy#2084]
### What would you like to share or ask?

Hi,
Seems like there is an issue using State variable.  When I am using Taipy state variable the UI, the variable get updated but the UI get stack. 
The UI looks like its loading for infint time and doesn't response anymore (seems like its 'bussy').

What am I doing wrong? am I not using correctly the State variable? I need help to fix it - else I am giving up =[
UI.py:
```python
project_number   = ''

main_page = """ ...
<|card
<center>Project Number</center>
 <center><|{project_number}|selector|width="180"|lov={project_numbers}|label=project numbers|dropdown|>
         <|Apply|button|on_action=update_master|>
 </center>
|>
|>
"""
```
utlity.py:
```python
def update_master(state):
...
project_num = state.project_number
...

notify(state, "success", "[INFO] Master file has been updated")
return
```
But the function get stack when the notify comes and than the UI is not responding anymore. 

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
Could you create a code from start to finish in a single file with your issue? And tell us what you would like it to do?

You can look into our [Tutorials](https://docs.taipy.io/en/latest/tutorials/getting_started/) to understand how Taipy works.

**Comment by AlexandreSajus** [comment]
Tal, if you need more help with this specific issue, please answer the emails we sent you.
