### ISSUE TITLE
UI/UX Improvements: Enhancing the visual design, adding or improving styles with CSS, or fixing layout issues.

### ISSUE THREAD

**Issue by rahul-chakradhari** [Avaiga/taipy#2086]
### Description

I would like to improve the user experience of the Composio website by incorporating CSS transformation effects to make the design more dynamic and engaging. I plan to implement the following:

Hover effects on buttons and links to create subtle scaling and rotation effects.
Use CSS transform properties like scale(), rotate(), and translate() to add animations to elements when users interact with them.
Add smooth transitions for interactive elements, such as navigation menus, to improve the overall look and feel.
Introduce 3D transformations on specific elements like cards or feature sections to add depth and dimension.

### Solution Proposed

I Use CSS transform properties like scale(), rotate(), and translate() to add animations to elements when users interact with them.

### Impact of Solution

It make;s the taipy website more interactive towards end users

### Acceptance Criteria

- [x] If applicable, a new demo code is provided to show the new feature in action.
- [x] Integration tests exhibiting how the functionality works are added.
- [x] Any new code is covered by a unit tested.
- [x] Check code coverage is at least 90%.
- [x] Related issue(s) in taipy-doc are created for documentation and Release Notes are updated.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
@RymMichaut

**Comment by rahul-chakradhari** [comment]
what??

**Comment by RymMichaut** [comment]
you're not on the right repo @rahul-chakradhari. This is Taipy and not Composio. ;)
