### ISSUE TITLE
[DOCS] <Change the About description>

### ISSUE THREAD

**Issue by RymMichaut** [Avaiga/taipy#2093]
### Issue Description

The current "About" description of Taipy isn't aligned with the website messaging

### Screenshots or Examples (if applicable)

![image](https://github.com/user-attachments/assets/9c48404b-3852-4169-9951-6fc015661ff4)

### Proposed Solution (optional)

 
**"Turns Data and AI algorithms into production-ready web applications in no time."**

Change it into:

**"Build Python Data & AI web applications"** 

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

### Acceptance Criteria

- [ ] The documentation set as been generated without error.
- [ ] The new text has been passed to a grammatical tool for review.
- [ ] The 100 character length limit has been respected as much as possible.
- [ ] The links and cross-references in the documentation are working.
- [ ] If applicable, screenshots of the new documentation are added to the pull request.

**Comment by sahilborse** [comment]
@RymMichaut Assign this issue to me

**Comment by RymMichaut** [comment]
@sahilborse This part cannot be done by someone else than the admins
