### ISSUE TITLE
[🐛 BUG]  Installation guide link not working

### ISSUE THREAD

**Issue by rohitdash08** [Avaiga/taipy#2105]
### What went wrong? 🤔

When clicking on the Installation guide from readme it's redirecting to 404 Not found.

![image](https://github.com/user-attachments/assets/dbd04113-9824-4909-8df3-ab0d1e035880)

### Expected Behavior

It should redirect to installation guide.

### Steps to Reproduce Issue

1. Click on the installation guide link from the readme.md

### Screenshots

![image](https://github.com/user-attachments/assets/ce38a291-302b-4059-b28b-6c4097c2ccb6)

### Acceptance Criteria

- [x] A unit test reproducing the bug is added.
- [x] Any new code is covered by a unit tested.
- [x] Check code coverage is at least 90%.
- [x] The bug reporter validated the fix.
- [x] Related issue(s) in taipy-doc are created for documentation and Release Notes are updated.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
Thank you for the feedback @rohitdash08, there are even other dead links. I am taking this issue directly as this is quite important.
