### ISSUE TITLE
Create Pull Request Template

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#2109]
Create PR templates by adding the necessary fields:

- Related issue.
- Short description of the feature/fix
- Reproducible path to exhibit the feature or the bug fix.
- Short description of the chosen solution. 
- Other branches or releases will backport the fix if applicable.
- Checklist that the contributor must check before merging the PR **into `develop`**:
    - The global feature is completed.
    - The issue checklist is completed.
    - The code is unit-tested, and the coverage is above the threshold.
    - Integration tests (end-to-end tests) are automated and executed.
    - A new entry in the change log and the release notes have been added.
    - The documentation is updated, or a dedicated issue is created.

**Comment by sahilborse** [comment]
/attempt @jrobinAV #2109 please assign me this issue

**Comment by FlorianJacta** [comment]
@sahilborse This is not open for contribution. You can look at issues with "good first issue" or "Help Wanted"
