### ISSUE TITLE
[🐛 BUG] Height property on chat control disables auto-scroll

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#2111]
### What went wrong? 🤔

Setting the `height` property on a chat control will disable the feature where the chat auto-scrolls down when new messages appear.

### Expected Behavior

The auto-scroll feature should function even when `height` is set

### Steps to Reproduce Issue

Run this code and type a bunch of messages until the chat is filled with messages:
```python
from taipy.gui import Gui
import taipy.gui.builder as tgb

messages = []


def evaluate(state, var_name: str, payload: dict):
    state.messages.append(
        [10, "The MP5 is pretty fun to shoot actually, virtually no recoil", "Robot"]
    )
    state.messages = state.messages


with tgb.Page() as page_home:
    tgb.chat(
        messages="{messages}",
        on_action=evaluate,
        height="80vh",
    )

gui = Gui(page=page_home)
gui.run()
```

The chat will not scroll down for the new messages
![image](https://github.com/user-attachments/assets/31badbba-b922-4338-8030-c8bf5b032335)

Removing the `height` property solves the issue

### Browsers

Chrome

### OS

Windows

### Version of Taipy

4.0.0

### Acceptance Criteria

- [ ] A unit test reproducing the bug is added.
- [ ] Any new code is covered by a unit tested.
- [ ] Check code coverage is at least 90%.
- [ ] The bug reporter validated the fix.
- [ ] Related issue(s) in taipy-doc are created for documentation and Release Notes are updated.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by TSP06** [comment]
@AlexandreSajus would like to take this up can you also label it hacktoberfest

**Comment by AlexandreSajus** [comment]
Putting this in High as a customer needs this in a dev release by the end of the year

**Comment by jrobinAV** [comment]
@TSP06 This issue is not open to contribution yet. The Taipy maintainers team first needs to qualify the issue.

**Comment by FredLL-Avaiga** [comment]
When the chat is filled with message, you need to scroll down once and then the chat does auto-scroll

**Comment by AlexandreSajus** [comment]
Fixed in 4.0.1
🎉

**Comment by inmani** [comment]
Is there a way to disable auto-scroll? I have placed an LLM chat window as a side window in my design.  The autoscroll is forcing the UI scroll down to the middle of the screen which is not ideal for my use case.

**Comment by FredLL-Avaiga** [comment]
> Is there a way to disable auto-scroll? I have placed an LLM chat window as a side window in my design.  The autoscroll is forcing the UI scroll down to the middle of the screen which is not ideal for my use case. 

Hi @inmani ,
Can you create another issue (feature request)?
I'm sure we can take it onboard and even purpose a CSS workaround.
Tx
