### ISSUE TITLE
Display/Notify developers of errors inside lambda functions

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#2144]
### Description

Taipy should provide the error raised in a Python expression/lambda expression bound to a visual element.

```python
from taipy.gui import Gui
import taipy.gui.builder as tgb

color_wl = 530.355


def compute_metric(color_wl):
    raise Exception("Error")


with tgb.Page() as page:
    tgb.metric(
        value=lambda color_wl: compute_metric(color_wl),
    )

Gui(page).run(title="Lambda function with error")
```

This code raises no errors.

### Acceptance Criteria

- [ ] Any new code is covered by a unit tested.
- [ ] Check code coverage is at least 90%.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
The exception is not shown for the first render but it *is* shown when you try to modify the value

**Comment by FlorianJacta** [comment]
I see. This is now my code:

```python
from taipy.gui import Gui
import taipy.gui.builder as tgb

color_wl = 530.355


def compute_metric(color_wl):
    raise Exception("Error")


with tgb.Page() as page:
    tgb.metric(
        value=lambda color_wl: compute_metric(color_wl),
    )
    tgb.button("Compute metric", on_action=lambda s: s.assign("color_wl", 550.355))

Gui(page).run(title="Lambda function with error")

```

```
C:\Users\jacta\.conda\envs\enterprise_4.0\Lib\site-packages\taipy\gui\utils\_evaluator.py:369: TaipyGuiWarning: Exception raised evaluating __lambda_2635848715776_1_TPMDL_0(color_wl):
Error
  _warn(f"Exception raised evaluating {expr_string}", e)
```

Is it possible to have the error on the first render? Some of my lambda functions are only called once, and then, I don't know the error that results. Is it possible to also create a better identifier for the lambda function: `__lambda_2635848715776_1_TPMDL_0(color_wl)` could be hard to find in a complex code

**Comment by FredLL-Avaiga** [comment]
about the identifier of the lambda function, the answer is no. we need that identifier to be unique.
About the exception, you're not showing the whole log ;-)
a bit over this, you 'll find the origin of the exception which is properly located in your file

**Comment by FlorianJacta** [comment]
This is my complete log. Here it is from the beginning:

```python
[2024-10-25 11:24:48.759][Taipy][INFO]  * Server starting on http://127.0.0.1:5000
[2024-10-25 11:24:48.760][Taipy][INFO]  * Application is accessible at http://localhost:5000
C:\Users\jacta\.conda\envs\enterprise_4.0\Lib\site-packages\taipy\gui\utils\_evaluator.py:369: TaipyGuiWarning: 
Exception raised evaluating __lambda_1916640202240_1_TPMDL_0(color_wl):
Error
  _warn(f"Exception raised evaluating {expr_string}", e)
```

**Comment by FredLL-Avaiga** [comment]
I get this
  File "...\taipy\demo-2144-lambda-exceptions.py", line 8, in compute_metric
    raise Exception("Error")
Exception: Error

**Comment by FredLL-Avaiga** [comment]
but I do agree that it would be nice to have the exception at first render ...
