### ISSUE TITLE
[🐛 BUG] Setting dimensions of the metric control

### ISSUE THREAD

**Issue by Yubarajhalder** [Avaiga/taipy#2160]
### What went wrong? 🤔

The issue lies in how you're setting the width and height properties in the metric widget.

Taipy GUI uses a specific syntax for styling, and width and height should be defined within a style attribute.

Try modifying your page string as follows:

```python
page = """
<|{value}|metric|style={"width": "300px", "height": "300px"}|>
"""
```

Or, for multiple styles:

```python
page = """
<|{value}|metric|style={"width": "300px", "height": "300px", "font-size": "24px"}|>
"""
```

This should correctly apply the width and height styles to your metric widget.

Additionally, consider using units like px for pixels or % for percentage-based sizing.

For more information on Taipy GUI styling, refer to the official documentation:

### Acceptance Criteria

- [ ] A unit test reproducing the bug is added.
- [ ] Any new code is covered by a unit tested.
- [ ] Check code coverage is at least 90%.
- [ ] The bug reporter validated the fix.
- [ ] Related issue(s) in taipy-doc are created for documentation and Release Notes are updated.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
What is this issue about?

**Comment by jrobinAV** [comment]
@Yubarajhalder, 

Can you provide a clearer explanation of the issue? 
For now I don't see anything to work on.

**Comment by FabienLelaquais** [comment]
Hi @Yubarajhalder 

There are several problems in your control definition:

- *style* is not a thing in Taipy 4.0.
  To style elements, you can use a CSS file or the *style* parameter of the Page class.
- You cannot create a Python dictionary in a Markdown or HTML visual element definition: Taipy uses the f-string facility that uses curly braces to indicate a Python expression to represent.
   You must create a dictionary, then reference it.

So, if *style* existed, you would do:
```
style = {"width": "300px", "height": "300px", "font-size": "24px"}
page = """
"<|{value}|metric|style={style}|>",
"""
```

And it still wouldn't work (in Taipy 4.0).
Now in Taipy 4.0, the way to do that would be:
```
page = Markdown(
    "<|{value}|metric|>",
    style={".taipy-metric":  {"width": "300px", "height": "300px", "font-size": "24px"}}
)
````

**Comment by FabienLelaquais** [comment]
Please let us know if this solves this issue.

**Comment by FabienLelaquais** [comment]
This is addressed with a future Taipy version.
