### ISSUE TITLE
Upload whole folders, preserving the nested structure with FileSelector

### ISSUE THREAD

**Issue by JosuaCarl** [Avaiga/taipy#2189]
### Description

When I want to process MS data, some manufacturers provide the output as folders, with which I want my application to interact. I can however not upload folders as a whole with the file_selector. This limits my ability to integrate my pipeline.

### Solution Proposed

- Add webkitdirectory support for File Selector that mimics the folder structure that is given to it

### Impact of Solution

The ability to exclude subfolders (for example via a regular expression or glob) could be important for use cases that want to upload parts of projects.

### Additional Context

The folder structure is defined here: 
https://github.com/Avaiga/taipy/blob/26e11259c7bce1e04d050460d91323805f4498c9/taipy/gui/gui.py#L1010C1-L1011C4

The FileSelector is implemented here:
https://github.com/Avaiga/taipy/blob/a131486fbe938acff9de2b0b3961158117b37458/frontend/taipy-gui/src/components/Taipy/FileSelector.tsx#L61-L73

and the HTML Element is defined here:
https://github.com/Avaiga/taipy/blob/a131486fbe938acff9de2b0b3961158117b37458/frontend/taipy-gui/src/components/Taipy/FileSelector.tsx#L189C1-L199C13 

### Acceptance Criteria

- [ ] If applicable, a new demo code is provided to show the new feature in action.
- [x] Integration tests exhibiting how the functionality works are added.
- [x] Any new code is covered by a unit tested.
- [x] Check code coverage is at least 90%.
- [ ] Related issue(s) in taipy-doc are created for documentation and Release Notes are updated.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by JosuaCarl** [comment]
I think I might need some help. I can get the folder structure with `webkitdirectory`, use `uploadFile` from `fileupload.worker.ts`  to pass it to `__upload_files` in `gui.py` and in case it is not empty, construct the directories as needed with the files landing in the right place. But the problem is, that `webkitdirectory `is not in React's `InputHTMLAttributes`, so i tried to extend the module with
```
declare module "react" {
    interface InputHTMLAttributes<T> extends HTMLAttributes<T> {
      // extends React's HTMLAttributes
      webkitdirectory?: string;
    }
};
```

This works fine, but when I declare `webkitdirectory ` with
```
const FileSelector = (props: FileSelectorProps) => {
    const {
        ...
        webkitdirectory = "",
        ...
    } = props;
```
, as ssuggested here: https://github.com/facebook/react/issues/3468#issuecomment-1031366038, the folder selector stays activated in the final HTML, regardless, whether `webkitdirectory ` is present in my markdown or not.

If I declare it like so:
```
const FileSelector = (props: FileSelectorProps) => {
    const {
        ...
        webkitdirectory,
        ...
    } = props;
```
the folder selector never appears, even when present in the markdown command chain. I initially tried to set the property to a boolean, but it seems this does not work with React, as it never appears.

A workaround I could picture would be the creation of a separate uploader, but this seems overkill to me.

**Comment by JosuaCarl** [comment]
Ok, I think I got it handled now. It seems I can make a string argument disappear by giving it nothing (like not even None).

**Comment by FredLL-Avaiga** [comment]
webkitdirectory is supposed to be a boolean
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory
so you can declare the corresponding property as boolean

**Comment by JosuaCarl** [comment]
> webkitdirectory is supposed to be a boolean https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory so you can declare the corresponding property as boolean

Yes it is supposed to be like that, but React will not accept it as such. Believe me, I've tried, and I don't know whether I missed something, but others have seemingly failed as well: https://github.com/facebook/react/issues/3468#issuecomment-1352639312
It is claimed, that it is an issue with it not being whitelisted (whatever that means, I'm not really deep into React).

**Comment by FredLL-Avaiga** [comment]
you can do it like this for now
```
const directoryProps = props.allowFolder ? {webkitdirectory: "", directory: "", mozdirectory: "", nwdirectory: ""}: undefined
<input type=file  {...directoryProps } />
```
