### ISSUE TITLE
[🐛 BUG] figure disappears

### ISSUE THREAD

**Issue by Khalilsqu** [Avaiga/taipy#2196]
### What went wrong? 🤔

The figure disappears when changing the value with the slider

### Steps to Reproduce Issue

```
from taipy.gui import Gui
import taipy.gui.builder as tgb
from math import cos, exp

value = 10

def compute_data(decay:int)->list:
    return [cos(i/6) * exp(-i*decay/600) for i in range(100)]

def slider_moved(state):
    state.data = compute_data(state.value)

with tgb.Page() as page:
    tgb.text(value="# Taipy Getting Started", mode="md")
    tgb.text(value="Value: {value}")
    tgb.slider(value="{value}", on_change=slider_moved)
    tgb.chart(data="{data}")

data = compute_data(value)

if __name__ == "__main__":
    Gui(page=page).run(title="Dynamic chart")
```

### Screenshots

![Animation](https://github.com/user-attachments/assets/bcd91d77-80e2-4d1c-b65b-a95343cc968e)

### Runtime Environment

windows 11

### Browsers

Chrome

### OS

Windows

### Acceptance Criteria

- [ ] A unit test reproducing the bug is added.
- [ ] Any new code is covered by a unit tested.
- [ ] Check code coverage is at least 90%.
- [ ] The bug reporter validated the fix.
- [ ] Related issue(s) in taipy-doc are created for documentation and Release Notes are updated.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by shindodkar** [comment]
@Khalilsqu can you assign me this issue

**Comment by nikhilmalkari8** [comment]
@Khalilsqu Can you please assign me this issue? "I can solve this issue along with two other enhancements to improve code functionality and reliability."

**Comment by Khalilsqu** [comment]
@shindodkar, @nikhilmalkari8, please ask the maintainer/owner.

**Comment by nikhilmalkari8** [comment]
@Khalilsqu can you please tell me how to find the author or maintainer

**Comment by FlorianJacta** [comment]
This is already fixed and should be released as a fix: https://github.com/Avaiga/taipy/issues/1992
