### ISSUE TITLE
Performance comparison with streamlit, and plotly

### ISSUE THREAD

**Issue by moghadas76** [Avaiga/taipy#2233]
### Description

Performance comparison with streamlit, and plotly

### Acceptance Criteria

- [ ] If applicable, a new demo code is provided to show the new feature in action.
- [ ] Integration tests exhibiting how the functionality works are added.
- [ ] Any new code is covered by a unit tested.
- [ ] Check code coverage is at least 90%.
- [ ] Related issue(s) in taipy-doc are created for documentation and Release Notes are updated.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by jrobinAV** [comment]
Hi @moghadas76 ,

Thank you for your issue proposal.

Do you propose to work on a performance benchmark between Plotly, Streamlit, and Taipy? What outcome do you expect? What would you compare exactly?
Please detail your proposal in the description or in a comment.

Thank you,

**Comment by FlorianJacta** [comment]
@moghadas76 Do you want to work on this issue? Could you detail it like @jrobinAV said?

**Comment by jrobinAV** [comment]
Without any more details, I am closing the issue.
