### ISSUE TITLE
[DOCS] documentation on how to include matlibplots in the community version

### ISSUE THREAD

**Issue by mjpan** [Avaiga/taipy#2254]
### Issue Description

On this page, it seems to indicate that matlibplots are available in all versions (including community version)
https://taipy.io/pricing

however, when I try to replace a Plotly chart (stubbed in a Markdown page, and created in Python), with a matlibplot, I get the following error. 
TaipyGuiWarning: 'figure' property value must be a plotly.graph_objects.Figure.
  _warn("'figure' property value must be a plotly.graph_objects.Figure.")

The only documentation that I can find about matlibplot is in Taipy Designer, which seems to indicate that both Plotly and matlibplot both use "fig" in the Designer, which does not seem to be part of the community version.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

### Acceptance Criteria

- [ ] The documentation set as been generated without error.
- [ ] The new text has been passed to a grammatical tool for review.
- [ ] The 100 character length limit has been respected as much as possible.
- [ ] The links and cross-references in the documentation are working.
- [ ] If applicable, screenshots of the new documentation are added to the pull request.

**Comment by FlorianJacta** [comment]
Check this [documentation ](https://docs.taipy.io/en/latest/refmans/gui/viselements/generic/part/#integrating-a-matplotlib-output) on how to integrate MatPlotlib.

```python
from matplotlib.figure import Figure
import numpy as np
from taipy import Gui 

def koch_snowflake(order, scale=10):
    def _complex(order):
        if order == 0:
            # initial triangle
            angles = np.array([0, 120, 240]) + 90
            return scale / np.sqrt(3) * np.exp(np.deg2rad(angles) * 1j)
        else:
            ZR = 0.5 - 0.5j * np.sqrt(3) / 3

            p1 = _complex(order - 1)  # start points
            p2 = np.roll(p1, shift=-1)  # end points
            dp = p2 - p1  # connection vectors

            new_points = np.empty(len(p1) * 4, dtype=np.complex128)
            new_points[::4] = p1
            new_points[1::4] = p1 + dp / 3
            new_points[2::4] = p1 + dp * ZR
            new_points[3::4] = p1 + dp / 3 * 2
            return new_points

    points = _complex(order)
    x, y = points.real, points.imag
    return x, y

figure = Figure(figsize=(5, 5))
plot = figure.subplots(1, 1)
x, y = koch_snowflake(4)
plot.fill(x, y, facecolor='none', edgecolor='purple', linewidth=2)

import taipy.gui.builder as tgb
with tgb.Page() as page:
    tgb.part(content="{figure}", height="520px")

Gui(page).run()

```

**Comment by FlorianJacta** [comment]
Can I close the issue? @mjpan

**Comment by mjpan** [comment]
I will try this out.  in the meantime yes you can close it
