### ISSUE TITLE
[OTHER] Input elements from other pages

### ISSUE THREAD

**Issue by JosuaCarl** [Avaiga/taipy#2259]
### What would you like to share or ask?

I have a larger data-processing application at hand, where I want the user to be able to set features manually. Doing this all in one file quickly gets very clunky. My question thus is:

Is there a way to integrate the code from another page into an existing one ? Maybe as a `tgb.part` ? I have tried various methods, but did not succeed until now.

Example:
`part1.py`:
```python
import taipy.gui.builder as tgb

some_text = "lorem"

with tgb.Page() as part1:
    tgb.text( "{some_text"} )
```

`part2.py`:
```python
import taipy.gui.builder as tgb

some_text = "ipsum"

with tgb.Page() as part2:
    tgb.text( "{some_text"} )
```

`main.py`:
```python

from taipy.gui import Gui
from part1 import part1
from part2 import part2

with tgb.Page() as page:
    part1 # or tgb.part( page=part1)
    part2

gui = Gui(page=page)
gui.run()
```

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by JosuaCarl** [comment]
I think I found a way with
```python
from taipy.gui import Gui
from part1 import part1
from part2 import part2

with tgb.Page() as page:
    tgb.part(page="part1")
    tgb.part(page="part2")

pages = { "page": page,
    "part1": part1,
    "part2": part2 }
gui = Gui(pages=pages)
gui.run()
```

This leads to site.x/page has the desired elements.

**Comment by JosuaCarl** [comment]
I still wonder whether there exists a more straightforward way to integrate python code into the larger framework (I tries with methods, but that complicated the linking of other methods or variables).

**Comment by FlorianJacta** [comment]
Should "some_text" be different for the two inputs?

You could so something like:


Example:
`part1.py`:
```python
import taipy.gui.builder as tgb

some_text_1 = "lorem"

def create_part_1_section():
    tgb.text( "{some_text_1"} )
```

`part2.py`:
```python
import taipy.gui.builder as tgb

some_text_2 = "lorem"

def create_part_2_section():
    tgb.text( "{some_text_2"} )
```

`main.py`:
```python

from taipy.gui import Gui
from part1 import create_part_1_section, some_text_1
from part2 import create_part_2_section, some_text_2

with tgb.Page() as page:
    with tgb.layout("1 1"): # Just an example with a layout 
        create_part_1_section()

        create_part_2_section()
    


gui = Gui(page=page)
gui.run()
```

You can put any visual elements inside a function and you can create _for_ loops or if statement in them. What you have to think about is page scope and Taipy's ability to access your variables. That's all
