### ISSUE TITLE
[🐛 BUG] Default stylekit should be consistent

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#2262]
### What went wrong? 🤔

Visual elements should have the similar position and layouts in the default stylekit. For example, if I place a selector and a button side by side, they should be aligned:

```python
from taipy.gui import Gui
import taipy.gui.builder as tgb


with tgb.Page() as page:
    with tgb.layout(columns="1 1 10"):
        with tgb.part():
            tgb.button("Click me")
        with tgb.part():
            tgb.selector("{selected}", lov="Furniture;Desk", dropdown=True)

Gui(page=page).run()
```

Here, they are misaligned:
![image](https://github.com/user-attachments/assets/64b3db15-3425-4d4b-8723-e85e1e6a5e1c)

This issue makes layouts a CSS nightmare in any application:
![image](https://github.com/user-attachments/assets/c5ddc14e-c27b-40f0-86cb-16b459ec6f41)

### Browsers

Chrome

### OS

Windows

### Version of Taipy

4.0.1

### Acceptance Criteria

- [ ] A unit test reproducing the bug is added.
- [ ] Any new code is covered by a unit tested.
- [ ] Check code coverage is at least 90%.
- [ ] The bug reporter validated the fix.
- [ ] Related issue(s) in taipy-doc are created for documentation and Release Notes are updated.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by Pushparaj13811** [comment]
Hi,

I would like to help resolve this issue. I will investigate the cause and implement a fix to ensure the layout elements align correctly across browsers. I will also add a unit test to reproduce the bug and ensure that the solution is thoroughly covered.

Looking forward to contributing!

**Comment by FlorianJacta** [comment]
Captured this issue here: https://github.com/Avaiga/taipy/issues/2305
