### ISSUE TITLE
[🐛 BUG] The checkbox / radio mode does not work in tree view

### ISSUE THREAD

**Issue by JosuaCarl** [Avaiga/taipy#2278]
### What went wrong? 🤔

The following snippet ignores the mode ("check" or "radio") and only returns a normal tree, despite being described otherwise in the documentation.

```python
tgb.tree( "{x}", mode="check", lov="{lov}" )
```

### Expected Behavior

Behave like:
```python
tgb.selector( "{x}", mode="check", lov="{lov}" )
```

### Steps to Reproduce Issue

1. Run
```python
x = ""
lov = [{'id': '1', 'label': 'P', 'children': [{'id': '2', 'label': 'C1', 'children': []}, {'id': '3', 'label': 'C2', 'children': []}]}]

with tgb.Page() as root:
    tgb.text( "Here's a Tree:")
    tgb.tree( "{x}",
        mode="check", lov="{lov}" )
    tgb.text( "Here's a Selector:")
    tgb.selector( "{x}",
        mode="check", lov="{lov}" )    

gui = Gui(page=root)

if __name__ == "__main__":
    gui.run( port=4999 )
```
2. Look for checkboxes in the tree.

### Solution Proposed

Implement "mode" in
https://github.com/Avaiga/taipy/blob/348d86d5f75b19dcfd9bb22c6721aebca5486709/frontend/taipy-gui/src/components/Taipy/TreeView.tsx#L146
, like in 
https://github.com/Avaiga/taipy/blob/348d86d5f75b19dcfd9bb22c6721aebca5486709/frontend/taipy-gui/src/components/Taipy/Selector.tsx#L128

### Browsers

Firefox

### OS

Windows

### Version of Taipy

4.0.1

### Acceptance Criteria

- [ ] A unit test reproducing the bug is added.
- [ ] Any new code is covered by a unit tested.
- [ ] Check code coverage is at least 90%.
- [ ] The bug reporter validated the fix.
- [ ] Related issue(s) in taipy-doc are created for documentation and Release Notes are updated.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
This as a documentation bug :-) 
Mode is not supported in the tree component.
You can request this feature, if you think it is interesting @JosuaCarl

**Comment by JosuaCarl** [comment]
I think it would be a good feature, but I am currently not available to work on it. Maybe I will come back to it in the new year.
