### ISSUE TITLE
[🐛 BUG] Multi-value slider with lov binds `value` to the post-adapter lov elements

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy#2290]
### What went wrong? 🤔

Example code:

```python
from taipy.gui import Gui
import taipy.gui.builder as tgb

aggregation_list = ["minute", "hour", "day", "week"]
selected_aggregation = [aggregation_list[0], aggregation_list[1]]

def aggregation_adapter(aggregation):
    return aggregation.title()

with tgb.Page() as page:
    tgb.text("# Adapter modifying bound value for multi-value slider", mode="md")
    tgb.slider("{selected_aggregation}", lov="{aggregation_list}", label="Aggregation", adapter=aggregation_adapter)
    tgb.text("{selected_aggregation}")

def on_change(state, var_name, var_value):
    print(var_name, type(var_value), var_value)

if __name__ == "__main__":
    gui = Gui(page=page)
    gui.run()
```

In develop, modifying the slider displays:

![image](https://github.com/user-attachments/assets/7b4087c5-aa7f-49c1-abcc-19398d8f37b3)

Seems to be a regression -- was working as expected in 4.0.1.

### Expected Behavior

Values should be lowercase

### Browsers

Chrome, Firefox

### OS

Windows, Linux

### Version of Taipy

develop

### Acceptance Criteria

- [ ] A unit test reproducing the bug is added.
- [ ] Any new code is covered by a unit tested.
- [ ] Check code coverage is at least 90%.
- [ ] The bug reporter validated the fix.
- [ ] Related issue(s) in taipy-doc are created for documentation and Release Notes are updated.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
Does it work for single value selection ?

**Comment by FredLL-Avaiga** [comment]
If you want an id different from your label, you need to specify it in your adapter:

```py
def aggregation_adapter(aggregation):
    return (aggregation, aggregation.title())

```

Does that work for you @arcanaxion ?

```py
import taipy.gui.builder as tgb
from taipy.gui import Gui

aggregation_list = ["minute", "hour", "day", "week"]
selected_aggregation = [aggregation_list[0], aggregation_list[1]]

def aggregation_adapter(aggregation):
    return (aggregation, aggregation.title())

with tgb.Page() as page:
    tgb.text("# Adapter modifying bound value for multi-value slider", mode="md")
    tgb.slider("{selected_aggregation}", lov="{aggregation_list}", label="Aggregation", adapter=aggregation_adapter)
    tgb.text("{selected_aggregation}")

def on_change(state, var_name, var_value):
    print(var_name, type(var_value), var_value)

if __name__ == "__main__":
    gui = Gui(page=page)
    gui.run(title="2290 [🐛 BUG] Multi-value slider with lov binds value to the post-adapter lov elements")

```

**Comment by arcanaxion** [comment]
@FredLL-Avaiga Yes, your correction works for me and it makes sense. Indeed the docs state that adapter should return a tuple.

But the inconsistency using my (wrong) method only seems to be affecting multi-value sliders:

```python
from taipy.gui import Gui
import taipy.gui.builder as tgb

aggregation_list = ["minute", "hour", "day", "week"]
selected_aggregation_multiple = [aggregation_list[0], aggregation_list[1]]
selected_aggregation = aggregation_list[0]
selected_aggregation_selector = aggregation_list[0]

def aggregation_adapter(aggregation):
    return aggregation.title()

with tgb.Page() as page:
    tgb.text("# Adapter modifying bound value for multi-value slider", mode="md")
    tgb.slider("{selected_aggregation_multiple}", lov="{aggregation_list}", adapter=aggregation_adapter)
    tgb.text("{selected_aggregation_multiple}")

    tgb.slider("{selected_aggregation}", lov="{aggregation_list}", adapter=aggregation_adapter)
    tgb.text("{selected_aggregation}")

    tgb.selector("{selected_aggregation_selector}", lov="{aggregation_list}", adapter=aggregation_adapter)
    tgb.text("{selected_aggregation_selector}")

def on_change(state, var_name, var_value):
    print(var_name, type(var_value), var_value)

if __name__ == "__main__":
    gui = Gui(page=page)
    gui.run()
```

![image](https://github.com/user-attachments/assets/e57b224b-00e7-43c4-b04b-5c84d0c48682)

Probably this should either work consistently, or perhaps raise an error if the adapter is not returning a 2-element tuple.

**Comment by FredLL-Avaiga** [comment]
@FabienLelaquais Doc ?

**Comment by arcanaxion** [comment]
@FredLL-Avaiga I think the issue I'm having is unrelated to adapters.

I'm comparing 3 versions:

1. 3.0.1 (I'm updating an old application using this version)
2. 4.0.1 (latest stable release)
3. develop (because I want the fix in #2250)

# Problem with tree

First I noticed that the "tree" element was returning ids instead of lov elements. Example copied from the [docs](https://docs.taipy.io/en/develop/refmans/gui/viselements/generic/tree/#display-a-tree-of-dictionary-entries):

```python
from taipy.gui import Gui, State, Markdown
from typing import Any

users = [
    {"id": "231", "label": "Johanna", "year": 1987, "children": [{"id": "231.1", "label": "Johanna's son", "year": 2006}]},
    {"id": "125", "label": "John",    "year": 1979, "children": []},
    {"id": "4",   "label": "Peter",   "year": 1968, "children": []},
    {"id": "31",  "label": "Mary",    "year": 1974, "children": []}
    ]

user_sel = users[2]

page = Markdown(
"""
# Trees

<|{user_sel}|tree|lov={users}|>

""")

def on_change(state: State, var_name: str, var_value: Any):
    print(var_name, type(var_value), var_value)

if __name__ == "__main__":
    gui = Gui(page=page)
    gui.run(run_browser=False)
```

When I click on John:
    - 3.0.1 and 4.0.1 would have var_value: `[{'id': '125', 'label': 'John', 'year': 1979, 'children': []}]`
    - develop would have var_value: `['125']`

Setting `not value_by_id` did not change anything, and that is already the default according to the docs.

This made me look at the example in this github issue again.

# Slider, without adapter

See the following. I'm not using tgb because the tgb.selector didn't seem to work for me in 3.0.1:

```python
from taipy.gui import Gui
import taipy.gui.builder as tgb


aggregation_list = [("minute", "Minute"), ("hour", "Hour"), ("day", "Day"), ("week", "Week")]
selected_aggregation_slider_multiple = [aggregation_list[0], aggregation_list[1]]
selected_aggregation_slider_single = None
selected_aggregation_selector_single = aggregation_list[0]

page = Markdown(
"""
# No adapter

<|{selected_aggregation_slider_multiple}|slider|lov={aggregation_list}|>

<|{repr(selected_aggregation_slider_multiple)}|>

<|{selected_aggregation_slider_single}|slider|lov={aggregation_list}|>

<|{repr(selected_aggregation_slider_single)}|>

<|{selected_aggregation_selector_single}|selector|lov={aggregation_list}|>

<|{repr(selected_aggregation_selector_single)}|>

""")

def on_change(state, var_name, var_value):
    print(var_name, type(var_value), var_value)


if __name__ == "__main__":
    gui = Gui(page=page)
    gui.run(run_browser=False, use_reloader=True)
```

## 3.0.1

This has the most expected behaviour to me:

https://github.com/user-attachments/assets/8dacc9b6-28c7-4a2f-a91b-ea5770a77efa

All 3 visual elements are giving the selected lov element (a tuple) as its value.

## 4.0.1

Here, a possibly unrelated issue, the single value slider becomes strange:

https://github.com/user-attachments/assets/ef58d099-74ce-499a-9e33-35b7bf1d2441

I'm expecting a single value slider but it's becoming a multi-value slider.

## develop

Here we start seeing what I think this github issue is related to:

https://github.com/user-attachments/assets/17e3ef0d-e98a-417e-a24e-3882c3472cea

The multi-value has renders the expected initial state. After interaction, the multi-value slider starts giving ids instead of lov elements, even though `value_by_id` is not set.

The unexpected behaviour for single value slider is also still present.

For all 3 versions, the selector has the same expected behaviour.

If this is actually just yet-to-be-documented behaviour for a future release, please let me know and I will go back to stable 😅

**Comment by FredLL-Avaiga** [comment]
I'll look into it
thanks for the detailed report @arcanaxion

**Comment by FredLL-Avaiga** [comment]
There was indeed a bug in the way we handle multiple selection in lov based components
