### ISSUE TITLE
Have part or dialog centered to the element clicked

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#2293]
### Description

Here, I have clicked on an icon and I have a dropdown menu of labels next to where I clicked:
![image](https://github.com/user-attachments/assets/025d60d6-8c2e-47ab-a534-74ac68ddc239)

Here, I have clicked on icon and I see a dialog/part showing up next to where I clicked:

![image](https://github.com/user-attachments/assets/0bba233b-f0c6-45f1-bd4a-33d6b99bf64c)

I want to do that generically to put anything in this part. If I click somewhere else, this dialog should disappear. 

### Acceptance Criteria

- [ ] If applicable, a new demo code is provided to show the new feature in action.
- [ ] Integration tests exhibiting how the functionality works are added.
- [ ] Any new code is covered by a unit tested.
- [ ] Check code coverage is at least 90%.
- [ ] Related issue(s) in taipy-doc are created for documentation and Release Notes are updated.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
it'a dialog then
But you want to position it relatively to another component.
Would it be acceptable to provide the id of the other component ? (would need to be defined in the other comp and dynamically in the dialog)

**Comment by jrobinAV** [comment]
This relates slightly to another issue: [#2252](https://github.com/Avaiga/taipy/issues/2252). By the way, a contributor has proposed to help with it.

**Comment by FlorianJacta** [comment]
@FredLL-Avaiga That works for me. What do you mean by dynamically?

**Comment by FredLL-Avaiga** [comment]
I mean that you can change the id to which the dialog is related.
Maybe we should make it a selector so that you can relate to any component (while still supporting the id for simplicity).

**Comment by FlorianJacta** [comment]
Ok, I agree that the id should be dynamic. Now, I don't understand the part about the selector 😆

**Comment by FredLL-Avaiga** [comment]
The id is a string that allows to locate a component on a page and position a dialog based on it.
this string could also be treated as a CSS selector to locate components that don't have an id.

**Comment by FlorianJacta** [comment]
Got it, thanks!

**Comment by FredLL-Avaiga** [comment]
How about this ?
https://github.com/user-attachments/assets/a23cc134-126f-4a82-9fbd-33f97d8179a1

**Comment by FredLL-Avaiga** [comment]
from 

```py
from taipy.gui import Gui, State

ref_id = None
pop_open = False
val = None

def on_action(state: State, id: str):
  if id == "dialog":
    state.ref_id = None
    state.pop_open = False
  elif id:
    state.ref_id = f"#{id}"
    state.pop_open = True
  else:
      state.val = state.val +1 if state.val is not None else 1

page = """
<|button 1 |button|id=id1|>
<|button 2|button|id=id2|>


<|button |button|id=id3|>
<|button |button|id=id4|>
<|button |button|id=id5|>


<|button |button|id=id6|>
<|button |button|id=id7|>
<|button |button|id=id8|>
<|button |button|id=id9|>


<|button |button|id=id10|>
<|button |button|id=id11|>

<|{pop_open}|dialog|popup|ref_id={ref_id}|id=dialog|
<|inside the popup|button|>

<|{val}|>
|>
"""

if __name__ == "__main__":
  Gui(page).run(title="2293 popup")

```

**Comment by FredLL-Avaiga** [comment]
any remark @FlorianJacta ?

**Comment by FlorianJacta** [comment]
Do you have any screenshot? @FredLL-Avaiga What do you need `id=dialog|`?

**Comment by FredLL-Avaiga** [comment]
> How about this ? https://github.com/user-attachments/assets/a23cc134-126f-4a82-9fbd-33f97d8179a1

better than a screen shot

**Comment by FlorianJacta** [comment]
What happens if you don't have your `  if id == "dialog":` in the `on_action`. Does this stay open?

**Comment by FredLL-Avaiga** [comment]
yes,
in this ultra simple example I use a generic on_action but you can defined different on_action callbacks

**Comment by FlorianJacta** [comment]
The default behavior for the width is to fit the content?
