### ISSUE TITLE
Add checker to check value type of configuration properties

### ISSUE THREAD

**Issue by toan-quach** [Avaiga/taipy#2298]
1. We should also add all the properties to check. not only the callable.

2. The dictionary should be moved close to the definition of the properties, in the DataNodeCOnfig class.

3. The format should be updated to `Dict[str, Dict[str, Any]]` from `Dict[str, List[Tuple[Any, List[str]]]]`

Example:
```
{
    DataNodeConfig._STORAGE_TYPE_VALUE_GENERIC: 
        {
            DataNodeConfig._OPTIONAL_READ_FUNCTION_GENERIC_PROPERTY: Callable,
            DataNodeConfig._OPTIONAL_WRITE_FUNCTION_GENERIC_PROPERTY: Callable
        },
    DataNodeConfig._STORAGE_TYPE_VALUE_SQL:
        {
            DataNodeConfig._REQUIRED_WRITE_QUERY_BUILDER_SQL_PROPERTY: Callable,
            DataNodeConfig._OPTIONAL_APPEND_QUERY_BUILDER_SQL_PROPERTY: Callable
        }
}
```

4. Add the changes to documentation
- An entry in the release notes as an improvement of the checkers for checking the property types.
- A new item in the list: https://docs.taipy.io/en/develop/userman/advanced_features/configuration/config-checker/

**Comment by toan-quach** [comment]
Hi @joaoandre-avaiga, @jrobinAV 

I want to ask you guys if we can expand this idea a bit further. I want to add 2 points that will make this ticket more complicated 😅 
1. Can we also include parameters that can be None?
2. Can we somehow declare that in case the value is None, we want to throw a warning except for an error (the message might have to be declared elsewhere)

I'm thinking about this as I found a missing implementation in the current databricks ticket: https://github.com/Avaiga/taipy-enterprise/pull/557/files#diff-6dd483af9d43a6ce79f513e4d9cd499ddceef45cddcbb1a30b589aace7255b30R81

**Comment by AlexandreSajus** [comment]
Works in 4.0.2.dev2. I triggered an error by inputting an incorrect storage_type
