### ISSUE TITLE
Feedback on scenario core viz elmt

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#230]
![image.png](https://images.zenhubusercontent.com/613716c8784bf2eff3a0fc0e/1b9e41ea-e7b7-4e36-96ba-b087509abb19)

- [ ] Title (the label) should be bigger (from @vhfgosselin)
- [x] Should be expanded by default
- [x] Sub title `custom properties` is unnecessary
- [x] Tags should be True by default
- [ ] tag edition not working?
- [x] cycle should be displayed with `scenario.cycle.get_simple_label()`
- [x] expanded does not work
- [x] expandable does not work

**Comment by FredLL-Avaiga** [comment]
Who is deciding what we should do or not ?
