### ISSUE TITLE
[🐛 BUG] Issue when rebuilding bar charts

### ISSUE THREAD

**Issue by enarroied** [Avaiga/taipy#2302]
### What went wrong? 🤔

I'm using Taipy 4.0.1
I created a bar chart, where I want a variable to determine the y axis, with always the same x. For example, I want to display the sales for a list of products, but sometimes I want the number of items sold, and sometimes I want the total amount in money units. And I can change the metric to use in y with a toggle button.

While I don't get log errors, the chart has a weird behavior, like if it resets the index or something like that. 

### Expected Behavior

The x axis shouldn't change, and the y axis should show the values of the selected column

### Steps to Reproduce Issue

```python
import pandas as pd
import taipy as tp
import taipy.gui.builder as tgb
from taipy.gui import Gui

df = pd.DataFrame(
    {
        "class": ["a", "b", "c", "d", "e"],
        "number_sales": [100, 200, 150, 180, 220],
        "amount_sales": [1503, 2560, 2009, 2302, 2708],
    }
)

sales_display = "number_sales"

with tgb.Page() as bug_chart:
    tgb.toggle("{sales_display}", lov=["number_sales", "amount_sales"])
    tgb.chart(
        data="{df}",
        type="bar",
        x="class",
        y="{sales_display}",
        rebuild=True,
    )

gui = Gui(page=bug_chart)
gui.run(rebuild=True)
```

### Runtime Environment

Windows 10, I used Python 12 within Anaconda, Taipy 4.0.1

### Browsers

Chrome

### OS

Windows

### Version of Taipy

4.0.1

### Acceptance Criteria

- [ ] A unit test reproducing the bug is added.
- [ ] Any new code is covered by a unit tested.
- [ ] Check code coverage is at least 90%.
- [ ] The bug reporter validated the fix.
- [ ] Related issue(s) in taipy-doc are created for documentation and Release Notes are updated.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
Fixed in 4.0.2
