### ISSUE TITLE
Create on_create callbacks on Scenario Selector

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#232]
### Issue

Add a callback on Scenario Selector called 'on_create' that will be called after the creation of the scenario.
This will allow the user to populate the scenario and manage it.

**Comment by FredLL-Avaiga** [comment]
or we could select it on creation => on_change would be enough ...
But I suppose you want to differentiate between creation and selection ...

**Comment by FlorianJacta** [comment]
Right now, the workaround is on_change. This is what I have used. A user told me the same yesterday but this makes it really hard.  _on_change_ will not work (or hardly work) on many use cases.

**Comment by FredLL-Avaiga** [comment]
on_creation with before or after
