### ISSUE TITLE
Adding a custom button in the login visual element

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#2326]
### Description

This feature request comes from a customer.

The customer wants a custom button in the login visual element next to the login button. This would allow him to create a "Login as guest" functionality where users could log in without entering credentials

![image](https://github.com/user-attachments/assets/50301189-99c3-4ecb-afc3-b25c6736507b)

What is the best way to do this? Should this be a feature in Taipy or should I just code a custom dialog visual element which satisfies his query?

### Acceptance Criteria

- [ ] If applicable, a new demo code is provided to show the new feature in action.
- [ ] Integration tests exhibiting how the functionality works are added.
- [ ] Any new code is covered by a unit tested.
- [ ] Check code coverage is at least 90%.
- [ ] Related issue(s) in taipy-doc are created for documentation and Release Notes are updated.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by AlexandreSajus** [comment]
A workaround using [dialog](https://docs.taipy.io/en/latest/refmans/gui/viselements/generic/dialog/):

![image](https://github.com/user-attachments/assets/d0fd8e19-2c1d-44da-8569-9d51bfd20cec)

```python
import os

from taipy.gui import Gui, notify
import taipy.gui.builder as tgb

from taipy.gui import notify
import taipy.gui.builder as tgb
from taipy.auth import hash_taipy_password, Credentials, Authenticator
import taipy.enterprise.gui as tp_enterprise


os.environ["TAIPY_AUTH_HASH"] = "taipy"

username = "login"

credentials = Credentials(user_name=username, roles=[])

passwords = {
    "Florian": hash_taipy_password("mp153ap63"),
    "Alexandre": hash_taipy_password("m4a1m995"),
}

roles = {
    "Florian": ["admin", "TAIPY_ADMIN"],
    "Alexandre": ["TAIPY_READER"],
}

authenticator = Authenticator(protocol="taipy", roles=roles, passwords=passwords)

username = ""
password = ""

login_dialog = True


def login(state):
    try:
        state.credentials = tp_enterprise.login(state, state.username, state.password)
        notify(state, "success", f"Logged in as {state.username}...")
        state.login_dialog = False
    except Exception as e:
        notify(state, "error", f"Login failed: {e}")
        print(f"Login exception: {e}")


def guest_login(state):
    notify(state, "success", "Logged in as Guest...")
    state.login_dialog = False


with tgb.Page() as page:
    with tgb.dialog("{login_dialog}", title="Welcome!"):
        tgb.input("{username}", label="Username")
        tgb.input("{password}", label="Password", password=True, on_action=login)
        tgb.html("hr")
        with tgb.layout("1 1 1"):
            with tgb.part():
                tgb.text("")
            with tgb.part():
                tgb.button("Guest Login", class_name="fullwidth", on_action=guest_login)
            with tgb.part():
                tgb.button("Login", class_name="fullwidth plain", on_action=login)

Gui(page).run()
```

**Comment by FredLL-Avaiga** [comment]
![Image](https://github.com/user-attachments/assets/dc398e7b-4295-4889-bb97-17e06b98ca2d)

**Comment by jrobinAV** [comment]
@FredLL-Avaiga 

This issue was not part of the product backlog; it should not have been implemented.

Last time we discussed it, we said we didn't want to implement it, but instead, we should communicate on the workaround.

Is a revert possible?
