### ISSUE TITLE
Scenario - Add a callback at the end of scenario execution

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#237]
### Feature improvement

The goal would be to add a callback at the end of a scenario execution. This relates to this issue: https://github.com/Avaiga/taipy/issues/211

This will also let the user define its own callback when the 'submit' is finished to notify the Gui or update the visual elements.

This could be done with a new property `after_execution=<user function>`.

WARNING: Any new API should ensure that further notifications can be taken care of in the future (progress, failure, blockers, partial success..)

### Found in version
 Taipy 2.3.1

**Comment by FredLL-Avaiga** [comment]
should we call it also after a pipeline submission ?

**Comment by jrobinAV** [comment]
I believe it s a duplicate of the ticket Avaiga/taipy-core#211.
Can we close this ticket that contains less details?

**Comment by FlorianJacta** [comment]
> should we call it also after a pipeline submission ? > pipeline execution

Maybe, we could try to create a general way to let the user know that a task/pipeline/scenario has been executed. It could also be a great feature. We can talk about it with @jrobinAV also. This will act like the scenario subscriber but linked directly with the GUI. Something that I wanted for the longest time.

**Comment by FredLL-Avaiga** [comment]
I can make a quick and (not too) dirty implementation of this (`long running call back and submit(wait=True)`) while waiting for core to provide the event.
What do you think @jrobinAV @FabienLelaquais ?

**Comment by jrobinAV** [comment]
So the quick and dirty implement would be only for 2.3.2 release, right ?
and the final implementation for 3.0.

I am fine with that.

**Comment by FredLL-Avaiga** [comment]
I didn't know there was a 2.3.2 in the pipes ...
What's in there ?

**Comment by jrobinAV** [comment]
Oh, there is not at this point. But if it is a critical priority, it can justify creating a 2.3.2.
No?
@FabienLelaquais ?

**Comment by FredLL-Avaiga** [comment]
or a 3.0.0.dev0 ?

**Comment by jrobinAV** [comment]
@FlorianJacta said it makes the core visual element not usable, which is the main content of the 2.3 version.
I believe we should create a 2.3.2 version.

**Comment by jrobinAV** [comment]
I close the ticket since this improvement will be implemented under two other tickets.
[core-#764](https://github.com/Avaiga/taipy/issues/409)
[taipy-#211](https://github.com/Avaiga/taipy/issues/211)
