### ISSUE TITLE
An interesting question, why aren't your official website and documentation pages made by Taipy?

### ISSUE THREAD

**Issue by qkxie** [Avaiga/taipy#263]

**Comment by FlorianJacta** [comment]
We started the documentation and website setup before Taipy was fully released, making it unfeasible to depend solely on Taipy. We did contemplate redeveloping both the documentation and website with Taipy, but after weighing the benefits against the costs, it didn’t align with our priorities.

Furthermore, Taipy's primary strength lies in supporting web applications that emphasize data, visualization, pipelines, and machine learning. With Taipy, you can seamlessly construct a backend featuring Data Nodes and pipelines, which can be effortlessly integrated into your application's GUI.
