### ISSUE TITLE
Double Click on line chart doesn't remove the zoom on MAC OS

### ISSUE THREAD

**Issue by ygosselin** [Avaiga/taipy#273]
I have a line chart with more than 20 columns, I'm zooming using the mouse certains parts of the chart. On the right corner of the page a tooltip appears saying to dooble click to cancel the zoom , but it doesn't work on my machine
I'm on Firefox 116.0.3 (64 bits) on MAC OS Ventura 13.5
The effect that the doble click has is to trigger a blink in the toolbar of the chart but no other action on the chart itself

**Comment by FlorianJacta** [comment]
Thank you for the issue! This feature typically works; we might try with your configuration.

**Comment by jrobinAV** [comment]
@Avaiga/community-success Can you reproduce the issue on a MacOS to confirm the ticket is still relevant?

**Comment by jrobinAV** [comment]
@dinhlongviolin1 Can you test it? Thank you in advance.

**Comment by FabienLelaquais** [comment]
@vhfgosselin 
@dinhlongviolin1 was not able to reproduce this problem on his Mac, on any browser including Firefox.

What version of Taipy did you find this problem on?

**Comment by FabienLelaquais** [comment]
Cannot reproduce.
