### ISSUE TITLE
Data Node viewer - Better indication for History 

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#274]
# Feature Improvement

There should be a better formulation than "Unknown" when a user writes a Data Node.

![image](https://github.com/Avaiga/taipy/assets/98709993/aee98968-5d46-4779-bd08-7535ac68119b)

# Environment

Taipy develop 3.0

**Comment by jrobinAV** [comment]
Ideally, we should display an optional comment provided by the end-users when they edit the data.

The functionality would be to ask the user to provide a comment when validating a modification in the data. A global (instead of local to a cell) edit mode might help simplify the UX.
