### ISSUE TITLE
Find a way to run test after taipy installation from pypi

### ISSUE THREAD

**Issue by florian-vuillemot** [Avaiga/taipy#28]
After pushing the _taipy_ package on _pypi_ we should test it to ensure the package works well and all components are correctly installed.

Moving structure to having `src`, make sure test succeed on both local and github with no import issue

Be able to run tests:
- [ ] Taipy-rest
- [ ] Taipy-airflow
- [ ] Taipy-entreprise
- [ ] Taipy

Expose the pb on a Friday meeting.

**Comment by jrobinAV** [comment]
OBSOLETE
