### ISSUE TITLE
Scenario Selector - optionally do not show form after clicking 'Add Scenario'

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#280]
# Feature Improvement

Possibility to remove the form after clicking 'Add Scenario'. The scenario creation would be done with default values or through the `on_creation` callback.

# Environment

Taipy Develop 3.0

**Comment by FredLL-Avaiga** [comment]
what happens if there's no on_creation callback ?
What are the default values ?

**Comment by FlorianJacta** [comment]
I think there are already default values when you just create a scenario with `tp.create_scenario`. And I guess, it should take the first Config found.

**Comment by jrobinAV** [comment]
The `scenario_config` has no default value. The other parameters have a default value.
I don't believe picking the first scenario configuration is a good solution. The order is not guaranteed when accessing them from `Config`.

Can we discuss the use case so I understand the purpose of this issue?

**Comment by FlorianJacta** [comment]
The use case is when the developer wants to manage himself how the scenario is created without letting the user decide. It also erases a possible unnecessary step when creating a scenario.

It is rare to have more than one Config, but we want it to be generic. Having a *config* property in the scenario selector makes sense to me.

**Comment by FredLL-Avaiga** [comment]
So what are your conclusions @jrobinAV @FlorianJacta ?

**Comment by jrobinAV** [comment]
Let me summarize:

**When the form is deactivated.** 

1. If there is an `on_creation` callback defined:
    It is called when clicking the button `add scenario`.The parameters passed to the callback are all
    the default values. 
    - If there is only one scenario configuration.
        It is passed to the callback.
    - If there are multiple scenario configurations
        No config is passed to the callback. 
3. If there is NO `on_creation` callback defined:
    The default callback is called when clicking the button `add scenario`.The parameters passed to 
    the callback are all the same default values. 
    - If there is only one scenario configuration.
        It is passed to the default callback.
    - If there are multiple scenario configurations
        An error is raised.

**Nothing change when the form is active**

**Comment by FredLL-Avaiga** [comment]
Config.scenarios always returns default ?
I suppose we don't want that one ? @jrobinAV

**Comment by jrobinAV** [comment]
Indeed. We want to filter out the default scenario configuration. 
To be honest, it is not a great design. It is a legacy code that should be removed at some point.
