### ISSUE TITLE
Taipy version in GlobalConfig

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#289]
- Populate Taipy version in GlobalConfig
- Check when running core service the Taipy version corresponds to the version installed. 
- documentation

**Comment by toan-quach** [comment]
Hi @jrobinAV ,
I'm a little lost, can you help explain again what you meant by "Check when running core service the Taipy version corresponds to the version installed."?

**Comment by toan-quach** [comment]
Hi @jrobinAV ,
I'm a little lost, can you help explain again what you meant by "Check when running core service the Taipy version corresponds to the version installed."?

**Comment by jrobinAV** [comment]
actually we should check the version of the toml file when reading the file, and not when running core.
When reading the toml file if the version in the file does not match the taipy version installed, we need to raise an error.
does it make sense?

**Comment by toan-quach** [comment]
@jrobinAV ah yep thanks! :D
