### ISSUE TITLE
Problem when importing Gui for the first time

### ISSUE THREAD

**Issue by gerileka** [Avaiga/taipy#33]
I'm trying to create a simple data viz following the tutorial : 
https://docs.taipy.io/getting_started/step_01/ReadMe/

`from taipy import Gui`

<img width="202" alt="image" src="https://user-images.githubusercontent.com/56592646/162963865-416dee6b-12ab-4e78-abd2-554a8bd2c201.png">

For info : 

<img width="105" alt="image" src="https://user-images.githubusercontent.com/56592646/162964047-7bf7a3ba-18fd-4bb2-b024-d82e8e19706c.png">

**Comment by FlorianJacta** [comment]
Hi @gerileka .

Update your *numpy* version to 1.21.0 with `pip install numpy==1.21.0`. You shouldn't have any errors anymore. In future releases, *numpy.typing* will not be necessary.

**Comment by gerileka** [comment]
@FlorianJacta  thanks, already did that
