### ISSUE TITLE
README for Hacktoberfest x Taipy!

### ISSUE THREAD

**Issue by marisogo** [Avaiga/taipy#330]
# <div align="center"> 🎉Taipy is taking part in Hacktoberfest 2023!🎉 </div>

*<div align="center">Don't miss out on the fun and register [here](https://hacktoberfest.com/) </div>* 

<img align="right" width="50%" src="https://github.com/Avaiga/taipy/assets/120181423/3c20626f-b18a-4e35-9932-28a805958406">

<div align="left">🔥 Win a limited edition t-shirt for a merged PR! </div>
<div align="left">🏆 Only 10 are up for grabs so hurry! </div>
<div align="left">🙌 Big or small, your contribution matters to us!
 </div>

<br>

Where to find Taipy's Hacktoberfest issues :
+ If you're team [front-end](https://github.com/Avaiga/taipy-gui)
+ If you're team [back-end](https://github.com/Avaiga/taipy-core)
+ Or find them all [here](https://github.com/Avaiga/taipy-gui/labels/hacktoberfest)

**Comment by ashutuptiwari** [comment]
Hey please look into this
![image](https://github.com/Avaiga/taipy/assets/106370097/a17fc7d7-0398-41de-ab81-8599dc180851)
@marisogo
