### ISSUE TITLE
UX improvements for the Scenario viewer

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy#341]
Tooltip on icons. The minimum would be:
- Submit buttons -> resp. "Submit scenario" and "Submit sequence"
      (or "Cannot submit [scenario|sequence]" - explanation would be even better but hey...)
- [✓] next to editable field -> "Apply"
- [×] next to editable field -> "Cancel"
- Trash icon next to edited custom property -> "Delete property"

Keyboard shortcuts:
- 'Enter' when editing the label, tags, custom properties or a sequence name should be equivalent to clicking the [✓] button.
- 'Esc' when editing the label, tags, custom properties or a sequence name should be equivalent to clicking the [×] button.

**Comment by FredLL-Avaiga** [comment]
👍

**Comment by FredLL-Avaiga** [comment]
tags: Enter is use to validate a tag
properties: There are 2 text fields when do we apply Enter ?
