### ISSUE TITLE
Scenario selector control - Issues with on_creation action

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy#343]
When requesting the creation of a scenario, the on_creation callback is invoked.

There are two bad problems that must be addressed:

This callback expects a 'payload' dictionary parameter.
- The payload has a 'label' parameter representing the user's 'label' setting. This is documented as 'name'.
- The payload has a 'properties' parameter that is documented as 'a dictionary' and nothing else.
   I was expecting that dictionary to hold the user-defined custom properties set at creation time.
   But the received dictionary is empty no matter what.
   What is the use of this empty dictionary? Should the user add its own properties in on_creation then return None to see these properties automatically added to the new scenario? Where are the user-defined user properties that the callback would certainly be willing to make use of?

**Comment by FredLL-Avaiga** [comment]
do you prefer label or name @FabienLelaquais ? Label it is
