### ISSUE TITLE
Taipy Install in Anaconda Navigator on MacOs

### ISSUE THREAD

**Issue by vhfgosselin** [Avaiga/taipy#35]
We use the Jupyter notebooks from within Anaconda Navigator. We did a !pip install taipy inside the notebooks., but the
from taipy import Gui led to errors.
![image](https://user-images.githubusercontent.com/20767690/163667564-c23440ac-520a-40e5-9c6a-b598ccce1ddb.png)

It seems that this problem only occurs on MacOS

**Comment by jrobinAV** [comment]
This is the same issue as https://app.zenhub.com/workspaces/taipy-613ef328affde6000ff77fb3/issues/avaiga/taipy-gui/208.

It is solved in the next version to be released soon.

**Comment by jrobinAV** [comment]
Fixed in https://github.com/Avaiga/taipy-core/releases/tag/1.0.1
