### ISSUE TITLE
BUG-Data Node Viewer does not update on scenario execution

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#350]
**Description**
The Data Node Viewer does not update itself when a scenario is executed again. This is problematic when the user runs a scenario, changes the inputs, and re-runs it. The Data Node Viewer will show data from the previous execution, and the user has to refresh the page to see the new result.

**How to reproduce**
Use the following code:
[core.zip](https://github.com/Avaiga/taipy-gui/files/13113593/core.zip)

1. On Taipy 3.0.0.dev3
2. Run app.py
3. Create a scenario using the scenario_selector
![image](https://github.com/Avaiga/taipy-gui/assets/62465003/afca366b-2d08-4738-a6b2-68fb0705c827)
![image](https://github.com/Avaiga/taipy-gui/assets/62465003/30fad646-86a5-4f4e-9392-d91383e3cbe8)
4. Select the scenario and run it
![image](https://github.com/Avaiga/taipy-gui/assets/62465003/e357585a-5c83-4266-bcee-6cc377e6b173)
5. Check the value in the Data Node Viewer for "evaluation" (should be a random float)
![image](https://github.com/Avaiga/taipy-gui/assets/62465003/5350bac9-fd6f-49e7-988c-7d68b57616e5)
6. Run the scenario again. The Data Node Viewer will still show the same value until you refresh the page

**Expected behavior**
Executing a scenario should update the Data Node Viewer elements with the data of the most recent execution

**Runtime environment**
 - OS: Windows 11
 - Browser: Chrome
 - Taipy 3.0.0.dev3

**Comment by FredLL-Avaiga** [comment]
Cannot this code be more minimalist ?

**Comment by AlexandreSajus** [comment]
This is already a minimalist recreation of the bug I had. The bug must still have a config with a scenario selector and a data node viewer.
