### ISSUE TITLE
loops in taipy markup

### ISSUE THREAD

**Issue by Forchapeatl** [Avaiga/taipy#366]
I need to use for loop in taipy markup. Please what is the correct syntax
I need something like this;
```
{% for i in range(4) %}
     My text: <|{i}|>
{% endfor %}
```

**Comment by FlorianJacta** [comment]
Hi, do you want _i_ to be interactive? To change the value in real-time?

In Taipy 3.0, you can use a Python API to create pages. Here is an example:

```python
from taipy.gui import Gui
import taipy.gui.builder as tgb

# Python API
with tgb.Page() as page:
    for i in range(4):
        tgb.text(f'My text: {i}')

# Markdown API
md = "Markdown page"

# Definition of th pages
pages = {"/": "<|navbar|>",
         'python': page,
         'markdown': md}


Gui(pages=pages).run()
```

![image](https://github.com/Avaiga/taipy/assets/98709993/a3675966-4269-40a5-83cc-a584bf9d7369)

**Comment by Forchapeatl** [comment]
@FlorianJacta , I get the idea now. Thank you so much.
