### ISSUE TITLE
Add markdown to page builder

### ISSUE THREAD

**Issue by Forchapeatl** [Avaiga/taipy#370]
I need to add markdown to taipy page builder , please how can i do this?

```
with tgb.Page() as page:
    for i in range(4):
        tgb.text(f'My text: {i}')

page.append("""<|submit|button|>""")

Gui(page).run()

```

**Comment by FlorianJacta** [comment]
All controls can be now written with this new Python API. Check the documentation [here](https://docs.taipy.io/en/latest/manuals/gui/page_builder/).

```python
with tgb.Page() as page:
    for i in range(4):
        tgb.text(f'My text: {i}')

    tgb.button("submit")

Gui(page).run()
```

**Comment by Forchapeatl** [comment]
Thank you for the information @FlorianJacta  ,  The problem is , the markdown accepts Global variables while the page builder can accept local variables. 

take these two samples for example:
**Sample 1**
```py
from taipy.gui import Gui
import taipy.gui.builder as tgb

# Python API
page = """"""


for i in range(4):
    page += '<|{i}|text|>'

# Markdown API
md = "Markdown page"

# Definition of th pages
pages = {"/": "<|navbar|>",
         'python': page,
         'markdown': md}


Gui(pages=pages).run()
```
![image](https://github.com/Avaiga/taipy/assets/24577149/989f16e9-f204-48cf-938a-23ea9a961d66)

**Sample2**
```py
from taipy.gui import Gui
import taipy.gui.builder as tgb

# Python API
with tgb.Page() as page:
    for i in range(4):
        tgb.text(f'{i}')

# Markdown API
md = "Markdown page"

# Definition of th pages
pages = {"/": "<|navbar|>",
         'python': page,
         'markdown': md}


Gui(pages=pages).run()
```
![image](https://github.com/Avaiga/taipy/assets/24577149/61ffa626-51f7-4dbb-88b8-75cbbbd44b01)

**Sample1** sees `{ i }`as a global variable while **Sample2** sees `{ i }` as a local variable. Thats why I need page builder in combination with the markdown.

**Comment by FlorianJacta** [comment]
In the Markdown example, you won't be able to change the value of each `i` independently. It is just displaying one variable.

To bind different variables with the Python API, you can put your variables in a dictionary.

```python
from taipy.gui import Gui
import taipy.gui.builder as tgb

dict_i = {}

# Python API
with tgb.Page() as page:
    for i in range(4):
        dict_i['id_'+str(i)] = i
        tgb.text('{dict_i.id_'+str(i)+'}')
        tgb.slider('{dict_i.id_'+str(i)+'}')

# Markdown API
md = "Markdown page"

# Definition of th pages
pages = {"/": "<|navbar|>",
         'python': page,
         'markdown': md}


Gui(pages=pages).run()
```
