### ISSUE TITLE
Getting started example should be fixed

### ISSUE THREAD

**Issue by s-celles** [Avaiga/taipy#372]
Hello,

On https://docs.taipy.io/en/latest/getting_started/ there is the following code

```python

from taipy import Gui


page = """
Name: <|{input_name}|input|>
<|submit|button|on_action=submit_scenario|>

Message: <|{message}|text|>
"""

input_name = "Taipy"
message = None


def submit_scenario(state):
    state.scenario.input_name.write(state.input_name)
    state.scenario.submit(wait=True)
    state.message = scenario.message.read()


if __name__ == "__main__":
    Core().run()
    scenario = tp.create_scenario(scenario_cfg)
    Gui(page).run()
```

but I see several problems.

- `Core` is not imported maybe it should be `from taipy import Gui, Core`
- `tp` doesn't exists maybe it should be `import taipy as tp`
- `scenario_cfg` doesn't exists.

Kind regards

PS : my opinion is that some getting started examples should provide the whole code.

**Comment by FlorianJacta** [comment]
Great feedback! We provide the entire user code below (with a download button), but we could try to put directly the whole code. We wanted to make it as short as possible. We are discussing it.

**Comment by jrobinAV** [comment]
Closed as the documentation as been updated, specifying the code is just a fragment.
