### ISSUE TITLE
data_node_selector does not select the right data node when multiple scenarios exist

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#373]
![image](https://github.com/Avaiga/taipy/assets/62465003/8f6f504d-691b-4789-81eb-75e63c421023)

- Here, I have created two scenarios: `prediction_scenario` and `2016`
- I have selected the scenario `prediction_scenario` using the scenario_selector (1)
- I want to select the `prediction` data node of the scenario `2016`, so I select it using the data node selector (2)
- The data node viewer shows me the `prediction` data node of `prediction_scenario` instead of `2016` (3)

**Expected Outcome:**
Selecting a data node using the data node viewer should override the scenario selector and select the correct data node of the correct scenario.

**Comment by jrobinAV** [comment]
Can you provide the code you are using?

**Comment by AlexandreSajus** [comment]
Ah yes my bad, the code is this repo: https://github.com/Avaiga/demo-yearly-prediction

**Comment by jrobinAV** [comment]
thx.

**Comment by jrobinAV** [comment]
The code comes from a template generation. It can be a bug in taipy-template then.

**Comment by FredLL-Avaiga** [comment]
Can you extract a reproduction example ?

**Comment by AlexandreSajus** [comment]
I tried on a smaller reproduction example and the issue was fixed. The issue seems to come from the build_dn_partial that existed in our template but the template has been updated to remove this function. Closing this as this is not an issue anymore/
