### ISSUE TITLE
Data Node viewer- Limit the table view to 25 rows 

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#375]
## Improvement

Limit the table view to only 25 rows for the Data Node view. The user can then change its size, but having more rows by default is not optimal in my opinion.

**Comment by FredLL-Avaiga** [comment]
We could set the page size to 25 ...

**Comment by jrobinAV** [comment]
We can reduce the default nb of rows It would also be good to align with the table control.

**Comment by FredLL-Avaiga** [comment]
The default page size for table is 50 I believe (that's what was used by default here)

**Comment by ioannastantzou** [comment]
Hello ,I would like to work on this issue! Could you please assign me on it? 
thank you in advance!

**Comment by FlorianJacta** [comment]
@FredLL-Avaiga @FabienLelaquais Could we assign this issue to @ioannastantzou and show how to do it? Is it in *taipy/frontend/taipy/src /DataNodeViewer.tsx*?

**Comment by FredLL-Avaiga** [comment]
I guess that would be the pageSize property of the Taipy Gui Table component
https://vscode.dev/github/Avaiga/taipy/blob/feature/%231044-chat/frontend/taipy/src/DataNodeTable.tsx#L200

**Comment by ioannastantzou** [comment]
hello and thank you! could i be assigned to start working on it?

**Comment by ioannastantzou** [comment]
So just a quick question , we want to make it by default only 25 rows or make it adjustable for the user to choose? thank you!

**Comment by FredLL-Avaiga** [comment]
> So just a quick question , we want to make it by default only 25 rows or make it adjustable for the user to choose? thank you!

I think that's a good idea: you can add a (not dynamic) number property to the datanode viewer control that allows to specify the page size (with a default of 25)

**Comment by jrobinAV** [comment]
@ioannastantzou Hello, Any news on this ticket?

**Comment by FredLL-Avaiga** [comment]
I'm sorry but it was so simple that I did it 
https://vscode.dev/github/Avaiga/taipy/blob/develop/frontend/taipy/src/DataNodeTable.tsx#L221

**Comment by jrobinAV** [comment]
OK, Great. Thank you. I let you close the ticket if needed.

**Comment by jrobinAV** [comment]
@FredLL-Avaiga Can we close the issue?
