### ISSUE TITLE
BUG-The cycle tutorial does not explain to the reader why he should use cycles, and lacks visuals

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#378]
https://docs.taipy.io/en/develop/knowledge_base/tutorials/cycles_scopes/

The cycles tutorial introduces the purpose of cycles with this. dense block of text:
![image](https://github.com/Avaiga/taipy-doc/assets/62465003/eefe98f1-765b-47eb-bdd7-a2ff6f7e8930)

This introduction is too abstract, too broad, and lacks visuals.

Maybe we should introduce the topic by just saying that cycles allow you to:
- share variables between scenarios in the same time frame, this way if I have three prediction scenarios for the month of June, I do not need to create three sales datasets for June but only use the one
- better organize variables in the application (here last_two_years is a shared dataset between both scenarios so it does not appear twice)
![image](https://github.com/Avaiga/taipy-doc/assets/62465003/ce648ed4-4868-4cfa-a282-f8600fe6a27b)

In general, any feature should have a visual associated to it. For example:
![image](https://github.com/Avaiga/taipy-doc/assets/62465003/05e6b73a-203a-4c6d-b29f-020a7e6b1a9c)
Why would I implement this unless it pushes the primary scenario to the top of the scenario_selector list, or unless it adds a star icon to my scenario.

I can work on this, just tell me if there are features of cycles that I am missing

**Comment by jrobinAV** [comment]
I fully agree with your remarks. 

Please be my guest proposing improvements. I believe you covered all the features covered by cycles.

I just edited the title and the label of the issue. This is not a bug but an enhancement.
