### ISSUE TITLE
BUG-Inputting the wrong column name in a chart reports empty data

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#379]
**Description**
Inputting the wrong column name in a chart visual element will report that the dataset used is empty when it is not. This leads the user to think that the issue is with the dataset instead of the column name.

**How to reproduce**
Running this code where I made a mistake on the y column of the chart visual element:

```python
from taipy import Gui
import pandas as pd

data = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})

page = """
<|{data}|chart|type=bar|x=a|y=hello|>
"""

Gui(page).run()
```

Leads to this error:
```
--- 1 warning(s) were found for page '/' in variable 'page' ---
 - Warning 1: Error column "hello" is not present in the Dataframe "Empty DataFrame
Columns: [a, b]
Index: []".
```

**Expected behavior**
The error should not mention that the DataFrame is empty, only that the column is not found

**Runtime environment**
 - OS: Windows 11
 - Browser: Chrome

**Comment by srinivaspavan9** [comment]
Hi  @AlexandreSajus  I have started working on this issue, I am trying to debug the code to find out where the warnings are being generated but it seems that I am not able to step into the Gui(page).run() line after hitting that breakpoint. what am i doing wrong ? and also i changed the first line to "from taipy.gui import Gui" as it was giving me import error. 
I need help

**Comment by AlexandreSajus** [comment]
@srinivaspavan9 Yes you are right about the import error, this code is probably outdated. I'm not sure what you mean about the breakpoint issue. Maybe @jrobinAV could help?

**Comment by srinivaspavan9** [comment]
> @srinivaspavan9 Yes you are right about the import error, this code is probably outdated. I'm not sure what you mean about the breakpoint issue. Maybe @jrobinAV could help?

I was trying to debug the code to find out where the warnings are being generated. But I am unable to debug because I am not able to get into the Gui(Page).run(), I mean right after hitting the break point the line is being skipped while debugging.

Can I know where the warnings are generated?

**Comment by AlexandreSajus** [comment]
> > @srinivaspavan9 Yes you are right about the import error, this code is probably outdated. I'm not sure what you mean about the breakpoint issue. Maybe @jrobinAV could help?
> 
> I was trying to debug the code to find out where the warnings are being generated. But I am unable to debug because I am not able to get into the Gui(Page).run(), I mean right after hitting the break point the line is being skipped while debugging.
> 
> Can I know where the warnings are generated?

Ah I see, I don't think you are going to be able to use breakpoints this simply. We do have a debug mode that should give you more information with `Gui(page).run(debug=True)`. Let me ask R&D how they debug their code and get back to you.

**Comment by srinivaspavan9** [comment]
> > > @srinivaspavan9 Yes you are right about the import error, this code is probably outdated. I'm not sure what you mean about the breakpoint issue. Maybe @jrobinAV could help?
> > 
> > 
> > I was trying to debug the code to find out where the warnings are being generated. But I am unable to debug because I am not able to get into the Gui(Page).run(), I mean right after hitting the break point the line is being skipped while debugging.
> > Can I know where the warnings are generated?
> 
> Ah I see, I don't think you are going to be able to use breakpoints this simply. We do have a debug mode that should give you more information with `Gui(page).run(debug=True)`. Let me ask R&D how they debug their code and get back to you.

Found this in utils.py
<img width="831" alt="image" src="https://github.com/Avaiga/taipy/assets/34889400/820af74c-296d-4ad0-9307-38d6bc07e30d">

I think this warning message can be modified. 
Can you confirm ?

**Comment by AlexandreSajus** [comment]
Yes this should be it

**Comment by srinivaspavan9** [comment]
I just submitted a PR for this issue #379
PR #617 

Your feedback and review would be greatly appreciated.

**Comment by AlexandreSajus** [comment]
Perfect! We'll take a look
