### ISSUE TITLE
"Property" should be replaced by metadata in Core GUI elements

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#380]
Rym, Vincent, and I were unclear on what properties were used for in Core GUI elements:
![image](https://github.com/Avaiga/taipy-gui/assets/62465003/00e64642-af94-4cc8-80b9-efc5f205dd19)
![image](https://github.com/Avaiga/taipy-gui/assets/62465003/983adbde-ed59-493f-9b4f-525cfd375fa0)
As far as I understand, these properties do not have functionality inside of Taipy apart from adding context and metadata. They should be renamed to metadata so the user understands they are optional contexts that can be added. I thought I could change the properties of a data node (like "skippable") using this, so there is confusion.

**Comment by jrobinAV** [comment]
Obsolete? @AlexandreSajus

**Comment by AlexandreSajus** [comment]
It is clarified in the manual, and the visual element has a property to hide this part so closed
