### ISSUE TITLE
BUG-Using "open" as the value for a dialog visual element as the documentation suggests fails

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#382]
**Description**
Using `open` as the main value for a dialog visual element will make the dialog permanently opened. This might be because open is a Python function available by default.

**How to reproduce**
```python
from taipy.gui import Gui, State, notify

open = True

modal_dialog = """
<|{open}|dialog|title=Are you a scientist?|width=30%|
**Warning**
You must be a scientist to be able to view this page
<br/>
<|I am a scientist|button|class_name=fullwidth plain|on_action=close_modal_window_and_render_page|>
|>

<|part|render={not open}|
All the sciency stuff now shows up here
|>
"""


def close_modal_window_and_render_page(state: State):
    state.open = False
    notify(state, "S", "Welcome, Scientist!")


gui = Gui(page=modal_dialog)

gui.run()
```

This code generates a dialog box that can't be closed (no errors in logs)
![image](https://github.com/Avaiga/taipy-gui/assets/62465003/d70903f4-76be-4c3e-91ad-05ea3f821bad)

Replacing `open` with `opening` fixes the issue.

**Expected behavior**
Either change the name of `open` in the documentation as an easy fix or find a way around this issue in the code

**Runtime environment**
 - OS: Windows 11
 - Browser: Chrome
 - Taipy: 3.0.0

**Comment by FredLL-Avaiga** [comment]
the issue here is that the user code uses a python reserved word
replacing the variable "open" vy "open_dialog" fixes the issue

```
from taipy.gui import Gui, State, notify

open_dialog = True

modal_dialog = """
<|{open_dialog}|dialog|title=Are you a scientist?|width=30%|
**Warning**
You must be a scientist to be able to view this page
<br/>
<|I am a scientist|button|class_name=fullwidth plain|on_action=close_modal_window_and_render_page|>
|>

<|part|render={not open_dialog}|
All the sciency stuff now shows up here
|>
"""


def close_modal_window_and_render_page(state: State):
    state.open_dialog = False
    notify(state, "S", "Welcome, Scientist!")


gui = Gui(page=modal_dialog)

gui.run()

```
