### ISSUE TITLE
BUG-Moving a data node then connecting it resets its position

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#384]
**Description**
Moving a data node then connecting it resets its position. This could be linked to other position reset bugs

![2023-05-25 02-04-35_1](https://github.com/Avaiga/taipy-core/assets/62465003/18c23480-0580-4f9c-b03f-5265d9016162)

**Runtime environment**
Please specify relevant indications.
 - Taipy version: 2.2.0
 - OS: Windows

**Comment by jrobinAV** [comment]
Fixed!
