### ISSUE TITLE
Create a Chatbot and add the demo to the documentation

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#387]
**Description**
The goal is to create a ChatBot application that will be featured as a demo in the documentation.

First, create the ChatBot using Taipy. Then, add it to the documentation in the Knowledge Base section in Demos by creating a text like other demos and creating the navigation to it.

You should make the changes of the documentation in this [taipy-doc](https://github.com/Avaiga/taipy-doc) repo.

**Comment by FredLL-Avaiga** [comment]
Would it be a good idea to create a control for displaying a chat @FabienLelaquais ?

**Comment by FlorianJacta** [comment]
@FredLL-Avaiga, I close this issue as it has been done. Here is the other issue to create a chat control: https://github.com/Avaiga/taipy/issues/1044
