### ISSUE TITLE
Time filtering for scenario getters

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#393]
**What would that feature address**
- Propose a way to filter scenarios by time period (start time - end time).

**Comment by FredLL-Avaiga** [comment]
Does the current filter address this ?

**Comment by FlorianJacta** [comment]
Is an API available now for Taipy users? (not just for SDM viz users)

**Comment by jrobinAV** [comment]
No, that's the purpose of the issue.

**Comment by trgiangdo** [comment]
@jrobinAV As I understanding, this method will filter by the `Scenario.creation_date`, not the Cycle time attribute right?

Because if filtering based-on Cycle, it would be duplicated with the ticket https://github.com/Avaiga/taipy/issues/413.

**Comment by jrobinAV** [comment]
Absolutely, it is based on the creation_date.
