### ISSUE TITLE
Create a Submission entity

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#409]
The purpose of this entity is to group and hold information about one submission:
- submit_id 
- list of jobs
- creation_date_time
- submission status (compilation of the job statuses)
- etc.

It will be exposed through a dedicated Manager (maybe we don't need a dedicated repository since all the information can be retrieved from the Job Repository).
Creating, editing, and deleting a submission should also trigger a core event.

The API to expose Submission should be discussed among the team.

Please refer to ticket [taipy-#211](https://github.com/Avaiga/taipy/issues/211) for more details on the purpose, the submission statuses.

**Comment by FredLL-Avaiga** [comment]
It would be nice if the submission Entity could hold some user data that would be passed through the submit call
This way taipy scenario management controls will be able to receive the right information (thinking client id & co. here) in the submission through an event

**Comment by jrobinAV** [comment]
Yep, good idea. It does make a lot of sense to me!
Can you create a separate ticket for that?

**Comment by FredLL-Avaiga** [comment]
why would it need a new ticket ?
