### ISSUE TITLE
Improve checker for configuration ids

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#411]
**What would that feature address**
Improve the checker of configuration names to deal with restricted names. For example, when the user calls a data node "name" or "default"

The restricted IDs correspond to all the attributes and properties of the following classes: Scenario, Sequence, Task, and DataNode (and children classes).

**Comment by trgiangdo** [comment]
I'm not sure to understand the requirement here @jrobinAV @FlorianJacta 
Does it mean the following configuration:
```python
dn_1_config = Config.configure_data_node(
    id="dn_1_id",
    storage_type="pickle",
    scope=Scope.SCENARIO,
    name="name"
    )
```
will raise an error in the ConfigChecker? Similar to `name="default"`.

Or `id="name"` will raise an error?

**Comment by jrobinAV** [comment]
![image](https://github.com/Avaiga/taipy/assets/88036007/d395560a-66f1-47ba-a89e-69300f24956a)

**Comment by jrobinAV** [comment]
Yes indeed. Scenario has an attribute called `name`. Thus `name` is restricted as a data_node_config_id because at run time, `scenario.name` would not be possible to retrieve the data node.

So `Config.configure_data_node(id="name", ...)` should raise a configchecker error.
