### ISSUE TITLE
Check dependencies are up-to-date

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#414]
Check dependencies are up-to-date

**Comment by toan-quach** [comment]
## Taipy-core dependencies version check

### For `setup.py`

**Required packages** (format: `taipy's requirement`   -  ` current latest version`)

*Not up-to-date*

```
"pyarrow>=10.0.1,<11.0"   -   pyarrow 14.0.1
"networkx>=2.6,<3.0”   -   networkx 3.2
```

*Within current version range*

```
"modin[dask]>=0.23.0,<1.0"   -   modin 0.24.1
"pymongo>=4.2.0,<5.0"   -   pymongo 4.5.0
"sqlalchemy>=2.0.16,<2.1"   -   SQLAlchemy 2.0.22
"toml>=0.10,<0.11"   -   toml 0.10.2
```

**Extra packages**

*Not up-to-date*

```
"fastparquet==2022.11.0"   -   fastparquet 2023.8.0
"pyodbc>=4,<4.1"   -   pyodbc 5.0.1
"pymysql>1,<1.1"   -   pymysql 1.1.0
```

*Within current version range*

```
"psycopg2>2.9,<2.10”   -   psycopg2 2.9.9
```

### For `Pipfile`

```
modin = {extras = ["dask"], version = "==0.23.0"}   -   modin 0.24.1
networkx = "==2.6"   -   networkx 3.2
pyarrow = "==10.0.1"   -   pyarrow 13.0.0
pymongo = "==4.2.0"   -   pymongo 4.5.0
sqlalchemy = "==2.0.16"   -   SQLAlchemy 2.0.22
toml = "==0.10"   -   toml 0.10.2
```

**Comment by jrobinAV** [comment]
LOST COMMENT FROM @toan-quach :

## Taipy-core dependencies version check

### For `setup.py`

**Required packages** (format: `taipy's requirement`   -  ` current latest version`)

*Not up-to-date*

```
"pyarrow>=10.0.1,<11.0"   -   pyarrow 13.0.0
"networkx>=2.6,<3.0”   -   networkx 3.2
```

*Within current version range*

```
"modin[dask]>=0.23.0,<1.0"   -   modin 0.24.1
"pymongo>=4.2.0,<5.0"   -   pymongo 4.5.0
"sqlalchemy>=2.0.16,<2.1"   -   SQLAlchemy 2.0.22
"toml>=0.10,<0.11"   -   toml 0.10.2
```

**Extra packages**

*Not up-to-date*

```
"fastparquet==2022.11.0"   -   fastparquet 2023.8.0
"pyodbc>=4,<4.1"   -   pyodbc 5.0.1
"pymysql>1,<1.1"   -   pymysql 1.1.0
```

*Within current version range*

```
"psycopg2>2.9,<2.10”   -   psycopg2 2.9.9
```

### For `Pipfile`

```
modin = {extras = ["dask"], version = "==0.23.0"}   -   modin 0.24.1
networkx = "==2.6"   -   networkx 3.2
pyarrow = "==10.0.1"   -   pyarrow 13.0.0
pymongo = "==4.2.0"   -   pymongo 4.5.0
sqlalchemy = "==2.0.16"   -   SQLAlchemy 2.0.22
toml = "==0.10"   -   toml 0.10.2
```

**Comment by jrobinAV** [comment]
@trgiangdo @joaoandre

**Comment by jrobinAV** [comment]
We need to review the version updates and apply them if they are OK.

**Comment by joaoandre-avaiga** [comment]
## Taipy-rest dependencies version check

PR with changes: https://github.com/Avaiga/taipy-rest/pull/140/files

### For `setup.py`

**Required packages** (format: `taipy's requirement`   -  ` current latest version`)

*Not up-to-date*

```
"apispec[yaml]>=5.1,<6.0"  -   apispec 6.3
```

*Unused*
"flask-migrate>=3.1,<4.0" - REMOVED
"flask-marshmallow>=0.14,<0.15" - Replaced by marshmallow(we only used functionallity from marshmallow)
 "marshmallow-sqlalchemy>=0.25,<0.29" - REMOVED

*Within current version range*

```
"flask-restful>=0.3.9,<0.4"   -   flask-restful 0.3.10
```


### For `Pipfile`

```
apispec = {extras = ["yaml"], version = "==5.0"}   -   apispec 6.3
```

*Unused*
passlib - Removed
pytest_factoryboy - Removed

**Comment by jrobinAV** [comment]
PyArrow got a critical vulnerability
it must be upgraded to 14.0.1
https://github.com/Avaiga/taipy-core/security/dependabot/4

**Comment by florian-vuillemot** [comment]
Two bugs were found:
- Tests are not executed when a PR is created. https://github.com/Avaiga/taipy/pull/786
- Requirements.txt should only be updated using python3.12 to ensure that the latest version of packages is installable (python3.8 will downgrade package requirements).
