### ISSUE TITLE
Access Gui-Core viz elements from the root of taipy gui builder

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#418]
All Gui-Core visual elements should be accessible through the Taipy Gui Builder API.

This should work:
```python
from taipy.gui import Gui 
import taipy.gui.builder as tgb


with tgb.Page() as page:
    tgb.scenario(None)


Gui(page=page).run()
```

**Comment by FlorianJacta** [comment]
Is it really solved? This is still not working on my side

![image](https://github.com/Avaiga/taipy/assets/98709993/3725adb8-9455-48c6-b59b-4d2bc6dc9b21)

**Comment by FlorianJacta** [comment]
Any update on this?

**Comment by dinhlongviolin1** [comment]
Did you try `tgb.gui_core.scenario`

**Comment by FlorianJacta** [comment]
```
C:\Users\jacta\.conda\envs\enterprise_3_1\lib\site-packages\taipy\gui\gui.py:774: TaipyGuiWarning: on_change(): callback function raised an exception:
module 'taipy.gui.builder' has no attribute 'gui_core'
```

Not working here

**Comment by dinhlongviolin1** [comment]
right now, on 3.1, you can use this syntax to access the gui_core
```
import taipy.gui.builder as tgb
from taipy.gui import Gui

with tgb.Page() as page:
    tgb.taipy_gui_core.scenario(None)


Gui(page=page).run()
```

**Comment by dinhlongviolin1** [comment]
I will allow the access of all element from the root of tgb

**Comment by FlorianJacta** [comment]
We believe that this behavior should be included in the 3.1.1 version as it seems quite important for the use of Taipy with Python @dinhlongviolin1 @FabienLelaquais What do you think?

**Comment by FlorianJacta** [comment]
>We believe that this behavior should be included in the 3.1.1 version as it seems quite important for the use of Taipy with Python

Any thoughts @dinhlongviolin1 @FabienLelaquais @jrobinAV ?

**Comment by jrobinAV** [comment]
I agree it should be in the 3.1.1 if possible.

**Comment by FabienLelaquais** [comment]
I also agree.

**Comment by dinhlongviolin1** [comment]
Sure why not, let me do it
