### ISSUE TITLE
There is always a scrollbar regardless of the size of the page

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#420]
Regardless of the contents of the page or the navigator used, Taipy apps always have a scrollbar:

```python
from taipy.gui import Gui
import pandas as pd

data = pd.DataFrame({"Time": [1, 2, 3], "Max AQI": [4, 5, 6]})

page = """
<|{data}|chart|height=10%|>
"""

Gui(page).run()
```
![image](https://github.com/Avaiga/taipy/assets/62465003/898b317c-8a68-4ce5-9aab-557a22a6cdce)

**When there is not enough content to fill the page, the scrollbar should disappear**

**Comment by FredLL-Avaiga** [comment]
body: height:100% in base.css:15
