### ISSUE TITLE
Have the possibility for filtering in Taipy table to be case insensitive

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#426]
**Description**
This will add the possibility to choose whether the filter is case-sensitive or not in Taipy tables (when the filter is on).

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by jrobinAV** [comment]
All taipy filtering mechanisms should apply this new feature and have a similar UX.

**Comment by Surani02** [comment]
Can you assign this to me? I am a Hacktoberfest participant.

**Comment by FlorianJacta** [comment]
I am assigning it to you @Surani02, thank your for your contribution!

**Comment by NILAY1556** [comment]
@quest-bot embark

**Comment by NILAY1556** [comment]
@Surani02 is not working on this issue ...please can i have a Assignee on this issue @FlorianJacta

**Comment by FlorianJacta** [comment]
You can also work on it @NILAY1556

**Comment by Surani02** [comment]
@FlorianJacta I tried to solve this issue as I could, but I couldn't solve it. Apologize for the inconvenience.

**Comment by Rishi-0007** [comment]
Hi @FlorianJacta @FredLL-Avaiga @jrobinAV , 
I would like to work on this issue, please assign this to me.
I plan to introduce a configuration option allowing users to toggle between case-sensitive and case-insensitive filtering. However, I would appreciate some guidance on the following points:

1. Could you please point me to the files responsible for handling the table filtering logic, both on the frontend and backend, so I can modify the comparison logic accordingly?
2. Are there any specific configuration files or settings within the Taipy framework where this new option should be added to ensure smooth integration?

Given the similarities to the [Alert component configuration](https://github.com/Avaiga/taipy/pull/1975) , I believe this change will be straightforward once I locate the appropriate files. Your advice on this would be invaluable.

Thank you for your time and support!

**Comment by Rishi-0007** [comment]
@quest-bot embark

**Comment by FlorianJacta** [comment]
Yes, go ahead, @Rishi-0007. Thank you for your contribution. I will let @FabienLelaquais or @FredLL-Avaiga answer you!

**Comment by NILAY1556** [comment]
hey @FlorianJacta , i am working on it and also i commented before @Rishi-0007

**Comment by NILAY1556** [comment]
or @Rishi-0007 , if you want to work on it together , please contact me i am a beginner and you also before work on this project so , here is my linkedin please message me bro : "https://www.linkedin.com/in/nilay-dhandhukiya-b81bab277/" , or mail me : "nilaydhandhukiya06@gmail.com"

**Comment by Rishi-0007** [comment]
> or @Rishi-0007 , if you want to work on it together , please contact me i am a beginner and you also before work on this project so , here is my linkedin please message me bro : "https://www.linkedin.com/in/nilay-dhandhukiya-b81bab277/" , or mail me : "[nilaydhandhukiya06@gmail.com](mailto:nilaydhandhukiya06@gmail.com)"

I will suggest you to pick `good first issue` to get yourself familiar with Taipy repository.

**Comment by NILAY1556** [comment]
okay , i'll sure 
and also if you want to , can you give me your any social links 'cause i didn't find any in your github account so i can connect with you that would be great

**Comment by Rishi-0007** [comment]
Sure, here is my [linkedin](https://www.linkedin.com/in/rishi-nayak-51b1a821a/). But asking queries to maintainers will help you more.

**Comment by NILAY1556** [comment]
okay , thanks

**Comment by Rishi-0007** [comment]
> Yes, go ahead, @Rishi-0007. Thank you for your contribution. I will let @FabienLelaquais or @FredLL-Avaiga answer you!

Hey @FabienLelaquais @FredLL-Avaiga , 
I am waiting for your guidance to start working on this issue.

**Comment by FredLL-Avaiga** [comment]
You make the first proposal and we'll tell you how you're doing

**Comment by FredLL-Avaiga** [comment]
You can start
Filter is done on the frontend in tableFilter.tsx and mainly in pandas_data_accessor.py in the backend

**Comment by Rishi-0007** [comment]
Hey @FredLL-Avaiga @FlorianJacta, Please check and review the PR.

**Comment by FredLL-Avaiga** [comment]
I think we need to discuss some spec on this.
Here is my proposal:
- in the Table Filter UI, add a switch indicating case sensitive or not when the filter type is string
- add the information to the FilterDesc interface (proposed name `matchCase`)
- in the data_accessor, act accordingly depending on the FilterDesc property value

Let me know what you think @FlorianJacta @jrobinAV @FabienLelaquais @Rishi-0007

**Comment by FabienLelaquais** [comment]
@FredLL-Avaiga I think that's great.
VSCode uses 
![image](https://github.com/user-attachments/assets/3081b192-2963-44f8-9066-cd9035ce3025)
which is a switch...
Do you know precisely where an equivalent icon would be located?

**Comment by FredLL-Avaiga** [comment]
didn't find it in https://mui.com/material-ui/material-icons
but I found a repo with some SVG 
https://github.com/mchaput/icons/blob/master/icon-case-sensitive.svg

**Comment by FabienLelaquais** [comment]
https://icon-sets.iconify.design/mdi/case-sensitive-alt/?
