### ISSUE TITLE
Table comparison control

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#429]
- Implement a table comparison control from requirements:
https://docs.google.com/document/d/19R0SiykrlGALWU9ONDdtmni4PNBmJ-95s9i755FhWgg/edit?pli=1#heading=h.f4whbbxdf5x3
- Unit tests
- User manual
- Reference manual
- release notes

**Comment by FredLL-Avaiga** [comment]
`<|{data}|table|data[1]={data1}|on_compare=on_compare|>`
if on_compare is not specified, a default comparison function is used.
multiple data can be provided as long as the index is continuous (ie date[1]=...,data[2]=...)

Representation needs to be defined
