### ISSUE TITLE
Incorporate Folium/Leaflet to Taipy

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#432]
**What would that feature address**
The possibility to use [Folium](https://github.com/python-visualization/folium)/[Leaflet](https://leafletjs.com/) inside Taipy and create maps through it.

***Description of the ideal solution***
The ideal solution is to use the [Taipy extension API](https://docs.taipy.io/en/develop/manuals/reference_guiext/) to create a new visual element for Folium/Leaflet. A workaround would be to create an [Iframe](https://github.com/Avaiga/taipy-gui/issues/669#issuecomment-1476339616) around it.

***Caveats***
This should not impact Taipy and be an addition to Taipy.

***Other options***
Any solution can be provided to have this feature inside Taipy. The goal is to expand the features of Taipy.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
Does the [part.content](https://docs.taipy.io/en/latest/manuals/gui/viselements/part/#p-content) help ?
And [register_content_provider](https://docs.taipy.io/en/latest/manuals/reference/taipy.gui.Gui/#taipy.gui.Gui.register_content_provider)

**Comment by FlorianJacta** [comment]
It is enough. This [page ](https://docs.taipy.io/en/latest/tutorials/integration/1_3rd_party_components/) explains how to do it.
