### ISSUE TITLE
Improve way to incorporate third party objects (Iframes)

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#437]
**Description**
The goal would be to simplify how to incorporate third party objects like `fig` from Plotly. The relationship between `get_user_content_url`, `on_user_content` and the url can be complex for new comers or for complex applications using this to create multiple visualizations.

```python
from taipy.gui import Gui, get_user_content_url, notify


def expose_plotly(fig):
    buffer = io.StringIO()
    fig.write_html(buffer)
    return buffer.getvalue()


html = expose_plotly(sankey_graph(data))
uc_url = None


def on_user_content(state, path: str, query: dict):
    return state.html

def on_init(state):
    state.uc_url = get_user_content_url(state, "val", {"name": "param"})

```

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by arcanaxion** [comment]
Indeed, beyond Avaiga/taipy-gui#980, I would also like the option of creating my own plotly figure object and having an easy way to pass it to taipy to display. I would still circumstantially want to use the taipy chart syntax (e.g. to use selected_traces), but I'm generally able to create more complicated charts quicker by using plotly.py itself

**Comment by FredLL-Avaiga** [comment]
is this covered by the new part property `content` ?

**Comment by FlorianJacta** [comment]
Could you reference the issue/PR where we have an example of code of how it works?

**Comment by FredLL-Avaiga** [comment]
```
from taipy.gui import Gui, State

import plotly.express as px
from plotly.graph_objs import Figure
import typing as t
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")

figure = px.scatter(df, x="sepal_length", y="sepal_width", color="species")

color = "species"


def change_color(state: State):
    state.color = "petal_width" if state.color == "species" else "species"


def get_scatter(color):
    return px.scatter(df, x="sepal_length", y="sepal_width", color=color)


# <|{figure}|plotly|height=40vh|>

md = """
# Taipy Plotly test


<|part|content={get_scatter(color)}|height=40vh|>

<|Change color|button|on_action=change_color|>

"""

Gui(md).run()

```

**Comment by FlorianJacta** [comment]
It solves this issue. This is hard to be easier than that. This is great!
