### ISSUE TITLE
Why is the "Data" tab not first in data node viewer

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#438]
As I understand, there have already been discussions about this. Why is the "Data" tab not the first one in a data node viewer:
![image](https://github.com/Avaiga/taipy-gui/assets/62465003/961ec738-ec97-4f1e-bfe0-8835d5010f44)

It is the only tab I use, so I constantly have to click on it to access it. I do not personally see the use for the property tab.

**Comment by FredLL-Avaiga** [comment]
it is since 3.1

**Comment by AlexandreSajus** [comment]
Perfect!
