### ISSUE TITLE
Update iframe content with taipy state variables without needing new query parameters

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy#440]
**Description**
See title.

I learned about embedding plotly figure objects into taipy here: https://docs.taipy.io/en/develop/knowledge_base/tips/iframes/

I see that since the `on_user_content(state, path: str, query: dict)` callback has access to state, I can access my state variables to modify my iframe content. For example, I can create a date control and create a figure in on_user_content with only data for that date. However, it seems that the callback does not get called if the query parameters are unchanged.

Take the following example:

```python
import plotly.express as px
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")
fig = px.scatter(df, x="sepal_length", y="sepal_width", color="species", title="Initial title")

from taipy.gui import Gui, get_user_content_url, Markdown
import io

def expose_plotly(fig):
    buffer = io.StringIO()
    fig.write_html(buffer)
    return buffer.getvalue()

def on_user_content(state, path: str, query: dict):
    if path == "iris":
        fig.update_layout(title_text=state.title)
        html = expose_plotly(fig)
    return html

def on_init(state):
    state.uc_url = get_user_content_url(state, "iris")

uc_url = None
title = ""
iframe_example = Markdown(
"""

<|part|page={uc_url}|height=800px|>

<|{title}|input|>

""")

def on_change(state, var_name, var_value):
    if var_name == "title":
        state.uc_url = get_user_content_url(state, "iris")

Gui(iframe_example).run()
```

The iframe does not change when `title` is modified.

### Encoding the query parameters

```python
def on_change(state, var_name, var_value):
    if var_name == "title":
        state.uc_url = get_user_content_url(state, "iris", dict(title=state.title))
```

Then, in `on_user_content`, I can retrieve the title from either:

1. `query` -- which will not work with non-strings since they were url encoded
2. `state` -- which means I'm only sending query params to force an update

### Toggle a query parameter

```python
n = 0
def on_change(state, var_name, var_value):
    if var_name == "title":
        state.n = 0 if state.n else 1
        state.uc_url = get_user_content_url(state, "iris", {"n": state.n})
```

Which works better for me but of course is not great.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
I suppose the problem is gone when using the [figure](https://docs.taipy.io/en/latest/manuals/gui/viselements/chart/#p-figure) property ?

**Comment by arcanaxion** [comment]
> I suppose the problem is gone when using the [figure](https://docs.taipy.io/en/latest/manuals/gui/viselements/chart/#p-figure) property ?

Yes, and it works excellently!

Closing this issue

**Comment by arcanaxion** [comment]
Well I don't know if it may still be an issue for other content providers, if they exist. But for the case of plotly `go.Figure` objects (which I opened this issue for), the solution you mentioned is perfect for me
