### ISSUE TITLE
Use Python API alongside Markdown dynamically

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#443]
**Description**

The goal is to be able to use Markdown for the static part of your application and Python for the dynamic part. A user for example, wanted to change the list of buttons on the application depending on external events. 

*A possible solution*
It is possible now to create a partial with the Python API but not possible to update the content with a Python object page/part.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by dinhlongviolin1** [comment]
This issue was solved by PR https://github.com/Avaiga/taipy-gui/pull/1023 referencing issue https://github.com/Avaiga/taipy/issues/445.
