### ISSUE TITLE
Tables with Filters

### ISSUE THREAD

**Issue by vhfgosselin** [Avaiga/taipy#45]
Would be nice to be able to filter data on displayed tables using an excel like method:
We could see the columns where filters apply: 
![image](https://user-images.githubusercontent.com/20767690/171995152-4b364bd1-0331-4f4c-9c3f-6de5118d8ad8.png)
One difficulty becomes that filters can be complex combinations (and/or) of formulas (for numbers or strings). We could certainly have a single formula in the first version!

**Comment by jrobinAV** [comment]
ADDRESSED BY # 27 on taipy-gui
