### ISSUE TITLE
Add width property to input control

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#453]
**Description**
Add the ability to change the width of the _input_ visual element.

`<|{user_prompt}|input|width=100%|>`

Something similar to the selector visual element.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by chialiotta** [comment]
Hello, I just created a pr for this issue, could I please be assigned to this issue?

**Comment by jrobinAV** [comment]
Sure! Thank you for helping us!

**Comment by FabienLelaquais** [comment]
@chialiotta Do you think you can make it back on this thing or should we reassign to someone else?
