### ISSUE TITLE
Timedelta in tables

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#455]
**Description**
This improvement will facilitate the use of _timedelta_ objects in tables. _timedelta_ objects are not serializable and cannot be used in tables. An error will be raised: `UserWarning: JSONEncoder has thrown Object of type Timedelta is not JSON serializable`

```python
from taipy.gui import Gui
import pandas as pd

data = {"label":['red', 'white'],
        "timedelta": [pd.Timedelta(days=1), pd.Timedelta(days=2)]}

md = "<|{data}|table|>"

Gui(md).run()
```

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
Default support will just display str(TimeDelta)
one could provide a JsonAdapter to manage TimeDelta in another way
