### ISSUE TITLE
Tabular Data: support a callback to change unsupported data type to supported one

### ISSUE THREAD

**Issue by FredLL-Avaiga** [Avaiga/taipy#457]
**What would that feature address**
display unsupported data type

***Description of the ideal solution***
If a dataframe holds a column with unsupported data, we could handle a user callback that would transform that column to a supported type

***Caveats***
performance ?

***Other options***
Raise an error (as of today)

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by ScalarJerk** [comment]
@FredLL-Avaiga to clarify, we're creating a user callback that alerts users of unsupported type errors and then suggests them to convert the data into a supported type as well? (which the user may accept or declineand fix the data by himself)

**Comment by FredLL-Avaiga** [comment]
That is not what I had in mind.
The objective is to allow the dev to define a callback that would transform a specific data from an unknown data-type to a supported data-type (that would fit in a DataFrame)
At the moment, we support datetime (ie transform them to str) so that the Dataframe can be jsonified

**Comment by eleensmathew** [comment]
Can i work on this?

**Comment by FlorianJacta** [comment]
@ScalarJerk Do you aim to work on this issue? 

@eleensmathew You have already been assigned to another issue.

**Comment by Ujj1225** [comment]
can i work on this issue?

**Comment by FlorianJacta** [comment]
@Ujj1225, I am assigning you this issue. Thank you for your contribution!

**Comment by Ujj1225** [comment]
@FlorianJacta  @FredLL-Avaiga  
can i get more insights on this? 
I checked into the codebase and its huge. Can you tell me in which part of the code is the data is loaded, inspected, or converted into a dataframe?

In a file _data_manager.py
I found a __create method, here there is a point where data_node_config._properties.copy() is used. I feel this might be the right place to handle unsupported data types by adding a check for data types in the props. Since the data nodes are created based on configurations, the place to handle unsupported data types might be during or right after the node's creation or configuration process, right? 

Can you please provide me more insights on this?

**Comment by FlorianJacta** [comment]
I will let the R&D answer you. Maybe, @FabienLelaquais can also jump on this discussion

**Comment by FredLL-Avaiga** [comment]
In the code you can check how we use data_accessors to transform different types of data into tabular data that is handled by our front end component.
The indirections are done in the class [_DataAccessors](https://github.com/Avaiga/taipy/blob/b2b7f8c8b0d677e58f8db646814833deb3d9991c/taipy/gui/data/data_accessor.py#L97)

In that class, we return an [_InvalidDataAccessor](https://github.com/Avaiga/taipy/blob/b2b7f8c8b0d677e58f8db646814833deb3d9991c/taipy/gui/data/data_accessor.py#L141) when we cannot handle the type of data.

The aim of this issue is to add a callback to Gui (like on_change or on_action) to let the developer change an unsupported data into a supported data type. I would propose `on_invalid_data` but I guess @FabienLelaquais might have a better proposition

**Comment by Ujj1225** [comment]
So, gui has to get a function where it should let developers set a custom function that defines how to handle and transform unsupported data types?
I have completed a design which allows the developer to register a function that will change unsupported data types to supported ones
And if developer doesnt define a callback, everything will proceed as it is. Will this work or is there something i am missing here?

**Comment by FredLL-Avaiga** [comment]
Please create a PR and we can discuss on that base

**Comment by Ujj1225** [comment]
@quest-bot embark
