### ISSUE TITLE
BUG-Encoding problem using Markdown file (.md)

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#458]
**Description**
There is some encoding problem using characters like é, è, à, ù in a Mardown (.md).

**How to reproduce**
In *main.py*:

```python
from taipy.gui import Gui, Markdown

Gui(Markdown('markdown_format.md')).run()
```

In *markdown_format.md* (encoded in UTF-8):
```
é

è

ù

à
```

The resulting page:
![image](https://github.com/Avaiga/taipy-gui/assets/98709993/a6d96fc1-cd23-450e-aff3-72c0c4324017)

**Expected behavior**
Accents should be correctly displayed.

**Runtime environment**
Taipy: 2.2

**Comment by FlorianJacta** [comment]
It comes from the encoding of the Markdown file vs Python.

**Comment by dinhlongviolin1** [comment]
@FlorianJacta Correct me if I am wront but I remember that this one was solved on taipy-gui previously

**Comment by FlorianJacta** [comment]
@dinhlongviolin1 This is not solved. The problem is the difference in encoding between your MD files (mine is utf-8 by default) and the default encoding for "my Python" (mine is Windows 1252 by default)

**Comment by dinhlongviolin1** [comment]
Do you have any idea on how to fix it. I have no idea what is happening :D

**Comment by dinhlongviolin1** [comment]
I am not sure to add the default encoding as utf-8. We can change the encoding to utf-8 on all file read but what I am suggesting is that you can also read the file manually yourself and put the content of the file into the Markdown class in this case

**Comment by dinhlongviolin1** [comment]
@FabienLelaquais any thought on your side

**Comment by FlorianJacta** [comment]
@dinhlongviolin1 What you could do, but maybe bad, is before opening the Markdown file, you could check the file's encoding. I don't think you can find out easily. There is a package called *chardet* that tries to predict it for you. You can open the file with the correct encoding when you know the encoding.

Then, maybe having this issue is enough, as people with the same issue could find the answer. I am unsure we want to depend on another package that is not actively maintained...

**Comment by dinhlongviolin1** [comment]
chardet is obsolete from what I have seen
charset-normalizer https://pypi.org/project/charset-normalizer/ seems to be a better alternative and still being well-maintained.
I will have a look to try and implement them

**Comment by dinhlongviolin1** [comment]
I have implemented charset-normalizer, you can test it in the next release or from develop branch @FlorianJacta

**Comment by FlorianJacta** [comment]
@dinhlongviolin1 I don't know if this comes from this issue but now in develop, I have a critical problem using layout:

My Markdown
```
<|layout|columns=1 1 1|
<|
# Col 1
|>

<|
# Col 2
|>

<|
# Col 3
|>
|>
```

The result:

![image](https://github.com/Avaiga/taipy/assets/98709993/4ce34692-aac6-4a89-9f06-b75ee6e80f9f)

**Comment by dinhlongviolin1** [comment]
how are you storing the markdown

**Comment by FlorianJacta** [comment]
I am putting it inside a Markdown file with "utf-8" encoding. It is telling me that the encoding is ASCII

**Comment by dinhlongviolin1** [comment]
I have ascii also, and it is running properly on my machine. It appears as ascii because we are using character within the ascii space.

**Comment by FlorianJacta** [comment]
How can I help you with this?
