### ISSUE TITLE
BUG-Possibility to create a chart wider than screen size

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#461]
**Description**
With stylekit enabled, charts are truncated if their size is wider than the screen size. With stylekit disabled, th chart takes the correct size without being truncated.

**How to reproduce**

```python
from taipy.gui import Gui

data = {"x":[1, 2, 3, 4, 5, 6],
            "y":[12, None, 31, 4, 8, 6],}

md = """
<|{data}|chart|x=x|y=y|width=400%|>
"""

Gui(md).run()#stylekit=False
```

**Expected behavior**
The charts should be wider than the screen size.

**Runtime environment**
Taipy Gui 2.3.1

**Comment by FredLL-Avaiga** [comment]
Workaround:
- add a class_name to the chart
- redefine overflow(-x) to auto or unset

auto: scroll on the chart
unset: scroll on the page

**Comment by jrobinAV** [comment]
Comment lost after transferring the issue:
![image](https://github.com/Avaiga/taipy/assets/88036007/f501446e-9b76-4896-a248-d75272fc43f0)

**Comment by FredLL-Avaiga** [comment]
@FlorianJacta is this fixed ?

**Comment by FlorianJacta** [comment]
It's still not fixed, but the workaround works. Here is the taipy-chart class from the style kit:

```
.taipy-chart {
    border-radius: var(--border-radius);
    background-color: var(--color-paper);
    box-shadow: var(--box-shadow);
    overflow: hidden;
}
```

The *overflow* is put to *hidden*.

**Comment by FredLL-Avaiga** [comment]
overflow shouldn't be a problem

**Comment by FlorianJacta** [comment]
I mean, it is this parameter that doesn't show the scrollbar for the chart.

**Comment by FredLL-Avaiga** [comment]
use !important

**Comment by FlorianJacta** [comment]
Yes, I know. I am questioning the fact that we are using `overflow: hidden` in the stylekit.

**Comment by FredLL-Avaiga** [comment]
I think the default is right

**Comment by FlorianJacta** [comment]
I have no idea. We can close this issue as "not planned".
