### ISSUE TITLE
BUG-taipy-gui requirements might be too constrained

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#463]
**Description**
When trying to install the following requirements using pip:
```
taipy==2.3.1
requests
pandas
pandasai==0.6.12
```

It fails with the error:
```bash
The conflict is caused by:
    pandasai 0.6.12 depends on python-dotenv<2.0.0 and >=1.0.0
    taipy-gui 2.3.1 depends on python-dotenv<0.21 and >=0.19
    pandasai 0.6.12 depends on python-dotenv<2.0.0 and >=1.0.0
    taipy-gui 2.3.0 depends on python-dotenv<0.21 and >=0.19
```

Our python-dotenv requirements are constrained between 0.19 and 0.21, which is very restrictive for a product that is supposed to work conjointly with other open-source tools. We should make our requirements less stringent.

**Comment by FredLL-Avaiga** [comment]
current version is `python-dotenv>=1.0.0,<=1.0.1`

**Comment by FredLL-Avaiga** [comment]
@AlexandreSajus is this still a valid issue ?

**Comment by AlexandreSajus** [comment]
Currently no user reports on this, you can close this if you want

**Comment by FredLL-Avaiga** [comment]
You should close it as the creator 🙏 @AlexandreSajus

**Comment by AlexandreSajus** [comment]
Closed for now as no user has reported issues on this currently
