### ISSUE TITLE
Possibility to add traces to an existing chart

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#465]
**Description**
Without a refresh, the chart will not show the three traces after clicking the button. After a refresh, it shows the three traces. The goal would be to avoid refreshing the page to show the traces.

```python
from taipy.gui import Gui

data = {
    "x": [1, 2, 3],
    "y": [1, 2, 3],
    "y2": [4, 5, 1],
}

properties = {
    "x":"x",
    "y[1]":"y",
    "y[2]":"y2",
}

def change(state):
    state.data['y3'] = [14, 15, 11]
    state.properties['y[3]'] = "y3"
    state.refresh('properties')
    state.refresh('data')

Gui("<|{data}|chart|properties={properties}|> <|change|button|on_action=change|>").run()
```

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
property [rebuild](https://docs.taipy.io/en/latest/manuals/gui/viselements/chart/#p-rebuild) ?

**Comment by FlorianJacta** [comment]
Not working with rebuild either.

**Comment by FredLL-Avaiga** [comment]
Does this work if you do *not* use the properties?

**Comment by FlorianJacta** [comment]
And how can I do that?

**Comment by FredLL-Avaiga** [comment]
Here is a workaround for you @FlorianJacta 

```
from taipy.gui import Gui

data = {
    "x": [1, 2, 3],
    "y": [1, 2, 3],
    "y2": [4, 5, 1],
}

properties = {
    "x":"x",
    "y[1]":"y",
    "y[2]":"y2",
    "y[3]":""
}

def change(state):
    state.data['y3'] = [14, 15, 11]
    state.properties['y[3]'] = "y3"
    state.refresh('data')

Gui("""
<|{data}|chart|properties={properties}|rebuild|>
<|change|button|on_action=change|>
""").run()

```

**NB**: the y[3] property is declared from the beginning but affected only when needed

Does that work for you ?

**Comment by FlorianJacta** [comment]
It does not work because, typically, I don't know that there is a third trace (or fourth, fifth...). I just discover it in runtime. But maybe, it is not the correct way to add a trace, they are maybe better ways

**Comment by FredLL-Avaiga** [comment]
Even better, I don't think you will disagree @FlorianJacta ...

```
from taipy.gui import Gui

data = {
    "x": [1, 2, 3],
    "y": [1, 2, 3],
    "y2": [4, 5, 1],
}

ys = ["y","y2"]

def change(state):
    with state: 
      state.data['y3'] = [14, 15, 11]
      state.refresh('data')
      state.ys = state.ys + ["y3"]

Gui("""
<|{data}|chart|x=x|y={ys}|rebuild|>
<|change|button|on_action=change|>
""").run()
```

**Comment by FredLL-Avaiga** [comment]
I must say there might be a slight bug as it's working half time 👿😗

**Comment by FlorianJacta** [comment]
I was thinking about this when I said it is maybe not the correct way to create to add a trace. If it can work everytime, it is even better

**Comment by FredLL-Avaiga** [comment]
That's the way to do it and it's supported for a long time.
Bugs happen... And will be fixed

**Comment by FlorianJacta** [comment]
Do we have to create another issue for this one ?

**Comment by FredLL-Avaiga** [comment]
No

**Comment by FredLL-Avaiga** [comment]
in fact, it works if a height is set for the chart :-(

**Comment by FredLL-Avaiga** [comment]
looks like it was a bug in plotly ...
I'll push a PR to make sure that we pick up the right plotly version (2.32.0)
