### ISSUE TITLE
Allow specifying width for "card" stylekit class

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy#468]
**Description**
Creating a part with the "card" class occupies the full horizontal space. Is there a way to specify the width of the card?

Currently, I can think of doing this by wrapping it in a layout block like so:

```python
from taipy.gui import Gui, Markdown

md = Markdown("""
<|layout|columns=15rem|

<|card|

Card content              

|>
              
|>
""")

Gui(md).run()
```

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
I think that's the plan: use a layout :-)

**Comment by jrobinAV** [comment]
Is it still relevant in the latest versions of Taipy?

**Comment by arcanaxion** [comment]
> Is it still relevant in the latest versions of Taipy?

I think it could still use improvements.

From my understanding, cards currently take up the full width of its container, and the height is based on height taken by the elements within the card. Half the time, this "default" works — notably when I'm just grouping a bunch of controls to have the same background.

But often I need the card's width to be just enough to fit its content (like how it currently works in height). An example use case is when I'm using cards to show some metric/KPI. Rather than wrap the card in a single-column layout block just so I can specify width, it'd be easier if I could do it directly with the card. Or even better, if I could do something like `<|card|width=fit-content|>` and it'd be just the right width to fit the metric etc.
