### ISSUE TITLE
Install Taipy on Google Colab

### ISSUE THREAD

**Issue by florian-vuillemot** [Avaiga/taipy#47]
Taipy should be able to run in Google Colab but the pip install is not working.

https://colab.research.google.com/

**Comment by florian-vuillemot** [comment]
Google colab only supports Python3.7 but taipy does not.
There is no acceptable way to run a Python3.8 version of Python inside in order to install taipy.
We will support it natively when they update the platform.

**Comment by baaastijn** [comment]
For information, tested in OVHcloud AI Notebooks (alternative to Colab), works like a charm :)
Have a good day
