### ISSUE TITLE
Add support for Sankey charts

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#471]
Description
Support plotly.js Sankey type

https://plotly.com/javascript/sankey-diagram/

Acceptance Criteria

Ensure new code is unit tested, and check code coverage is at least 90%
Add relevant demos (doc/examples/charts)

**Comment by FredLL-Avaiga** [comment]
DOes this work with the [figure](https://docs.taipy.io/en/latest/manuals/gui/viselements/chart/#p-figure) property ?

**Comment by FlorianJacta** [comment]
It works, and I think it is enough.
