### ISSUE TITLE
Allow the Chart component to temporarily display in full-screen

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy#472]
**Description**

Because charts may be represented in small areas, it would be nice to let end-users be able to temporarily show any individual chart in a maximized dialog sitting on top of the current page.
This will work as a toggle.

Would `https://stackoverflow.com/questions/69042546/is-there-a-way-to-create-a-full-screen-popup-window-of-a-plotly-chart-in-r` help?

**Acceptance Criteria**
- [ ] Document the shortcut in the `chart` and the `datanode_viewer` elements.

**Comment by FredLL-Avaiga** [comment]
https://community.plotly.com/t/adding-a-button-to-modebarbuttons-with-cutom-image/401

[list of available icons](https://github.com/plotly/plotly.js/blob/master/src/fonts/ploticon.js)
I guess we can use [full screen](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Afullscreen%3A) and [close full screen](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aclose_fullscreen%3A)

A [codepen](https://codepen.io/etpinard/pen/YWEdpo) to add a button to the bar

**Comment by FlorianJacta** [comment]
Love this feature by the way!

**Comment by FabienLelaquais** [comment]
Yeah nice.
Should we add a code example that demonstrates how to do that?
I'll be happy to include it!

**Comment by FredLL-Avaiga** [comment]
I'm working on integrating this in the chart component...
