### ISSUE TITLE
No possiblity to change width of file_selector and file_upload

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#474]
## Issue

There is no possibility to extend the file_selector or file_upload to the full width of the page.

## How to replicate

![image](https://github.com/Avaiga/taipy/assets/98709993/a7d7fdda-540a-4c3f-a59c-5acfb18a15b2)

```python
from taipy.gui import Gui


page = """
<|{None}|file_selector|label=Selector|width=100%|class_name=fullwidth|>

<|{None}|file_download|label=Download|width=100%|class_name=fullwidth|>
"""

if __name__ == "__main__":
    Gui(page=page).run()
```

## Expected behavior

This should take all the width of the page.

## Environment
Taipy 3.0.0

**Comment by qmohitsingh** [comment]
hey @FlorianJacta , Could you please assign this issue to me? Thank you

**Comment by FlorianJacta** [comment]
@qmohitsingh Sure! Thank you for contributing to Taipy! Some indication: the code to change is inside [Taipy](https://github.com/Avaiga/taipy) repo. You will find how to [contribute](https://github.com/Avaiga/taipy-gui/blob/develop/CONTRIBUTING.md) and [install](https://github.com/Avaiga/taipy-gui/blob/memo-installation-rewrite/INSTALLATION.md) Taipy GUI there. Of course, feel free to contact us if you need any help. We also have a [Discord](https://discord.gg/XBT5q2Ar) with a 'contributing' channel where we can also talk.

**Comment by FredLL-Avaiga** [comment]
Taipy GUI repo has been merged into taipy repo

**Comment by FlorianJacta** [comment]
Hi @qmohitsingh, do you need any help for this issue?

**Comment by FlorianJacta** [comment]
Hi @qmohitsingh, please let us know if you are still working on this issue. We'll assume you're no longer available in one week and will reassign it. Thank you!

**Comment by Satoshi-Sh** [comment]
Can I take this issue?

**Comment by FlorianJacta** [comment]
Thank you @Satoshi-Sh. I have assigned it to you. Let us know if you need anything
