### ISSUE TITLE
`Events col` on the `cloud.taipy`

### ISSUE THREAD

**Issue by mbiesiad** [Avaiga/taipy#478]
Hi,

First of all, great work! 
Looks like `Events column on the cloud.taipy.io` contains redundant info at this moment.

# Repro steps:
1. Go to https://www.taipy.io/ and scroll down to see `Events`
2. Go to https://cloud.taipy.io/ and scroll down to see `Events`
3. Compare

# Screenshots:
Looks fine ✔ from step 1:
![image](https://github.com/Avaiga/taipy/assets/18367606/2bffb92a-7c6a-4fe9-8fa3-a49a09caa58a)

Looks bad ❌ from step 2:
![image](https://github.com/Avaiga/taipy/assets/18367606/dcae816a-0b55-459a-b997-a045589c7f5d)

# Additional information:
What is the purpose to show (referring to the step 2) there links to `404 Error` or `Logout` (when user is not logged in)?
It could be more transparent.

Best wishes,

**Comment by FlorianJacta** [comment]
Thank you for your feedback! We are taking care of it as soon as possible.

**Comment by coderbm1** [comment]
Thank you for your message, sounds great! ✨

**Comment by FlorianJacta** [comment]
Done!
