### ISSUE TITLE
Lack of Security file

### ISSUE THREAD

**Issue by coderbm1** [Avaiga/taipy#479]
Hello,
It would be great to see Security.md file https://github.com/Avaiga/taipy/security I think. (with at least some contact to the proper Team)

Details can be found at https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository.

Kind regards,

**Comment by FlorianJacta** [comment]
Thank you for your feedback! We are currently discussing about it.

**Comment by jrobinAV** [comment]
Done
