### ISSUE TITLE
Error in default date behavior documentation

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#495]
## Issue

There is an error in the date documentation. The default behavior for date is without time. So a 'with_time' must be added to the visual element to have time, not the contrary.

![image](https://github.com/Avaiga/taipy/assets/98709993/f250ad41-97ad-4b84-b7c5-b8690b26e130)

The documentation from this [repository](https://github.com/Avaiga/taipy-doc) has to change.

**Comment by Forchapeatl** [comment]
Hi, may I take this issue ?

**Comment by trgiangdo** [comment]
Sure. I assigned it to you @Forchapeatl. Thank you
