### ISSUE TITLE
BUG -  `CoreSection` init should not use default value

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#497]
Ok, but I get inspired from what is done in `CoreSection`: https://github.com/Avaiga/taipy-core/blob/develop/src/taipy/core/config/core_section.py#L100
which does pretty much the same...

_Originally posted by @gmarabout in https://github.com/Avaiga/taipy-enterprise/pull/265#discussion_r1406248345_

**Comment by trgiangdo** [comment]
The same snippet also exists in the `JobSection`. We need to fix both.

**Comment by jrobinAV** [comment]
Does it have an impact on enterprise package as well?

**Comment by trgiangdo** [comment]
It doesn't.

But since the PR #1035 has some refactoring on the Job config checker, there is an opening PR on enterprise that propagates the change.
