### ISSUE TITLE
Stop using the README as long description in the various setup.py

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#507]
In all the `setup.py` files (config, gui, core, rest, taipy, templates), the long_description is populated with the README.md content. 
This is NOT a good practice since the long description represents a description of the package built. It is used in Pypi to describe the package. The readme is also exposed as the landing page of the repo and used as instructions on how to use the code base. These have different purposes and different lifecycles. The content should be different.

The general idea is to split the use cases:

- [ ] Propose for each setup.py a new long description content stored directly in the setup.py. The version could be dynamically injected if needed.
- [ ] Include the update of the long descriptions in the release process
- [ ] Use the readme.md for each package (config, GUI, core, rest, templates,) as an introduction page for contributors it should be related to a specific taipy version. 
- [ ] Use the global taipy readme.md as a landing page on the github repo independent from the taipy versions.

**Comment by trgiangdo** [comment]
This issue is under review
