### ISSUE TITLE
Linter reports no existing member for taipy gui builder

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#510]
Linters (Pylint and Pycharm) do not detect the members of taipy.gui.builder and report them as warnings

![image](https://github.com/Avaiga/taipy/assets/62465003/5f3309a6-8cfb-452d-9ed6-3de697bd43ef)

**Comment by AlexandreSajus** [comment]
![image](https://github.com/Avaiga/taipy/assets/62465003/2ab2e40e-6e4c-4ed7-90ad-1614155d12c0)

Another user reported that this is difficult to work with since he does not get auto-completion due to this issue

**Comment by dinhlongviolin1** [comment]
Thanks for creating the issue. This is due to missing pyi files within the previous release. We should get this fix in the next release

**Comment by dinhlongviolin1** [comment]
This is now available in taipy-gui 3.1.0

**Comment by FlorianJacta** [comment]
This is so great! Good job! 🥇
