### ISSUE TITLE
`um-field-error` still displayed after filled out missing fields

### ISSUE THREAD

**Issue by mbiesiad** [Avaiga/taipy#528]
Hi,

# Repro steps:
Go to https://cloud.taipy.io/register/ and click Create account. See displayed `um-field-error` for proper fields.
Next, fill out missing fields (meet the requirements) - still can see `um-field-error`.

# Screenshot
![image](https://github.com/Avaiga/taipy/assets/18367606/a156e3cf-de55-4e0a-bc1f-28143be3d32f)

# Proposed solution
Validation - if it is fine, no `um-field-error` message.

Best wishes,

**Comment by florian-vuillemot** [comment]
Hello and thank you for your report. Taipy-cloud is currently undergoing a major migration. We'll take care of it right after.

**Comment by jrobinAV** [comment]
The graphical interface has been redone, and the Taipy Cloud service will be shut down end of April 2024.
