### ISSUE TITLE
Installing on Windows with Python 3.12 fails due to pinned dependency

### ISSUE THREAD

**Issue by joaomcarlos** [Avaiga/taipy#529]
Hi,

Could you please unpin "pyarrow" or repin with a more modern version?

Right now, using the most modern python version, which is 3.12, it fails to install on Windows because `"arrow": ["pyarrow>=10.0.1,<11.0"],` which obviously doesnt exist for 3.12 since pyarrow is at version 14 already.

Thank you!

**Comment by FlorianJacta** [comment]
Thank you for the issue @joaomcarlos! We'll take a look at the repercussions of this change as soon as possible. We do not support 3.12 yet but we will.

**Comment by jrobinAV** [comment]
Closed for duplication.
#627 Is critical and proposes to support Python 3.12.
