### ISSUE TITLE
How to set host to 0.0.0.0

### ISSUE THREAD

**Issue by Lix1993** [Avaiga/taipy#533]
when set host to 0.0.0.0, it returns Server starting on http://localhost:{port}/

```
from taipy import Gui

# 设置全局配置，包括端口号

excitement_page = """
# Welcome to Taipy
### How excited are you to try Taipy?

<|{excitement}|slider|min=1|max=100|>

My excitement level: <|{excitement}|>
"""
excitement = 100


Gui(page=excitement_page).run(host = '0.0.0.0',port = 7411)
```

[2023-12-04 13:59:02][Taipy][INFO] Running in 'single_client' mode in notebook environment
[2023-12-04 13:59:02][Taipy][INFO]  * Server starting on http://localhost:7411/

![image](https://github.com/Avaiga/taipy/assets/12579295/6a9d8808-c393-45c3-8c81-0d3004841117)

**Comment by FlorianJacta** [comment]
This should have the same meaning as "0.0.0.0". Your application is also now accessible inside your private network. Do you have something in mind on what it should return?

**Comment by Lix1993** [comment]
Thank you for your response. I modified the parameters of 'run' in the notebook and could not connect after running it again, so I thought it was an issue with the host setting. I assumed that 'localhost' could only be accessed locally. However, after running it again, I realized that both 'localhost' and '127.0.0.1' can also be used within a private network.
