### ISSUE TITLE
CRUD operations withMongodb Atlas

### ISSUE THREAD

**Issue by Forchapeatl** [Avaiga/taipy#534]
* Taipy version: 3.0.0
* Python version: 3.8.10
* Operating System:  Linux

### Description
Take this connection string for example 
```mongodb+srv://SoumiBardhan:<password>[@cluster](http://twitter.com/cluster)-test.fndbj.mongodb.net/myFirstDatabase?retryWrites=true&w=majority```

How can I perform CRUD (Create ,Read, Update, Delete) operations with mongodb atlas. What happens after this

```

from taipy import Config

historical_data_cfg = Config.configure_mongo_collection_data_node(
    id="historical_data",
    db_username="SoumiBardhan",
    db_password="password",
    db_name="myFirstDatabase",
    collection_name="historical_data_set",
)

historical_data_cfg.insert_one({"_id":0, "user_name":"Soumi"})

```
#Error
![image](https://github.com/Avaiga/taipy-core/assets/24577149/80b47588-cfcc-4f3a-b55b-2338005504c1)

I don't know how to insert , read , updtae and delete  form mongo collection

**Comment by trgiangdo** [comment]
Hello @Forchapeatl, the `historical_data_cfg` you created here is only a Datanode Configuration.

Before read or write to the database, you need to create a data node entity from the configuration by:
- Submitting a relevant scenario, or
- Use the `tp.create_global_data_node(historical_data_cfg)`.

Please check the [Create a data node documentation page](https://docs.taipy.io/en/latest/manuals/core/entities/data-node-mgt/#create-a-data-node) for more details.
