### ISSUE TITLE
S3DataNode

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#536]
- [x] Implement a new predefined storage type "s3" in `DataNodeConfig`, to model a single data object stored on an S3 bucket.
- [x] List and design the configuration attributes required.
- [x] Implement the corresponding `S3DataNode` inheriting from the parent `DataNode` class.
- [ ] Add reference manual documentation

**Comment by Forchapeatl** [comment]
Please can I handle this issue ? If yes please tell more about  it.  It seems like it's 5  millstones for a single future.  I don't know where to start debugging.

**Comment by toan-quach** [comment]
Hi @Forchapeatl 

Thanks for reaching out! The idea of this ticket is that we want to support more predefined data nodes so our users can retrieve data from more sources, and S3 is 1 of them. To implement this ticket I'd suggest taking a look at the other predefined data nodes such as CSVDataNode, MongoDataNode, ExcelDataNode, etc., and also the DataNodeConfig where we define the configuration for data nodes.
After that, I'd suggest to start with defining the S3DataNode entity class and a new data node configuration for S3DataNode. On a side note, the S3DataNode should inherit from DataNode class.

You can assign me or @jrobinAV for reviewing after you have finished!

Thanks again for helping us out on this project!!! We really appreciate it!

**Comment by Forchapeatl** [comment]
Thank you fro the explaination @toan-quach . I have made some analysis  on this issue, Please correct me if I am in the wrong direction.

- **Case Study : Amazon S3 bucket.**

![image](https://github.com/Avaiga/taipy-core/assets/24577149/2e04aaff-01f3-44ec-9b8a-06e4f1e3e73a)

**Assumptions:** 

1. We know what the contents of the file are ( _.png, .jpeg,  .json , .npy , .csv  ... etc_ )
2.  We are retriving csv data.

The following example retrieves an object for an S3 bucket. 
```py
response = client.get_object(
    Bucket='examplebucket',
    Key='SampleFile.csv',
)

return response['body']
```
Refferences [get_object - Boto3 1.28.79 documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/get_object.html#)

**Comment by toan-quach** [comment]
@Forchapeatl 

Yep I think you're on the right direction! I also wanted to add, since we can't expect the file format that the user's storing on s3, it makes sense to request the user to provide us with a "read_file" function so we can load the data from that file and maybe "write_file" so that we can store it if it makes sense to you. Let me know what you think!
