### ISSUE TITLE
Repair GitHub actions

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#539]
Re-create all the GitHub actions for all packages. 
- [x] packaging tests
- [x] dev releases
- [x] releases
- [x] code coverage
- [ ] integration testing
- [ ] benchmark
- [x] codeQL

Try to factorize the GitHub actions

**Comment by FredLL-Avaiga** [comment]
the requirements in ./setup.py should be built dynamically from the different requirements in tools/packages/**/setup.py
