### ISSUE TITLE
table filter: removing a filter does not reset the data

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#545]
On a table visual element with filter. Applying a filter and then removing it using the trashbin icon (A) will not reset the data to its initial state. Plus, it renders the reset list button (B) non-clickable which makes the data stuck in the filtered state:
![image](https://github.com/Avaiga/taipy/assets/62465003/b7b4d3e6-b829-4f3a-a9fd-a1978487b504)

## Expected Result
Remove the "Reset List", the "Apply Filter" as they are redundant. The ✔️ button should be a toggle that applies the filter. The 🗑️  button should delete and disable the filter

Related to #502

**Comment by srinivaspavan9** [comment]
Is this issue still open ?

**Comment by FredLL-Avaiga** [comment]
No, why?
