### ISSUE TITLE
Mapbox token management

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy#555]
**Description**

Mapbox is used by Plotly to create map charts.

Users may need to use a Mapbox Access token (see https://plotly.com/python/mapbox-layers/) is order to use the Mapbox service.
We need to find a way for users to provide Taipy with their specific Mapbox token.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
I guess via the Gui config and a property that defaults to the config value

**Comment by BaunaBadmosh** [comment]
i would like to work on this

**Comment by anupriyakkumari** [comment]
Hi, could this get assigned to me?

**Comment by FlorianJacta** [comment]
Hi all, I will assign @PRIYANKjakharia as he is the first to ask. Thank you for your contribution.

@anupriyakkumari, many other issues are waiting for you!

**Comment by ShootingStarD** [comment]
FYI the mapbox plotly API is deprecated and may be removed in future versions of plotly. I don't know if taipy already updated its code based on that : https://plotly.com/python/tile-map-layers/#mapbox

**Comment by FredLL-Avaiga** [comment]
yes, we support the new mapbox

**Comment by FredLL-Avaiga** [comment]
Should this be closed or Should we support the token while plotly still support mapbox ? @FabienLelaquais

**Comment by FabienLelaquais** [comment]
We don't want to base ant code on deprecated libraries.
