### ISSUE TITLE
Add an example on how to integrate Matplotlib

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy#558]
**What would that feature address**

Many Python programmers are using [Matplotlib](https://matplotlib.org/) as a way to create charts.

These are static, and we want to let users in charge of defining their charts entirely.

***Description of the ideal solution***

The best way to do this seems to be using `mpld3` and the `plugins` module.

An example would show how to create a Matplotlib chart, and how to integrate it in a Taipy page (certainly using the `content` property of the part control).

**Acceptance Criteria**
- [ ] The example is part of the documentation set.

**Comment by abhayg-07** [comment]
@FabienLelaquais can u assign this issue to me

**Comment by FabienLelaquais** [comment]
Sure thing, thanks a lot!

Note that my approach would be to use the `part` control, where the *page* property would be set to the returned value of `taipy.gui.get_user_content_url()`... Not really straightforward hu? Any idea on simplifying that is welcome!
Thanks again.

**Comment by FredLL-Avaiga** [comment]
With the latest content property on part, you can simply provide a Matplotlib figure as a value
`<|part|content={mp_figure}|>`

**Comment by FabienLelaquais** [comment]
Indeed as @FredLL-Avaiga mentioned, Taipy GUI (only in the develop branch at this point) was complemented with a new property for the `part` control that makes it possible to insert any HTML content coming from a third-party library.
This needs a bit of documentation, which is on the way (see [doc issue](https://github.com/Avaiga/taipy-doc/issues/739)).

We plan to close this issue at the end of next week.

**Comment by SGCODEX** [comment]
Hi @FabienLelaquais @jrobinAV 
Can you please assign me this issue under Hacktoberfest and Devfest ai?

**Comment by jrobinAV** [comment]
Sure @SGCODEX . Thank you for your contribution.

**Comment by SGCODEX** [comment]
Thank you @jrobinAV sir, will get started on it now.

**Comment by Saedbhati** [comment]
Hii @jrobinAV can you assign this issue to me?

**Comment by SGCODEX** [comment]
Sir have raised the PR, please check

**Comment by DeepSkyWonder** [comment]
Hi There,

If this is still waiting for a contributor, can you assign this to me as part of Hacktobeberfest.? I can submit a matplotlib example or two using the part control with a content provider.

I have two examples:

(1) Displaying an astronomy image (download from the internet) in FITS format, along with metadata displayed in a table using the AstroPy library that professional astronomers use. 

(2) I also have an example that uses matplotlib along with 'part' and a 'content provider' to display a latex equation, using matplotlib's internal mathtex implementation (a subset of tex). And if you want something really cool, I created one that will generate mathml, and use an SVG trick to fallback to a matplotlib generated png image of the equation on browsers that do not support mathml. (I'm also working on creating a content provider that will use the katex library clientside to display the equations, but it is still a work in progress.)

Cameron :-)
(Deep Sky Wonder)

**Comment by AbisoyeOnanuga** [comment]
Hi @jrobinAV If this issue still needs contributions, I'd like to give it a good try

**Comment by jrobinAV** [comment]
Hi @AbisoyeOnanuga, Please feel free to work on it and propose a PR. 
You can also review the existing PRs and eventually collaborate with @SGCODEX to benefit from each other's experience.

**Comment by AbisoyeOnanuga** [comment]
Thanks @jrobinAV   for the assignment. I made an update on @SGCODEX based on their experience on this issue. I reviewed the existing PRs on it and I tried to apply a solution based on the concept ```<|part|content={mp_figure}|>```, inserting the generated content directly, which removes the need to save chart images to a file. Only custom css is used, but tgb is not used @FredLL-Avaiga Please, see https://github.com/Avaiga/taipy/pull/2179. Thank you

**Comment by SGCODEX** [comment]
@jrobinAV @FredLL-Avaiga @FabienLelaquais , if #2179 as proposed by @AbisoyeOnanuga solves the markdown example directly without using the save image feature. Then we can go ahead with that for the markdown example and my example for the tgb can be used as mentioned in earlier parts of #1930. Please let me know the changes I should do in my PR. Thank you.

**Comment by AbisoyeOnanuga** [comment]
@jrobinAV @FredLL-Avaiga @FabienLelaquais after updating to Taipy 4.0.0 my solution https://github.com/Avaiga/taipy/pull/2179 avoids using image file. Your example for the tgb can be used from https://github.com/Avaiga/taipy/pull/1930.
I used the same folder structure as @SGCODEX if that helps
