### ISSUE TITLE
Add formatting in tables using functions

### ISSUE THREAD

**Issue by chrisOnWheels** [Avaiga/taipy#564]
Currently Taipy uses printf style formatting in tables
~~~ python
<|table|data={my_data}|columns={col_format}|...|>
col_format = {'Sales':'%.2f'}
~~~

This could be extended by allowing functions, like in <|selector|adapter={...}> 

~~~ python
col_format={ "Sales": {"format_function": format_func}}

def format_func(data, column_name) -> list[str]:
    ... apply formatting ...
    return formatted_column_data
~~~

Such functions might even return images 

Background:  
I'd like to have floats formatted like 9.999,99 which seems not possible using pure printf style syntax in Taipy.
Taipy doesn't support %'d to get locale aware thousands separator.
AFAIK printf doesn't support thousands separators in floats.

**Comment by FlorianJacta** [comment]
Thank you for your issue! It seems like a good feature! We will talk about it inside our R&D team

**Comment by yaten2302** [comment]
Hey @FlorianJacta, is this feature required, may I give it a try to add this?

**Comment by FlorianJacta** [comment]
@FabienLelaquais @FredLL-Avaiga Could this issue be assigned?

**Comment by FabienLelaquais** [comment]
It certainly can. The thing is, it is far more complicated than it looks since the conversion to string has to be performed on the server side, which is going to be a problem. Especially for the edition part.
But hey, let's move forward yes.

**Comment by yaten2302** [comment]
Hey @FabienLelaquais @FlorianJacta , I've a doubt in this, like instead of letting the user provide the format function, can we provide our own format functions? like, we can have some functions which renders a specific number of rows that the user requires or something like that?

If the user passes the format function, then will it be possible to implement that?

**Comment by FlorianJacta** [comment]
I am not sure I understand your issue @yaten2302. We want a function that converts all values of the rows of a column into other values that will be the ones displayed.

**Comment by yaten2302** [comment]
@FlorianJacta actually, I'm not completely able to understand this? Could you please explain this once again - "We want a function that converts all values of the rows of a column into other values that will be the ones displayed."?

**Comment by FlorianJacta** [comment]
We want to use a user function to format column values. Just, like the example written in the issue.

Maybe you already understand it this way, and I am just overcomplicating it.
