### ISSUE TITLE
BUG-Text Visual Element does not support break lines

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#565]
**Description**
I can not find a way to break lines in a text visual element
I expected one of those two to work:
<|{"a\nb"}|text|>
<|{"a<br\>b"}|text|>
But unfortunately, it just shows <br\> as text and ignores and hides \n

**Expected behavior**
\n should break lines in a text visual element

**Runtime environment**
 - OS: Windows 11
 - Browser: Chrome

**Comment by ashutuptiwari** [comment]
Please explain this issue in greater detail and assign it to me. ASAP(3 days left for hacktobefest)

**Comment by AlexandreSajus** [comment]
Yeah sure:

We have a visual element to display text on a webpage. The syntax is <|{text_to_display}|text|>. The problem is it does not support break lines with \n

Here is an example, `pip install taipy` and then run this code:

```python
from taipy.gui import Gui

text = "a\nb"

page = """
<|{text}|text|>
"""

Gui(page=page).run()
```

This displays:
![image](https://github.com/Avaiga/taipy-gui/assets/62465003/923452c8-a11a-4ed2-ade3-74aef9a33d50)

Instead of "a" then on another line "b"

**Comment by ashutuptiwari** [comment]
![image](https://github.com/Avaiga/taipy-gui/assets/106370097/e7a45dee-bdbe-41f7-b968-68e15e3cd51e)
Am i doing something wrong? I was following the INSTALLATION.md

**Comment by FredLL-Avaiga** [comment]
Did you execute the previous commands
Ie
$ cd gui
# Install the DOM dependencies (once and for all)
$ cd dom
$ npm i
$ cd ..
# Install the web app dependencies
$ npm i --omit=optional
# Build the web app
$ npm run build

**Comment by ashutuptiwari** [comment]
yes i did 
![image](https://github.com/Avaiga/taipy-gui/assets/106370097/29c0a788-fdc0-4978-b650-56f70f760b6d)

**Comment by ashutuptiwari** [comment]
any feedback? @FredLL-Avaiga

**Comment by FabienLelaquais** [comment]
For some unknown (yet) reason, it seems that the 'resolve-cwd' module was not installed..
Can you try a `npm install resolve-cwd` before you re-run the build command?

Maybe it can also be due to an outdated `package-lock.json`, sitting next to `package.json` in the `gui` directory.
You may also try to remove that file and run `npm run inst` then `npm run build`.

Please let us know if this helped.

**Comment by VibhorGits** [comment]
Hey @AlexandreSajus @FabienLelaquais Can I also try this as hacktoberfest is about to end.

**Comment by ashutuptiwari** [comment]
Yes please @VibhorGits . I'll remove my assignment.

**Comment by VibhorGits** [comment]
Cool. Hey @ashutuptiwari May I ask you to guide me through the problem so that I get an idea about it.

**Comment by FredLL-Avaiga** [comment]
Duplicate for [taipy-Gui #420](https://github.com/Avaiga/taipy-gui/issues/420)

**Comment by AlexandreSajus** [comment]
I don't think this should be closed. Text visual element still does not support break lines

**Comment by FredLL-Avaiga** [comment]
it should be closed
mode=pre
