### ISSUE TITLE
BUG-Scope issue when assigning to state using lambda

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy#568]
**Description**
Using the [example in the docs](https://docs.taipy.io/en/develop/manuals/gui/binding/#lambda-expressions) for using a lambda expression to assign to state does not work in a subpage.

**How to reproduce**

```python
# app.py
import taipy as tp
from fruit import fruit_md

pages = {
    "/": "<|navbar|>",
    "fruit": fruit_md,
}

def on_change(state, var_name, var_value):
    print(var_name, var_value)

tp.Gui(pages=pages).run()
```

```python
# fruit.py
from taipy.gui import Markdown

fruit_list = ["apple", "banana", "cherry"]
selected_fruits = fruit_list[:]

fruit_md = Markdown(
"""
# Select fruit

<|{selected_fruits}|selector|lov={fruit_list}|multiple|>

# assign
                                        
<|Select All|button|on_action={lambda s: s.assign("selected_fruits", s.fruit_list)}|> - does not work

<|Clear All|button|on_action={lambda s: s.assign("selected_fruits", [])}|> - does not work
                    
# setattr
                    
<|Select All|button|on_action={lambda s: setattr(s, "selected_fruits", s.fruit_list)}|> - does not work

<|Clear All|button|on_action={lambda s: setattr(s, "selected_fruits", [])}|> - works
                    
# fn

<|Select All|button|on_action=select_all|> - works

<|Clear All|button|on_action=clear_all|> - works
""")

def select_all(state):
    state.selected_fruits = state.fruit_list

def clear_all(state):
    state.selected_fruits = []
```

**Expected behavior**
All 6 buttons above should work

**Screenshots**
When available and relevant, screenshots better help show the problem.

**Runtime environment**
Please specify relevant indications.
 - taipy-gui dev branch

**Comment by dinhlongviolin1** [comment]
I and @FredLL-Avaiga has retested this issue on the current dev branch and it is working as expected. @arcanaxion please retest it and let us know if it is working for you too.

**Comment by arcanaxion** [comment]
> I and @FredLL-Avaiga has retested this issue on the current dev branch and it is working as expected. @arcanaxion please retest it and let us know if it is working for you too.

Yes it all works now, thanks!

**Comment by dinhlongviolin1** [comment]
Thanks @arcanaxion 
I will close the issue then
