### ISSUE TITLE
Improve chart VS for interactive multi-traces charts

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#570]
The goal of this issue to improve the plotting of interactive charts with multiple traces. (This is in relation with https://github.com/Avaiga/taipy-gui/issues/980)

Plotting `n` (not known ahead of time) traces in Taipy is currently difficult. There are 2 existing options:

## 1. content property

Literally use plotly.express with the content property. Code looks clean and easy to understand.

```python
from taipy.gui import Gui, Markdown
import plotly.express as px

df = px.data.stocks()

def create_fig(selected_tickers):
    chart_df = df.melt(id_vars="date", var_name="Ticker", value_name="Closing")
    chart_df = chart_df[chart_df.Ticker.isin(selected_tickers)]
    return px.line(chart_df, x="date", y="Closing", color="Ticker")

ticker_list = df.columns.to_list()[1:]
selected_tickers = ticker_list[:3]

md = Markdown(
"""
<|{selected_tickers}|selector|lov={ticker_list}|multiple|dropdown|>

<|part|content={create_fig(selected_tickers)}|height=70vh|>
"""
)

Gui(page=md).run(run_browser=False)
```

## 2. taipy partials

The result looks much better than the content iframe method. But the code is still too complicated for a simple chart that new users might be deterred.

```python
from taipy.gui import Gui, Markdown
import plotly.express as px

df = px.data.stocks()

def create_chart_partial(selected_tickers):
    y_params = "|".join([f"y[{i+1}]={ticker}" for i, ticker in enumerate(selected_tickers)])
    return f"<|{{df}}|chart|x=date|{y_params}|>"

ticker_list = df.columns.to_list()[1:]
selected_tickers = ticker_list[:3]

md = Markdown(
"""
<|{selected_tickers}|selector|lov={ticker_list}|multiple|dropdown|on_change={lambda s: s.partial.update_content(s, create_chart_partial(s.selected_tickers))}|>

<|part|partial={partial}|>
"""
)

gui = Gui(page=md)
partial = gui.add_partial(create_chart_partial(selected_tickers))
gui.run(run_browser=False)
```

## Goal

The goal would be to improve the chart's visual elements to make it easy to create this type of interactive chart.

## Environment

Taipy 3.0

**Comment by srinivaspavan9** [comment]
Hi @FlorianJacta 

I'm eager to assist with the multi-traces charts in Taipy. Could you clarify what specific improvements are needed for the chart's visual elements and user experience?
and also the first code snippet (Content Property ) isnt producing any chart, am i doing any thing wrong ?

**Comment by FlorianJacta** [comment]
Hi @srinivaspavan9 ,

Have you tried the first code with the develop branch? This is a new feature where you can put Plotly fig inside Taipy. The goal of the issue is to make creating muti-trace charts easy.

This is quite a subject, maybe @FredLL-Avaiga or @FabienLelaquais have some idea. It might be an issue a bit too complex at the moment.

**Comment by FredLL-Avaiga** [comment]
did you try with properties ?

**Comment by FredLL-Avaiga** [comment]
@FlorianJacta Does the chart [figure](https://docs.taipy.io/en/develop/manuals/gui/viselements/chart/#p-figure) property answer this question ?

**Comment by FlorianJacta** [comment]
It does.
