### ISSUE TITLE
Re-execution of 'main.py'

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#59]
The code of "main.py" of a Taipy project is being re-runned by default on the Gui side with "use_reloader=True" (when a change is done to the code). It is also re-runned when a worker is created on the Core side. These behaviors could be changed or documented.

Because of this, it is also important to explain how to initialize the variables for the Gui in a good manner in order to get the desired result when the 'main.py' is being re-executed.

Version of Taipy:
taipy-core 1.1.1
taipy-gui 1.1.1

**Comment by jrobinAV** [comment]
@FabienLelaquais I have a spark of an idea related to this. We can discuss it.

**Comment by FabienLelaquais** [comment]
But be my guest.

**Comment by jrobinAV** [comment]
- Open a new API to let the user provide a custom function (or list of functions) to be executed once before the application starts. The function must be passed as an optional parameter to the taipy.run method.

- Add documentation in the user manual to clearly states that it is not recommended to have scripted code (outside any function) in the main.py script.
