### ISSUE TITLE
Missing file in complete application tutorial

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#591]
On this [page](https://docs.taipy.io/en/latest/knowledge_base/tutorials/complete_application/step_01/step_01/):
![image](https://github.com/Avaiga/taipy/assets/62465003/259c745b-ea50-4ed2-bf1e-b1462a636e7f)
The highlighted download link is dead. It should point to this [file](https://github.com/Avaiga/taipy-doc/blob/531fae277b89cb6fca1aa2eed0914f0165f1939b/docs/knowledge_base/tutorials/complete_application/src/src.zip).

**Comment by FlorianJacta** [comment]
It does point to this file...

**Comment by jrobinAV** [comment]
Must be changed in both develop and latest

**Comment by FlorianJacta** [comment]
Is this a build problem? zip files are not put on the website or something like that?
