### ISSUE TITLE
Error when displaying 'b' in a text

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#601]
## Issue

Displaying the letter `b` or `B` results in a NaN. This issue may have other undefined impact on Taipy.

## How to replicate

```python
from taipy import Gui

some_text = "b"

Gui("<|{some_text}|>").run()
```

![image](https://github.com/Avaiga/taipy/assets/98709993/033396f2-73ae-4b00-be9b-caa8f13e178a)

## Environment

Taipy 3.0.0

**Comment by FredLL-Avaiga** [comment]
pandas.api.types.is_integer_dtype('b') returns True !!!
but pandas.api.types.is_integer_dtype('a') returns False

Explanation:
https://numpy.org/doc/stable/reference/arrays.dtypes.html#index-6
