### ISSUE TITLE
Improvement on date visual elements to not break the line

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#605]
## Issue

Without a date visual element, everything is on the same line:

![image](https://github.com/Avaiga/taipy/assets/98709993/ca65c2e0-8cf1-49b4-ae79-0764f7ecc1c9)

Putting a date visual element breaks the line:

![image](https://github.com/Avaiga/taipy/assets/98709993/81a8c765-a8e5-47e9-81cf-d427d2361ed3)

```python
from taipy.gui import Gui 

md = """
<|Medium|input|>
<|Medium|input|>
<|{None}|date|>
<|Medium|input|>
<|Medium|input|>
"""

Gui(md).run()
```

## Improvment

Visual elements should behave similarly. `date` should not skip the line.

## Environment
Taipy 3.0.0

**Comment by amitvikramraj** [comment]
Hi @FlorianJacta
Can I pick up this issue?

Got to know about taipy from [Santiago Valdarrama](https://www.linkedin.com/in/svpino/overlay/about-this-profile/). Since this is a `low priority` issue and a `good first issue`. And this is my first time trying to contribute to open-source projects. Would love to contribute to this project.

Here is my [Linkedin profile](https://www.linkedin.com/in/avr27/) if you're interested

Best,
Amit

**Comment by FlorianJacta** [comment]
Hi @avr2002 , you can of course take this issue. Right now, we are stabilizing the mono repo so the R&D is not the most available but they will help you on this task @FredLL-Avaiga  

You can ask for help and we will try to help you the best. [Here](https://github.com/Avaiga/taipy/blob/develop/CONTRIBUTING.md) is how you can contribute to Taipy. Are you familiar with GitHub?

**Comment by amitvikramraj** [comment]
Thank you @FlorianJacta and @FredLL-Avaiga 

Yes I'm familar with github. Can you tell me where can I go to ask my doubts? is it Discord? I have joined it just now

**Comment by FlorianJacta** [comment]
If it is related to the issue, you can put your questions here. If it is more general, you can go to our Discord, there is a contributing channel!

**Comment by srinivaspavan9** [comment]
Hi i have started working on this issue and i need a bit of clarity on this issue 
Is this issue about how the string is being wrongly processed for the <|{None}|date|> tag cause i have noticed that its being processed as markdown while debugging. am i right ? 
I need help

**Comment by FredLL-Avaiga** [comment]
No the issue is related to the way the date component is rendered in the HTML Page.
it is rendered in a new block 
And I suppose the reporter would have like the component to be rendered in line ie within the current block

hint: looks related to css in date.css ...

**Comment by srinivaspavan9** [comment]
> No the issue is related to the way the date component is rendered in the HTML Page. it is rendered in a new block And I suppose the reporter would have like the component to be rendered in line ie within the current block
> 
> hint: looks related to css in date.css ...

I have applied the required changes and in the css file but its not reflecting on the browser, when i inspected the element it seems that the updated file is not being served. I have tested the change to make sure that i am doing the right thing by changing the css using developer tools in the browser and its working.
do i need to rebulid the project or reinstall the taipy in my dev environement ? what am i doing wrong ?

**Comment by FredLL-Avaiga** [comment]
You need to rebuild the js bundle
in frontend/taipy-gui 
- `npm run build`

**Comment by srinivaspavan9** [comment]
> You need to rebuild the js bundle in frontend/taipy-gui
> 
> * `npm run build`

It worked,

Thank you

**Comment by srinivaspavan9** [comment]
I've created a pull request [#615 ](https://github.com/Avaiga/taipy/pull/615) on this issue
I welcome any feedback or suggestions

**Comment by FlorianJacta** [comment]
Great, I put @FredLL-Avaiga and @FabienLelaquais as reviewers, as well as putting some labels to your PR.
