### ISSUE TITLE
Input visual element has a frustrating delay

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#610]
The input visual element will register the inputted text at a specific time delay (defined by the property change_delay). When this register happens, the app will have a quick lag that will cause typed text not to be registered. This is very frustrating: The user is typing something, stops for half a second, and then continues typing, and some of his new characters are missing.

You can test this issue on [TalkToTaipy](https://talk-to-taipy.taipy.cloud/) or [TaipyGPT](https://demo-llm-chat.taipy.cloud/). Just type at different speeds while taking quick pauses; some characters won't be registered at some point, which will be frustrating. You can also try it on mobile; the change_delay seems to change between local, Cloud, and Mobile.

**Discussion**

An example such the Chat situation obviously raises the problem of the continuous update of the text value. Only the final value makes sense.

We may want to force the user to press Enter when he's done. Setting change_delay to -1 may be the solution.

Another track is to figure out, with a ping on the connection initialization, the bandwidth and adapt the delays accordingly.

**Expected change**
The text should only be registered regularly if the user defines an on_change function. In my two use cases, I only need the user's text when he presses "Enter" (on_action). I do not need it registered regularly, so I did not define on_change.

**Comment by AlexandreSajus** [comment]
We have been getting many complaints on this, switching priority to critical. Also there might be the same issue on the slider visual element

**Comment by FlorianJacta** [comment]
For the slider, you have the `continuous` property to not call the *on_change* function every time the variable is updated.

**Comment by AlexandreSajus** [comment]
Sometimes, even with continuous disabled, the app does not have enough resources to keep up and will lag the slider. Maybe that's another issue

**Comment by FredLL-Avaiga** [comment]
when changeDelay = -1 & Enter in ActionKeys (or no ActionKeys) => the input value will be updated only on Enter

**Comment by FlorianJacta** [comment]
What is the reason to also have an *on_action*? Will the value still go to the *on_change* callback each time if there is an *on_action* and no *on_action*?

**Comment by FredLL-Avaiga** [comment]
> What is the reason to also have an _on_action_? Will the value still go to the _on_change_ callback each time if there is an _on_action_ and no _on_action_?

Fixed the spec
