### ISSUE TITLE
Add the possibility in treemap to set a color according to a specific value and a size depending on a weight set on the sector 

### ISSUE THREAD

**Issue by ygosselin** [Avaiga/taipy#622]
Enhancement proposition : Add the possibility in treemap to set a color according to a specific value and a size depending on a weight set on the sector 
the weight being a third element in addition to the value and to the name
it could look like this see the two files attached
<img width="447" alt="testmap" src="https://github.com/Avaiga/taipy/assets/38358724/1a1f0263-a075-48da-b4ff-c3a8aec3430d">
and
[map.csv](https://github.com/Avaiga/taipy/files/13716357/map.csv)

**Comment by FlorianJacta** [comment]
You can change the color of the treemap through the *treemapcolorway* in the *layout* parameter or the *marker* property.

Layout:

```python
from taipy.gui import Gui 

# Data set: the first 10 elements of the Fibonacci sequence
n_numbers = 10
fibonacci = [0, 1]
for i in range(2, n_numbers):
    fibonacci.append(fibonacci[i-1]+fibonacci[i-2])

data = {
    "index": [i for i in range(1, n_numbers+1)],
    "fibonacci": fibonacci,
}


layout = {"treemapcolorway":["red" if i % 2 == 0 else "blue" for i in range(1, n_numbers+1)]}

md = "<|{data}|chart|type=treemap|labels=index|values=fibonacci|layout={layout}|>"

Gui(md).run()
```

Marker:

```python
from taipy.gui import Gui 

# Data set: the first 10 elements of the Fibonacci sequence
n_numbers = 10
fibonacci = [0, 1]
for i in range(2, n_numbers):
    fibonacci.append(fibonacci[i-1]+fibonacci[i-2])

data = {
    "index": [i for i in range(1, n_numbers+1)],
    "fibonacci": fibonacci,
}

markers = {
    "colors": ["red" if i % 2 == 0 else "blue" for i in range(1, n_numbers+1)],
}


md = "<|{data}|chart|type=treemap|labels=index|values=fibonacci|marker={markers}|>"

Gui(md).run(debug=True)
```

![image](https://github.com/Avaiga/taipy/assets/98709993/af72d27d-142e-474f-b7db-d92ea6fc63c0)

Here, you define colors in advance, and it is not continuous. It seems it is possible through Plotly Express [here](https://plotly.com/python/treemaps/#treemap-of-a-rectangular-dataframe-with-continuous-color-argument-in-pxtreemap). It is now possible to integrate Python Plotly in Taipy by putting your *fig* inside the content. See this issue: https://github.com/Avaiga/taipy/issues/640

**Comment by FlorianJacta** [comment]
@FredLL-Avaiga I haven't found a way to have this continuous color shown in the Plotly express example. Also, is there any simplification on how to assign colors? Maybe through a column name?

**Comment by FredLL-Avaiga** [comment]
In the marker dict, column names can be assigned to the following properties `"color", "size", "symbol", "opacity"`

**Comment by FlorianJacta** [comment]
It does not work this way for treemaps, it seems @FredLL-Avaiga 

```python
from taipy.gui import Gui 

# Data set: the first 10 elements of the Fibonacci sequence
n_numbers = 10
fibonacci = [0, 1]
for i in range(2, n_numbers):
    fibonacci.append(fibonacci[i-1]+fibonacci[i-2])

data = {
    "index": [i for i in range(1, n_numbers+1)],
    "fibonacci": fibonacci,
    "color": ["red" if i % 2 == 0 else "blue" for i in range(1, n_numbers+1)],
}

markers = {
    "color": "color",
}


md = "<|{data}|chart|type=treemap|labels=index|values=fibonacci|marker={markers}|>"

Gui(md).run()
```

The code above doesn't show the correct colors.

The property is *colors* and not *color* like the code from my other answer.

**Comment by ygosselin** [comment]
It seems that treemap is not what I should use, because i have the need for two values and it works for only one from what i have seen
I think I may be able to have different colours , but a different size depending of a second value (the weight) no unfortunately. So this is not a taipy enhancement.
for the color i will try this
fig = px.treemap(df, path=[px.Constant("all"), 'component'], 
                 values='confidence', color='confidence',
                  color_discrete_map={'(?)':'lightgrey','5':'green','4':'yellow','3':'red'})
fig.update_layout(margin = dict(t=50, l=25, r=25, b=25))
fig.show()

**Comment by FredLL-Avaiga** [comment]
The layout way is possible today.
I will add `colors` to the list of supported column names properties in the marker dict
