### ISSUE TITLE
Documentation Error for LTTB decimator

### ISSUE THREAD

**Issue by vhfgosselin** [Avaiga/taipy#625]
**Description**
English mistake inside the description of the LTTB decimator. See the screenshot attached.
Replace 'using by using' with 'using' only!

    ```
![image](https://github.com/Avaiga/taipy/assets/20767690/4958a197-9744-45c3-bf24-617a5e5dfd9d)

**Comment by Mikerniker** [comment]
Hello @vhfgosselin & @jrobinAV ! Can I try to fix this?

**Comment by trgiangdo** [comment]
You are very welcome to. Thank you

**Comment by Mikerniker** [comment]
ok, thanks @trgiangdo ! Will try to send a PR soon :)
