### ISSUE TITLE
Standalone Taipy GUI visual element syntax checker

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy#657]
**What would that feature address**

A user has requested a standalone syntax checker for visual elements expressed in Markdown.

***Description of the ideal solution***

A simple Python script (and/or API) that is based on taipy/gui/viselements.json that, provided a sting containing the definition of a known Taipy visual elements in its Markdown syntax, generates error messages or validates the string.
The script may contain the json description file, or rely on an external one (next to the script, in the taipy-gui installation...).

**Acceptance Criteria**
- [ ] The resulting script could be attached in this issues as the outcome.

**Comment by dinhlongviolin1** [comment]
Working example is in the gist
https://gist.github.com/dinhlongviolin1/d68dbcfbc85ff2cb102167ae198f102e
