### ISSUE TITLE
Add .gitignore and init git repo for taipy cli

### ISSUE THREAD

**Issue by toan-quach** [Avaiga/taipy#671]
When using django cli or reactjs cli to generate a project, it always comes with a folder that already has git initialized along with a .gitignore. This is very convenient to have in taipy cli as well

**Comment by jrobinAV** [comment]
We need to list the file patterns to be in the `.gitignore`:

EDITED: 
Add the version generated by GitHub + `.taipy`, `.data`, `user_data`

**Comment by jrobinAV** [comment]
The .gitignore should be added to the default template.

**Comment by anunayasri** [comment]
Hi @jrobinAV I want to work on this. I have setup the codebase and am exploring it further. Can you point me to the entrypoint to taipy cli please.

**Comment by toan-quach** [comment]
Hi @anunayasri ,

The entry point to the CLI would be in the `taipy/_cli` folder. However, I believe this issue is looking to develop a default `.gitignore` and initiate a git repo for the to-be-created Taipy project through Taipy template. So it might be to your interest to have a look at Taipy template at `taipy/templates` as well :D Do let me know if you have further questions!

Thanks for supporting us and giving us a helping hand!!!

**Comment by anunayasri** [comment]
Hi @toan-quach. 

Thanks for the response and for correcting me. I need one more help please. I am trying to run the `taipy` cli. For some reason, `pip install .` doesn't create an executable in the venv's bin folder. Taipy is installed only in site-packages folder. Any leads on how to resolve it? Ultimately I want to run `taipy create --template <>`.

**Comment by trgiangdo** [comment]
There is a problem with the `pip install .` since it does not follow the `setup.py` logic. You can read more about it here: https://stackoverflow.com/questions/21781734/entry-points-does-not-create-custom-scripts-with-pip-only-with-easy-install-in.

To sum up, what you can do is going to a different working directory and installing Taipy with an absolute path to the `taipy` directory. For example:

```
pip install $HOME/src/taipy
```

Please let me know if it can work.

**Comment by anunayasri** [comment]
Hi @trgiangdo . Sorry, I was not able to respond your comment earlier. I tried switching to a different directory but it didn't work. I tried using `pip install --upgrade .` and that also didn't work. :/

**Comment by trgiangdo** [comment]
Again, installing with the "." will not work.

Please try to create a separate environment in a different directory than taipy, then install using the taipy path.

**Comment by anunayasri** [comment]
@trgiangdo Installing in a different directory also didn't work. I have already tried it. I have solved it temporarily by reverse engineering the `taipy` executable. Mentioning the steps below if someone else is facing the same problem.

```sh
cd $PROJECT_ROOT
touch extaipy.py  # executable taipy
# Paste the python script given below in the file 
# Update the python executable based on your venv

chmod +x extaipy.py

./extaipy.py help
```

```python
#!/Users/anunayasri/workspace/taipy/.venv/bin/python    <<<<< Update based on your venv
import re
import sys
from taipy._entrypoint import _entrypoint

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(_entrypoint())
```

**Comment by anunayasri** [comment]
Hi. I wasn't able to be give time to wrap up this issue. I have picked it up to raise the PR. Getting the following error. I would appreciate if someone could help.

I have added `git init` logic to post-gen hook in both the tempaltes: `taipy/templates/default/hooks/post_gen_project.py` and `taipy/templates/scenario-management/hooks/post_gen_project.py` but mypy thinks these are duplicate packages. I have just added logic to existing packages! 

```shell
taipy/templates/scenario-management/hooks/post_gen_project.py: error: Duplicate module named "post_gen_project" (also at "taipy/templates/default/hooks/post_gen_project.py")
taipy/templates/scenario-management/hooks/post_gen_project.py: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more info
taipy/templates/scenario-management/hooks/post_gen_project.py: note: Common resolutions include: a) using `--exclude` to avoid checking one of them, b) adding `__init__.py` somewhere, c) using `--explicit-package-bases` or adjusting MYPYPATH
```

**Comment by trgiangdo** [comment]
In the `pyproject.toml`, we defined mypy to exclude `(taipy/templates/|generate_pyi.py|tools)"`, which also excludes the duplicated modules in `taipy/templates`.

I'm not sure why you are getting the error tbh, but it should be fine when you commit and push the branch.

**Comment by trgiangdo** [comment]
@anunayasri I assigned the issue to you because you are already working on it. Let me know if it's ok.

Thank you

**Comment by anunayasri** [comment]
@trgiangdo. Thanks for the help. I am totally fine to be the assignee. 👍🏼 Will raise the PR in some time.

**Comment by anunayasri** [comment]
Hi @trgiangdo . I have raised the PR. Could you have a look.
https://github.com/Avaiga/taipy/pull/1247
