### ISSUE TITLE
Styling a table styles the whole data and not just the rows displayed which causes performance issues

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#673]
Styling a table using the style property of a table visual element will style the entire dataset and not the rows displayed. When I have a dataset of 20 000 rows but I only display 100 rows, it takes 5 seconds to generate the table which is inconvenient.

style should only be applied to the displayed rows of a table visual element. The style should be reapplied when the user looks at new rows, increases the number of rows displayed, filters the table, edits the table...

**Comment by yaten2302** [comment]
Hey @AlexandreSajus, I was just checking the doc for Taipy tables, I just found that only specific number of tables can also be styled without styling the entire table - https://docs.taipy.io/en/latest/tutorials/visuals/2_using_tables/

![image](https://github.com/Avaiga/taipy/assets/129659514/12749cf3-c3d1-41ac-9f51-e0f567a33e87)

Is this the error which you were talking about?

**Comment by AlexandreSajus** [comment]
I don't think we are talking about the same thing here. Let's say the dataset used for the table in your image is a 20 000 rows dataset. Taipy seems to be checking if "Category = Dessert" on all 20 000 rows instead of just checking the 100 rows displayed. This causes performance issues.

**Comment by yaten2302** [comment]
> I don't think we are talking about the same thing here. Let's say the dataset used for the table in your image is a 20 000 rows dataset. Taipy seems to be checking if "Category = Dessert" on all 20 000 rows instead of just checking the 100 rows displayed. This causes performance issues.

Ohh! @AlexandreSajus so, is it like as you said - there are 20k rows and we want to display only 100 and apply formatting only on those 100 rows, which will increase the performance, am I right?

**Comment by AlexandreSajus** [comment]
Yes exactly

**Comment by yaten2302** [comment]
Got it @AlexandreSajus 👍 actually, I've one more doubt, there are 2 types of tables - `autoLoadingTable` and `paginatedTable`, so is this feat has to be applied on both?

**Comment by yaten2302** [comment]
@FredLL-Avaiga, just wanted to ask that can this be fixed? actually, I haven't read the Table.tsx part, so that's why I was just asking?

**Comment by FredLL-Avaiga** [comment]
It can certainly be fixed
But I'm not sure it'll be easy

**Comment by yaten2302** [comment]
Yeahh @FredLL-Avaiga I was also thinking the same, I'll just check that if it can be fixed, I'll give it a try 👍
BTW, I wanted to ask that this has to fixed for both `autoLoadingTable` and `paginatedTable`, right?

**Comment by FredLL-Avaiga** [comment]
Both tables use the same backend

**Comment by yaten2302** [comment]
> Both tables use the same backend

I'll try to understand the table.tsx part 👍

**Comment by yaten2302** [comment]
Hey @FredLL-Avaiga , actually, I was understanding the Table part. But, I've a doubt, that in the file `TableUtils.tsx` , it's used for all the button clicks, right? Like, editing a cell in a table or deleting a column or a row, something like that?

And the `PaginatedTable.tsx` or `AutoLoadingTable.tsx` is for the styling of the table, like which rows have to be highlighted and stuff, am I right?

**Comment by yaten2302** [comment]
@FredLL-Avaiga , actually, I was trying to go understand the PaginatedTable.tsx. I've a doubt that in [this file](https://github.com/Avaiga/taipy/blob/develop/frontend/taipy-gui/src/components/Taipy/PaginatedTable.tsx), do we've to make changes in the `styTt` function on line [158](https://github.com/Avaiga/taipy/blob/develop/frontend/taipy-gui/src/components/Taipy/PaginatedTable.tsx#L158)

**Comment by FredLL-Avaiga** [comment]
No, as I said it's all in the backend (python) side

**Comment by yaten2302** [comment]
@FredLL-Avaiga , could you please tell that in which file it's present? I'll try try to understand that part...

**Comment by FredLL-Avaiga** [comment]
@AlexandreSajus I think this has been fixed, can you confirm and close ?

**Comment by FredLL-Avaiga** [comment]
@AlexandreSajus up

**Comment by AlexandreSajus** [comment]
> @AlexandreSajus up

I wanted to test this but I am blocked by: https://github.com/Avaiga/taipy/issues/1754

**Comment by AlexandreSajus** [comment]
Fixed in 4.0.0.dev2

**Comment by jrobinAV** [comment]
@AlexandreSajus Note that 4.0.0.dev2 is an unstable version.
This feature will be part of the stable version 4.0.
