### ISSUE TITLE
Possibility to kill, change the port or abort when port already used

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#687]
**What would that feature address**
When running an application on a port already taken, the application will not work. It can be frustrating as sometimes we don't know which port is already used.

***Description of the ideal solution***
The goal would be to let the user choose between three options:
- kill the port so the other application using it cannot use it anymore.
- change it to another port
- abort: the application will not run

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Create related issue in taipy-doc for documentation and Release Notes
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it
- [ ] Ensure any change is well documented

**Comment by dinhlongviolin1** [comment]
I will have a discussion with the team on this issue. Thanks FJ!
