### ISSUE TITLE
Add switch visual element

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#691]
**What would that feature address**
Add switch visual element to Taipy: [example](https://mui.com/material-ui/react-switch/) 

![image](https://github.com/Avaiga/taipy-gui/assets/98709993/1c6d4875-04c7-4208-afba-934fe45b562b)

Parent issue: #436 

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Create related issue in taipy-doc for documentation and Release Notes
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
toggle mode=switch (only when lov length == 2 ? @FabienLelaquais

**Comment by FredLL-Avaiga** [comment]
```
from taipy.gui import Gui, State

bval = True

def on_change(state: State, var: str, val: str):
  print(f"on_change(state, var={var}, val={val})")

md = """
Demo Toggle as switch

<|{bval}|toggle|label=active|>
<|{bval}|toggle|label=not active|not active|>

"""

Gui(md).run()
```
