### ISSUE TITLE
Add progress bar/circle visual element

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#692]
**What would that feature address**
Add progress bar/circle visual element to Taipy: [example](https://mui.com/material-ui/react-progress/) 

![image](https://github.com/Avaiga/taipy-gui/assets/98709993/ad829356-ea17-48cc-9133-8ad1fdcbc001)

Parent issue: #436
Linked to: #551 

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Create related issue in taipy-doc for documentation and Release Notes
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it
- [ ] Ensure any change is well documented

**Comment by manojkr19** [comment]
Really looking forward to this feature.  I've a UI that pulls data, which may have a few seconds to a min.  Need to provide some feedback to the user while they are waiting.

**Comment by FlorianJacta** [comment]
For the meantime, you can use the [*notify*](https://docs.taipy.io/en/latest/manuals/reference/taipy.gui.notify/) function to create a notification saying that the user has to wait.

**Comment by FlorianJacta** [comment]
Another user on Discord asked for it again. I am moving this to High as a result.

**Comment by chialiotta** [comment]
Hi, I would like to contribute to this issue. Could you please assign it to me?

**Comment by FabienLelaquais** [comment]
That is great news Chiara!
You are going to need Python, Typescript, React, and MUI, but that should be fun!

We would like a new control called 'progress', using the referenced MUI component.
We'll improve on the requirements when something is usable on the front-end.

Welcome to Taipy!

**Comment by FredLL-Avaiga** [comment]
Do not hesitate to ask questions here 😎

**Comment by chialiotta** [comment]
Great, thank you! Will do :)

**Comment by chialiotta** [comment]
Hello, I have started to work on the React components, however, I want to make sure I'm taking all the steps required. I have made a .tsx and .spec.tsx and from what I understand I now need to update factory.py and then tests to both tests/gui/builder/control and  tests/gui/control. What exactly is the difference between these last two? 
Also, maybe a dumb question, but how can I locally visually test out the generation of the new component?

**Comment by FredLL-Avaiga** [comment]
test/gui/builder/control uses the Builder API
while test/gui/control uses Markdown/HTML
Don't forget to update the viselements.json file (used in the doc for for API generation)

Once you've built the front-end bundle
To test, you can create a demo python file at the root of the repo and it will use the current version of Taipy without installing it

**Comment by chialiotta** [comment]
I built the frontend bundle and created a demo file, but it tells me that the new component is not registered. How am I supposed to register it?

**Comment by FredLL-Avaiga** [comment]
There's an export.ts file I think

**Comment by chialiotta** [comment]
Unfortunately that doesn't seem to fix it

**Comment by yaten2302** [comment]
> **What would that feature address** Add progress bar/circle visual element to Taipy: [example](https://mui.com/material-ui/react-progress/)
> 
> ![image](https://private-user-images.githubusercontent.com/98709993/276560623-ad829356-ea17-48cc-9133-8ad1fdcbc001.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MjY0NjQsIm5iZiI6MTcxNTQyNjE2NCwicGF0aCI6Ii85ODcwOTk5My8yNzY1NjA2MjMtYWQ4MjkzNTYtZWExNy00OGNjLTkxMzMtOGFkMWZkY2JjMDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDExMTYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4YTg2YjY0NmMwODdjZjg5NTQ4OTRmNmI2ZTM5MmY5MzY0OTUwMTg2ODlhOTg0MThiN2Y5ODRiYTg3MWRiYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z3f9eAn1R2b0iISi6jUFZgRzbNbCoesUv9Z5dbhUXEg)
> 
> Parent issue: #436 Linked to: #551
> 
> **Acceptance Criteria**
> 
> * [ ]  Ensure new code is unit tested, and check code coverage is at least 90%
> * [ ]  Create related issue in taipy-doc for documentation and Release Notes
> * [ ]  Check if a new demo could be provided based on this, or if legacy demos could be benefit from it
> * [ ]  Ensure any change is well documented

Hey @FlorianJacta, actually I was reading about this issue, but I was not able to understand this completely, could you please guide that where this visual element has to be added, like in what sense? And @chialiotta since you've previously worked on this issue, could you also please guide me regarding this, maybe we can work on this together?

**Comment by FredLL-Avaiga** [comment]
> Unfortunately that doesn't seem to fix it

Sorry, you need to add your component in the list in [index.ts](https://vscode.dev/github/Avaiga/taipy/blob/bug/%231201-table-rebuild-lov/frontend/taipy-gui/src/components/Taipy/index.ts#L72)

**Comment by FlorianJacta** [comment]
@yaten2302 Taipy relies on visual elements to bring interactivity to the GUI. These visual elements come from different Javascript libraries (MUI, for example). The goal is to incorporate another visual element into Taipy natively.

You can read about the extension API [here](https://docs.taipy.io/en/latest/manuals/gui/extension/). This API enables you to extend Taipy with a new object. However, we would want to add Taipy directly here. Maybe, @FredLL-Avaiga or @FabienLelaquais could help you with that

**Comment by yaten2302** [comment]
Hey @FlorianJacta, if I've understood this correctly, what exactly we've to do is that, we've to create 2 new files in [this dir](https://github.com/Avaiga/taipy/tree/develop/frontend/taipy-gui/src/components/Taipy) named - `Circle.tsx` and `Circle.spec.tsx`(for testing).
We're  basically incorporating a new visual element in Taipy, right?

**Comment by FlorianJacta** [comment]
I think @chialiotta is working on this issue. Are you still working on it? Please let me know if you need any help.

If you are not, we could maybe assign you @yaten2302 and provide you with more explanation to keep things organized.

**Comment by yaten2302** [comment]
Sure @FlorianJacta , if no one is working on this, I'll definitely work on this issue👍

**Comment by chialiotta** [comment]
Hey, I was working on this, but I don’t have time right now to finish it, so if you want to take over @yanten2302 you are welcome to
________________________________

**Comment by yaten2302** [comment]
Hey @FlorianJacta, could you please assign this issue to me, I want to work on it.

**Comment by FredLL-Avaiga** [comment]
Welcome @yaten2302  
do not hesitate to ask questions here.

**Comment by yaten2302** [comment]
Thank you so much @FredLL-Avaiga for your help.
Sure, I'll definitely ask if I encounter any problem or doubt.
Currently I'm trying to understand the `Button.tsx` and `Button.spec.tsx` file in [frontend dir](https://github.com/Avaiga/taipy/tree/develop/frontend/taipy-gui/src/components/Taipy). Then I'll start with the new element i.e. the progress bar 👍🏼

**Comment by FredLL-Avaiga** [comment]
For your information,
Once, your happy with the tsx component, you need to declare it in 
- `taipy\gui\_renderers\factory.py` and `frontend\taipy-gui\src\components\Taipy\index.ts`

**Comment by yaten2302** [comment]
Hey @FredLL-Avaiga, to get started by developing the front-end part, I've to install both of these right? - [Taipy Front-end](https://github.com/Avaiga/taipy/blob/develop/frontend/taipy/README.md) and [Taipy GUI Front-end](https://github.com/Avaiga/taipy/blob/develop/frontend/taipy-gui/README.md)

**Comment by FredLL-Avaiga** [comment]
fine, but you don't need Taipy front-end as it concerns core visual elements (scenario_selector ...)

**Comment by yaten2302** [comment]
Hey @FredLL-Avaiga, actually I've a doubt, could you clarify this? Like, for the progress bar, by default(if there are no params entered by the user) the element rendered will be this(the circular indeterminate one), right? <br>
![image](https://github.com/Avaiga/taipy/assets/129659514/b28696a9-a1da-475b-8007-d7e947620516)<br>
And if the user enters the params like - color, show_progress, then the element rendered will be like this: <br>
![image](https://github.com/Avaiga/taipy/assets/129659514/7e60c15b-0144-4e86-b6cd-3c336f790fbd)

**Comment by FredLL-Avaiga** [comment]
You're right
I'm not sure we want a color property
but I'm sure we want a circular and another linear with the same element name

**Comment by yaten2302** [comment]
Got it 👍🏼 I'll leave the color property for now and will add the circular and the linear progress bars👍🏼

**Comment by yaten2302** [comment]
Hey @FredLL-Avaiga, actually I was having a doubt, if I want to run only a specific file let's say - `Button.tsx`, then how can I do that? I'm asking this because I want to check the new element (it's not complete right now, but I just wanted to do a dry run kind of thing).

**Comment by FredLL-Avaiga** [comment]
> For your information,
> Once, your happy with the tsx component, you need to declare it in 
> - `taipy\gui\_renderers\factory.py` and `frontend\taipy-gui\src\components\Taipy\index.ts`
> 

You declare your component in those files
And then you add it to a really page in python

**Comment by yaten2302** [comment]
Hey @FredLL-Avaiga, I'm creating a draft PR to show the changes that I've made till now. It's not complete, but I just wanted to confirm if I'm doing everything right or do I need to change something. Could you please review the draft PR and then guide if there's some mistake?
Also, I wanted to ask that, do I've to push the `package-lock.json` file as well? It was created when I was installing [Taipy GUI Front-end](https://github.com/Avaiga/taipy/blob/develop/frontend/taipy-gui/README.md)<br>
![image](https://github.com/Avaiga/taipy/assets/129659514/a4069473-f54d-4255-8484-51302438fe6a)

**Comment by FredLL-Avaiga** [comment]
I will, you just have to add me as a reviewer. 
Don't bother with the package-lock.json

**Comment by yaten2302** [comment]
@FredLL-Avaiga, actually I'm facing an issue while pushing my code, could you please help me out with this. I've pushed the changes, but I'm not able to see them to create a PR. Here's the screenshots:<br>
![image](https://github.com/Avaiga/taipy/assets/129659514/91be219d-df9b-4c2c-ba5e-9757ab764eb0)
<br>
![image](https://github.com/Avaiga/taipy/assets/129659514/d989623b-3361-4411-a459-1f3b98183974)

**Comment by yaten2302** [comment]
Hey @FredLL-Avaiga, I guess there's some issue while creating a PR, I'll just delete my fork and create a new one and then submit the draft PR. Apologies for inconvenience🙏🏼

**Comment by yaten2302** [comment]
Hey @FredLL-Avaiga, I've created a [draft PR](https://github.com/Avaiga/taipy/pull/1294) for this issue, could you please have a look at the `ProgressBar.tsx` if I'm doing it right or do I've to change something in it?

**Comment by yaten2302** [comment]
Hey @FredLL-Avaiga, @FabienLelaquais, really sorry for the delay. I've now created a new PR for the changes which were suggested and also added the complete functionality as discussed. The progress bar now has multiple options including - linear progress bar, show progress, and number of progress bars to be shown. If any changes are required, kindly let me know, I'll make the required changes ASAP 👍🏼
Also, if this PR looks fine, may I start working on the tests?
