### ISSUE TITLE
Add alert visual element

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#693]
**What would that feature address**
Add an alert visual element to Taipy. It is not a notification but a visual element in the application that doesn't disappear. [example](https://mui.com/material-ui/react-alert/)

![image](https://github.com/Avaiga/taipy-gui/assets/98709993/ef9b883a-8189-427c-8739-160b04d18c20)

Parent issue: #436 

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Create related issue in taipy-doc for documentation and Release Notes
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it
- [ ] Ensure any change is well documented

**Comment by meetpatel0963** [comment]
Hello, I am new to taipy and I would love to contribute to this issue. Is it still open?

**Comment by FlorianJacta** [comment]
This is still open. @FabienLelaquais @FredLL-Avaiga ?

**Comment by FlorianJacta** [comment]
Any update @FredLL-Avaiga @FabienLelaquais ?

**Comment by FredLL-Avaiga** [comment]
Not yet, can you set up a meeting so that we can discuss what, how and when?

**Comment by FlorianJacta** [comment]
@FredLL-Avaiga proposes that it be first developed as an extension to be in the product afterwards. What do you think @FabienLelaquais ?

**Comment by Paulie-Aditya** [comment]
can I be assigned this issue?
Follow-up: how to replicate this issue

**Comment by FlorianJacta** [comment]
This is not an issue to replicate. This is a new feature to add to Taipy. The ticket is about adding a new visual element called alert to Taipy

**Comment by jrobinAV** [comment]
@Paulie-Aditya 
If you are still interested, I can assign the issue to you. 

Thank you for your contribution.

**Comment by Paulie-Aditya** [comment]
Thanks, could you kindly help me out by answering the following questions briefly:
Where and when should this visual element come up?
Could you guide me as to how to work upon this, Should I build it with plain js/react or some other framework you guys are comfortable with?
Lastly, if typing out all this seems hectic, could we connect for a short call and discuss all of it? I promise I won't take up a lot of your time.

**Comment by jrobinAV** [comment]
Hi @Paulie-Aditya ,

For front-end matters, the key guys to answer your questions are @FredLL-Avaiga @FabienLelaquais @namnguyen20999 @dinhlongviolin1.

**Comment by Paulie-Aditya** [comment]
Hey @FredLL-Avaiga @FabienLelaquais @namnguyen20999 @dinhlongviolin1 , kindly help me out by answering the above questions.

Thanks for your time.

**Comment by namnguyen20999** [comment]
Hi @Paulie-Aditya,

1. All components are located in the **`taipy/frontend/taipy-gui/src/components/Taipy`** directory. Please build them using React and MUI. Once done, run **`npm run build:dev`**.
2. After completing your component, add it to both the **`factory.py`** and **`viselements.json`** files. You could take a look into some of our components to see how to add it into those file, take **`Indicator`** component for example 😉
3. Once the above steps are complete, create a Python script that utilizes your component and the feature you're working on. Run the script and debug your component in the browser.

For examples of simple scripts, refer to the **`doc/gui/examples`** directory.

Let me know if you'd like any further tweaks!

**Comment by Paulie-Aditya** [comment]
Thanks for the help! Will work on it and definitely reach back to you with updates!

**Comment by Rishi-0007** [comment]
@quest-bot embark

**Comment by Rishi-0007** [comment]
### Help needed

@FredLL-Avaiga @FabienLelaquais @namnguyen20999 @dinhlongviolin1 

I have created a custom `AlertComponent` in React and made changes to register it in the `Taipy` environment. However, when running the component, I get the error: 

```
<|INVALID SYNTAX - Control is 'alert'|>
```

Additionally, when testing with a Python script, I get a warning about the `alert` control being unrecognized.

### Files and Changes

#### `AlertComponent.tsx`:

```typescript
import React from "react";
import Alert from "@mui/material/Alert";
import { TaipyBaseProps } from "./utils";

interface AlertComponentProps extends TaipyBaseProps {
    severity?: "error" | "warning" | "info" | "success";
    message: string;
}

const AlertComponent = (props: AlertComponentProps) => {
    const { severity = "info", message } = props;
    return (
        <Alert severity={severity} id={props.id} className={props.className}>
            {message}
        </Alert>
    );
};

export default AlertComponent;
```

#### Changes in `factory.py`:

```python
"alert": lambda gui, control_type, attrs: _Builder(
    gui=gui,
    control_type=control_type,
    element_name="AlertComponent",  
    attributes=attrs,
)
.set_value_and_default(with_update=False)
.set_attributes(
    [
        ("severity", PropertyType.string),
        ("message", PropertyType.dynamic_string),
    ]
),
```

#### `viselements.json`:

```json
[
    "alert",
    {
        "inherits": ["shared"],
        "properties": [
            {
                "name": "severity",
                "default_property": true,
                "type": "dynamic(str)",
                "default_value": "\"info\"",
                "doc": "Defines the severity level of the alert. Valid values: \"error\", \"warning\", \"info\", \"success\"."
            },
            {
                "name": "message",
                "type": "dynamic(str)",
                "default_value": "\"\"",
                "doc": "The message displayed in the alert."
            },
            {
                "name": "variant",
                "type": "str",
                "default_value": "\"filled\"",
                "doc": "Defines the variant of the alert. Can be \"filled\", \"outlined\", or \"standard\"."
            }
        ]
    }
]
```

#### `test.py`:

```python
from taipy.gui import Gui

severity_level = "info"
alert_message = "This is an alert message!"

Gui("""
# Testing Alert Component
<|{severity_level}|alert|message={alert_message}|>
""").run()
```

#### Screenshot of the Error:
![image](https://github.com/user-attachments/assets/ed07ab2b-b5a1-4029-95ea-a6e2fbdab28d)

**Comment by FredLL-Avaiga** [comment]
you need to add the default property name [here](https://github.com/Avaiga/taipy/blob/ba3505aaa206bc198006a948580975d33eb28798/taipy/gui/_renderers/factory.py#L32)

**Comment by FredLL-Avaiga** [comment]
I suppose message would be the default property ?
then it doesn't need to be declared in 
`.set_attributes(`

and `with_update` should be True as it is a dynamic property in `.set_value_and_default(with_update=True)`

you should look in other components to see how className is handled

**Comment by Rishi-0007** [comment]
@FredLL-Avaiga  

Made changes as mentioned but still error remains the same. Please Help!

```
<|INVALID SYNTAX - Control is 'alert'|>
```

### Files and Changes

#### `AlertComponent.tsx`:

```typescript
import React, { useCallback, useMemo } from "react";
import Alert from "@mui/material/Alert";
import { TaipyBaseProps } from "./utils";
import { useClassNames } from "../../utils/hooks";

interface AlertComponentProps extends TaipyBaseProps {
    severity?: "error" | "warning" | "info" | "success";
    message: string;
    variant?: "filled" | "outlined" | "standard";
}

const AlertComponent = (props: AlertComponentProps) => {
   
    const { severity = "info", message, variant = "filled" } = props;

    // Handle className using a custom hook, if applicable
    const className = useClassNames(props.libClassName, props.dynamicClassName, props.className);

    // Memoize the severity and message rendering to optimize performance
    const renderAlert = useCallback(() => {
        return (
            <Alert severity={severity} variant={variant} id={props.id} className={className}>
                {message}
            </Alert>
        );
    }, [severity, message, variant, className, props.id]);

    // Use useMemo to potentially optimize complex rendering, though here it's simple
    return useMemo(() => renderAlert(), [renderAlert]);
};

export default AlertComponent;

```

#### Changes in `factory.py`:

```python
 __CONTROL_DEFAULT_PROP_NAME = {
        "alert": "message",
}
 __CONTROL_BUILDERS = {
        "alert": lambda gui, control_type, attrs: _Builder(
            gui=gui,
            control_type=control_type,
            element_name="AlertComponent",  
            attributes=attrs,
        )
        .set_value_and_default(with_update=True)  # Enable dynamic updates for the default property (message)
        .set_attributes(
            [
                ("severity", PropertyType.string),  # Add severity as it's not the default property
            ]
        ),
}
```

#### `test.py`:

```python
from taipy.gui import Gui, Markdown

# Initialize the alert message and severity
alert_message = "This is an alert message!"
alert_severity = "info"

# Define the page with the custom alert component
page = Markdown(
    """
# Alert Component Test

## Current Alert:
<|{alert_message}|alert|severity={alert_severity}|>

### Update Alert Message:
<|{alert_message}|input|on_change=update_alert|>

### Update Alert Severity:
<|{alert_severity}|selector|lov={['error', 'warning', 'info', 'success']}|on_change=update_alert|>
"""
)

# Update the alert properties dynamically
def update_alert(state, var_name, value):
    if var_name == "alert_message":
        state.alert_message = value
    elif var_name == "alert_severity":
        state.alert_severity = value

# Run the GUI
if __name__ == "__main__":
    Gui(page).run(title="Test Alert Component")

```

#### Screenshot:
![image](https://github.com/user-attachments/assets/675f1b80-331a-4a0a-9724-df533d9f1719)

P.S. `npm run build:dev` compiles successfully.

**Comment by FredLL-Avaiga** [comment]
Why don't you create a branch and a PR?
Then we can discuss.

**Comment by Rishi-0007** [comment]
Hey @FredLL-Avaiga 

I've created a branch and opened a PR as suggested. This is my first time submitting a PR, so I kindly request your review. If I've made any mistakes, I would greatly appreciate your guidance and feedback. Apologies in advance for any errors!

Here’s the link to the PR:  
[https://github.com/Avaiga/taipy/pull/1975](https://github.com/Avaiga/taipy/pull/1975)

Thank you for your time!

**Comment by FredLL-Avaiga** [comment]
> Hey @FredLL-Avaiga 
> 
> I've created a branch and opened a PR as suggested. This is my first time submitting a PR, so I kindly request your review. If I've made any mistakes, I would greatly appreciate your guidance and feedback. Apologies in advance for any errors!
> 
> Here’s the link to the PR:  
> [https://github.com/Avaiga/taipy/pull/1975](https://github.com/Avaiga/taipy/pull/1975)
> 
> Thank you for your time!
> 

No problem
That's exactly the purpose of a PR
Purpose a base for discussion

**Comment by namnguyen20999** [comment]
@Rishi-0007, don’t forget to import your component into **`taipy/frontend/taipy-gui/src/components/Taipy/index.ts`**. After that, make sure to add the imported component to the object inside the getRegisteredComponents function. This make sure your component registered

**Comment by Rishi-0007** [comment]
Hi @namnguyen20999 ,

I've implemented the changes as suggested, including registering the `AlertComponent` in `index.ts` and modifying `test.py` to ensure dynamic behavior is tested. However, I'm still encountering the same issue with the control being unrecognized.

Here is the output when running the test:

```
python test-alert.py
[2024-10-09 03:28:39][Taipy][INFO]  * Server starting on http://127.0.0.1:5000
/usr/lib/python3.12/subprocess.py:1127: ResourceWarning: subprocess 326835 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
WARNING:root:
--- 1 warning(s) were found for page '/' in variable 'md' ---
 - Warning 1: Unrecognized control alert at line 5: "<|{alert_message}|alert|severity={alert_severity}|variant={alert_variant}|>".
--------------------------------------------------------------

alert_severity changed to: success
alert_severity changed to: success
^CKeyboardInterrupt
2024-10-08T21:58:55Z
Traceback (most recent call last):
  File "/home/rishi/taipy/frontend/taipy-gui/src/components/Taipy/test-alert.py", line 36, in <module>
    Gui(md).run()
  File "/home/rishi/taipy/venv/lib/python3.12/site-packages/taipy/gui/gui.py", line 2530, in run
    return self._server.run(
           ^^^^^^^^^^^^^^^^^
  File "/home/rishi/taipy/venv/lib/python3.12/site-packages/taipy/gui/server.py", line 319, in run
    self._ws.run(**run_config)
  File "/home/rishi/taipy/venv/lib/python3.12/site-packages/flask_socketio/__init__.py", line 718, in run
    self.wsgi_server.serve_forever()
  File "/home/rishi/taipy/venv/lib/python3.12/site-packages/gevent/baseserver.py", line 400, in serve_forever
    self._stop_event.wait()
  File "src/gevent/event.py", line 163, in gevent._gevent_cevent.Event.wait
  File "src/gevent/_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable.__wait_to_be_notified
  File "src/gevent/_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
KeyboardInterrupt
```

The main warning I'm receiving is:
```
--- 1 warning(s) were found for page '/' in variable 'md' ---
 - Warning 1: Unrecognized control alert at line 5: "<|{alert_message}|alert|severity={alert_severity}|variant={alert_variant}|>".
```

Despite the component being registered as per the previous instructions, the `alert` control is still not recognized. Could you please advise on what might be missing or misconfigured? I have also opened a PR [https://github.com/Avaiga/taipy/pull/1975](https://github.com/Avaiga/taipy/pull/1975)

Thank you for your time and assistance.

**Comment by namnguyen20999** [comment]
> Hi @namnguyen20999 ,
> 
> I've implemented the changes as suggested, including registering the `AlertComponent` in `index.ts` and modifying `test.py` to ensure dynamic behavior is tested. However, I'm still encountering the same issue with the control being unrecognized.
> 
> Here is the output when running the test:
> 
> ```
> python test-alert.py
> [2024-10-09 03:28:39][Taipy][INFO]  * Server starting on http://127.0.0.1:5000
> /usr/lib/python3.12/subprocess.py:1127: ResourceWarning: subprocess 326835 is still running
>   _warn("subprocess %s is still running" % self.pid,
> ResourceWarning: Enable tracemalloc to get the object allocation traceback
> WARNING:root:
> --- 1 warning(s) were found for page '/' in variable 'md' ---
>  - Warning 1: Unrecognized control alert at line 5: "<|{alert_message}|alert|severity={alert_severity}|variant={alert_variant}|>".
> --------------------------------------------------------------
> 
> alert_severity changed to: success
> alert_severity changed to: success
> ^CKeyboardInterrupt
> 2024-10-08T21:58:55Z
> Traceback (most recent call last):
>   File "/home/rishi/taipy/frontend/taipy-gui/src/components/Taipy/test-alert.py", line 36, in <module>
>     Gui(md).run()
>   File "/home/rishi/taipy/venv/lib/python3.12/site-packages/taipy/gui/gui.py", line 2530, in run
>     return self._server.run(
>            ^^^^^^^^^^^^^^^^^
>   File "/home/rishi/taipy/venv/lib/python3.12/site-packages/taipy/gui/server.py", line 319, in run
>     self._ws.run(**run_config)
>   File "/home/rishi/taipy/venv/lib/python3.12/site-packages/flask_socketio/__init__.py", line 718, in run
>     self.wsgi_server.serve_forever()
>   File "/home/rishi/taipy/venv/lib/python3.12/site-packages/gevent/baseserver.py", line 400, in serve_forever
>     self._stop_event.wait()
>   File "src/gevent/event.py", line 163, in gevent._gevent_cevent.Event.wait
>   File "src/gevent/_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
>   File "src/gevent/_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
>   File "src/gevent/_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
>   File "src/gevent/_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable.__wait_to_be_notified
>   File "src/gevent/_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
>   File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
>   File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
>   File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
> KeyboardInterrupt
> ```
> 
> The main warning I'm receiving is:
> 
> ```
> --- 1 warning(s) were found for page '/' in variable 'md' ---
>  - Warning 1: Unrecognized control alert at line 5: "<|{alert_message}|alert|severity={alert_severity}|variant={alert_variant}|>".
> ```
> 
> Despite the component being registered as per the previous instructions, the `alert` control is still not recognized. Could you please advise on what might be missing or misconfigured? I have also opened a PR #1975
> 
> Thank you for your time and assistance.

Can you please push your latest commit to your PR so that we could take a look into it ? 🧐

**Comment by Rishi-0007** [comment]
> > Hi @namnguyen20999 ,
> > I've implemented the changes as suggested, including registering the `AlertComponent` in `index.ts` and modifying `test.py` to ensure dynamic behavior is tested. However, I'm still encountering the same issue with the control being unrecognized.
> > Here is the output when running the test:
> > ```
> > python test-alert.py
> > [2024-10-09 03:28:39][Taipy][INFO]  * Server starting on http://127.0.0.1:5000
> > /usr/lib/python3.12/subprocess.py:1127: ResourceWarning: subprocess 326835 is still running
> >   _warn("subprocess %s is still running" % self.pid,
> > ResourceWarning: Enable tracemalloc to get the object allocation traceback
> > WARNING:root:
> > --- 1 warning(s) were found for page '/' in variable 'md' ---
> >  - Warning 1: Unrecognized control alert at line 5: "<|{alert_message}|alert|severity={alert_severity}|variant={alert_variant}|>".
> > --------------------------------------------------------------
> > 
> > alert_severity changed to: success
> > alert_severity changed to: success
> > ^CKeyboardInterrupt
> > 2024-10-08T21:58:55Z
> > Traceback (most recent call last):
> >   File "/home/rishi/taipy/frontend/taipy-gui/src/components/Taipy/test-alert.py", line 36, in <module>
> >     Gui(md).run()
> >   File "/home/rishi/taipy/venv/lib/python3.12/site-packages/taipy/gui/gui.py", line 2530, in run
> >     return self._server.run(
> >            ^^^^^^^^^^^^^^^^^
> >   File "/home/rishi/taipy/venv/lib/python3.12/site-packages/taipy/gui/server.py", line 319, in run
> >     self._ws.run(**run_config)
> >   File "/home/rishi/taipy/venv/lib/python3.12/site-packages/flask_socketio/__init__.py", line 718, in run
> >     self.wsgi_server.serve_forever()
> >   File "/home/rishi/taipy/venv/lib/python3.12/site-packages/gevent/baseserver.py", line 400, in serve_forever
> >     self._stop_event.wait()
> >   File "src/gevent/event.py", line 163, in gevent._gevent_cevent.Event.wait
> >   File "src/gevent/_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
> >   File "src/gevent/_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
> >   File "src/gevent/_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
> >   File "src/gevent/_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable.__wait_to_be_notified
> >   File "src/gevent/_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
> >   File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
> >   File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
> >   File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
> > KeyboardInterrupt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The main warning I'm receiving is:
> > ```
> > --- 1 warning(s) were found for page '/' in variable 'md' ---
> >  - Warning 1: Unrecognized control alert at line 5: "<|{alert_message}|alert|severity={alert_severity}|variant={alert_variant}|>".
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Despite the component being registered as per the previous instructions, the `alert` control is still not recognized. Could you please advise on what might be missing or misconfigured? I have also opened a PR #1975
> > Thank you for your time and assistance.
> 
> Can you please push your latest commit to your PR so that we could take a look into it ? 

Done please check it [here](https://github.com/Avaiga/taipy/pull/1975/commits). Thank you for your time and assistance.

**Comment by Rishi-0007** [comment]
Hi @FredLL-Avaiga @namnguyen20999 ,

I've followed the steps for adding the `Notification` component, but I'm still encountering an issue where the component is not recognized. The error shows: 

#### `test`
```python
from taipy.gui import Gui

# Define the dynamic properties for the notification
alert_message = "This is a dynamic notification!"
alert_severity = "info"
alert_variant = "filled"

# Define the page with the notification component
page = """
<|{alert_message}|alert|severity={alert_severity}|variant={alert_variant}|>
"""

if __name__ == "__main__":
    Gui(page).run(title="Notification Test")
```
#### output:

`Unrecognized control alert at line 2: "<|{alert_message}|alert|severity={alert_severity}|variant={alert_variant}|>"`.

![image](https://github.com/user-attachments/assets/4b11dc43-5fc4-45b8-b77a-6252016a8630)

Despite trying multiple fixes, the issue persists. Could you please help me troubleshoot this?

Thank you!

---

Let me know if you'd like to adjust anything further!

**Comment by FredLL-Avaiga** [comment]
when your building the frontend bundle do you have any error in the log (scroll up to be sure) ?
