### ISSUE TITLE
Filter ON - new record does not show up

### ISSUE THREAD

**Issue by hudzik** [Avaiga/taipy#705]
Hi,
can you add a total number of records in table?
A filter sign on a filtered column?

Or show empty record ready to enter new information. When user wants to save it and does not fit the filter, than a warning - it will disappear after saving.

https://github.com/Avaiga/taipy/assets/32644626/b8ceb171-b1b0-4653-b4bb-263ccd250406

**Comment by FlorianJacta** [comment]
This is an interesting remark. I don't know what is the optimal way to solve this. Maybe letting the developer create its own solution is the better solution. When adding a new line, you could notify in the *on_add* function that a row has been created:

```python
from taipy.gui import notify

def add_a_row(state, var_name, payload):
    empty_row = pd.DataFrame([[None for _ in state.food_df.columns]], columns=state.food_df.columns)
    state.food_df = pd.concat([empty_row, state.food_df], axis=0, ignore_index=True)

    notify(state, "S", f"Added a new row.")
```


What do you think? @FabienLelaquais @FredLL-Avaiga

**Comment by FredLL-Avaiga** [comment]
In the develop version there is a badge on the filter icon indicating how many filters are applied
I know this doesn't answer the question but at least, there *is* a visual feedback about filters

**Comment by FabienLelaquais** [comment]
... may be we want to add something to show any many rows are filtered out... (hover on the filter?)
Not that obvious

**Comment by FredLL-Avaiga** [comment]
tooltip on filter icon shows the numbers of rows not displayed
