### ISSUE TITLE
Scenario Management Visual Elements are unintuitive

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#709]
This feedback comes from a one-hour beta testing session of scenario management using this tutorial as reference:
https://docs.taipy.io/en/develop/knowledge_base/tutorials/scenario_management_overview/

This issue is a discussion, it probably duplicates other issues and should be split into the features we want to implement. This issue is important for the positioning of Scenario Management: if we want to advertise Scenario Management visual elements as products for end-users they should be very user-friendly.

The Beta Tester found the Scenario Management Visual Elements not user-friendly for multiple reasons:

1. The "execute scenario" button is too small and unclear:
![image](https://github.com/Avaiga/taipy/assets/62465003/9aa63d51-bb05-4d3c-92a1-676853cac0e5)

2. There is no notification of progress when you execute a scenario. If your scenario lasts 2 hours, you have no clear indication of which task is being executed. The beta tester suggested highlighting the task that is being run in the displayed dag:
![image](https://github.com/Avaiga/taipy/assets/62465003/fd9a6ada-8e53-472a-9752-d60c63c66d3a)
Something similar to this:
![flow_example](https://github.com/Avaiga/taipy/assets/62465003/864bee1a-19b8-4336-ba10-7a7af8a7e937)

3. The output data is not easily accessible, being the third tab of the data node viewer:
![image](https://github.com/Avaiga/taipy/assets/62465003/7ce6d8b3-72c5-46c4-ab26-ba91910ecd75)

4. When the scenario tutorial was done, the user created a new scenario here and inputted a date:
![image](https://github.com/Avaiga/taipy/assets/62465003/b470826a-ea3d-4798-8ac5-f80db3400d3d)
He was then frustrated to find this error
![image](https://github.com/Avaiga/taipy/assets/62465003/2e018e83-b271-48e7-9c36-f46859aae2a2)
Why can he not submit his scenario? The notification should be more clear.

**Comment by FabienLelaquais** [comment]
@AlexandreSajus I encourage you to reach @AAstridVH and organize some short meeting where we could decide how to approach this. There are many topics in there, to be addressed with different means.
Does it make sense?

**Comment by AlexandreSajus** [comment]
Sure, I'll ask her and schedule a meeting

**Comment by AlexandreSajus** [comment]
Closing this issue to separate it into 3 separate issues:
#744 
#745 
#746
