### ISSUE TITLE
Atrribute,name and Input related error even after successful installation of Taipy

### ISSUE THREAD

**Issue by Annapurna0311** [Avaiga/taipy#730]
*Description*
While installing the open-source full-stack Python library, Taipy, several bugs and related issues were encountered. Upon successfully installing Taipy, an error message occurred during the execution of the pip command.

Even after successful deployment of the web, there were some fluctuations in the website with randomly throwing the attribute, name and inputs error even with the correct output.
But sometimes, the reinstalling made it little bit executable on the localhost server through the environment.
*How to reproduce*

```python
import pickle
import numpy as np
import pandas as pd
# import sklearn
from taipy.gui import Gui, Markdown

# Load the model
model = pickle.load(open('classifier.pkl', 'rb'))

def init_scope():
    return {"input_data": 0, "prediction": None}
def predict(state):
    input_data = state['input_data']
    input_data = np.array([input_data])
    prediction = model.predict(input_data)
    state['prediction'] = prediction[0]
state = init_scope()

page = """
# Predict using ML Model
Enter a number:

<|{state.input_data}|number|>

<|Submit|button|on_action=predict|>

<|{state.prediction}|text|>
"""

def on_action(action):
    if action == "predict":
        predict(state)

Gui(page=page).run()
```

- And/or Taipy GUI Markdown or HTML files

*Expected behavior*
The library should provide consistent and intuitive APIs (Application Programming Interfaces) to interact with its features. This consistency makes it easier for developers to use the library effectively.
*Screenshots*
![1](https://github.com/Avaiga/taipy/assets/146976500/a794bd4c-8a83-41ca-bd80-e9bf13c3bd7b)

*Runtime environment*
Please specify relevant indications.
 - Taipy branh
 - OS: Windows 64-bit operating system
 - Browser: Chrome, Edge

*Acceptance Criteria*
-  Ensure new code is unit tested, and check code coverage is at least 90%

**Comment by FlorianJacta** [comment]
I have rearranged a bit to solve your different issues. Some key points:

- There should never be `state` in the Markdown.
- There should never be a `state = ...` in the code. Taipy handles the *state* for you. This is a collection of every variable used in the application. To access or read variables, you should use `state.variable_name` / `state.variable_name =`

```python
import pickle
import numpy as np
import pandas as pd
# import sklearn
from taipy.gui import Gui, Markdown

# Load the model
model = pickle.load(open('classifier.pkl', 'rb'))


def predict(state):
    input_data = state.input_data
    input_data = np.array([input_data])
    prediction = model.predict(input_data)
    state.prediction = prediction[0]

input_data = 0
prediction = None

page = """
# Predict using ML Model
Enter a number:

<|{input_data}|number|>

<|Submit|button|on_action=predict|>

<|{prediction}|text|>
"""

Gui(page=page).run()
```

Do you think this fixes your problem? Here is a tutorial on how to use the [GUI](https://docs.taipy.io/en/latest/knowledge_base/tutorials/understanding_gui/).

**Comment by Annapurna0311** [comment]
The error is still not resolved. Now, I tried to again install the taipy along with reinstalling the pip to upgrade it and ran the same code. But it's indicating the that this error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyarrow. 
After that again I tried to reinstall both pyarrow and taipy but nothing turned well. Might be there is  a problem with the dependencies because all the libraries are upgraded.

**Comment by FlorianJacta** [comment]
Create a new environment with a Python version between 3.8 and 3.11 and `pip install taipy`. There are conflicts in dependencies with *pyarrow*, as you mentioned. This will be fixed in the next Taipy release, which will be out in a month.

**Comment by Annapurna0311** [comment]
Yeah, I did the same but the issue is still not resolved. I tried upgrading the version of python to 3.12.1 and on the command prompt pip install taipy echoed the same error of pyarrow. Please add this issue under improvement or under the updation of taipy section, as this issue hasn't been reported till now untill the next release and for the developers who are beginners to taipy can get to know the conflict in advance.

**Comment by FlorianJacta** [comment]
A warning will be put on the documentation for this issue

**Comment by Annapurna0311** [comment]
Thank you sir this will help every folk new to Taipy library.
