### ISSUE TITLE
BUG- Wrong pip Symbol used in Documentation

### ISSUE THREAD

**Issue by Makuls** [Avaiga/taipy#731]
***Description***
There is a bug which i found while going through the documentation of taipy on the official website. The documentation shows that for Installation with pip (https://docs.taipy.io/en/latest/getting_started/#installation-with-pip)
Prerequisites: Ensure you have Python (version 3.8 or higher) and [pip](https://pip.pypa.io/)installed.
Installation Command: Run the following in your terminal or command prompt: $ pip install taipy.

*How to reproduce*
$ pip install taipy.

*Expected behavior*
Here it is shown that we have to use the $ pip, but when i performed it on many platforms and ide such as collab , juypter notebook , vs code and as taipy being a tool for data science we uses the above notebook only for collaboration, the code was showing the error of SyntaxError: invalid syntax.

In Order to atleast initiate the installation we have to use ! syntax instead of $ in the code. After using the ! Syntax we get the error of blinker. Which has to be solved separately in order to completely install taipy.

![Screenshot 2024-01-20 231913](https://github.com/Avaiga/taipy/assets/139635989/8fcd4913-afc7-45df-97c0-6bb7cf1d30a3)
![Screenshot 2024-01-20 232008](https://github.com/Avaiga/taipy/assets/139635989/777ff991-74d1-4451-926c-5c4aba39192b)

Runtime Environment
Software Used - Google Colab , Juypter notebook

Os- Windows 11
Browser - Chrome

**Comment by cyberholics** [comment]
Hi, the $ symbol shows the code is meant to be written on the command line. In the command line or terminal, the dollar sign ($) is often used to represent the command prompt or shell prompt. It's a symbol indicating that the text following it is a command to be entered in the command-line interface.

**Comment by Makuls** [comment]
> Hi, the $ symbol shows the code is meant to be written on the command line. In the command line or terminal, the dollar sign ($) is often used to represent the command prompt or shell prompt. It's a symbol indicating that the text following it is a command to be entered in the command-line interface.

**Comment by Makuls** [comment]
> Hi, the $ symbol shows the code is meant to be written on the command line. In the command line or terminal, the dollar sign ($) is often used to represent the command prompt or shell prompt. It's a symbol indicating that the text following it is a command to be entered in the command-line interface.

In the documentation for the taipy website it has been written that this tool is supposed to be for the data scientist level and being a student of data science we are mandate to work on notebooks such as jupyter and Google Colab and there it is not working as per my issue description. I used the same code to run on vs code as well and there also the issue remains the same with the syntax. If it was as you say for the terminal then i was getting the version error sometimes, i would just request you to kindly update the existing documentation with the instructions that how to do that for Google Colab and jupyter notebook as well.
Thank you

**Comment by cyberholics** [comment]
As a data scientist, it's crucial to be familiar with using the command line. The documentation assumes that you understand how to use the command line. To enhance the documentation, consider adding a prerequisite: familiarity with the command line. Installing libraries and packages is more straightforward using the command line. Moreover, if you intend to implement environment management, you will still need to use the command line.

**Comment by muskansingh0712** [comment]
> As a data scientist, it's crucial to be familiar with using the command line. The documentation assumes that you understand how to use the command line. To enhance the documentation, consider adding a prerequisite: familiarity with the command line. Installing libraries and packages is more straightforward using the command line. Moreover, if you intend to implement environment management, you will still need to use the command line.

Yeah, I also agree that Taipy should add the pre-requisite of familiarity with command line in their documentation as it is not present correctly so that new users can also use it.

**Comment by FlorianJacta** [comment]
Thank you for your feedback! There is an entire Installation page [here](https://docs.taipy.io/en/latest/installation/). However, it is true that we could improve our documentation to make it easier to get started with Taipy. We could maybe erase the `$` and avoid confusion @Makuls. What do you think?

The goal of the Getting Started is to be able to get started quickly with Taipy and also troubleshoot common questions

**Comment by Makuls** [comment]
> Thank you for your feedback! There is an entire Installation page [here](https://docs.taipy.io/en/latest/installation/). However, it is true that we could improve our documentation to make it easier to get started with Taipy. We could maybe erase the `$` and avoid confusion @Makuls. What do you think?
> 
> The goal of the Getting Started is to be able to get started quickly with Taipy and also troubleshoot common questions

Thank You Sir for the response . Sir i do think that this problem is faced by not only me but many of the peers, because as a beginner we all work on Different types of Data Science Notebooks colab , jupyter etc. and at that time implementing the codes with $ really become a challenge for us so i do think that if you could add some lines in the documentation that if we have to work on colab or jupyter notebook then don't run these $ codes in your runtime , as it would really help in streamlining the Getting Started process to enhance user experience and make Taipy more accessible.
If there is any other way i could help you it would be really my honor.
Thank You

**Comment by FlorianJacta** [comment]
Thank you for your response! This is really great to have your feedback on this
