### ISSUE TITLE
Error-cannot uninstall blinker at the time of pip install taipy

### ISSUE THREAD

**Issue by muskansingh0712** [Avaiga/taipy#734]
**Description**
The time we use command **`!pip install taipy`**, after all the processing of necessary packages at last we get an error stating that:

**ERROR: Cannot uninstall 'blinker'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.**

**Acceptance Criteria**
To correct this particular issue, after hitting and trial I came up with the thing of using the next command as:

**`!pip install --ignore-installed taipy`**

After running this code I got the following message and after that I got to Restart session 

**WARNING: Upgrading ipython, ipykernel, tornado, prompt-toolkit or pyzmq can cause your runtime to repeatedly crash or behave in unexpected ways and is not recommended. If your runtime won't connect or execute code, you can reset it with "Disconnect and delete runtime" from the "Runtime" menu.
WARNING: The following packages were previously imported in this runtime:
  [_distutils_hack,certifi,dateutil,numpy,pkg_resources,psutil,setuptools,six,tornado]
You must restart the runtime in order to use newly installed versions.**

### Issue in pip install taipy 
![pip install taipy](https://github.com/Avaiga/taipy/assets/89463469/2aaa836b-f4d7-4cdc-9257-6a5e5176fad1)

### Correct format of pip install taipy
![correct pip install taipy](https://github.com/Avaiga/taipy/assets/89463469/7ac621f6-c59e-4be8-b6d0-f0a6ad6764a7)
![correct pip install taipy 2](https://github.com/Avaiga/taipy/assets/89463469/54f0e864-1ccf-4716-b064-46ab66c2aa8a)

**Comment by FlorianJacta** [comment]
Thank you for your issue @muskansingh0712. Here is a related issue: https://github.com/Avaiga/taipy/issues/365 
An issue was created on the documentation to solve it: https://github.com/Avaiga/taipy-doc/issues/693

Do you think the last issue will solve yours?

**Comment by muskansingh0712** [comment]
> Thank you for your issue @muskansingh0712. Here is a related issue: #365 An issue was created on the documentation to solve it: [Avaiga/taipy-doc#693](https://github.com/Avaiga/taipy-doc/issues/693)
> 
> Do you think the last issue will solve yours?

Sir, the issue that was resolved earlier had different Blinker version but sir my issue is regarding the latest blinker version i.e 
 Blinker 1.7.0 Kindly acknowledge this issue for the current version.

**Comment by FlorianJacta** [comment]
Let's create what has to be done for Colab on the Getting Started and Installation page

**Comment by muskansingh0712** [comment]
Sure sir it would be really great to add a new installation and running process for Google Colab, as it would really help all the future coders on working with Taipy.

**Comment by muskansingh0712** [comment]
> Let's create what has to be done for Colab on the Getting Started and Installation page

I would suggest that we should add a new section for Installation and Running Process for Google Colab, in Taipy Documentation
