### ISSUE TITLE
Update zenhub workflow and uniformize Labels

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#74]
Reference for labels : 

https://opensource.creativecommons.org/contributing-code/repo-labels/

**Comment by trgiangdo** [comment]
@jrobinAV Can we add a new tag for the versioning system? "Version control" for example.

**Comment by jrobinAV** [comment]
Here is the first proposal: 
https://github.com/Avaiga/taipy-airflow/labels

Please challenge, append, comment...

**Comment by trgiangdo** [comment]
I'm not a fan of **Goal: bug fix** so much.

I'm thinking of using **Type: ...* prefix, something like:
- Type: bug
- Type: refactoring
- Type: testing

Also, we can add some status to the issue as suggested in https://github.com/abdonrd/github-labels in case there will be some duplicated bug report, or wrong bug, ...

Btw, love the icons.

**Comment by jrobinAV** [comment]
So you mean you propose to replace `Goal` prefix by `Type` prefix ?

I used this [link ](https://opensource.creativecommons.org/contributing-code/repo-labels/) provided by Joao as a reference. I am good with renaming goal into type.

**Comment by jrobinAV** [comment]
Regarding the status (which is also a proposal from the [source](https://opensource.creativecommons.org/contributing-code/repo-labels/) I used) label, I have the feeling it is not useful for now. 
For me, each status label corresponds to either to an action or to a 'talk' label, like 
- `duplicated bug report` -> Close the ticket with a comment referring to the other ticket.
- `confirmed `-> Comment the ticket with more details and move it to the appropriate column.
- 'can't reproduce' -> Comment the ticket, asking the author for more details, and move it to the appropriate column or use a 'talk: question' label.
- ...

What do you think ? Do I miss a case where we need statuses ?

**Comment by trgiangdo** [comment]
As I see it, the status labels are mostly useful for contributor's issue.
So yes, I agree. We can response directly in the issue. Not a big deal tbh.

However, for the `Status: Blocked`, it can be useful when the issue is being blocked, and we can not work on that, but it should be working on in the future.

**Comment by jrobinAV** [comment]
yes you are right lets add a blocked status.

**Comment by florian-vuillemot** [comment]
Backend, frontend, cloud, studio for labelling on the taipy repository ?
Performance ?

**Comment by jrobinAV** [comment]
I updated the labels according to your remarks.

If there are no other remarks, I propose trying to apply them.
