### ISSUE TITLE
Make "Submit Scenario" Button larger and more intuitive

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#744]
As discussed and reported by a user, the "Submit Scenario" button on the scenario visual element is too small and unintuitive:
![image](https://github.com/Avaiga/taipy/assets/62465003/82e6444d-591a-4b0c-bde4-6a650c298bc6)

Make it larger and it should display the text "Submit Scenario" when there is enough space

**Comment by jrobinAV** [comment]
After discussion, @AAstridVH is going to propose some mockup to improve the UX.

**Comment by FredLL-Avaiga** [comment]
Label added to submit button in #292

**Comment by ioannastantzou** [comment]
Hello! I would like to work on this issue! Could you please assign me on it? thank you

**Comment by AlexandreSajus** [comment]
@ioannastantzou Our bad, this issue is fixed. We just forgot to close it:
![image](https://github.com/Avaiga/taipy/assets/62465003/aa91b348-f7f6-41e3-8f77-5169b6d6461b)
