### ISSUE TITLE
"Cannot submit scenario" in scenario visual element without explanation

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#746]
The scenario visual element can display a grey send icon with "Cannot submit scenario" without an explanation:
![image](https://github.com/Avaiga/taipy/assets/62465003/86d0c990-0894-4c25-9ea0-d78a66428668)

This bug gets triggered in the [Scenario Management Overview](https://docs.taipy.io/en/develop/knowledge_base/tutorials/scenario_management_overview/) tutorial when the user creates a new scenario and tries to run it

**How to reproduce:**

1. Use the code provided in the Scenario Management Overview tutorial:

```python
from taipy import Config
import taipy as tp
import pandas as pd
import datetime as dt


data = pd.read_csv("https://raw.githubusercontent.com/Avaiga/taipy-getting-started-core/develop/src/daily-min-temperatures.csv")


# Normal function used by Taipy
def predict(historical_temperature: pd.DataFrame, date_to_forecast: str) -> float:
    print(f"Running baseline...")
    historical_temperature['Date'] = pd.to_datetime(historical_temperature['Date'])
    historical_same_day = historical_temperature.loc[
        (historical_temperature['Date'].dt.day == date_to_forecast.day) &
        (historical_temperature['Date'].dt.month == date_to_forecast.month)
    ]
    return historical_same_day['Temp'].mean()

# Configuration of Data Nodes
historical_temperature_cfg = Config.configure_data_node("historical_temperature")
date_to_forecast_cfg = Config.configure_data_node("date_to_forecast")
predictions_cfg = Config.configure_data_node("predictions")

# Configuration of tasks
predictions_cfg = Config.configure_task("predict",
                                        predict,
                                        [historical_temperature_cfg, date_to_forecast_cfg],
                                        predictions_cfg)

# Configuration of scenario
scenario_cfg = Config.configure_scenario(id="my_scenario", task_configs=[predictions_cfg])

Config.export('config.toml')

if __name__ == '__main__':
    # Run of the Core
    tp.Core().run()

    # Creation of the scenario and execution
    scenario = tp.create_scenario(scenario_cfg)
    scenario.historical_temperature.write(data)
    scenario.date_to_forecast.write(dt.datetime.now())
    tp.submit(scenario)

    print("Value at the end of task", scenario.predictions.read())

    def save(state):
        state.scenario.historical_temperature.write(data)
        state.scenario.date_to_forecast.write(state.date)
        tp.gui.notify(state, "s", "Saved! Ready to submit")

    date = None
    scenario_md = """
<|{scenario}|scenario_selector|>

Put a Date
<|{date}|date|on_change=save|active={scenario}|>

Run the scenario
<|{scenario}|scenario|>
<|{scenario}|scenario_dag|>

View all the information on your prediction here
<|{scenario.predictions if scenario else None}|data_node|>
"""

    tp.Gui(scenario_md).run()
```

2. Run the app and create a new scenario
![image](https://github.com/Avaiga/taipy/assets/62465003/2c0a681c-dec6-4a5f-989f-3685f3228f83)

3. The scenario visual element won't let you run the new scenario
![image](https://github.com/Avaiga/taipy/assets/62465003/34316358-4753-4547-823e-9f83429f2912)

**Comment by jrobinAV** [comment]
Today, the `is_submitable` taipy API called with a scenario or a sequence returns a simple boolean value. We can imagine returning a reason as well.

**Comment by jrobinAV** [comment]
Two missing pieces at this stage: 
- The submit button should be dynamic and refreshed every time the `is_submittable` function changes value.
- The scenario management should provide a reason and the scenario viz elmt should be able to display it.

**Comment by jrobinAV** [comment]
We will propose a design for a Reason object to be returned by `is_submittable` and a mechanism to publish appropriate events.
- The reason should behave like a boolean to not break APIs.
- The reason should have a str representation containing a reason in proper English to be displayed as mouse over tooltip in the Scenario viewer visual element.
- When the return value of `is_submittable` changes (for a scenario, a sequence, or a task), Taipy should publish the appropriate events without degrading the performances. Since the value does not persist and is dynamically computed. Multiple solutions have been discussed to be able to publish events.
    1. Everytime a data node becomes `ready-for-reading` Taipy must search for all parents who should be the subject of an event.
    2. Persist cross-references of all parent entities in data nodes so that when a data node becomes `ready-for-reading` we can easily retrieve them to publish events.
    3. Keeping an in-memory cache of the submittable entities indexed by data nodes that must be the subject of an event. New entries in the cache can be created every time the `is_submittable` is called. Question: When old entries should be deleted?

**Comment by FredLL-Avaiga** [comment]
This has been fixed on the UI side while integrating the necessary changes in visual elements for supporting is_submittable(): Reason!
[PR](https://github.com/Avaiga/taipy/pull/1307)
