### ISSUE TITLE
Support for file upload in JavaScript taipyApp

### ISSUE THREAD

**Issue by bengaid** [Avaiga/taipy#766]
JavaScript websocket API needs a function support enabling frontend to upload files, to be used in the standard Taipy way:

```python
from taipy import Gui
import pandas as pd

# Initialize the GUI and set the default DataFrame
gui = Gui()

df = pd.DataFrame()

# Callback function to load the CSV file
def load_csv(state):
    state.df = pd.read_csv(state.path)
    
path=""
```

**Comment by muskansingh0712** [comment]
I may be somewhere wrong but try using this particular code, I think so it may help you

**Comment by muskansingh0712** [comment]
I may be wrong but try this

**Comment by muskansingh0712** [comment]
I may be wrong but give a try to this 

```
from taipy import Gui
import pandas as pd

gui = Gui()

df = pd.DataFrame()

def load_csv(state):
    try:
        state.df = pd.read_csv(state.path)
        print("CSV file loaded successfully!")
    except Exception as e:
        print(f"Error loading CSV file: {e}")

def set_file_path(state, path):
    state.path = path

gui.add_button("Load CSV", load_csv)

gui.add_file_input("Select CSV file", key="path", change=set_file_path)

gui.run()
```

**Comment by bengaid** [comment]
> I may be wrong but give a try to this
> 
> ```
> from taipy import Gui
> import pandas as pd
> 
> gui = Gui()
> 
> df = pd.DataFrame()
> 
> def load_csv(state):
>     try:
>         state.df = pd.read_csv(state.path)
>         print("CSV file loaded successfully!")
>     except Exception as e:
>         print(f"Error loading CSV file: {e}")
> 
> def set_file_path(state, path):
>     state.path = path
> 
> gui.add_button("Load CSV", load_csv)
> 
> gui.add_file_input("Select CSV file", key="path", change=set_file_path)
> 
> gui.run()
> ```

Thanks for help @muskansingh0712, but my request was for more adavanced API. Thanks anyway
