### ISSUE TITLE
BUG-Slider multi-selection is broken when running as root

### ISSUE THREAD

**Issue by gbritoda** [Avaiga/taipy#781]
**Description**
While running TaiPy on WSL (Ubuntu), the Slider does not work with Multi Selection when it is run as root. Works fine with regular user

**How to reproduce**
That is my `main.py` file. Run it with
`python3 main.py`
then
`sudo python3 main.py`

The sliders also behave differently.
I've also seen a similar behaviour with the `menu` control but haven't documented it yet.

```python
from taipy.gui import Gui

selection = ["3","5"]

page = """
Multiple selection

<|{selection}|slider|lov=1;2;3;4;5;6;7;8;9;10|>

"""

Gui(page).run()
```
![image](https://github.com/Avaiga/taipy/assets/33906448/e4758ae1-ea19-44be-a977-36b55578eb40)
![image](https://github.com/Avaiga/taipy/assets/33906448/2b8d3c82-94eb-4956-a848-9523a00060aa)

**Expected behavior**
Expected to have the multiple sliders, even when running as root. But that doesn't seem to happen

**Runtime environment**
Taipy:
```
taipy @ git+https://github.com/Avaiga/taipy.git@7518e798d48289a9017faa93b10002361f946490
taipy-config==3.0.0
taipy-core==3.0.0
taipy-gui==3.0.0
taipy-rest==3.0.0
taipy-templates==3.0.0
```
WSL Versions:
` 5.15.133.1-microsoft-standard-WSL2`
```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
```

**Comment by FlorianJacta** [comment]
- Do you have any error messages in the Python console?

- Do you have any error messages in the client console (F12)?

![image](https://github.com/Avaiga/taipy/assets/98709993/6bdfd5f4-cccc-4b89-a291-2ffdbb0f2be7)


- Could you try setting *extended_status* to True in the *run()*?

**Comment by gbritoda** [comment]
Ran with `extended_status=True` but nothing is different.
python only shows this
```
[2024-01-31 09:33:37][Taipy][INFO]  * Server starting on http://127.0.0.1:5000
/usr/local/lib/python3.10/dist-packages/taipy/gui/data/data_scope.py:41: TaipyGuiWarning: Session id 20231026140919251428-0.5834406851162792 not found in data scope. Taipy will automatically create a scope for this session id but you may have to reload your page.
  _warn(
```

And the console is empty

![image](https://github.com/Avaiga/taipy/assets/33906448/c9ad3482-6147-44e3-8d0d-fdfd410d6e20)

**Comment by FlorianJacta** [comment]
`python` and `sudo python` may be 2 different Python executables. The Python system could have installed an older version of Taipy. Can you test it?

**Comment by gbritoda** [comment]
You are absolutely right!
When doing `sudo python3 -m pip freeze | grep taipy` I get taipy 2.4.0!

So I assume this feature is present only on 3.0.0?

Sorry about this, will close the ticket
