### ISSUE TITLE
Submit a scenario multiple times

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#782]
**Description** 
Can a user submit the scenario (or a sequence) multiple times, even when the previous one still needs to be completed?

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by trgiangdo** [comment]
First, I would imagine "multiple submissions" is the ability to call `taipy.submit(list_of_scenarios)`.
However, the description sounds like a `re-submit` method.

Second, I'm not sure to understand the use-case here. Why would a user want to re-submit a scenario when the previous submission is still on-going?

**Comment by jrobinAV** [comment]
> First, I would imagine "multiple submissions" is the ability to call `taipy.submit(list_of_scenarios)`. However, the description sounds like a `re-submit` method.
> 
> Second, I'm not sure to understand the use-case here. Why would a user want to re-submit a scenario when the previous submission is still on-going?

I renamed the issue to make it more clear.

@trgiangdo, your second question makes sense to me. It is actually the same as the one in the description. Can we imagine a use case where an end user wants to submit twice the same scenario?
If the answer is yes, we can close the ticket.
If the answer is no, since today, there is no mechanism to prevent submitting a scenario multiple times, do we want to prevent an end user from submitting a scenario again if the previous submission still needs to be finished? As a subsidiary question: Do we want to prevent an end user from submitting a scenario if one of its tasks still needs to be finished?

@FlorianJacta What do you think?

1. The scenario inputs might have changed. We still want to complete the first run, and right after submitting it again.
2. Some tasks or data nodes could have side effects. Submitting a scenario twice could for example trigger something intended on a third-party component.

**Comment by FlorianJacta** [comment]
I think we want to be able to submit again. One use case is when you have changed your inputs and want to resubmit your scenario without having to wait for the previous submission to finish which can take a lot of time.

A second use case is that you don't know how people use a scenario. Submitting a scenario multiple times will not always destroy the previous scenario but add on top of it. Let's take an example. You have a pipeline that takes 1 minute to run, and at the end of the pipeline, it **adds** the result at the end of your SQL database as a row.  You might want to submit this pipeline each 10 seconds with the same parameters or different parameters. For me, it does seem like a true use case.

However, I believe that it is very dangerous. We could have a *force=True* to pass to allow this behavior and have warnings around that. We also might want to discuss if it should cancel the jobs of the previous scenario or not, depending on the use case.

In the first use case, we want to cancel previous jobs. In the second one, we don't want to cancel them.

Does it make sense? @jrobinAV @trgiangdo

**Comment by jrobinAV** [comment]
@FlorianJacta I agree. I would suggest closing this ticket then.
