### ISSUE TITLE
Excel DN read inconsistency behavior

### ISSUE THREAD

**Issue by toan-quach** [Avaiga/taipy#796]
The behavior here https://github.com/Avaiga/taipy/pull/780/files#diff-aac43197fa9809f987114de3c8e433f615f121aa127da68fabaa40dfe4d296c5R298 contains inconsistency with what we have for numpy (`test_write_without_header_single_sheet_numpy_without_sheet_name()`) and pandas (test_write_without_header_single_sheet_pandas_without_sheet_name) as it's returning a list of value directly instead of a dictionary. We should have a discussion to determine if we want to keep it the same as it is or if we want to change that to have a consistent behavior.

**Comment by jrobinAV** [comment]
@FlorianJacta @AlexandreSajus Any opinion or feedback could help.

**Comment by FlorianJacta** [comment]
I would aim for consistency, but I don't know the specifics of the issue.
