### ISSUE TITLE
BUG-dict variable state not sent to front-end

### ISSUE THREAD

**Issue by bengaid** [Avaiga/taipy#809]
Let this test example for Taipy / Chalk'it : <https://github.com/bengaid/covid_taipy_chalkit>

Please clone it to get it. Use latest Taipy / Chalk'it setup for running it.

In this example, a new JSON-like Python dict option_e is recomputed after country-list user selection: 
```python
def on_change(state, var, val):
    if (var == 'selected_countries'):
        state.selected_countries = val
        state.covid_filtered = get_covid_filtered(covid_data_frame, val)
        state.option_e = echarts_option(state.covid_filtered, val)
```

But websocket does not send the updated value to front-end. The ECharts chart is not updated.

**Comment by FredLL-Avaiga** [comment]
Dict are blocked by default
Workaround: [dict()]

**Comment by dinhlongviolin1** [comment]
@bengaid 
@FredLL-Avaiga suggestion is on point. You can try his workaround to see if it works for you or not.

**Comment by bengaid** [comment]
Dear @dinhlongviolin1 and @FredLL-Avaiga . Thanks for hint.
After deep invetigation, bug was on Chalk'it side (on the new Taipy Manager). Sorry for that.
I close the issue.
