### ISSUE TITLE
BUG-Taipy in Colab not working, example on website returns ngrok error

### ISSUE THREAD

**Issue by Coderambling** [Avaiga/taipy#819]
**Description**
The example given in the [documentation](https://docs.taipy.io/en/develop/knowledge_base/tips/colab_with_ngrok/ ) using Colab with ngrok does not work. Produces error below.

line:1919             ngrok.set_auth_token(app_config["ngrok_token"])

[2024-02-11 17:20:49][Taipy][INFO] Running in 'single_client' mode in notebook environment
INFO:Taipy:Running in 'single_client' mode in notebook environment

> NameError                                 Traceback (most recent call last)
> [<ipython-input-58-4fcec58e4152>](https://localhost:8080/#) in <cell line: 2>()
>       1 import pyngrok as pyngrok
> ----> 2 Gui(pages=pages).run(ngrok_token = 'NGROK_TOKEN')
> 
> 1 frames
> [/usr/local/lib/python3.10/dist-packages/taipy/gui/gui.py](https://localhost:8080/#) in __init_ngrok(self)
>    1917             if not util.find_spec("pyngrok"):
>    1918                 raise RuntimeError("Cannot use ngrok as pyngrok package is not installed.")
> -> 1919             ngrok.set_auth_token(app_config["ngrok_token"])
>    1920             http_tunnel = ngrok.connect(app_config["port"], "http")
>    1921             _TaipyLogger._get_logger().info(f" * NGROK Public Url: {http_tunnel.public_url}")
> 
> NameError: name 'ngrok' is not defined

**How to reproduce**

- A code fragment
```
#Minimal code example:
# !pip install taipy --quiet
import taipy
# import Markdown
# from taipy.gui import Markdown
page_md = Markdown("Page Content")
gui = Gui(page=page_md).run(ngrok_token=ngtoken)
# Gui.run(run_browser=False)
!pip install pyngrok --quiet
import pyngrok
Gui.run((ngrok_token=ngtoken)) # ngtoken is a variable with a working ngrok token
```

When running the line Gui.run(run_browser=False) (and omitting the rest of the lines in the code example, the output returns a url: http://127.0.01:5000 . So the first part of the code is confirmed to work.

**Expected behavior**
Example works, and output in Colab shows an ngrok URL.

**Screenshots**
When available and relevant, screenshots to better highlight the problem.

**Runtime environment**
Google Colab

**Comment by FlorianJacta** [comment]
I wasn't able to replicate your issue:

```
!pip install --ignore-installed taipy
!pip install pyngrok
```

```python
from taipy.gui import Markdown, Gui
page_md = Markdown("Page Content")
gui = Gui(page=page_md)
```

```python
gui.run(ngrok_token=NGROK_TOKEN)
```

This code created me a tunnel to my application with Ngrok. Sometimes in the results of the `pip install` cell, Colab asks you to restart your session. If you have not, maybe try that or make sure pyngrok is installed in your Colab.

**Comment by FlorianJacta** [comment]
@Coderambling Can I close this issue?

**Comment by Coderambling** [comment]
Hi @FlorianJacta . Thanks for looking into this! I have not been able to look at the issue again in the meantime. If you can succesfully run your code, then I guess that means my code has an issue.

Maybe because of the (( in the last line: Gui.run((ngrok_token=ngtoken)) or because I did not restart my session as you mentioned. So fine to close it.

PS Are you on the Taipy Discord? Would like to discuss sometime. Am I correct that with Taipy you can use AI to help with coding of Taipy applications? What are your experiences? Any links to examples of that?

PPS I understand Colab runs on a rather old fork of Jupyter at the moment. Something to keep in mind you run into limitations / strange behaviour in Colab.

**Comment by FlorianJacta** [comment]
@Coderambling yes, I am on Discord. We have a beta version of a Taipy copilot but we have seen that Copilot is often better to propose suggestions as Taipy is easy to use. The goal of Taipy is to bring value to the data and models that you have created! The goal is also to be able to build pilots and applications that can be deployed in production
