### ISSUE TITLE
BUG-spam of GEVENT_SUPPORT logs in Colab

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#822]
**Description**

Running a Taipy application on Colab will show a message about GEVEN_SUPPORT. This message will be shown everywhere in the Notebook for each cell after a first run of the application. This is highly annoying for a user.

![image](https://github.com/Avaiga/taipy/assets/98709993/ec01172c-28c9-4372-87b5-508a70119c53)

**How to reproduce**

Run a Taipy application on Colab.

**Expected behavior**
We shouldn't see this message.

**Runtime environment**
Please specify relevant indications.
 - Taipy: 3.0
 - Environment: Colab
 
**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Create related issue in taipy-doc for documentation and Release Notes if relevant

**Comment by FredLL-Avaiga** [comment]
workaround: Gui().run(debug=True)

**Comment by dinhlongviolin1** [comment]
for google colab, please move to eventlet
@FabienLelaquais should we note this somewhere

```
!pip install eventlet

from taipy.gui import Gui
gui = Gui()
gui.run(async_mode="eventlet")
```

**Comment by dinhlongviolin1** [comment]
I will move the issue to closed. If you have any problem/issue, you can reopen the issue.
