### ISSUE TITLE
Data Node Selector - Custom filter

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#824]
## Improvement

It can be extremely useful to display only some data nodes (some can be irrelevant) and have a custom user function to handle this filter. 

Example: The selector could use a function for each Data Node, which could return True to display the Data Node in the Data Node Selector.

Example of code:
```
<|{datanode}|data_node_selector|filter_scenario={scenario}|filter={my_filter}|>
```

Example of function:

```python
def my_filter(data_node:DataNode) -> bool:
    return data_node.config_id == "TOTO"
```

Note: The generic and scenario filters should be applied with an AND operator.

Taipy version:
Taipy 3.0

**Comment by bobbyshermi** [comment]
I have the same need. 
As an alternative to your proposal of a filter callback, I was thinking of leveraging the variable binding mechanism of taipy.
Why not binding a value to a list of data nodes directly, just like the lov property of the selector widget?

**Comment by FlorianJacta** [comment]
@bobbyshermi I like this idea, but I think there is also an issue with the *lov*. It is that the developer has to know and code how to update it properly each time a scenario is created or deleted. What do you think?

**Comment by ioannastantzou** [comment]
hello could i be assigned for this?

**Comment by FlorianJacta** [comment]
I think this should now be like what has been done with the scenario selector meaning passing a list of *data_nodes* that will be bound to the visual element: https://docs.taipy.io/en/develop/manuals/gui/corelements/scenario_selector/

https://github.com/Avaiga/taipy/issues/1040

`<|{datanode}|data_node_selector|data_nodes={list_of_data_nodes}|>` or

```python
tgb.data_node_selector("{datanode}", data_nodes="{list_of_data_nodes}")
```

What do you think @FabienLelaquais @jrobinAV ? Is the issue ready to be taken with this state?
