### ISSUE TITLE
Cluster mode: Create a Taipy application to demonstrate the cluster mode

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#831]
The application should submit a lot of tasks in a distributed remote environment.

[distributed-taipy-core-sales-main.zip](https://github.com/Avaiga/taipy-enterprise/files/13921765/distributed-taipy-core-sales-main.zip)

**Comment by trgiangdo** [comment]
The demo repository: https://github.com/Avaiga/demo-cluster-mcdo.

The demo has been successfully deployed to a CPU cluster and a GPU cluster on Azure.
The performance of the GPU cluster is 7 - 10 times better than CPU, which is exactly what we want to demonstrate.

**Comment by jrobinAV** [comment]
Awesome!
