### ISSUE TITLE
Requirements core visual elements

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#87]
Requirements : 
https://docs.google.com/document/d/19R0SiykrlGALWU9ONDdtmni4PNBmJ-95s9i755FhWgg/edit#

- [x] Scenario selector
- [x] Scenario viewer
- [x] Scenario DAG
- [x] Job selector
- [ ] Job viewer
- [x] Data node selector
- [x] Data node viewer
- [ ] quick access icons
- [ ] Scenario comparator

Specifications : 
https://docs.google.com/document/d/10GMDUZj0PJ5Tz24nOueA3whgTLHfU8WYvjwHoUv6K1w/edit#

**Comment by FredLL-Avaiga** [comment]
[figma](https://www.figma.com/proto/eYWPeIhAufVFFuV8EbQDRa/Taipy-GUI-components-for-Core?node-id=20-7769&show-proto-sidebar=1)
