### ISSUE TITLE
BUG-use_reloader does not work when writing in a separate Markdown file

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#882]
Example:
- I have a `main.py` Python file:
```python
from taipy.gui import Gui, Markdown

page = Markdown("page.md")

Gui(page).run(use_reloader=True)
```
- I also have a `page.md` Markdown file:
```markdown
# Hello
```

If I run `main.py`, it does show a webpage with `Hello`.
But when I change the contents of `page.md`, save the file, and reload the page, the page does not get updated with my changes even though `use_reloader` is set to `True`

**Comment by dinhlongviolin1** [comment]
use_reloader should only detect python file and not external file extension

**Comment by AlexandreSajus** [comment]
Yes, that's what I thought as well. Too bad

**Comment by dinhlongviolin1** [comment]
One day we will have it :D
