### ISSUE TITLE
[Q&A] : How to get variable dynamic value & print it accordingly on terminal

### ISSUE THREAD

**Issue by vinaybridge** [Avaiga/taipy#91]
Hello Team,

<img width="290" alt="image" src="https://user-images.githubusercontent.com/125438192/218959624-f7fe6799-97c1-410b-8db8-9a0d6ad29334.png">

1. How to get dynamic value from UI component and store it in variable, lets say I need param_2  value in slider at current state which is 77 and I want to print it on terminal logs or pushing it somewhere else

2. How to set decimal value in slider like min 0.1 and max 1.0 ?  currently it only supports int for auto-filling in between values

Thank you

**Comment by FlorianJacta** [comment]
Hi,

1. There are multiple ways to do it. We can either have a local callback attached to our visual element or a global callback:
- The **local callback** is put on the visual element `<|{value}|slider|on_change=fct|>` where `fct` is the user function. This function will be called whenever the slider is being changed.
- The **global callback** is the function that is called whenever a value of a visual element (any visual element) is being changed. To use it, write in your code a function with this name: `on_change(state, var_name, var_value)`

For more information, please look in the [Getting Started](https://docs.taipy.io/en/latest/getting_started/getting-started-gui/) this [concept](https://docs.taipy.io/en/latest/getting_started/getting-started-gui/step_03/ReadMe/#how-to-connect-two-variables-the-on_change-function).

2. To be able to select values between 0 and 1, a list of values can be passed to the slider visual element or you can have a slider between 0 and 100 and rescale it in your code.

Here is a code explaining the concept of callbacks and how to pass a list of values to a slider:

```python
from taipy.gui import Gui, notify

# initialization of variables
param_2 = 10
param_3 = 0.15
param_4 = 20

# Markdown page translated to a Web Page
md = """
param_2: <|{param_2}|>

<|{param_2}|slider|on_change=on_change_slider_2|width=100%|>

param_3: <|{param_3}|>

<|{param_3}|slider|lov={[str(i/20) for i in range(20)]}|labels=True|width=100%|>

param_4: <|{param_4/100}|>

<|{param_4}|slider|width=100%|>

"""

# Callbacks of the application

def on_change_slider_2(state):
    print("Param 2", state.param_2)
    # If the first slider/param_2 is greater than 50, then
    # the second slider/param_3 takes 0.5 as a value
    if state.param_2 >= 50:
        # We can notify the user with this Taipy function
        notify(state, 'info', f'Param 3 changed from {state.param_3} to 0.5')
        state.param_3 = 0.5


# Run the Web Page
Gui(md).run(use_reloader=True)
```

I hope it helps and that I answered your questions!

**Comment by vinaybridge** [comment]
Perfect ! @FlorianJacta 
That is what I am looking for. It works for me.

<img width="921" alt="image" src="https://user-images.githubusercontent.com/125438192/218989858-1e7d63a9-9b19-4e93-bd8f-983d57f1c48f.png">

Thanks a lot!
