### ISSUE TITLE
remove the rules(tool.ruff.lint.ignore) in  `pyproject.toml` and pass the ruff lint

### ISSUE THREAD

**Issue by ooooo-create** [Avaiga/taipy#921]
I see the TODO in `pyproject.toml`.  It seems we can open the rules directly, but I open a issue to make sure these should be turned on.
If that , i can do this by relating this issue
https://github.com/Avaiga/taipy/blob/750afd0337dad810e7ce3c87202dc813129be0da/pyproject.toml#L29-L35

- [x] C401 #919 
- [x] C405 #964 
- [x] C408 #1039 
- [x] C409 #1067 
- [x] C416 #920

**Comment by trgiangdo** [comment]
Thank you @ooooo-create, I will assign this issue for you.

And FYI, we are currently in the release process, so it will take some time before we can review and merge your PRs. Thank you for your patience.

**Comment by ooooo-create** [comment]
> Thank you @ooooo-create, I will assign this issue for you.
> 
> And FYI, we are currently in the release process, so it will take some time before we can review and merge your PRs. Thank you for your patience.

Understood and no problem at all! Thanks for the heads up about the ongoing release process.Cheers!

**Comment by trgiangdo** [comment]
All PRs related to this issue have been merged. We can close this.
