### ISSUE TITLE
Improve taipy sub-package design

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#923]
**Description**
The design of sub-packages has some issues regarding the logger and the CLI. We need to discuss how to improve it.

**Acceptance Criteria**
- [x] Set up a meeting with relevant people to discuss the new design
- [x] The expected outcome of the meeting is an action plan including: 
    - The action to do 
    - The targeted version 
    - The list of new github issues created

**Comment by trgiangdo** [comment]
The current sub-package design: 
https://docs.google.com/drawings/d/104EvVKGHdA7MBDwTDMAZNE23jUPqBNc9sITpKusFK2I/
![image](https://github.com/Avaiga/taipy/assets/88036007/dfbc304e-88d5-491b-b837-277f0eaa09ef)


The proposal design (discussion required):
https://docs.google.com/drawings/d/17PWDRNRYJa1DxKzY8csKiGbLCTG3iyBR80yLNJZfJv8/
![image](https://github.com/Avaiga/taipy/assets/88036007/9a5a9274-03e2-4f74-a8df-29e90623a794)


We can continue the discussion in the comment in the new proposal.

**Comment by jrobinAV** [comment]
Can we move this to review? or eventually to done?

**Comment by trgiangdo** [comment]
I believe it's done. The dev release is working, right?

**Comment by joaoandre-avaiga** [comment]
I've moved to review because of the push to pypi that needs fixing.
