### ISSUE TITLE
BUG-onChange callback not called for JSON update in gui

### ISSUE THREAD

**Issue by bengaid** [Avaiga/taipy#932]
To reproduce

- Clone or pull from repositoy <https://github.com/bengaid/covid_taipy_chalkit>
- Install Chalk'it with Taipy link
```sh
pip install py-chalk-it-0.4.0.tar.gz
```
- Run the example
```sh
python covid_demo.py
```

When the user changes the country, the Python callback is correctly called, option_e dict is correctly computed. It is sent to front-end but the onChange callback is not called.

**Comment by dinhlongviolin1** [comment]
thanks @bengaid. The demo is running on my side. Debugging it atm

**Comment by dinhlongviolin1** [comment]
this was fixed and merged into the develop branch

**Comment by bengaid** [comment]
Thanks @dinhlongviolin1 
We will test soon and let you know.

**Comment by bengaid** [comment]
Warm thanks @dinhlongviolin1 , the problem is solved !
For info @FabienLelaquais

**Comment by dinhlongviolin1** [comment]
My pleasure @bengaid
