### ISSUE TITLE
Coverage step is failing

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#937]
The Coverage step on the overall test GitHub workflow is failing with the following error:
```
HttpError: Resource not accessible by integration
```

This is very recent and systematic.

This must be fixed since it prevents us from merging any new PR.

**Comment by joaoandre-avaiga** [comment]
This is a weird github issue, it comes and goes. It happens when we try to interact with some of their APIs, like when creating a release or writting a comment on a PR. Im not sure of the reason for that.

I will separate the coverage in a another step to see if that helps.
