### ISSUE TITLE
[Chart] How to display charts based on dynamic data?  When the Y-axis column name is changed, the chart can't be displayed correctly.

### ISSUE THREAD

**Issue by livia0803** [Avaiga/taipy#94]
# How to display charts based on dynamic data?
## When the Y-axis column name is changed, the chart can't be displayed correctly.

1. Data can’t be displayed correctly.
2. The timeline has become 100 years
3. The legend of the first data is still displayed, and is not regenerated based on the new data

```python
<|{data}|chart|mode=line|x=shift|type[1]=line|y[1]=preferred|type=bar|properties={bar_properties}|width=calc(100vw - 130px)|layout={stack_bar_layout}|>

# The y-axis data is dynamically generated from the input `data`
bar_properties = {f"y[{(i + 2)}]": y_axis[i] for i in range(len(y_axis))}

```

**Comment by FlorianJacta** [comment]
Hi!

Taipy still needs to be able to automatically change the schema (name and type of columns) of the data frame on the fly. It has yet to be implemented. An [issue](https://github.com/Avaiga/taipy-gui/issues/443) has been created to handle it for the next release. However, it is possible to do so using [partials](https://docs.taipy.io/en/latest/manuals/gui/pages/#partials). A partial is a section of your Markdown that can be changed/updated/reloaded in run time. Here is a code sample:

```python
from taipy.gui import Gui 

data = {"x": [1, 2, 3, 4, 5],
        "y_ini":[8, 12,63, 4, 5],
        "y1":[45, 42, 23, 14, 8],
        "y2":[84, 41, 12, 4, 5]}

properties = {}

md = "<|part|partial={partial}|> <|Change schema|button|on_action=change_schema|>"

chart_md = "<|{data}|chart|x=x|y[1]=y_ini|properties={properties}|>"

def change_schema(state):
    state.properties = {"y[1]": "y1", "y[2]": "y2"}
    state.partial.update_content(state, chart_md)


gui = Gui(md)

partial = gui.add_partial(chart_md)
gui.run()
```

## Before clicking on button:

![image](https://user-images.githubusercontent.com/98709993/219436260-63e295a2-f327-408a-a488-34f5529e5bb2.png)

## After clicking on button:

![image](https://user-images.githubusercontent.com/98709993/219436384-94a681f5-ad21-426d-b4ec-9a0e62507e8c.png)

The data in these columns can be changed dynamically without a problem.

Tell me if it answers your issue. We will come back to you when this improvement is done.

**Comment by livia0803** [comment]
Hi， @FlorianJacta 

It seems that the change  of `state.properties` can't be applied to `chart`.

In the given sample, `properties` has only been assigned once. When it changes again, it will not work properly.

Here is my test code .
```python
import json

from taipy.gui import Gui

data = {"x": [1, 2, 3, 4, 5],
	"y_ini": [8, 12, 63, 4, 5],
	"y2": [45, 42, 23, 14, 8],
	"y3": [84, 41, 12, 4, 5],
	"y4": [84, 41, 12, 4, 5]}

properties ={"y[2]": "y2", "y[3]": "y3"}
p_str = json.dumps(properties)
md = "<|part|partial={partial}|> <|Change schema|button|on_action=change_schema|><|{p_str}|>"
chart_md = "<|{data}|chart|x=x|y[1]=y_ini|properties={properties}|>"


def change_schema(state):
	state.properties = {"y[2]": "y4", "y[3]": "y3"}
	state.p_str = json.dumps(state.properties._dict)
	state.partial.update_content(state, chart_md)


gui = Gui(md)

partial = gui.add_partial(chart_md)
gui.run()
```

## Before clicking on button:
**_It works well._**
*  **Expect**: `y_ini`, `y2`, `y3`
*  **Actual**: `y_ini`, `y2`, `y3`
---
<img width="1670" alt="image" src="https://user-images.githubusercontent.com/5668597/219558924-6169b723-1160-4927-b0f2-9bef469ddb60.png">


## After clicking on button:
**_It doesn't work as expected._**
*   **Expect**: `y_ini`, `y4`, `y3`
*  **Actual**: `y_ini`, `y2`, `y3`
---

![image](https://user-images.githubusercontent.com/5668597/219555687-f8f8b120-2a5e-44fb-b4b2-9c036d631226.png)

**Comment by FlorianJacta** [comment]
Hi, there are some exceptions to this solution. Another more robust and general solution would be to regenerate the Markdown depending on the property dictionary.

```python
from taipy.gui import Gui

def write_md(properties):
    prop_str = ""
    for k, v in properties.items():
        prop_str += f"|{k}={v}"
    
    chart_md = "<|{data}|chart" + prop_str + "|>"
    print(chart_md)
    return chart_md

data = {"x": [1, 2, 3, 4, 5],
	    "y_ini": [8, 12, 63, 4, 5],
	    "y2": [45, 42, 23, 14, 8],
	    "y3": [84, 120, 122, 114, 115],
	    "y4": [-10, -15, -3, -35, -5]}

properties ={"x":"x",
             "y[1]":"y_ini",
             "y[2]": "y2",
             "y[3]": "y3"}

md = "<|part|partial={partial}|> <|Change schema|button|on_action=change_schema|>"


def change_schema(state):
	properties = {"x":"x",
                  "y[1]":"y_ini",
                  "y[2]": "y4",
                  "y[3]": "y3"}
	state.partial.update_content(state, write_md(properties))


gui = Gui(md)
partial = gui.add_partial(write_md(properties))
gui.run()
```

This should solve your issue until it is directly implemented in Taipy in an efficient way.
