### ISSUE TITLE
Clickable Links in a Table

### ISSUE THREAD

**Issue by herrschmidt** [Avaiga/taipy#945]
**What would that feature address**
It is not possible to show clickable links in a table

***Description of the ideal solution***
It would be great to be able to tell Taipy that a column's data type is "link" in the table definition to make http links clickable. And it would be nice to pass markdown or html links into the table to have a link text and url property available.

***Caveats***
Maybe passing markdown or html links into the table is too much. Setting the data type to "link" would be great already!

***Other options***
-

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Create related issue in taipy-doc for documentation and Release Notes
- [ ] Check if a new demo could be provided based on this, or if legacy demos could be benefit from it
- [ ] Ensure any change is well documented

**Comment by FredLL-Avaiga** [comment]
supporting a simple version of markdown links might be faisable
ie \[label](action)
would render as a button that will dispatch the table on_button_action with the label and action as args

**Comment by FlorianJacta** [comment]
This is a fantastic feature!

**Comment by pranshu-raj-211** [comment]
I had a question regarding this issue - would this work even if the table is accessed from a dataframe (link columns are specified in a list while passing to md or the tgb page as args). Also, could we choose to just show a button to click instead of links as some links might be too long.

Would be willing to contribute if this is not implemented yet.

**Comment by FredLL-Avaiga** [comment]
Hi @pranshu-raj-211 ,
This has already been implemented as a button when the value matches the format `[label](action)`.
Thank you for proposing.
I'm sure you can contribute on another issue.
