### ISSUE TITLE
Clean DN inheritance

### ISSUE THREAD

**Issue by toan-quach** [Avaiga/taipy#957]
The inheritance mechanism for all data nodes would benefit from some cleaning.

Suggestions:

- The `_AbstractTabularDataNode` is not a data node but a mixin. The name is misleading. It is more like a mixin.
- Same for `_AbstractFileDataNode`.
- However, the `_abstract_sql` is a data node sub-class. Why this inconsistency?
- The `FilterDataNode` is not a data node sub-class nor a mixin. It is just a delegated class. I guess it should be renamed to `DataNodeFilter`.
- The exposed type code is duplicated in many data node implementations. I believe we can factorize the code in the `_AbstractTabularDataNode` class since the exposed type is for tabular data.

**Comment by toan-quach** [comment]
@jrobinAV I think the inconsistency for `abstract_sql` is due to it extending from `DataNode` class. So instead of for example, the SQLTableDataNode class extending from DataNode and AbstractSQLDataNode, it only extending from AbstractSQLDataNode (and the abstract sql dn is extending DataNode)

**Comment by jrobinAV** [comment]
> AbstractSQLDataNode

Yes. I believe we can turn it into a Mixin as well. No?

**Comment by toan-quach** [comment]
@jrobinAV yep surely can, I'm working on it at the moment but it proved to be quite difficult as it contains many things in it
