### ISSUE TITLE
Publish Greg's demo on face recognition

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy#98]
- Apply GUI extension template 
- Review code
- Decide what Core features should be exposed
----------------------------
- Add core features (scenario mgt)
- Deploy on Cloud
- Publish on website

**Comment by jrobinAV** [comment]
The ticket is blocked since opencv is not available on taipy cloud for now.

**Comment by FlorianJacta** [comment]
I found a way to install OpenCV. Installing `opencv-python` will raise an error:

```
Traceback (most recent call last):
  File "/home/.../apps/face-recognition/main.py", line 3, in 
    import cv2
  File "/home/.../apps/face-recognition/.venv/lib/python3.10/site-packages/cv2/__init__.py", line 181, in 
    bootstrap()
  File "/home/.../apps/face-recognition/.venv/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

```

Choosing from OpenCV to the `headless` packages made it work.

> `opencv-python-headless` is a package of OpenCV bindings for Python without the user interface (GUI) features. This package is useful when you want to use OpenCV in a headless environment like a server, Docker, or when you don't need GUI components.


```
taipy==2.1
opencv-python-headless==4.7.0.72
opencv-contrib-python-headless==4.7.0.72
pillow
```

Here is the deployed application working: https://face-recognition.taipy.cloud/


@FabienLelaquais @florian-vuillemot  What do you think the next step should be? Should we document it in a way (an article that I can write) or is there a need to be able to install `opencv-python` directly?
