### ISSUE TITLE
BUG-delay updating a GUI element that uses a class attribute

### ISSUE THREAD

**Issue by VFLins** [Avaiga/taipy#980]
**Description**

When triggering an `on_change` action that uptades a class attribute used by the GUI, the update behaves delayed, recieving the change applied before the current change.

**How to reproduce**

```python
from taipy.gui import Gui

class BasicForm:
    def __init__(self):
        self.fmt_amount = "0,00"
        self.input_amount = "0"
    

form = BasicForm()


def fmt(inp: str) -> str:
    if inp is str:
        inp = inp.replace(",", "")

    try:
        return f"{int(inp)/100:.2f}".replace(".", ",")
    except ValueError:
        return "0,00"


def chg_amount(state):
    state.form.fmt_amount = fmt(state.form.input_amount)
    return


PAGE = """
# Very smart app:

Amount: $ <|{form.fmt_amount}|text|>

<|{form.input_amount}|input|on_change=chg_amount||>
"""

if __name__ == "__main__":
    app = Gui(page=PAGE)
    app.run()
```

**How to currently get around the bug**

The only way to get around the issue is to use `fmt_amount` as a variable, instead of a class attribute.

**Expected behavior**

It's expected that the `form.fmt_amount` update on the current change like any variable, instead of the previous change.

**Runtime environment**
 - Taipy 3.1.0
 - OS: Windows 10 22H2

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Create related issue in taipy-doc for documentation and Release Notes if relevant

**Comment by FlorianJacta** [comment]
It is a normal behavior in Taipy. Taipy won't refresh an element if its subelements have been changed. This is the case for tables, objects, and so on.

If it did, it would have a massive impact on performance. Taipy refreshes the UI when the user writes `state.your_variable = ...`. When changing the subelements of a table or an object, you should use the refresh function to propagate your changes to the UI.

```python
def chg_amount(state):
    state.form.fmt_amount = fmt(state.form.input_amount)
    state.refresh('form')
    return
```

Tell me if this works and if we can close the issue

**Comment by VFLins** [comment]
Thanks for clarifying that! The solution works very well.

I don't think I have seen this in the documentation, would be nice to have it there. Issue can be closed.

**Comment by FlorianJacta** [comment]
I created an issue on our doc to improve this aspect. https://github.com/Avaiga/taipy-doc/issues/875
