### ISSUE TITLE
Taipy installation issues

### ISSUE THREAD

**Issue by abhigyan631** [Avaiga/taipy#983]
I am trying to install taipy using pip install taipy on Google Colab 
and I get the error "ERROR: Cannot uninstall 'blinker'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall."

Am I the only one who is getting this or someone else is getting this too? Maybe I am missing something

Also in the next step I am trying to set up the Taipy environment on colab and I execute

import taipy as tp
import pandas as pd
from taipy import Config, Scope, Gui

I am getting this error
ImportError: cannot import name 'Config' from 'taipy' (/usr/local/lib/python3.10/dist-packages/taipy/__init__.py)

Is it a dependency issue or the version of the taipy module installed may not be compatible with the code?

Can anyone please help?
Thank you for your support.

**Comment by FlorianJacta** [comment]
Have you checked the documentation on [how to install Taipy](https://docs.taipy.io/en/latest/installation/#installing-taipy-with-colab)? 

Note that Colab is not the preferred way to use Taipy. Taipy runs the web application locally. This means that Colab runs on your Cloud machine rather than yours. You can bypass that if you follow the article provided in the installation using NGROK. Certain functionality in Colab will also not work due to how Colab works.

**Comment by dinhlongviolin1** [comment]
@FlorianJacta They could try this. Works for me when testing out colab
```
pip install taipy --ignore-installed
```

**Comment by FlorianJacta** [comment]
@dinhlongviolin1 Yes and then, follow the tip that is in the documentation.

**Comment by abhigyan631** [comment]
> @FlorianJacta They could try this. Works for me when testing out colab
> 
> ```
> pip install taipy --ignore-installed
> ```

I run the command every time on colab and the session times out and I have to restart the session every time.

**Comment by FlorianJacta** [comment]
You just have to restart it once; then you should be good to go

**Comment by abhigyan631** [comment]
I restarted once, but now the Config is not imported so it shows 
"FileNotFoundError: [Errno 2] No such file or directory: 'config.toml'"

**Comment by FlorianJacta** [comment]
What is your code? Are you trying to import a *config.toml* file?

**Comment by abhigyan631** [comment]
I am trying to redo the "User Interface Generation and Scenario & Data Management" from https://github.com/Avaiga/taipy and test taipy into my local system. Not colab now.

**Comment by FlorianJacta** [comment]
Great! To learn Taipy, please follow the first or second tutorial [here](https://docs.taipy.io/en/develop/tutorials/fundamentals/). One will show how to create a Taipy app with no data & scenario management. And the other one will show you this.

Try to run this to see that everything is working. See the explanation of this getting started [here](https://docs.taipy.io/en/develop/getting_started/):
```python
from taipy.gui import Gui 
import taipy.gui.builder as tgb
from math import cos, exp

value = 10

def compute_data(decay:int)->list:
    return [cos(i/6) * exp(-i*decay/600) for i in range(100)]

def on_slider(state):
    state.data = compute_data(state.value)

with tgb.Page() as page:
    tgb.text(value="Taipy Getting Started", class_name="h1")
    tgb.text(value="Value: {value}")
    tgb.slider(value="{value}", on_change=on_slider)
    tgb.chart(data="{data}") 

data = compute_data(value)

if __name__ == "__main__":
    Gui(page=page).run(title="Dynamic chart")
```

If you need any help, we have a [Discord channel](https://discord.gg/ZuYAXf2x) where the community interacts a lot.

**Comment by abhigyan631** [comment]
I could run the code block (the one you shared) fine and could change the slider values too earlier but now it can't connect. It shows this error.

builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.

**Comment by FlorianJacta** [comment]
Did the application stop? And if you rerun the code?

**Comment by abhigyan631** [comment]
It works now after I restarted my Jupyter lab and can change the slider values too, I will try out the tutorials you shared, thanks.
