### ISSUE TITLE
BUG- Expandable not working properly with Python API

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#993]
**Description**

If the user tries to create an expandable, they will not be able to expand or close this expandable. The user has to provide a *title* property to the expandable to make it possible. Note this property doesn't exist in the documentation.

**How to reproduce**
```python
from taipy.gui import Gui
import taipy.gui.builder as tgb

with tgb.Page() as page:
    with tgb.expandable("Not working", expanded=False):
        tgb.text("The user cannot expand/close the expandable section")

    with tgb.expandable(value="Not working", expanded=False):
        tgb.text("The user cannot expand/close the expandable section")

    with tgb.expandable(title="Working"):
        tgb.text("The user can expand/close the expandable section")


Gui(page).run()

```

![image](https://github.com/Avaiga/taipy/assets/98709993/69faa5ea-0fdb-4725-91d0-a1d0374fad78)

**Expected behavior**
We should either document this property or the two first examples should work as described in the documentation.

**Runtime environment**
 - Taipy version: 3.1

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Create related issue in taipy-doc for documentation and Release Notes if relevant

**Comment by dinhlongviolin1** [comment]
This is a doc issue and will be fixed and propagated to both develop and 3.1

**Comment by FlorianJacta** [comment]
Great! Will the default property of the *expandable* also change then?

**Comment by FabienLelaquais** [comment]
>> Will the default property of the expandable also change then?


No
