### ISSUE TITLE
BUG-

### ISSUE THREAD

**Issue by TheAnuRock** [Avaiga/taipy#998]
**Description**
A complete and clear description of the problem.

**How to reproduce**

- A code fragment
    ```python
    from taipy import ...
    ```

- And/or configuration files or code:
    ```python
    from taipy import Config;


    Config.configure_data_node(...)
    ...
    ```

- And/or Taipy GUI Markdown or HTML files

**Expected behavior**
Description of what would be the expected outcome.

**Screenshots**
When available and relevant, screenshots to better highlight the problem.

**Runtime environment**
Please specify relevant indications.
 - Taipy version (or branch name):
 - OS: [e.g. Linux, Windows] and version
 - Browser: [e.g. Chrome, Edge, Safari] and version (if relevant)
and any other relevant information.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Create related issue in taipy-doc for documentation and Release Notes if relevant

**Comment by FlorianJacta** [comment]
I guess it is not a real issue. I will close it if you like.
